### ISSUE TITLE
witherspoon rvitals reports wacky fan speed for fan1.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#3726] opened 2017-08-18 16:02 UTC
most of our nodes report 0 for fan speed for fan1
```
rvitials c460c802
c460c802: Ambient: 20.951 C
c460c802: Fan0 0: 9973 RPMS
c460c802: Fan0 1: 10838 RPMS
c460c802: Fan1 0: 0 RPMS
c460c802: Fan1 1: 0 RPMS
c460c802: Fan2 0: 9973 RPMS
c460c802: Fan2 1: 10683 RPMS
c460c802: Fan3 0: 10080 RPMS
c460c802: Fan3 1: 10838 RPMS
```

two nodes report wack numbers.
```
[root@c460mgt01 ~]# rvitals witherspoon | grep 'Fan1' | sort
c460c801: Fan1 0: 0 RPMS
c460c801: Fan1 1: 0 RPMS
c460c802: Fan1 0: 0 RPMS
c460c802: Fan1 1: 0 RPMS
c460c803: Fan1 0: 0 RPMS
c460c803: Fan1 1: 0 RPMS
c460c804: Fan1 0: 0 RPMS
c460c804: Fan1 1: 0 RPMS
c460c805: Fan1 0: 0 RPMS
c460c805: Fan1 1: 0 RPMS
c460c806: Fan1 0: 0 RPMS
c460c806: Fan1 1: 0 RPMS
c460c807: Fan1 0: 0 RPMS
c460c807: Fan1 1: 0 RPMS
c460c808: Fan1 0: 0 RPMS
c460c808: Fan1 1: 0 RPMS
c460c809: Fan1 0: 0 RPMS
c460c809: Fan1 1: 0 RPMS
c460c810: Fan1 0: 0 RPMS
c460c810: Fan1 1: 0 RPMS
c460c811: Fan1 0: 21802 RPMS
c460c811: Fan1 1: 23734 RPMS
c460c812: Fan1 0: 21551 RPMS
c460c812: Fan1 1: 23291 RPMS
c460c813: Fan1 0: 21802 RPMS
c460c813: Fan1 1: 23437 RPMS
c460c814: Fan1 0: 0 RPMS
c460c814: Fan1 1: 0 RPMS
    
```

Here are the complete rvitals for all our nodes.

rvitals witherspoon  | sort >/tmp/ws.rvitals.txt
[ws.rvitals.txt](https://github.com/xcat2/xcat-core/files/1234925/ws.rvitals.txt)

**Comment by whowutwut** [comment] 2017-08-18 18:37
@ralphbellofatto Can you run the following: 

```
IP=<FILL IN BMC IP>

curl -c cjar -k -X POST -H 'Content-Type: application/json' -d '{"data": [ "root", "0penBmc" ] }' https://$IP/login

curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X GET https://$IP/xyz/openbmc_project/sensors/fan_tach/enumerate
```

And what is the output for those lines ?

**Comment by ralphbellofatto** [comment] 2017-08-18 19:49
results of the above commands on all the nodes.
[fancurl.txt](https://github.com/xcat2/xcat-core/files/1235490/fancurl.txt)

**Comment by whowutwut** [comment] 2017-08-18 20:22
So looks like the API is passing back those high numbers.. ...  Let me see if the openbmc team thinks this is correct or not..

**Comment by ralphbellofatto** [comment] 2017-08-18 20:24
I suspect an uninitialized variable in the BMC...

**Comment by whowutwut** [comment] 2017-08-18 20:30
They are all running the same FW level too right?

**Comment by whowutwut** [comment] 2017-08-18 21:20
From OpenBMC team 
> old builds had a device driver problem that would sometimes report double the RPM value 

so I guess we should just wait.....

**Comment by ralphbellofatto** [comment] 2017-08-18 21:27
these are all on the 1730c firmware driver....

**Comment by amboar** [comment] 2017-08-18 22:20
Looks like the fan controller has the wrong tach pulses value configured. Have there been other troubles with the fan controller on this system?

**Comment by ralphbellofatto** [comment] 2017-08-18 23:53
how would we tell if there were other problems?

**Comment by amboar** [comment] 2017-08-19 00:15
One or more fans not appearing, or failure trying to read fan rates from the controller

**Comment by ralphbellofatto** [comment] 2017-08-20 11:53
how would a failure to read the fan rates show up in the rvitals here?

**Comment by amboar** [comment] 2017-08-21 00:04
@ralphbellofatto I have no experience with rvitals, so I'm not sure how it would react. However I did write the kernel driver for the fan controller, so I've come across some of these funky behaviours during testing.

In terms of the kernel/userspace interface, sometimes the driver fails to bind to the device, in which case no fans are presented in sysfs. Other times there have been mis-configured fans which may lead to the fan being marked as disabled.

We have a work-around for both of these issues and an investigation to determine the root cause is on-going.

There have also been reports of errors reading the fan - i.e. instead of the sysfs `fanX_input` file providing the current fan rate, the read attempt gives an error.

**Comment by ralphbellofatto** [comment] 2017-08-21 11:12
Rvitials reports the data that is returned by the RESTAPI,  for the above data, this is the data returned:

https://github.com/xcat2/xcat-core/files/1235490/fancurl.txt

Are you saying that the fan speed of 0 is an actual hardware error and the wacky double number is speed being returned double?

**Comment by whowutwut** [comment] 2017-08-21 14:33
@amboar  xCAT `rvitals` does a GET on the  sensor/enumerate endpoint and then parses the JSON data and passes through the information formatting based on the scale property.  We try not to massage any of the data returned to allow for the code to support anything that OpenBMC sends back to us without additional code changes.

**Comment by ralphbellofatto** [comment] 2017-08-21 14:38
well that's fine, so what does fan speed 0 signify?  faulty firmware, or faulty hardware.?

**Comment by msbarth** [comment] 2017-08-21 19:50
Depends on the state/configuration of the system, which should be taken into account.
- System powered off & tach feedback == 0
    - Fan is off / rotor not spinning / fan not present
- System powered on & tach feedback == 0
    - Fan is not present
    - Fan is not required/controlled in system config
    - Fan is faulted, rotor(s) not spinning

Please provide the specific BMC version info of the system or systems showing the 20k tach feedback speed. In the case of what you're seeing, its likely these system(s) are being read as water cooled if this only shows up on Fan1 since that is not a required fan nor used within fan control. A bug existed to correct the jumper reading for air vs water cooled systems after 1730C. I would say in the case this was a water cooled system, Fan1 speeds should be ignored since its not required by configuration of the system.

**Comment by msbarth** [comment] 2017-08-21 19:58
Also, I think an update was made to the fan controller chip's driver as @amboar mentioned that should be provided in the next release which changed how its configuration registers are initialized. Its possible the systems reporting the bogus tach feedback numbers are newer and the controller chip never got its tach pulses register init'd (which has been fixed in the driver updated by @amboar).

**Comment by whowutwut** [comment] 2018-01-05 19:19
Asking Tom L. to open this with FW team as this issue is in the wrong place.

**Closed by whowutwut** 2018-01-05 19:19 UTC
Labels: status:fixed_elsewhere, status:rejected
