### ISSUE TITLE
[FVT] Could not get Firestone's firmware version for component 4

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#446] opened 2015-11-20 07:24 UTC
root@c910f03c05k22:/firmware# lsxcatd -v
Version 2.11 (git commit 51316df775cb2e410708aab98c3afe9c8ef6ea1d, built Thu Nov 19 03:16:29 EST 2015)

The  firmware version for component 4 is always 0.00 00000000
```
root@c910f03c05k22:/firmware# time rflash c910f05c37 -c 8335_810.1543.20151102d_update.hpm
HPM firmware version for component 1:  2.13 4C4C0100
HPM firmware version for component 2:  2.13 4C4C0100
HPM firmware version for component 4:  1.01 0B010701
c910f05c37: Node firmware version for component 1:   2.13 4C4C0100
c910f05c37: Node firmware version for component 2:   2.13 4C4C0100
c910f05c37: Node firmware version for component 4:   0.00 00000000
```

**Comment by chenglch** [comment] 2015-11-20 08:19
We can keep this issue here. This is a defect from firmware or BMC, there is no need for xcat to fix this issue.

**Comment by whowutwut** [comment] 2016-03-14 14:26
I moved this back to 2.11.1 because we should fix this in 2.11 and cherry-pick it to 2.12.  The Issue is the same as in #593 so I've assigned this to @pdlun92.  

Really this is a firmware issue so once the firmware team decides to flash component 4, it should resolve itself.  In the #593 issues, we discuss the possibility of hiding the field if it's 0, but I think this is masking the problem, so we should not do this.  

Really #593 should be assigned as duplicate but since it's customer opened, we can just integrate the changes when ready and close both these issues out.

**Comment by whowutwut** [comment] 2016-03-14 14:33
Looking at this again.. I just changed to invalid because from xCAT's point of view, we will not do anything about this.  I am contacting the firmware team to ask why the BIOS component (component 4) always shows up as 0.00.  The firmware file does have a version associated but it doesn't reflect when the firmware is flashed.    Once I get a response we can figure out what to do....

**Comment by tingtli** [comment] 2016-03-23 08:58
@whowutwut  so we will keep this bug to trace it?

**Comment by whowutwut** [comment] 2016-04-22 13:48
The issue has been flagged to the Firmware team and they need to decided the priority. So for now, xCAT should just report back what the firmware reports back, we will not do anything to hide the output from the users even thought it does not make much sense to display `0.00`

**Closed by whowutwut** 2016-04-22 13:48 UTC
Labels: component:hw_control, priority:low, status:invalid
