### ISSUE TITLE
go-xcat failed due to dependency on libcrypto.so.10

### ISSUE THREAD

**Issue by wangwhao** [xcat2/xcat-core#1612] opened 2016-08-01 11:47 UTC
On my RHEL 6.3 server, openssl version is openssl-1.0.0-20.el6_2.5.x86_64. go-xcat update failed with such error message
```
--> Finished Dependency Resolution
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
-- 8< update_xcat stderr -- --
Unable to read consumer identity
Error: Package: ipmitool-xcat-1.8.15-2.x86_64 (xcat-dep)
           Requires: libcrypto.so.10(libcrypto.so.10)(64bit)
```
It seems we are requiring the specified version of openssl unnecessarily. Need remove the restriction.

**Comment by zet809** [comment] 2016-08-01 11:55
The ipmitool-xcat-1.8.15-2 shall be build on an early version of RH both for x86_64 and ppc64.

**Comment by whowutwut** [comment] 2016-08-02 18:07
Investigated this today...  I was able to re-create using go-xcat... 

The version that is downloaded from xcat.org has the following requirements based on querying the RPM: 

```
wget http://xcat.org/files/xcat/repos/yum/xcat-dep/rh6/x86_64/ipmitool-xcat-1.8.15-2.x86_64.rpm

[root@c910f04x42vm101 tmp]# sum ipmitool-xcat-1.8.15-2.x86_64.rpm.1
48353   282
[root@c910f04x42vm101 tmp]# rpm -qipR ./ipmitool-xcat-1.8.15-2.x86_64.rpm  | grep libcry
warning: ./ipmitool-xcat-1.8.15-2.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID c6565bc9: NOKEY
libcrypto.so.10()(64bit)  
libcrypto.so.10(libcrypto.so.10)(64bit)
```

Then re-building on a RHEL 6.0 machine resulted in the following file:
```
[root@c910f04x42vm106 x86_64]# sum ./ipmitool-xcat-1.8.15-2.x86_64.rpm 
59688   320
[root@c910f04x42vm106 x86_64]# rpm -qipR ./ipmitool-xcat-1.8.15-2.x86_64.rpm  | grep libcry
libcrypto.so.10()(64bit)  
```

Re-building this RPM on a RHEL 6.3 machine resulted in the following: 
```
[root@c910f04x42vm101 tmp]# cat /etc/*release*
Red Hat Enterprise Linux Server release 6.3 (Santiago)
Red Hat Enterprise Linux Server release 6.3 (Santiago)
cpe:/o:redhat:enterprise_linux:6server:ga:server
[root@c910f04x42vm101 x86_64]# sum ./ipmitool-xcat-1.8.15-2.x86_64.rpm 
60645   319
[root@c910f04x42vm101 x86_64]# rpm -qipR ./ipmitool-xcat-1.8.15-2.x86_64.rpm  | grep libcry
libcrypto.so.10()(64bit)  
```

So it looks like something is strange with the build machine that you used @zet809 to create the RPM,  there seems to be an extra requires: `libcrypto.so.10(libcrypto.so.10)(64bit)` that is not present when I build the ipmitool-xcat RPM.  But I always start with a new RHEL install to build the ipmitool RPM.  Could that be the case?  

I'm going to re-package this to a new xcat-deps using the version built on RHEL 6.0 above and upload to xcat.org.

**Comment by whowutwut** [comment] 2016-08-02 18:19
@tingtli @neo954  Do we have `go-xcat` testcases that will be able to detect the issue here? We should validate that `go-xcat` works with all the platform/arch/OS that we support with the latest mod level of the OS.  I think that would be best done using automation testing.  I added the "testcase_requested" label, if you have a pull request that adds the testcases you can associate with this issue and remove the label

**Comment by whowutwut** [comment] 2016-08-02 18:26
With the new package uploaded to xcat.org, I am able to install xCAT using the `go-xcat` script on RHEL 6.3 x86_64. 
```
# /tmp/go-xcat install 
....
....
Congratulations
===============

The fact that you got this far is a strong indication that xCAT bas been
installed correctly.

Please notice if this is the first time you install xCAT. You need to do one
of the following.

1. Log out and then log in again, or
2. run the following command to set the environment variables.

    for sh,
        `source /etc/profile.d/xcat.sh`
    or csh,
        `source /etc/profile.d/xcat.csh`
```
@wangwhao  You should be able to install now using `go-xcat`   thanks for reporting this bug!

**Comment by wangwhao** [comment] 2016-08-03 01:56
I was able to update xCAT to 2.12.1 this time. Thanks for the quick fix.

**Comment by zet809** [comment] 2016-08-03 02:21
@wangwhao Will you pls close this defect?

**Closed** 2016-08-03 02:23 UTC
Labels: component:go-xcat, status:pending, test:testcase_requested

**Comment by tingtli** [comment] 2018-04-25 02:58
I think go-xcat cases covers this scenarios. The problem is that we don't run the test against rhels6.3. So i remove the test_case requested label on this issue.
