### ISSUE TITLE
statelite NFS mount options are ignored 

### ISSUE THREAD

**Issue by john-d-williams** [xcat2/xcat-core#2786] opened 2017-03-30 15:34 UTC
This problems occurred with x86_64, SLES 12 SP2 and xCAT v2.13.2
The nodeset command ignores the NFS mount options in statelite table i.e.

# tabdump statelite
#node,image,statemnt,mntopts,comments,disable
"n01",,"sn1-cnfs:/install/statelite","rsize=32768,wsize=32768",,

The tftpboot file generated for the node, by nodeset is syntactically incorrect:
1. No space before MNTOPTS=
2. Mount options contained within single-quotes, which is invalid.

i.e. nodeset generates:
console=ttyS0,115200MNTOPTS='rsize=32768,wsize=32768' BOOTIF=01-${netX/machyp}

but should be:
console=ttyS0,115200 MNTOPTS=rsize=32768,wsize=32768 BOOTIF=01-${netX/machyp}

**Comment by bybai** [comment] 2017-03-31 06:03
Hi @john-d-williams， thanks for your description. I can reproduce this in my environment. And I think you know the work around, manually change the tftpboot file for the node under /tftpboot/xcat/xnba/nodes/.
Since xcat2.13.3 is released within this 1 week, it will be fixed in xcat2.13.4.

**Comment by bybai** [comment] 2017-03-31 06:58
The problem code:
sles.pm:                $kcmdline .= "MNTOPTS=\'$mntoptions\'";
should be 
sles.pm:                $kcmdline .= " MNTOPTS=$mntoptions";

**Comment by bybai** [comment] 2017-03-31 07:25
fixed in  #2791

**Closed** 2017-03-31 07:28 UTC
Labels: component:os_provision, sprint2
