### ISSUE TITLE
[fvt]2.13.5 rvitals still could return value enven using wrong command 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#3125] opened 2017-05-24 07:42 UTC
env:bmc env
build:
[root@fs1 ~]# lsxcatd -v
Version 2.13.4 (git commit 305ec7d71e4333f43f325e546daaf97fa943cd56, built Wed May 17 06:15:47 EDT 2017)
[root@fs1 ~]# 
How to reproduce:
```
1.[root@fs1 ~]# rvitals  frame45cn07 fansppd
frame45cn07: Fan 1: 4400 RPM
frame45cn07: Fan 2: 4300 RPM
frame45cn07: Fan 3: 4300 RPM
frame45cn07: Fan 4: 4300 RPM
[root@fs1 ~]# echo $?
0
2.
[root@fs1 ~]# rvitals  frame45cn07 fanspeed
frame45cn07: Fan 1: 4300 RPM
frame45cn07: Fan 2: 4300 RPM
frame45cn07: Fan 3: 4300 RPM
frame45cn07: Fan 4: 4400 RPM
--------------------> on the first step I used wrong command but still have right output

```

**Comment by gurevichmark** [comment] 2017-05-24 19:43
@junxiawang This is the same problem as in issue #3126 (perhaps one of these issues can be closed as a dup)

The problem is that `rvitals` command does not verify if specified option is a valid one.
The command appears to accept any string, as long as it contains a valid option in it.
For example, the following options generate identical output: `temp`, `testtemp`, `temptest`, `testtemptest`.
Same is true for all other `rvitals` options: `fan`, `power`, etc. (`junkfantestme`, `thisismypower`, etc. )

**Comment by zet809** [comment] 2017-06-05 06:24
Same issue with #3126 , so set duplicated with it and close this one.

**Closed by zet809** 2017-06-05 06:24 UTC
Labels: priority:normal, sprint1, type:bug
