### ISSUE TITLE
[Customer]rflash  "component 4" field always blank on node 

### ISSUE THREAD

**Issue by japuzzo** [xcat2/xcat-core#593] opened 2016-01-13 21:28 UTC
Even though the firmware update worked on updating a Firestone Power 8 system
There is an issue with what rflash is reporting

Before update:
```
# rflash -c c712f6n07 hpm/1549D.hpm 
HPM firmware version for component 1:  2.13 7B4E0100
HPM firmware version for component 2:  2.13 7B4E0100
HPM firmware version for component 4:  1.01 11010701
c712f6n07: Node firmware version for component 1:   2.11 AE4A0100
c712f6n07: Node firmware version for component 2:   2.11 AE4A0100
c712f6n07: Node firmware version for component 4:   0.00 00000000 
```
After update:
```
# rflash -c c712f6n07 hpm/1549D.hpm
HPM firmware version for component 1:  2.13 7B4E0100
HPM firmware version for component 2:  2.13 7B4E0100
HPM firmware version for component 4:  1.01 11010701
c712f6n07: Node firmware version for component 1:   2.13 7B4E0100
c712f6n07: Node firmware version for component 2:   2.13 7B4E0100
c712f6n07: Node firmware version for component 4:   0.00 00000000
```
In both cases 'component, 4 is missing from the 'node' readout.
Using raw ipmitool commands we can see where the numbers are derived:
```
# ssh ADMIN@c712f6bmc07 cat /proc/ractrends/Helper/FwInfo                          
ADMIN@c712f6bmc07's password: 
FW_VERSION=2.13.85627.65366
FW_DATE=Dec 7 2015
FW_BUILDTIME=12:41:23 CDT
FW_DESC=8335 SRC BUILD RR9 12072015
FW_PRODUCTID=1
FW_RELEASEID=RR9
FW_CODEBASEVERSION=2.X
```
Thus 'component 1' and 'component 2' are based on FW_VERSION. 
I think that 'component 2' should be FW_DATE or something more meaningful than just a repeat of  'component 1' 
```
# firmware/ipmitool-1.8.15 -U ADMIN -P admin -H c712f6bmc07 fru print | grep IBM-firestone                                                                                             
 ...
 Unknown FRU header version 0x00
 Product Version       : IBM-firestone-ibm-OP8_v1.7_1.17 
```
Now an ipmitool 'fru print' will expose 'OP8_v1.7_1.17' which is what  'component 4' is obviously based on. Thus, there is no reason that  'component 4' is all zeros, thus this is a defect.

**Comment by tingtli** [comment] 2016-01-14 01:10
@chenglch  Would you please give some comments for this issue? Thanks!

**Comment by japuzzo** [comment] 2016-01-15 19:15
This occurred when updating Firestone nodes ( Power 8 )
Using latest xCAT version (Poughkeepsie IBM lab)
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:43:11 EST 2015)
If you have any questions send me email at apuzzoj(at)us.ibm.com

**Comment by whowutwut** [comment] 2016-01-15 19:21
@pdlun92 , any ideas on this?

**Comment by whowutwut** [comment] 2016-01-18 10:46
Assign to @pdlun92  to look into this issue

**Comment by pdlun92** [comment] 2016-01-19 21:33
identified the root cause in the code.  in `xCAT-server/lib/xcat/plugins/ipmi.pm` line 1557
```
$sessdata->{ipmisession}->subcmd(netfn=>0x2c, command=>0x2f,
                                         data=>[0,$c_id/2,1],
                                         callback=>\&_on_receive_version,
                                         callback_args=>$sessdata);
```
Currently working with ipmitool raw commands to get desired output.  Hope to get a fix in within 24 hours

**Comment by pdlun92** [comment] 2016-01-20 20:44
Here is the information that rflash -c is currently displaying (some information redacted)
NOTE: While the rflash code uses the raw version of the ipmitool "hpm compprop" command for each component, the "hpm check" command displays the same information in better human readable format.
```
root@<management node>:~/fw# ipmitool -H <BMC IP> -U <BMC USER> -P <BMC Password> hpm check

PICMG HPM.1 Upgrade Agent 1.0.9:

-------Target Information-------
Device Id          : -----
Device Revision    : -----
Product Id         : ------
Manufacturer Id    : ------


--------------------------------------------------------------------------
|ID  | Name        |                     Versions                        |
|    |             |     Active      |     Backup      |      Deferred   |
--------------------------------------------------------------------------
|*  0|BOOT         |   2.13 794E0100 | ---.-- -------- |   0.00 00000000 |
|*  1|APP          |   2.13 794E0100 | ---.-- -------- |   0.00 00000000 |
|*  2|BIOS         |   0.00 00000000 | ---.-- -------- |   0.00 00000000 |
--------------------------------------------------------------------------
(*) Component requires Payload Cold Reset
```
So at the least, the Component IDs are misleading or incorrect.  Additionally, this seems to suggest that the update to the BIOS ("component 4" referenced in Issue title) may not be applied.  Looking into this further.  May contact firmware team.

**Comment by daniceexi** [comment] 2016-01-21 00:46
@zet809 I known you have more information of why there's twist between the firmware package and real system, could you give more explaination?

**Comment by whowutwut** [comment] 2016-02-08 14:12
This should really go into both the 2.11 and 2.12 branches, changing to 2.11...

**Comment by pdlun92** [comment] 2016-04-22 13:56
The firmware team has been made aware of this issue. xCAT will continue to directly report what the firmware reports in the mean time, even to display a version of "0.00."  Once a fix is reported by the firmware team xCAT will re-address this issue if it persists.

**Closed by pdlun92** 2016-04-22 13:56 UTC
Labels: component:hw_control
