### ISSUE TITLE
Support for aarch64-Server

### ISSUE THREAD

**Issue by Phhere** [xcat2/xcat-core#2946] opened 2017-04-26 12:13 UTC
Hello,
we have some arm / aarch64 based servers and would like to deploy these from xcat but there is no netboot option for this arch.
my Server definition:
```
arch=aarch64
os=centos7.3
netboot=xnba
mgt=ipmi
```

```
rinstall xxxxx osimage=xxxxx_centos7.x_compute_arm
Warning: xxxxx: xnba might be invalid when provisioning xxxxxx_centos7.x_compute_arm,valid options: "". For more details see the 'netboot' description in the output of "tabdump -d noderes".
```

The server is uefi based und should work with xnba. Do you have a small hack to enable it?

**Comment by immarvin** [comment] 2017-04-28 05:41
hi @Phhere , we will consider take this as a warning in the following releases. as a workaround, please use ``nodeset xxxx osimage=xxxxx_centos7.x_compute_arm`` and ``rpower xxxx boot`` instead of ``rinstall``. of course, you should make sure the node will be boot over network devices instead of hard disk on ``rpower``

**Comment by Phhere** [comment] 2017-04-28 08:23
Thank you for your idea but then it fails in nodeset because it does not find the vmlinux file
`Error: Install image not found in /install/centos7.3/aarch64
Error: Some nodes failed to set up install resources on server xcat, aborting`

It seems to be related to the following statement:
https://github.com/xcat2/xcat-core/blob/fc924a8d49caa79302f86d8d1b7e1bffffb6eab8/xCAT-server/lib/xcat/plugins/anaconda.pm#L1365
There is no definition for arch=aarch64, so it does not find the files also they are in the same location as x86

**Comment by immarvin** [comment] 2017-04-28 08:28
a suggestion is to fake the arch "aarch64" to "x86_64" in the osimage definition and pkgdir to /install/centos7.3/x86_64 to workaround ``nodeset``, might be little tricky.

or you can look into the code for x86_64 you pasted and hack the code to work  for aarch64

**Comment by Phhere** [comment] 2017-04-28 08:38
I hacked the code for aarch64 into anaconda.pm but now the boot failes because /tftpboot/pxelinux.0 can not run on aarch64 :(

**Comment by immarvin** [comment] 2017-04-28 08:48
@Phhere , yes, this is a problem, xCAT only shipped NBP for firmware on x86_64 and PowerPC.  XNBA is a xCAT customized NBP compiled with gpxe/ipxe source code, you can compile it for aarch64, the source code can be found in https://github.com/xcat2/xNBA

**Comment by Phhere** [comment] 2017-04-28 10:41
Your version of ipxe is from 2014 and does not include the required drivers for Cavium ThunderX-Servers.
So i have to merge it by my own and recompile it.
Is there any option in xcat to use a different xnba binary for a specific node? Because all my nodes are x86 except for this one new aarch64-Server

**Comment by immarvin** [comment] 2017-05-02 09:21
hi @Phhere , in xCAT term, "xnba" netboot method is for x86 servers only. If you want to use recompiled xnba might need to add a new netboot method, for example  "xnba-aarch64",  for aarch64-Server. then you can make a copy for xnba.pm to xnba-aarch64.pm and hack it for "xnba-aarch64". Then you can specify the netboot of aarch64-Server nodes to "xnba-aarch64".

**Comment by immarvin** [comment] 2017-05-19 06:00
no response, close this, please  reopen if any update

**Comment by Phhere** [comment] 2017-11-13 18:11
Today Redhat accounced GA for RHEL on Arm.
Is there any hope that xcat will get support for arm?
https://www.redhat.com/en/blog/red-hat-introduces-arm-server-support-red-hat-enterprise-linux
https://access.redhat.com/articles/3158541

**Comment by jjohnson42** [comment] 2017-11-20 18:38
FYI:
https://github.com/jjohnson42/xcat-core/tree/aarch64

Specifically:
https://github.com/jjohnson42/xcat-core/commit/926e026236c4f942e775a8ebde1df2d9b186557f

I'm not crazy about it as it means tftp transfer of kernel and initrd and was hoping to adapt xnba since in theory ipxe should have aarch64 support now, but haven't got aarch64 systems to work with anymore personally.

**Comment by Phhere** [comment] 2017-11-20 20:36
Thank you!
I will try it tomorrow and will give you some feedback.

**Comment by immarvin** [comment] 2018-06-19 10:02
no update , close this ticket first, will reopen it if any update

**Closed by immarvin** 2018-06-19 10:02 UTC

**Comment by viniciusferrao** [comment] 2019-10-24 21:32
Hello, I'm in need of this feature too. Jarrod already made a patch. Can it be merged on upstream?

**Comment by bybai** [comment] 2019-10-25 02:05
@viniciusferrao, do you try to use Jarrod patch https://github.com/jjohnson42/xcat-core/tree/aarch64? 

@cxhong I think xCAT can consider to support aarch64 since there was already a patch, thanks.

**Comment by viniciusferrao** [comment] 2019-10-25 02:33
I will install the machine in the next week, probably on Tuesday/Wednesday. And definitely gonna use the Jarrod patch. I can report back what happened, but reading the code appears to be really straight forward, so I think it will be good.

**Comment by bybai** [comment] 2019-10-25 04:37
@viniciusferrao, I am appreciate if you can share your results here after you have a try next week.

**Comment by besawn** [comment] 2019-11-19 14:04
@viniciusferrao Any update on whether you were able to successfully install with the patch from here: https://github.com/jjohnson42/xcat-core/commit/926e026236c4f942e775a8ebde1df2d9b186557f

**Comment by viniciusferrao** [comment] 2019-11-19 14:22
Hello @besawn, we are still waiting on the customer side. The deployment has been delayed. I will report back when we touch the machine.

**Comment by viniciusferrao** [comment] 2020-02-10 15:17
Hello, I finally got my hands on the machine. But, the patch didn't work.

How I've applied:
Created the file: `/opt/xcat/lib/perl/xCAT_plugin/armgrub.pm`
Modified the files: `/opt/xcat/lib/perl/xCAT_plugin/dhcp.pm` and `/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm`

After the modification I've imported the ISO file with `copycds`:
`copycds CentOS-7-aarch64-Everything-1908.iso`

The ISO got copied to the filesystem at: `/install/centos7.7/aarch64`.

Added the node successfully to xCAT:

>[root@headnode tftpboot]# lsdef -t node n17
Object name: n17
    arch=aarch64
    bmc=172.25.0.17
    bmcpassword=ADMIN
    bmcusername=ADMIN
    cons=ipmi
    consoleenabled=1
    currchain=boot
    currstate=install centos7.7-aarch64-compute
    groups=compute,all
    ip=172.26.0.17
    mac=b4:2e:99:3a:fe:40
    mgt=ipmi
    netboot=xnba
    nicips.ib0=172.27.0.17
    nicnetworks.ib0=application
    nictypes.ib0=InfiniBand
    os=centos7.7
    postbootscripts=otherpkgs,confignics
    postscripts=syslog,syncfiles
    profile=compute
    provmethod=centos7.7-aarch64-netboot-compute
    serialflow=hard
    serialport=0
    serialspeed=115200
    status=powering-on
    statustime=02-05-2020 17:01:38

 But when I tried to do the usual `genimage` and `packimage`, the problems started:

1. genimage fails:

> /opt/xcat/share/xcat/netboot/centos
 yum -y -c /tmp/genimage.246949.yum.conf --installroot=/install/netboot/centos7.7/aarch64/compute/rootimg/ --disablerepo=* --enablerepo=centos7.7-aarch64-0  install  bash.aarch64 dracut-network.aarch64 nfs-utils.aarch64 openssl.aarch64 dhclient.aarch64 kernel.aarch64 openssh-server.aarch64 openssh-clients.aarch64 iputils.aarch64 bc.aarch64 irqbalance.aarch64 procps-ng.aarch64 wget.aarch64 vim-minimal.aarch64 ntp.aarch64 rpm.aarch64 rsync.aarch64 rsyslog.aarch64 e2fsprogs.aarch64 parted.aarch64 net-tools.aarch64 gzip.aarch64 tar.aarch64 xz.aarch64 ethtool.aarch64
No package bash.aarch64 available.
No package dracut-network.aarch64 available.
No package nfs-utils.aarch64 available.
No package openssl.aarch64 available.
No package dhclient.aarch64 available.
No package kernel.aarch64 available.
No package openssh-server.aarch64 available.
No package openssh-clients.aarch64 available.
No package iputils.aarch64 available.
No package bc.aarch64 available.
No package irqbalance.aarch64 available.
No package procps-ng.aarch64 available.
No package wget.aarch64 available.
No package vim-minimal.aarch64 available.
No package ntp.aarch64 available.
No package rpm.aarch64 available.
No package rsync.aarch64 available.
No package rsyslog.aarch64 available.
No package e2fsprogs.aarch64 available.
No package parted.aarch64 available.
No package net-tools.aarch64 available.
No package gzip.aarch64 available.
No package tar.aarch64 available.
No package xz.aarch64 available.
No package ethtool.aarch64 available.
Error: Nothing to do
yum invocation failed

2. The directory /tftpboot/armgrub wasn't created at all. I done this by hand, copying the files from ISO, to see if at least DHCP works. But no.

For reasons unknown the DHCP server gives the IP address but the PXE process does not even start, the client machine failes to issue the DHCPREQUEST:

> Feb  9 00:49:24 headnode dhcpd: DHCPDISCOVER from b4:2e:99:3a:fe:40 via em2
Feb  9 00:49:24 headnode dhcpd: DHCPOFFER on 172.26.0.17 to b4:2e:99:3a:fe:40 via em2
Feb  9 00:49:27 headnode dhcpd: DHCPDISCOVER from b4:2e:99:3a:fe:40 via em2
Feb  9 00:49:27 headnode dhcpd: DHCPOFFER on 172.26.0.17 to b4:2e:99:3a:fe:40 via em2
Feb  9 00:49:35 headnode dhcpd: DHCPDISCOVER from b4:2e:99:3a:fe:40 via em2
Feb  9 00:49:35 headnode dhcpd: DHCPOFFER on 172.26.0.17 to b4:2e:99:3a:fe:40 via em2
Feb  9 00:49:51 headnode dhcpd: DHCPDISCOVER from b4:2e:99:3a:fe:40 via em2
Feb  9 00:49:51 headnode dhcpd: DHCPOFFER on 172.26.0.17 to b4:2e:99:3a:fe:40 via em2

So that's my status update.

**Comment by bybai** [comment] 2020-05-26 10:04
@viniciusferrao So in the end, do you have success to install ARM servers?

**Comment by viniciusferrao** [comment] 2020-05-26 15:59
Hi @bybai

Unfortunately not. But I didn't report back since I'm not sure it is xCAT fault. Something appear to be broken on the UEFI PXE code from the machine firmware, since the netboot requests does not even arrive at the DHCP server on xCAT.

The hardware is this one: https://www.gigabyte.com/ARM-Server/R281-T94-rev-100

**Comment by bybai** [comment] 2020-07-15 12:21
@viniciusferrao , I got success to install centos diskful. But I compiled ipxe by myself. I embed ipxe scripts with kernel and initrd location in ipxe xxx.efi, I changed dhcpd.conf "00:0b" to add xxx.efi.

**Comment by viniciusferrao** [comment] 2020-07-15 22:34
I tried exactly this, but nothing works. I think the issue is on the hardware that I have, the UEFI bios never tries to fetch an IP during the boot phase and I don't have other ARM machines to test. Which hardware you've tested?

**Comment by bybai** [comment] 2020-07-16 04:03
@viniciusferrao "UEFI bios never tries to fetch an IP".  I can not get dhcprequests, when using normal host xxxx section in dhcpd.lease. Then it can get dynamic range ip, or only mac bind ip, no other dhcp advance configuration in lease file. only left mac and fix-address in one host section.

**Comment by samveen** [comment] 2020-08-28 14:05
@viniciusferrao Can you give me an idea of what servers you're using? I'm definitely interested in getting xcat to work on aarch64/arm64 platform too.

**Comment by viniciusferrao** [comment] 2020-08-28 20:58
Hello, I've mentioned in an earlier reply:
The hardware is this one: https://www.gigabyte.com/ARM-Server/R281-T94-rev-100

Unfortunately I can't put the machine in maintenance to do the testing... it is on a client. We ended up installing the system baremetal without xCAT, which is bad.
