### ISSUE TITLE
[CUSTOMER] If packimage is not run, osimage in the chain table will fail on netboot images

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2362] opened 2017-01-03 16:11 UTC
xCAT provides the ability for the `chain` table attribute to automatically install an operating system by using the `osimage` keyword in the chain table.  For example: 

```
chain=runcmd=bmcsetup,osimage=rhels7.3-GA-ppc64le-netboot-compute
```

for diskful installs, this is OK, but for diskless installs, if the osimage is not prepared, the error message is quite cryptic and hard to figure out the cause.  

The logs would show a cryptic msg similar to: 

```
xcat[33755]: xcatd: destiny plugin bug, pid 33755, process description: 'xcatd SSL: nextdestiny for cn5@cn5: destiny instance: petitboot instance: destiny instance' with error 'Died at /opt/xcat/sbin/xcatd line 1944, <$parfd> line 2.#012'
```

But looking at the `commands.log` , we see the reason: 

```
====================================================
[Date]       2016-09-28 10:01:12
[ClientType]
[Request]    nextdestiny
[Response]
Error: Did you run "genimage" before running "packimage"? kernel cannot be found at /install/netboot/rhels7.2/ppc64le/compute/kernel on mn01
...
...
```

Is there any way to better reflect the error message back up to the user?  Some thoughts:
- Instead of a "Died" have a better msg in the log files
- Update the status in the node definition with a meaningful message  "Could not install <os>, verify image is available on the server" 
- xCAT probe command to detect incorrect configuration?

**Comment by chenglch** [comment] 2017-01-09 03:13
Hi @tingtli, can you help recreate this issue in our test environment? From the description above, I can not locate where the real error is.

**Comment by zet809** [comment] 2017-01-09 12:40
@whowutwut Hi, victor, it seems the result got by nextdestiny had already ncluded useful messages. It would  return 3 error messages, the 1st one pointed to the root cause. And the last is got from xcatd.

Maybe just outputting the 1st error message is reasonable? What is your idea?

[xCAT Genesis running on frame45cn14 /]# /bin/nextdestiny 192.168.3.29:3001

  <error>**No packed image for platform rhels7.3-GA, architecture ppc64le, and profile compute found at /install/netboot/rhels7.3-GA/ppc64le/compute/rootimg.gz or /install/netboot/rhels7.3-GA/ppc64le/compute/rootimg.sfs on fs1.pok.stglabs.ibm.com, please run packimage (e.g.  packimage -o rhels7.3-GA -p compute -a ppc64le**</error>
  <errorcode>1</errorcode>
  <error>Some nodes failed to set up netboot resources on server fs1.pok.stglabs.ibm.com, aborting</error>
  <errorcode>1</errorcode>
  <error>destiny plugin bug, pid 81261, process description: 'xcatd SSL: nextdestiny for frame45cn14@frame45cn14: destiny instance: petitboot instance: destiny instance' with error 'Not a reference at /opt/xcat/sbin/xcatd line 2441, &lt;$parfd&gt; line 2.
'</error>
  <errorcode>1</errorcode>

**Comment by whowutwut** [comment] 2017-01-10 03:31
@zet809  I believe those messages that we see when we execute it manually in the genesis kernel  are not saved in any xCAT log files except for the `commands.log` so if we can make the messages more transparent in `/var/log/messages` or `/var/log/xcat/cluster.log` , it should be OK. 

As we talked on the phone, maybe it is better to gracefully exit instead of the die which causes the plugin bug.  That looks like an unexpected error from the users point of view.

**Comment by zet809** [comment] 2017-01-10 09:35
@whowutwut Hi, victor, a small take with @hu-weihua shows that we don't need to write the redundant error message into log files other than commands.log. So within pull request #2388, I just remove the incorrect error message about xcatd.

**Comment by whowutwut** [comment] 2017-02-24 18:43
@zet809  I'm trying to verify this out.. but  Based on the description in PR #2388, I can't tell the intended behavior. Also from the conversation above, I can't tell the intended fix provided for this issue?  Is it just to remove the "died" message and then continue to only provide a message in commands.log? 

From our investigation yesterday, it seems like there's no improvement inside the genesis kernel.  So if the user rcons, the window will just keep spinning "retrying xcat in 60 seconds..." . Nothing here indicating why we cannot continue.  

Can we get the error message to be more informative in the genesis shell... or maybe somewhere in /var/log/xcat/computes.log.  It's not intuitive that the commands.log message has the error... because we are debugging compute node discovery and the user did not directly issue a command.

**Comment by adambertsch** [comment] 2017-02-24 18:50
I was the customer who opened this PMR.  The intent here is that the main log, instead of saying "died" might say something like:  File not found <location of packed image>, have genimage and packimage been run?

**Comment by adambertsch** [comment] 2017-02-24 18:52
Basically the content from commands.log is what we should see presented immediately, since the current log message with the perl die() output doesn't point us towards anything useful.  It would also be reasonable to put a pointer to commands.log in the die() output.  Basically spelunking in the source to find out why it didn't work shouldn't be necessary.

**Comment by whowutwut** [comment] 2017-02-25 00:18
@adambertsch Thanks! Agreed. The error should  be propagated up

**Comment by whowutwut** [comment] 2017-02-27 19:26
@zet809  The fix should not be accepted... moving to 2.13.3...   can we make the error more transparent?  Seems like two enhancements could be..     

Like Adam said above... instead of the Error, can we have a more descriptive message...    
"Error while trying to boot <osimage name>.  If diskless, did you run genimage/packimage?" 

Then on the console, can we have a more descriptive message about what is happening, instead of "Communicating with xCATd in 60 seconds" looping.... 

Please assign to someone if you do not have the time for this release.

**Comment by zet809** [comment] 2017-03-02 09:57
@whowutwut Hi, victor, yes, I agree with you that we shall have a better solution. What I am doing now include:
1. To have the xcatd return 1 error message when checking destiny.
2. In genesis, for nextdestiny script, it can return error message rather than hung to get a valid value.
3. In doxcat, if the nextdestiny script get an error destiny, it can do it current work first, then output the error mesage or unknow destiny and output it.
The pull request will be ready tomorrow and let you know once it is ready.

**Comment by zet809** [comment] 2017-03-10 09:52
hi, @whowutwut , my modification are include in pull request #2593 , pls help to take a look at. Thx!

**Comment by zet809** [comment] 2017-04-24 03:00
Hi, @whowutwut , I had verified this issue and the error message can be found within compute.log, I had pasted the message in slack channel. 
So I close this defect, if there is any concerns pls fell free to reopen this defect. Thx!

**Closed by zet809** 2017-04-24 03:00 UTC
Labels: component:os_provision, sprint1, status:pending
