### ISSUE TITLE
[PCM]Sequence disordered when synchronizing /etc/passwd that has special characters

### ISSUE THREAD

**Issue by SmilefoxEd** [xcat2/xcat-core#3827] opened 2017-08-31 10:02 UTC
When the updatenode command is run, because of the special characters, such as +, @, *, the sequence of the lines get changed.
**FROM**
`pcmadmin:x:30496:30496:Spectrum Cluster Foundation Server:/var/lib/pcmadmin:/bin/sh`
`lsfadmin:x:30498:30498::/home/lsfadmin:/bin/bash`
`mysql:x:27:27:MariaDB Server:/var/lib/mysql:/sbin/nologin`
`advocate:x:993:989:Advocate:/opt/IBM/advocate:/sbin/nologin`
`+@sysadmins::::::`
`+@p8users::::::`
`+:*:::::/sbin/nologin`

**TO**
`+@p8users::::::`
`lsfadmin:x:30498:30498::/home/lsfadmin:/bin/bash`
`+:*:::::/sbin/nologin`
`mysql:x:27:27:MariaDB Server:/var/lib/mysql:/sbin/nologin`
`advocate:x:993:989:Advocate:/opt/IBM/advocate:/sbin/nologin`
`+@sysadmins::::::`
`pcmadmin:x:30496:30496:Spectrum Cluster Foundation Server:/var/lib/pcmadmin:/bin/sh`

The sequence does matter for the below three lines only to make NIS work on compute nodes. The below three lines should be pushed to CNs, in the same sequence.
Can we make it work?
`+@sysadmins::::::`
`+@p8users::::::`
`+:*:::::/sbin/nologin`

**Comment by immarvin** [comment] 2017-08-31 11:39
hi, what command did you run when you observed this issue?

**Comment by whowutwut** [comment] 2017-08-31 11:45
@robin2008 FYI, I think this is related to the open PMR you are looking at

**Comment by robin2008** [comment] 2017-09-01 01:46
This issue is caused by CFMutil.pm,
updatenode will call it to generate a mergefile first (based on the backup on MN and the current passwd file),  and then using xdcp to populated to CN.

Now the populate is no issue, but the generating file is messed.

**Comment by robin2008** [comment] 2017-09-04 03:16
Fix it by https://github.com/xcat2/xcat-core/pull/3839

**Comment by robin2008** [comment] 2017-09-04 03:16
It requires to be merged into 2.12.3-pcm and 2.13-pcm branch.

**Closed** 2017-09-04 03:20 UTC

**Comment by robin2008** [comment] 2017-09-04 05:02
merge to 2.12.3-pcm  https://github.com/xcat2/xcat-core/pull/3840

**Comment by robin2008** [comment] 2017-09-04 05:05
merge to 2.13-pcm https://github.com/xcat2/xcat-core/pull/3842
