### ISSUE TITLE
can't use rflash if node fails to boot after using rflash.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#2706] opened 2017-03-21 18:44 UTC
We did the following on a node.

```
rflash c460c037 8335GTB_820.1642.20170316o_update.hpm
```
After the flash was done, the node refused to boot...

and reventlog showed:
```

[root@c460mgt01 garrison]# reventlog c460c[037] | p8oemsel.pl
c460c037: 03/20/2017 10:30:40 System Firmware Progress, Baseboard or motherboard initialization (FW Boot Progress)
c460c037: 03/20/2017 10:31:36 Watchdog 2, Hard Reset OEM (Watchdog)
c460c037: 03/20/2017 10:31:39 OEM SEL c0:3a1503: Primary side boot failed
c460c037: 03/20/2017 13:59:40 OEM SEL c0:3a1503: Primary side boot failed
c460c037: 03/21/2017 14:30:25 OEM SEL c0:3a1504: Golden side boot failed
```

Subsequent attempts to use rflash to recover resulted in:
```
rflash c460c037 8335GTB_820.1636.20161013b_update.hpm
c460c037: Error: Unknown FRU header version 0x00
```

so once a node decides it is not booting, we can't use rflash again.

**Comment by whowutwut** [comment] 2017-03-21 19:03
The error `Unknown FRU header version 0x00` is caused by the node requiring a power on before FRU information is populated after a firmware flash.  

We need to talk to the FW team about what the proper steps is to recover from this situation...

**Comment by chenglch** [comment] 2017-03-22 01:54
@whowutwut As the issue #2682, I have to refactor the code structure that wait the child processes, I will add the `check  ipmi session` and `power on` steps to fix this issue at the same time.

**Comment by chenglch** [comment] 2017-03-28 03:43
@whowutwut 
```
Running ipmitool command /opt/xcat/bin/ipmitool-xcat -H 50.45.2.1 -I lanplus -U ADMIN -P admin fru print 3 failed:  Unknown FRU header version 0x00
```

I upgrade the firmware to `8335GTB_820.1642.20170307o_update.hpm`, hit this issue again. `power on` can not solve this problem on this version of firmware.  From my experience, on an earlier firmware version, FRU information was not missing, even if we did not run power on after rflash.

**Comment by chenglch** [comment] 2017-03-28 09:15
@zet809 
We need more help from firmware team to find the proper steps, this issue can not be solved in this release, please help remove the high label.

**Comment by ralphbellofatto** [comment] 2017-03-28 11:56
There needs to be a way to bypass the fru check as the first thing to try to fix after hitting this problem is to reflash the device,  

Right now the only way to reflash the device is through ipmitool directly.  And if not done properly, will cause the BMC to loose its ip address assignment, further compounding the problem.

**Comment by zet809** [comment] 2017-04-05 00:47
So, it means we can add a new option 'force' to allow to update the BMC firmware without checking fru, right?

**Comment by gurevichmark** [comment] 2017-04-05 18:52
I think we might have found a reason for this failure.

After the firmware update is done, the BMC returns ready state `00` for about 13 seconds. It will then reboot itself and after 1 minute will return `c0`. Finally after 1 more minute it will start returning ready state again `00`.

It seems to me that our `rflash` code issues firmware update and then immediately starts waiting for `00` state. It catches the very first `00` before the BMC gets a chance to reboot. 

Suggestion from Viswanathan is to sleep for 60 seconds after firmware update. Then wait for `c0` state. Once `c0` is received, wait for `00`. After that we can issue `chassis power on`.

**Comment by whowutwut** [comment] 2017-04-05 21:44
Great job investigating this! it's been quite a pain!!

**Comment by gurevichmark** [comment] 2017-04-06 17:54
Taking ownership of this issue.

**Comment by gurevichmark** [comment] 2017-04-06 21:07
Fixed by PR #2807.
On advice from @whowutwut implemented a slightly different solution than suggested above.
Wait for BMC ready code to be `00` for a little longer than 1 min before assuming BMC is ready.

**Comment by whowutwut** [comment] 2017-04-14 17:28
Closing this issue.

**Closed by whowutwut** 2017-04-14 17:28 UTC
Labels: component:hw_control, priority:high, sprint2, status:pending

**Comment by whowutwut** [comment] 2017-04-25 13:48
@chenglch create a patch for users on xCAT 2.13.1 to apply the fixes contained in the PR associated with the issue.   A patch is currently only provided for version 2.13.1

_The recommendation is to upgrade to the latest version of xCAT (>= 2.13.3)_ 

[rflash.patch.2.13.1.tar.gz](https://github.com/xcat2/xcat-core/files/955133/rflash.patch.2.13.1.tar.gz)

Contents: 
```
$ sum rflash.patch.2.13.1.tar.gz
64822    18
$ tar -tzvf rflash.patch.2.13.1.tar.gz
-rw-r--r-- longcheng/wheel 43913 2017-04-24 23:18 rflash_redhat.patch
-rw-r--r-- longcheng/staff 42174 2017-04-24 22:26 rflash_ubuntu.patch
```

### Instructions
Apply, as root: 
1) download the rflash.patch.2.13.1.tar.gz
2) mkdir -p /tmp/rflash.patch
3) cd /tmp/rflash.patch/ 
4) tar -xzvf /path_to/rflash.patch.2.13.1.tar.gz
5) cd /   # must change to the root directory 
6) patch -p1 < /tmp/rflash.patch/rflash_redhat.patch

### Example: 
```
[root@fs2vm104 ~]# pwd
/root
[root@fs2vm104 ~]# sum rflash.patch.2.13.1.tar.gz
64822    18
[root@fs2vm104 ~]# mkdir -p /tmp/rflash.patch
[root@fs2vm104 ~]# cd /tmp/rflash.patch/
[root@fs2vm104 rflash.patch]# tar -xzvf /root/rflash.patch.2.13.1.tar.gz
rflash_redhat.patch
rflash_ubuntu.patch
[root@fs2vm104 rflash.patch]# cd /
[root@fs2vm104 /]# patch -p1 < /tmp/rflash.patch/rflash_redhat.patch
patching file opt/xcat/lib/perl/xCAT_plugin/ipmi.pm
patching file opt/xcat/share/doc/man1/rflash.1.html
patching file opt/xcat/share/man/man1/rflash.1
```
