### ISSUE TITLE
[DEV]kvm_nodedata not updated by chdef when changing vmstorage from dev to dir

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#199] opened 2015-09-18 15:34 UTC
vmstorage attribute for kvm1 originally set to "phy:/dev/sdb1" Following attempts to change to directory storage, "/var/lib/libvirt/images", rpower would give an error referring to "/dev/sbd1" 

```
chdef kvm1 vmstorage=dir:///var/lib/libvirt/images
mkvm kvm1 -s 20G
nodeset kvm1 osimage=<osimage>
rpower kvm1 on
```

The following error is observed

```
kvm1: Error: Cannot access storage file '/dev/sdb1' (as uid:107, gid:107): No such file or directory
Error: A fatal error was encountered, the following information may help identify a bug: Can't use string ("Cannot access storage file '/dev"...) as an ARRAY ref while "strict refs" in use at /opt/xcat/sbin/xcatd line 3008.
ERROR/WARNING: communication with the xCAT server seems to have been ended prematurely
```

Additionally, tabdump reveals

```
[root@kvm1 ~]# tabdump kvm_nodedata
#node,xml,comments,disable
      ...
      <source dev=""/dev/sdb1"" />
      <target bus=""ide"" dev=""hda"" />
    </disk>
```

"source dev" remains set to "/dev/sdb1" while lsdef shows

```
[root@kvm1 ~]# lsdef kvm1
Object name:kvm1
    ...
    **vmstorage=dir:///var/lib/libvirt/images**
```

"vmstorage" correctly set to "dir:///var/lib/libvirt/images

**Comment by whowutwut** [comment] 2015-09-18 15:47
Pat and I will take a look at this

**Comment by zet809** [comment] 2015-11-11 15:11
Have you run "rmvm <kvm1>" before running "mkvm <kvm1> -s 20G"?

**Comment by pdlun92** [comment] 2015-11-11 20:06
```
rmvm kmv1
rm kvm1.hda.qcow2   # on hypervisor in /var/lib/libvirt/images
mkvm kvm1 -s 20G
rpower kvm1 on
```

Node was provisioned successfully and ``source dev`` attribute was removed from ``kvm_nodedata`` table.

I think this may have been user error on my part, rather than a bug

**Comment by whowutwut** [comment] 2015-11-12 00:00
If I recall correctly...I think the initial issue is setting the vmstorage attribute to a hard drive (/dev/sdb)... And then trying to change it to a directory storage.   even though it changes in the node object, the kvm_nodedata was not updated..

In the last case when you are doing a rmvm, The storage was already set to the directory so it changed ok. I still think there is a problem here...

**Comment by zet809** [comment] 2015-11-12 05:20
Update node definition won't affect the kvm_nodedata entries. 
Only chvm or mkvm can update the kvm_nodedata table. But for this case, changing vmstorage attribute, only rmvm/mkvm can regenerate the kvm_nodedata entries.

**Comment by zet809** [comment] 2015-11-19 05:40
@whowutwut Do you think whether we can close this defect?

**Comment by whowutwut** [comment] 2015-11-23 02:34
I'd like to move this to 2.12 so that we can take a closer look.  Pat and I talked about this on Friday, maybe we need to modify the documentation in the section where we execute "mkvm" If this fails, the user need to rmvm and re-create it..     I think this is the problem here....  

If we defined the VM incorrectly the FIRST time, then we try to chdef the VM, from the lsdef, it appears that the attribute has changed,  but in the kvm_nodedata table, the attribute is still the old one... then mkvm fails... 

With the documentation change, maybe it would be good to know which attributes can be changed with chvm and which one cannot....

**Comment by zet809** [comment] 2015-11-23 08:22
Yes, I agree with you that if there is an VM created before with the same name as specified, the mkvm need to return an error msg like "The VM xxx have been created before, pls use other name or using '-f' option to overwrite the old one".

**Comment by tingtli** [comment] 2016-03-23 07:33
@pdlun92 @whowutwut  Is there any updates for this bug?

**Comment by whowutwut** [comment] 2016-03-26 00:11
No, there has been some higher priority items going on, this one we will keep as low priority and hopefully can get around to it.

**Comment by daniceexi** [comment] 2016-04-26 08:25
Since this is low priority issue and it does not impact the real functionality, I move it to 2.12.1.

**Comment by gurevichmark** [comment] 2017-03-22 19:27
I think the problem is more generic than just `vmstorage`. Any VM related attribute change using `chdef` for node object is not reflected in the `kvm_nodedata`.  Similarly, any attribute change using `chvm` is reflected in the `kvm_nodedata`, but not in the VM related attribute for node object. Basically, we have 2 different definitions for the same VM, which can get out of sync.

I can think of two different ways to address this:
1. (Simple) Any time `chdef` is issued for VM object or `chvm` is issued, we can display a warning message telling the user how to make sure both definitions are in sync.
2. (More complex) Any time `chdef` is issued for VM object, call an appropriate `chvm` command to update `kvm_nodedata`. Any time `chvm` is issued, call an appropriate `chdef` command to update node object.

**Closed** 2018-06-19 08:46 UTC
Labels: component:virtualization, priority:low, status:future, status:won't fix, type:bug

**Comment by kleykenb** [comment] 2018-06-20 10:01
Just wanted to chime in from own experience : currently it is possible to skip 'mkdef <node>' altoghether and simply create a definition for a node by doing 'chdef <node> group=kvm ip= .... '. This gives the impression that all is well but without the 'mkdef' the sync with kvm_nodedata appears to not work and subsequently commands like 'mkvm' fail.
