### ISSUE TITLE
Confignetwork cases failed in automation 

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#3394] opened 2017-07-05 02:41 UTC
1. ubuntu16.04.1-ppc64el

confignetwork_secondarynic_updatenode, confignetwork_secondarynic_nicextraparams_updatenode, confignetwork_niccustomscripts, confignetwork_secondarynic_thirdnic_multiplevalue_updatenode

2. sles12.2-ppc64le

confignetwork_s_installnic_secondarynic_updatenode, confignetwork_niccustomscripts

3. rhels7.3-ppc64le

confignetwork_s_installnic_secondarynic_updatenode, confignetwork_niccustomscripts

4. rhels7.3-ppc64

confignetwork_s_installnic_secondarynic_updatenode, confignetwork_niccustomscripts

5. rhels6.9-ppc64

confignetwork_s_installnic_secondarynic_updatenode, confignetwork_niccustomscripts

6. sles11.4-ppc64

confignetwork_s_installnic_secondarynic_updatenode, confignetwork_secondarynic_nicextraparams_updatenode, confignetwork_niccustomscripts, confignetwork_secondarynic_thirdnic_multiplevalue_updatenode

7. ubuntu14.04.4-ppc64el

confignetwork_s_installnic_secondarynic_updatenode, confignetwork_secondarynic_updatenode, confignetwork_secondarynic_nicextraparams_updatenode, confignetwork_niccustomscripts, confignetwork_secondarynic_thirdnic_multiplevalue_updatenode

**Comment by bybai** [comment] 2017-07-05 03:16
I checked all the failed test cases. These failures are not caused by confignetwork code. Since these test cases are first running on all the platforms, there are little failures in some output check. All the failed testcases should be enhanced for autotest env.

**Comment by tingtli** [comment] 2017-07-05 08:22
Fixed in PR#3402

**Closed** 2017-07-12 07:00 UTC
Labels: priority:high, sprint1, status:pending
