### ISSUE TITLE
The "switches" table doesn't support groups

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#2450] opened 2017-01-28 01:04 UTC
### Issue
The `switches` table doesn't support specifying groups as the first field. It could be very useful for installation with many similar switches.

### Observed behavior
If I define the `switchtype` for a group name in the `switches` table:
```
# tabdump switches
#switch,snmpversion,username,password,privacy,auth,linkports,sshusername,sshpassword,protocol,switchtype,comments,disable
"switch_group",,,,,,,,,,"Dell",,
```
the nodes belonging to this group don't inherit the switchtype:
```
# lsdef test_switch -i groups,switchtype
Object name: test_switch
    groups=switch_group
    switchtype=
```

### Expected behavior
```
# lsdef test_switch -i groups,switchtype
Object name: test_switch
    groups=switch_group
    switchtype=Dell
```

**Comment by immarvin** [comment] 2017-02-07 06:53
hi @bybai ,would you please take a look at this?

thanks

**Comment by zet809** [comment] 2017-03-21 07:57
Hi, @bybai , will you pls verify this issue? Thx!

**Comment by bybai** [comment] 2017-03-22 07:44
Hi @zet809 , the issue can be reproduced using new code.
Hi @cxhong , could you look at this issue, there are switch table and switches table, I think you know it better.

**Comment by cxhong** [comment] 2017-03-22 13:36
yes,  I noticed this issue while I was working on PDU object.  As I mentioned before, if we change to have switch object,   it will lost all the information in the switches table while user upgrade the xcatd.  User needs to save infos in the switches table, after upgrade xcatd , then restore the switches table.   We need to very carefully to document this process to somewhere.

**Comment by zet809** [comment] 2017-03-24 01:51
Hi, @cxhong , is there something wrong when we deal with the switches table? Why the information lost when updating xCAT?

**Comment by cxhong** [comment] 2017-03-27 21:05
@zet809 ,  it looks like group only supports node object.  we can create switch object, but won't inherit attributes from group.     ```getNodeAttribs```  routine are getting attributes from nodelist which build from "node", "groups".    I don't think there is easy way to create a switchlist from "switch" and "group" based on xcat framework.

**Comment by kcgthb** [comment] 2017-03-27 21:17
@cxhong I thought switches were a regular node object, with a specific "nodetype" attribute:
```
#  lsdef -t node sh-ethsw-101-01 -i nodetype
Object name: sh-ethsw-101-01
    nodetype=switch
```

Actually, when I list all the nodes in my system with `lsdef -t node`, I get the switches in the list.

**Comment by cxhong** [comment] 2017-03-28 00:26
yes, switch is in the nodelist, but switches table use "switch" as key.
````
switches => {
        cols => [qw(switch snmpversion username password privacy auth linkports sshusername sshpassword protocol switchtype comments disable)],
        keys         => [qw(switch)],
        nodecol      => "switch",
        table_desc   => 'Parameters to use when interrogating switches',
        descriptions => {
            switch => 'The hostname/address of the switch to which the settings apply',
            ...............................
`````
that's why it won't inherit any attributes from the group.   In order to do this,  I have to change the keyword "switch" to "node",   so, we can use "node" as objkey to access switch hash table and include switches table to the nodelist.  but once I change that,  it will lose all the entries in the switches table after upgrade xCAT with this version of Schema.

**Comment by daniceexi** [comment] 2017-03-28 00:34
@cxhong it might be unacceptable to change the interface that does not support backward compatibility. 
Hua Zhong did the group support for osimage. The same code logic can be used for switch support. The only concern is the performance impact for the node group handling with this change.

**Comment by cxhong** [comment] 2017-03-29 20:48
@chenglch , can u help to look into this issue?

**Comment by cxhong** [comment] 2017-05-26 13:13
close the issue.

**Closed by cxhong** 2017-05-26 13:13 UTC
Labels: component:network, sprint1, status:pending, type:feature
