### ISSUE TITLE
Switch discovery with cisco switch is not working

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#2596] opened 2017-03-03 15:46 UTC
Discovery with a Cisco switch is failing:
```
[root@c712csm1 ~]# xcatprobe switch_macmap switch
Switch      Port      MAC address         Node
------------------------------------------------------------------
c712f11u26  Gi1/0/1          N/A
c712f11u26  Gi1/0/10         N/A
c712f11u26  Gi1/0/11         N/A
c712f11u26  Gi1/0/12         N/A
c712f11u26  Gi1/0/13         N/A
c712f11u26  Gi1/0/14         N/A
c712f11u26  Gi1/0/15         N/A
c712f11u26  Gi1/0/16         N/A
c712f11u26  Gi1/0/2          N/A
c712f11u26  Gi1/0/3          N/A
c712f11u26  Gi1/0/39         N/A
c712f11u26  Gi1/0/40         N/A
c712f11u26  Gi1/0/41         N/A
c712f11u26  Gi1/0/42         N/A
c712f11u26  Gi1/0/43         N/A
c712f11u26  Gi1/0/44         N/A
c712f11u26  Gi1/0/45         N/A
c712f11u26  Gi1/0/46         N/A
c712f11u26  Gi1/0/47         N/A
c712f11u26  Gi1/0/49         N/A
c712f11u26  Gi1/0/5          N/A          c712f11n05
c712f11u26  Gi1/0/50         N/A
c712f11u26  Gi1/0/51         N/A
c712f11u26  Gi1/0/52         N/A
c712f11u26  Gi1/0/6          N/A          c712f11n06
c712f11u26  Gi1/0/7   98:be:94:66:23:86   s1p7,c712f11n07
c712f11u26  Gi1/0/8   98:be:94:66:0e:c6   s1p8,c712f11n08
c712f11u26  Gi1/0/9          N/A
------------------------------------------------------------------
```

```
c712f11u26#show interface status

Port Name Status Vlan Duplex Speed Type
Gi1/0/1 notconnect 1 auto auto 10/100/1000BaseTX
Gi1/0/2 notconnect 1 auto auto 10/100/1000BaseTX
Gi1/0/3 notconnect 1 auto auto 10/100/1000BaseTX
Gi1/0/4 notconnect 1 auto auto 10/100/1000BaseTX
Gi1/0/5 notconnect 1 auto auto 10/100/1000BaseTX
Gi1/0/6 notconnect 1 auto auto 10/100/1000BaseTX
Gi1/0/7 connected 1 a-full a-1000 10/100/1000BaseTX
Gi1/0/8 connected 1 a-full a-1000 10/100/1000BaseTX
Gi1/0/9 notconnect 1 auto auto 10/100/1000BaseTX
```

**Comment by zet809** [comment] 2017-03-06 02:31
@markprez Hi, mark, what the issue is?
For me, in the output of 'show interface status', it seems port 1-6 is DOWN, you need to  check the physical link.
As for the output of xcatprobe, the N/A means no information got for that port.
Pls let me know if there is any more concerns. Thx!

**Comment by cxhong** [comment] 2017-03-06 14:31
@markprez , The results are different than the time I was look at.  It looks like have correct information now. 
````
c712f11u26  Gi1/0/5          N/A          c712f11n05
c712f11u26  Gi1/0/50         N/A
c712f11u26  Gi1/0/51         N/A
c712f11u26  Gi1/0/52         N/A
c712f11u26  Gi1/0/6          N/A          c712f11n06
c712f11u26  Gi1/0/7   98:be:94:66:23:86   s1p7,c712f11n07
c712f11u26  Gi1/0/8   98:be:94:66:0e:c6   s1p8,c712f11n08
````
Port 7 and 8 have mac address and port 5 and 6 didn't show because they are not connect.
```
c712f11u26>show mac address-table
..........................
2    70e2.8414.0122    DYNAMIC     Gi1/0/22
   2    70e2.8414.0f88    DYNAMIC     Gi1/0/23
   2    70e2.8414.0f8d    DYNAMIC     Gi1/0/24
   2    a042.3f32.0019    DYNAMIC     Gi1/0/17
   1    98be.9466.0ec6    DYNAMIC     Gi1/0/8
   1    98be.9466.2386    DYNAMIC     Gi1/0/7

c712f11u26>show interface status
............................................
Gi1/0/5                      notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/6                      notconnect   1            auto   auto 10/100/1000BaseTX
Gi1/0/7                      connected    1          a-full a-1000 10/100/1000BaseTX
Gi1/0/8                      connected    1          a-full a-1000 10/100/1000BaseTX
````

**Comment by zet809** [comment] 2017-03-08 08:01
It seems that it is not a issue for xCAT. @markprez Will you pls close this defect?

**Comment by cxhong** [comment] 2017-03-13 13:50
I will close this issue.

**Closed by cxhong** 2017-03-13 13:50 UTC
Labels: component:discovery
