### ISSUE TITLE
[xCAT 2.9.1]`discoverydata.method` not updated for manually discovered node

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#3091] opened 2017-05-18 05:24 UTC
We have been doing manual discovery for a large number of nodes in our environment. Everything worked as expected except for one weird issue: For a very small number of nodes, `manual` discovery works fine, but the `discoverydata.method` attribute for the nodes isn't updated to manual.
For the problem nodes, everything works as expected: the node definitions, the destiny chain, and all the rest, as far as I can see in the logs. There isn't any error message in the logs, just messages that show that everything is proceeding with the nodes as expected.

OS configuration:
```
[vndc:samveen@xcatmn1 ~]$ uname -a
Linux xcatmn1.vndc 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[vndc:samveen@xcatmn1 ~]$ cat /etc/system-release
CentOS Linux release 7.1.1503 (Core)
```
xCAT and DHCP versions:
```
[vndc:samveen@xcatmn1 ~]$ lsxcatd  -v
Version 2.9.1 (git commit 7f6043fffd62d482931b17b60f9488eb5754fdc1, built Thu Mar 19 03:25:35 EDT 2015)
[vndc:samveen@xcatmn1 ~]$ lsxcatd  -t
```
This is a Management Node

**Comment by daniceexi** [comment] 2017-05-18 09:00
@samveen So you did run ``nodediscoverdef`` command update the node from discovered entry, but the ``method`` column was not changed to manual in the **discoverydata** table.

Did you see the message like **"xcat.discovery.nodediscover: <node> has been discovered"** when you run ``nodediscoverdef``?

**Comment by samveen** [comment] 2017-05-18 11:44
Yes. It did:
 Looks like I forgot to add logs to the OP:
```
[vndc:samveen@xcatmn1 ~]$ nodediscoverls -t undef |grep  00000000-0000-0000-0000-0CC47AA33EAC
  00000000-0000-0000-0000-0CC47AA33EAC    spare-a282135x7408239undef                    A282135X7408
[vndc:samveen@xcatmn1 ~]$ nodediscoverls  -l -u 00000000-0000-0000-0000-0CC47AA33EAC
Object uuid: 00000000-0000-0000-0000-0CC47AA33EAC
    node=spare-a282135x7408239
    method=undef
    discoverytime=05-17-2017 13:15:15
    arch=x86_64
    cpucount=40
    cputype=Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
    memory=128828MB
    serial=A282135X7408239
    nicdriver=enp1s0f0!ixgbe,enp1s0f1!ixgbe
    nicipv4=enp1s0f0!10.81.106.225/24,enp1s0f1!10.18.30.149/20
    nichwaddr=enp1s0f0!0C:C4:7A:A3:3E:AC,enp1s0f1!0C:C4:7A:A3:3E:AD
    nicpci=enp1s0f0!0000:01:00.0,enp1s0f1!0000:01:00.1
    switchname=enp1s0f0!SGDC-LSW-00106,enp1s0f1!SGDC-E3-EX3300T-41RU-E3-2-SRVC
    switchaddr=enp1s0f0!10.17.16.51
    switchdesc=enp1s0f0!corrupted TLV ilen = 322, tlv_len=360,enp1s0f1!Juniper Networks, Inc. ex3300-48t , version 12.3R9.4 Build date: 2015-02-12 11:25:30 UTC
    switchport=enp1s0f0!xe-0/0/13,enp1s0f1!ge-0/0/13.0
[vndc:samveen@xcatmn1 ~]$ sudo grep spare-a282135x7408239 /var/log/messages-20170518  |grep -v lsdef
2017-05-17T13:06:44.235651+00:00 xcatmn1.vndc xCAT[20845]: xCAT: Allowing mkdef spare-a282135x7408239-ipmi groups=allipmi mac=0c:c4:7a:d5:34:55 ip=10.18.5.51 for samveen from localhost
2017-05-17T13:06:45.363726+00:00 xcatmn1.vndc xCAT[20876]: xCAT: Allowing makehosts to spare-a282135x7408239-ipmi for samveen from localhost
2017-05-17T13:06:46.599412+00:00 xcatmn1.vndc xCAT[20913]: xCAT: Allowing makedns to spare-a282135x7408239-ipmi for samveen from localhost
2017-05-17T13:06:50.979914+00:00 xcatmn1.vndc named[45080]: client 10.18.16.10#45424/key xcat_key: updating zone 'vndc/IN': adding an RR at 'spare-a282135x7408239-ipmi.vndc' A
2017-05-17T13:06:52.999551+00:00 xcatmn1.vndc xCAT[21134]: xCAT: Allowing makedhcp to spare-a282135x7408239-ipmi for samveen from localhost
2017-05-17T13:13:51.030633+00:00 xcatmn1.vndc xCAT[36418]: xCAT: Allowing mkdef spare-a282135x7408239 groups=all,setupipmi,supermicro,newprovgroup ip=10.81.106.225 for samveen from localhost
2017-05-17T13:13:52.162218+00:00 xcatmn1.vndc xCAT[36456]: xCAT: Allowing makehosts to spare-a282135x7408239 for samveen from localhost
2017-05-17T13:15:10.989895+00:00 xcatmn1.vndc xCAT[40401]: xCAT: Allowing nodediscoverdef -u 00000000-0000-0000-0000-0CC47AA33EAC -n spare-a282135x7408239 for samveen from localhost
2017-05-17T13:15:15.508338+00:00 xcatmn1.vndc journal: xCAT node discovery: spare-a282135x7408239 has been discovered
2017-05-17T13:15:23.390169+00:00 xcatmn1.vndc named[45080]: client 10.18.16.10#24789/key xcat_key: updating zone 'vndc/IN': adding an RR at 'spare-a282135x7408239.vndc' A
2017-05-17T13:15:23.390404+00:00 xcatmn1.vndc named[45080]: client 10.18.16.10#24789/key xcat_key: updating zone 'vndc/IN': adding an RR at 'spare-a282135x7408239.vndc' TXT
2017-05-17T13:15:23.392569+00:00 xcatmn1.vndc dhcpd: Added new forward map from spare-a282135x7408239.vndc to 10.81.106.225
2017-05-17T13:15:23.392802+00:00 xcatmn1.vndc dhcpd: Unable to add reverse map from 225.106.81.10.in-addr.arpa. to spare-a282135x7408239.vndc: not found
2017-05-17T13:15:28.722969+00:00 xcatmn1.vndc xCAT[42034]: xCAT: Allowing getcredentials x509cert from spare-a282135x7408239
2017-05-17T13:15:33.593532+00:00 xcatmn1.vndc xCAT[42435]: xCAT: Allowing nextdestiny for spare-a282135x7408239 from spare-a282135x7408239
2017-05-17T13:15:42.060796+00:00 xcatmn1.vndc xCAT[43002]: xCAT: Allowing nextdestiny for spare-a282135x7408239 from spare-a282135x7408239
2017-05-17T13:15:51.683016+00:00 xcatmn1.vndc xCAT[43733]: xCAT: Allowing getbmcconfig for spare-a282135x7408239 from spare-a282135x7408239
[vndc:samveen@xcatmn1 ~]$ sudo journalctl -u xcatd -n 300000 |grep -v lsdef |grep spare-a282135x7408239
May 18 04:28:06 xcatmn1.vndc xCAT[20416]: xCAT: Allowing getcredentials x509cert from spare-a282135x7408239
```

**Comment by daniceexi** [comment] 2017-05-18 14:34
@samveen I could not easily find the root cause through reading code. Then several questions might help to narrow the cause:
* Did the failure happened on fixed nodes? That means would it success if running ``nodediscoverdef`` again against the failed nodes?
* Could tabdump the **discoverydata** table, especially the entry for certain failed node? I'd like to recreate the issue locally.

**Comment by samveen** [comment] 2017-05-22 05:09
@daniceexi While running discovery, I noticed that when I ran `nodediscoverls -t manual` immediately after running `nodediscoverdef -u ... -n ...`, the node showed up as `manual` for some time, but then changed from type `manual` to type `undef` after some indeterminate time (less than `2` minutes).

could it be that the discovery worker is reverting the type of the node on processing discovery requests that were **queued before** I ran `nodediscoverdef` but were **processed after** I ran it?

**Comment by daniceexi** [comment] 2017-05-25 14:58
@samveen I am thinking that whether the discovery process did not finish for the node so it's continuously send the discovery request. Could you check the log to see whether there's discovery request message for node after you manually run the ``nodediscoverdef``.

**Comment by samveen** [comment] 2017-05-26 04:20
@daniceexi Do you mean something like: 
```
2017-05-17T13:15:15.508338+00:00 xcatmn1.vndc journal: xCAT node discovery: spare-a282135x7408239 has been discovered
```

**Comment by samveen** [comment] 2017-05-29 07:50
@daniceexi I have some more insight into the issue:
The nodes have 2 interfaces, and it seems that while the `doxcat` is setting up the primary interface correctly and running the chain, the secondary interface is being used to send discovery packets to the server at the same time (both interfaces are connected to the server via different networks).

**Comment by daniceexi** [comment] 2017-05-31 02:36
@samveen I meant it was possible that even after you run the ``nodediscoverdef`` command, the node still in the loop to send the discovery request. This would overwrite the ``method`` attribute. You could verify this by taking look of log to see whether there was discovery message for the node even after you run ``nodediscoverdef`` command.

**Comment by samveen** [comment] 2017-06-03 07:57
@daniceexi Yes. That looks exactly what's happening in our case. I'll try adding a `reboot` into the chain and see if that helps.

**Comment by zet809** [comment] 2017-06-05 02:48
Hi, @samveen , will you pls close this issue if it is resolved?

**Comment by samveen** [comment] 2017-06-06 10:01
Closing for now as problem seems to be in my environment instead of xCAT. I'll reopen if I find out it's not just my environment.

**Closed** 2017-06-06 10:01 UTC
Labels: component:discovery

**Comment by zet809** [comment] 2017-06-06 13:01
Thx @samveen .
