### ISSUE TITLE
Genesis image should now be centos7

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#2258] opened 2016-12-05 16:56 UTC
Hi chaps,

We've had numerous issues the past year, that would have helped to have the genesis image to be el7, I would suggest that we should do this, as at the moment, we have build a runimage image in el6 first, and find an el6 machine to do this on.

We should also add IB drivers into it, so that we are able to discover via 100G ethernet as well as 10G and 1G

thanks,
Arif

**Comment by whowutwut** [comment] 2016-12-05 22:35
Hi @arif-ali   Interesting timing....  I spent a good amount of time today re-creating the build machine to xCAT-genesis-base using CentOS 6.6...   I think @zet809 added IB drivers into the ppc64 genesis kernel.   Let me give it a quick try tonight and discuss with the team.  We are 1 week away from the 2.13 GA and not sure if we want to do it now.. but maybe it's the best time...  .  Would you have a chance to try out the xCAT-genesis-base for x86_64 if we provided a test rpm?

**Comment by whowutwut** [comment] 2016-12-05 22:42
@arif-ali  which version of centos are you using 7.0, 7.1, 7.2?

**Comment by arif-ali** [comment] 2016-12-05 23:16
Well, I have a workaround at the moment, that will hopefully work for the customer, which they will try tomorrow, i.e. 

```
mkdir mlx5_test
wget http://vault.centos.org/6.6/os/x86_64/Packages/kernel-2.6.32-504.el6.x86_64.rpm
rpm2cpio kernel-2.6.32-504.el6.x86_64.rpm | cpio -i --make-directories
mkdir -p /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/lib/modules/2.6.32-504.el6.x86_64/kernel/drivers/net/mlx5/core
cp ./lib/modules/2.6.32-504.el6.x86_64/kernel/drivers/net/mlx5/core/mlx5_core.ko /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/lib/modules/2.6.32-504.el6.x86_64/kernel/drivers/net/mlx5/core/
mknb x86_64
```

But no doubt, if we gave the customer to test the genesis image with a el7, then they would be happy to test. I doubt much that the version of CentOS will matter much in this specific case, as for runimage, the shared libraries would just work. The key things I think, that we we need in the genesis image should include, Mellanox 100G driver (mlx5_core), and the Intel OPA driver (hfi1), in addition to what we already have for mlx4 and ipath

**Comment by whowutwut** [comment] 2016-12-06 03:27
@zet809  I took a quick look at this, the last two commits in my forked copy are the changes needed for mlx5_core and building xCAT-genesis-base on CentOS7.2 on x86_64.  
https://github.com/whowutwut/xcat-core/commits/centos7_genbase , e6af2b4cf1269ebcbc1d125120661c73095eb9dc and 8943c7fb41f6bd938456146440859e9a25f39b07

I haven't gotten around to looking into hfi1 driver, it looks like we have to download the driver and install it into CentOS7.2..    What do you think about this?   Is this something we should pursue for the 2.13 GA or should we hold off for 2.13.1?

**Comment by arif-ali** [comment] 2016-12-06 08:43
@whowutwut I looked at the hfi1 driver yesterday, and from the VM I am running, it locates it in `kernel/drivers/staging/hfi1/hfi1.ko`, however, I am running the latest release of the centos7.2 kernel from updates, where I am on `3.10.0-327.36.3.el7.x86_64`

I believe the CentOS 7.3 is built in the CR repo, and you should be able to get a somewhat 7.3 base in, if you wanted to, and that should (maybe) have it in the mainstream directories

**Comment by arif-ali** [comment] 2016-12-06 14:29
@whowutwut Could you get us a test image, as our work-around didn't work, and we need to get the customer up and running with the `mlx5_core` driver working correctly

**Comment by arif-ali** [comment] 2016-12-06 16:31
@whowutwut I tried to do a few things, and I managed to create a genesis rpm using the following diff from your repo

```diff
diff --git a/xCAT-genesis-builder/buildrpm b/xCAT-genesis-builder/buildrpm
index a01271f..fa2151f 100755
--- a/xCAT-genesis-builder/buildrpm
+++ b/xCAT-genesis-builder/buildrpm
@@ -187,7 +187,7 @@ fi
 if [ $BUILDARCH = "ppc64" ]; then
     dracut -m "xcat base" -N -f /tmp/xcatgenesis.$$.rfs $KERNELVERSION
 else
-    dracut -m "xcat base" -f /tmp/xcatgenesis.$$.rfs $KERNELVERSION
+    dracut -m "xcat base" -f /tmp/xcatgenesis.$$.rfs -d "`cat $DRACUTMODDIR/modules | xargs`" $KERNELVERSION
 fi
 
 if [ $? -ne 0 ]; then
@@ -197,7 +197,7 @@ fi
 
 echo Expanding the initramfs into /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs ...
 cd /tmp/xcatgenesis.$$/opt/xcat/share/xcat/netboot/genesis/$BUILDARCH/fs 
-zcat /tmp/xcatgenesis.$$.rfs|cpio -dumi
+/usr/lib/dracut/skipcpio /tmp/xcatgenesis.$$.rfs | zcat | cpio -dumi
 
 if [ $? -ne 0 ]; then
     echo "ERROR - expanding the initramfs, please correct the issues and try again"
@@ -222,4 +222,4 @@ tar jcf ~/rpmbuild/SOURCES/xCAT-genesis-base-$BUILDARCH.tar.bz2 opt
 # build the rpm
 echo Building xCAT-genesis-base rpm from ~/rpmbuild/SOURCES/xCAT-genesis-base-$BUILDARCH.tar.bz2 and $DIR/xCAT-genesis-base.spec ...
 rpmbuild -ba $DIR/xCAT-genesis-base.spec 
-rm -rf $DRACUTMODDIR
+#rm -rf $DRACUTMODDIR
diff --git a/xCAT-genesis-builder/installkernel b/xCAT-genesis-builder/installkernel
index 3c17da7..6c7228d 100755
--- a/xCAT-genesis-builder/installkernel
+++ b/xCAT-genesis-builder/installkernel
@@ -14,3 +14,4 @@ instmods ipr # IBM Power RAID
 instmods i40e # Intel 40GbE
 instmods rtc-opal # For hardware clock
 instmods mlx5_core # For mellanox connect-IB adapter cards
+instmods hfi1 # Intel OPA Cards 
diff --git a/xCAT-genesis-builder/modules b/xCAT-genesis-builder/modules
new file mode 100755
index 0000000..5ff6951
--- /dev/null
+++ b/xCAT-genesis-builder/modules
@@ -0,0 +1,16 @@
+ nfs sunrpc
+ e1000 e1000e virtio_net virtio_pci igb ines sfc mlx4_en cxgb3 cxgb4 tg3 bnx2 bnx2x bna ixgb ixgbe qlge mptsas mpt2sas mpt3sas ata_piix megaraid_sas virtio_blk ahci ibmaem xhci-hcd sd_mod pmcraid be2net vfat ext3 ext4 btrfs reiserfs usb_storage scsi_wait_scan kvm kvm-intel kvm-amd ipmi_powernv ipmi_si ipmi_devintf qlcnic xfs mlx5_core hfi1
+ macvlan macvtap 8021q bridge bonding vmxnet3 cpufreq_ondemand acpi-cpufreq powernow-k8 cdc_ether
+ mptctl
+ mlx4_ib ib_umad
+ reiserfs
+ ibmveth
+ ibmvscsi
+ ehea
+ dm-mod
+ sg
+ 
+ i40e
+ rtc-opal
+ mlx5_core
+ hfi1
diff --git a/xCAT-genesis-builder/xCAT-genesis-base.spec b/xCAT-genesis-builder/xCAT-genesis-base.spec
index 9899805..63e38b9 100755
--- a/xCAT-genesis-builder/xCAT-genesis-base.spec
+++ b/xCAT-genesis-builder/xCAT-genesis-base.spec
@@ -1,4 +1,4 @@
-%define version     %%REPLACE_CURRENT_VERSION%%
+%define version     2.13ocf
 Version: %{?version:%{version}}%{!?version:%(cat Version)}
 Release: %{?release:%{release}}%{!?release:snap%(date +"%Y%m%d%H%M")}
 %ifarch i386 i586 i686 x86
```

The resulting RPM is http://yum.ocf.co.uk/rh7/xCAT-genesis-base-x86_64-2.13ocf-snap201612061622.noarch.rpm

**Comment by whowutwut** [comment] 2016-12-06 21:23
@arif-ali Were you able to provide this to your customer?  Did it work?

**Comment by whowutwut** [comment] 2016-12-06 21:44
@zet809  what are your thoughts on this.  Will try and catch you online later if I can.

**Comment by arif-ali** [comment] 2016-12-06 22:34
@whowutwut, I built it in my xCAT vm, and tested it on an internal VM network, and I was able to boot it, which was the main thing. I was able to see that the `mlx5_core` and `hfi1` modules were available, which was the other main thing

For us, it was the end of the day, so will only find out tomorrow UK time, to see if it actually worked for them. I will keep you posted

**Comment by samveen** [comment] 2016-12-07 01:52
@whowutwut @arif-ali We're already using a centos 7 based image in my organization for the last year. I'll see if I can get my teammate who did this magic to share his secret sauce if any.

**Comment by zet809** [comment] 2016-12-07 09:32
@whowutwut Hi, Victor, 1. as mentioned in another defect, we may need to include all the available driver on the builder host within genesis package, 2. if centos can support ppc64le, we can change our genesis ppc64 host to be centos.

**Comment by arif-ali** [comment] 2016-12-07 16:50
@whowutwut just to confirm, the RPM, that I compiled has worked for the customer in question, so thanks for all your help.

I will keep that available for my customers, but if there is an official one as well, that would make things a little easier as well

**Comment by zet809** [comment] 2017-01-12 07:48
Will rebuild genesis-base based on Centos7.3 in next release.

**Comment by samveen** [comment] 2017-03-21 10:39
@zet809 Can you clarify if you're going to do this with Centos7.3 `[base]` only packages or with `[updates]` packages installed as well?

**Comment by zet809** [comment] 2017-03-21 12:36
The current plan is just include the basic commands that had been included in genesis-base that was based on Fedora.
Do you have any special requirement that what kind of packages need to be included?

**Comment by samveen** [comment] 2017-03-22 11:51
Not really. I working on building an in-house overlay package, so if I have details of the base used for creating the x86_64 genesis, I can match versions of the overlay appropriately.

**Comment by zet809** [comment] 2017-03-24 10:15
Hi, @samveen , I had done some verification to build genesis-base ppc64 based on centos7.3, seems it will break our current supporting such as i40e driver, mlx driver and xcat dependencies. So, we plan to delay the building of genesis-base on centos.

**Comment by arif-ali** [comment] 2017-03-24 11:10
@zet809 Could you still not support x86 guys?

**Comment by samveen** [comment] 2017-03-24 13:04
@zet809 I'm building genesis_base on centos7.3 base with `[epel]` and `[elrepo]` enabled (no updates repo).
The `install` file has library paths and versions specific to centos6, as far as I can see, which gives errors during dracut-install runs for those particular files:
```dracut-install: ERROR: installing '/lib64/libnss_dns-2.12.so'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.XbNZj9/initramfs -a lldptool /lib64/libnss_dns-2.12.so /lib64/libnss_dns.so.2
dracut-install: ERROR: installing '/lib/libc.so.6'
dracut-install: ERROR: installing '/lib/ld-linux.so.2'
dracut-install: ERROR: installing '/lib/libdl.so.2'
dracut-install: ERROR: installing '/lib/libm.so.6'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.XbNZj9/initramfs -a chmod /lib/libc.so.6 /lib/ld-linux.so.2 /lib/libdl.so.2 /lib/libm.so.6 /sbin/route /sbin/ifconfig /usr/bin/whoami /usr/bin/head /usr/bin/tail basename /etc/redhat-release ping tr lsusb /usr/share/hwdata/usb.ids
dracut-install: ERROR: installing '/lib/libpthread.so.0'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.XbNZj9/initramfs -a /lib/libpthread.so.0
dracut-install: ERROR: installing '/lib/libncurses.so.5.7'
dracut-install: ERROR: installing '/usr/lib/libstdc++.so.6.0.13'
dracut-install: ERROR: installing '/lib/libgcc_s.so.1'
dracut-install: ERROR: installing '/lib64/libtinfo.so.5.7'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.XbNZj9/initramfs -a /lib/libncurses.so.5.7 /usr/lib/libstdc++.so.6.0.13 /lib/libgcc_s.so.1 /lib64/libtinfo.so.5.7
dracut-install: ERROR: installing '/usr/lib64/libsasl2.so.2'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.XbNZj9/initramfs -a /lib64/libldap-2.4.so.2 /lib64/liblber-2.4.so.2 /usr/lib64/libsasl2.so.2
dracut-install: ERROR: installing '/lib64/libnss_dns-2.12.so'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.XbNZj9/initramfs /lib64/libnss_dns-2.12.so
dracut-install: ERROR: installing '/lib/terminfo/l/linux' to '/lib/terminfo/l/linux'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.XbNZj9/initramfs /lib/terminfo/l/linux /lib/terminfo/l/linux
dracut-install: ERROR: installing '/lib/terminfo/v/vt100' to '/lib/terminfo/v/vt100'
/usr/lib/dracut/dracut-install -D /var/tmp/dracut.XbNZj9/initramfs /lib/terminfo/v/vt100 /lib/terminfo/v/vt100
```

**Comment by samveen** [comment] 2017-03-27 02:40
@arif-ali Have you pushed your changes to any public-access git repo? I'd like to try building the package using your changes, to see where I've diverged from your packaging.

**Comment by zet809** [comment] 2017-03-27 03:31
Hi, @arif-ali , in fact, for genesis-base-x86_64, it is based on centos 6.6.
And @samveen , I am sorry that we haven't port building genesis-base-x86_64 based on Centos 7.x. The latest version was based on centos6.6 for x86_64.

**Comment by arif-ali** [comment] 2017-03-27 14:31
@samveen 

I had it on one of my VMs, I went from @whowutwut's branches, and from then on, updated, and then got it working, See link below

https://github.com/ocfplc/xcat-core/tree/centos7_genbase

**Comment by whowutwut** [comment] 2017-03-27 18:49
Just to be clear, this request is really only to move the xCAT genesis base for x86_64 to centos, the ppc64 one is currently being built using Fedora 23 or 24..   I haven't looked at this for a long time and forgotten where I left off.  I did find the machine I built the changes from the centos7_genbase branch on.   :-(

**Comment by samveen** [comment] 2017-03-28 04:05
@zet809 That's all right. 

However, as per my understanding dracut_install takes care of dynamic library dependencies automagically, so why does the `install` script have so many libraries in there? I can understand `dracut_install` calls for dynamic modules are loaded on demand (like the rsyslog modules), but not for `libc`, and `std-libc++`. Just pollutes the script needlessly.

**Comment by samveen** [comment] 2017-03-29 06:04
@zet809 That's all right.

@whowutwut as per my understanding dracut_install takes care of dynamic library dependencies automagically, so why does the install script have so many libraries in there? I can understand dracut_install calls for dynamic modules are loaded on demand (like the rsyslog modules), but not for libc, and std-libc++ (and other such libraries). These just pollutes the script needlessly.

**Comment by samveen** [comment] 2017-03-31 08:21
@arif-ali Would you care to review https://github.com/samveen/xcat-core/tree/c7_gen . It takes some of of the parts of changes you and @whowutwut made in your respective branches. 

It also has 2 new files `xCAT-genesis-overlay.spec` and `buildoverlayrpm` to allow building overlays with file lists as input (this is for an in-house requirement to manage additions of custom extras to the genesis image in an reproducible manner).

**Comment by arif-ali** [comment] 2017-11-20 17:17
This is worth a bump, due to further discussions on the mailing list. Is there a timeline for this to get included in the main xCAT dist, otherwise, I will do one for any additions as people need it on our server?

**Comment by immarvin** [comment] 2017-11-21 02:35
ping @zet809

**Comment by zet809** [comment] 2017-11-21 09:48
Hi, @arif-ali , we have modified the script to include all drivers built in host kernel to xCAT-genesis-base, will build one for x86_64 based on centOS 7.

**Comment by zet809** [comment] 2017-11-27 06:32
hi, @arif-ali , I have build genesis-base-x86-64 based on Centos7.4 to include all modules build in host OS, it is available at https://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-genesis-base-x86_64-2.13.9-snap201711270044.noarch.rpm.
There is an issue to update xCAT-genesis-base-x86_64 from 2.13.2 to 2.13.9 since the directory changing between centos6 and centos7.
You have to remove xCAT-genesis-base-x86_64 and xCAT-genesis-scripts-x86_64, and then install new xCAT-genesis-base-x86_64-2.13.9 and xCAT-genesis-scripts-x86_64 at present.

**Comment by samveen** [comment] 2017-11-29 03:31
@zet809 Finally 👍 . I have a few patches pulled from Victor and Arif, which I think would improve this even more. let me see if I can make a PR for it.

**Comment by zet809** [comment] 2017-12-05 14:53
hi, @arif-ali and @samveen , with the genesis-base build on centos 7.4 x86_64, I encountered an issue when boot the CN into genensis shell. 
When I use `rcons node` to monitor the CN that boot into genesis shell, the screen will be cleared every second.
Do you notice this issue with your build? Thx!

**Comment by samveen** [comment] 2017-12-06 06:53
@zet809 Yes. This is definitely something I have observed in our environment.

**Comment by zet809** [comment] 2017-12-06 07:05
It seems can be fixed by modifying this line below, and then run `mknb x86_64` again. Do you have any idea?
```
diff --git a/xCAT-genesis-builder/xcat-cmdline.sh b/xCAT-genesis-builder/xcat-cmdline.sh
index 67b0848..4846585 100755
--- a/xCAT-genesis-builder/xcat-cmdline.sh
+++ b/xCAT-genesis-builder/xcat-cmdline.sh
@@ -36,7 +36,7 @@ mkdir -p /var/log
 ip link set lo up
 echo '127.0.0.1 localhost' >> /etc/hosts
 if grep console=ttyS /proc/cmdline > /dev/null; then
-       while :; do sleep 1; screen -x console < /dev/tty1 > /dev/tty1 2>&1; clear; done &
+       screen -x console < /dev/tty1 > /dev/tty1 2>&1; clear;
 fi
 while :; do screen -ln < /dev/tty2 > /dev/tty2 2>&1; done &
```

**Comment by ladams00** [comment] 2017-12-08 07:03
@zet809 , Is it possible to produce some deb packages for that Centos 7.4 based genesis-base-x86-64?  I have my MN on Ubuntu 16.04, and would like to try this new genesis base for a set of new compute nodes with Intel X550 NICs that use modern ixgbe modules.

**Comment by zet809** [comment] 2017-12-08 08:44
Hi, @ladams00 , pls try the file below and let me know the result. Thx!
https://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/beta/xcat-genesis-base-amd64_2.13.9-snap201711270044_all.deb

**Comment by ladams00** [comment] 2017-12-08 16:02
@zet809 , This works wonderfully!  The modules included with CentOS 7.4 load and initialize the NIC interfaces just fine.  Thank you :-)

**Comment by zet809** [comment] 2018-01-18 06:04
hi, @arif-ali and @ladams00 , we will ship genesis-base-x86_64 which is based on centos7.4 in 2.13.10(will be GAed at Jan 26), the RC build will be ready next Monday(Jan 22), will you pls help to check then and let me know the result? Then, we can close this issue. Thx a lot!

**Comment by ladams00** [comment] 2018-01-18 18:09
Hello @zet809 , I'll give 2.13.10 a shot next week and report back how well the new genesis image works on the new Intel HNS2600BPB compute systems.

**Comment by zet809** [comment] 2018-01-29 02:05
hi, @ladams00 , we released 2.13.10 last Friday, the latest xCAT-genesis-base-x86_64 is shipped, will you pls take a try and let us know the result? The release notes is available at https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.10_Release_Notes. 
Thx a lot!

**Comment by ladams00** [comment] 2018-01-29 06:20
Hello @zet809 , my apologies for the delay.  I will test this out in the next couple days.  Thank you for the link to the 2.13.10 release notes.  I see the remark there regarding centos7 for x86_64.

**Comment by whowutwut** [comment] 2018-02-02 20:24
This should be completed, will close to clean up the release issues, if there are additional issues seen , please reopen

**Closed by whowutwut** 2018-02-02 20:24 UTC
Labels: component:discovery, sprint2
