### ISSUE TITLE
investigate the issue  #2859 xCAT daemon stuck for months and cause problem when xCAT upgrading

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2930] opened 2017-04-25 02:10 UTC
for issue https://github.com/xcat2/xcat-core/issues/2859:

@neo954 will spend some time to investigate the issue:
1. find the way to recreate the issue 
2. estimate the influence of this issue

**Comment by hu-weihua** [comment] 2017-04-28 05:22
This is a problem, but now we have not had root cause and solution, compare with other work item in 2.13.4 sprint2, it has lower priority, so move it to 2.13.5 sprint1

**Comment by zet809** [comment] 2017-06-12 12:34
Close this task and reopen it if we plan to put effort to find the root cause.

**Closed** 2017-06-12 12:34 UTC
Labels: component:xcatd, priority:low, sprint2, type:feature
