### ISSUE TITLE
The return code is zero when noderange is /abc for some commands

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4481] opened 2017-12-08 08:13 UTC
xcat version:
 Version 2.13.9 (git commit e7e6b60215ff075dd6bc33337ea85014cf525813, built Thu Dec  7 06:16:04 EST 2017)

The return code is zero when rflash option d goes to error

```
RUN:rflash -d /1234 [Fri Dec  8 02:44:36 2017]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
Usage:
    rflash [ -h|--help|-v|--version]
    PPC (with HMC) specific:
	rflash <noderange> -p <rpm_directory> [--activate {concurrent | disruptive}] [-V|--verbose]
	rflash <noderange> {--commit | --recover} [-V|--verbose]
    PPC (using Direct FSP Management) specific:
	rflash <noderange> -p <rpm_directory> [--activate {disruptive|deferred}] [-d <data_directory>]
	rflash <noderange> [--commit | --recover] [-V|--verbose]
        rflash <noderange> [--bpa_acdl]
    OpenPOWER BMC specific (using IPMI):
        rflash <noderange> [<hpm_file_path>|-d <data_directory>] [-c|--check] [--retry=<count>] [-V]
        rflash <noderange> --recover <bmc_file_path>
    OpenPOWER OpenBMC specific:
        rflash <noderange> {[-c|--check] | [-l|--list]}
        rflash <noderange> <tar_file_path> {[-c|--check] | [-a|--activate] | [-u|--upload]}
        rflash <noderange> <image_id> {[-a|--activate] | [-d|--delete]}
CHECK:rc != 0	[Failed]
```

**Comment by bybai** [comment] 2017-12-08 08:48
I checked, all the ``rflash`` command options have the same problem. If there is no noderange but with an  "directory'' behind option, ``rflash`` will print usage and exit 0.

**Comment by gurevichmark** [comment] 2017-12-08 13:39
This might get fixed with PR #4482

The problem is probably because in many places, our code is using:
`xCAT::SvrUtils::sendmsg("Error: message", $callback, $node);`
instead of
`xCAT::SvrUtils::sendmsg([1, "message"], $callback, $node);`

**Comment by bybai** [comment] 2017-12-11 05:50
@gurevichmark , If there are noderange, PR #4482 fixed. But if there is no noderange like  "rflash -a /abc", the issue is still there.

**Comment by bybai** [comment] 2017-12-11 07:12
Hi @chenglch , could you look into this issue?  
``rflash -a /abc`` should be the same result with ``rflash -a abc``, like ``Error: Invalid nodes and/or groups in noderange: ...``

**Comment by chenglch** [comment] 2017-12-11 07:41
@hu-weihua. @bybai  For xcat command, the first argument should be <noderange> , won't fix for this.

**Comment by zet809** [comment] 2017-12-12 03:23
I think it is a little hard to check a string is a noderange or parameter, so, I suggest we modify the return code to be 1 if usage is returned but no '-h' specified.

**Comment by chenglch** [comment] 2017-12-12 05:40
This error also happens for rpower command
``
[root@briggs01 ~]# rpower -t /a
[root@briggs01 ~]# echo $?
0
```

**Comment by zet809** [comment] 2017-12-14 08:24
This is a general issue for xCAT command, so I'd like to move this issue forward.

**Comment by zet809** [comment] 2018-04-17 07:57
A general issue for xCAT command, we not not plan to put effort on this, so close this issue.

**Closed by zet809** 2018-04-17 07:57 UTC
Labels: component:openbmc, sprint2, type:bug

**Comment by whowutwut** [comment] 2018-04-17 10:56
@zet809 seems like a usability issue if we can’t detrct the issue and print an error message. Can you fill out the correct label for this if we won’t fix it. Seems like something should be done...but maybe no time right now..
