### ISSUE TITLE
xCAT provision Sles11.2 will hang-on when excuting remoteshell script

### ISSUE THREAD

**Issue by SStar1314** [xcat2/xcat-core#106] opened 2015-08-20 08:11 UTC
xCAT provision Sles11.2 will hang-on and wait for input passphrase when executing "ssh-keygen -y -f /etc/ssh/ssh_host_ecdsa_key > /etc/ssh/ssh_host_ecdsa_key.pub" command in remoteshell script.  
Root Cause: Sles11.2 install openssh-5.1p1-41.57.1 build-in package, and this version openssh don't support ecdsa key type.
So there needs a openssh support check before ecdsa key generation. In remoteshell script, line 283, we will add "ssh-keygen -t ecdsa -y -f /etc/ssh/ssh_host_ecdsa_key -P "" " command and check the result to judge support or not. 
Follow is changes:
<code>star@userver:~/xcat-core$ git diff</code>
<code>diff --git a/xCAT/postscripts/remoteshell b/xCAT/postscripts/remoteshell</code>
<code>index 8177bee..e4eb788 100755</code>
<code>--- a/xCAT/postscripts/remoteshell</code>
<code>+++ b/xCAT/postscripts/remoteshell</code>
<code>@@ -281,9 +281,14 @@ if [ -f /etc/ssh/ssh_host_ecdsa_key ]; then</code>
<code>        if ! grep "PRIVATE KEY" /etc/ssh/ssh_host_ecdsa_key > /dev/null 2>&1 ; then</code>
<code>                rm /etc/ssh/ssh_host_ecdsa_key</code>
<code>        else</code>
<code>-               ssh-keygen -y -f /etc/ssh/ssh_host_ecdsa_key > /etc/ssh/ssh_host_ecdsa_key.pub</code>
<code>-               chmod 644 /etc/ssh/ssh_host_ecdsa_key.pub</code>
<code>-               chown root /etc/ssh/ssh_host_ecdsa_key.pub</code>
<code>+                ssh-keygen -t ecdsa -y -f /etc/ssh/ssh_host_ecdsa_key -P ""</code>
<code>+                if [ "x$?" = "x0" ]; then</code>
<code>+                       ssh-keygen -y -f /etc/ssh/ssh_host_ecdsa_key > /etc/ssh/ssh_host_ecdsa_key.pub</code>
<code>+                       chmod 644 /etc/ssh/ssh_host_ecdsa_key.pub</code>
<code>+                       chown root /etc/ssh/ssh_host_ecdsa_key.pub</code>
<code>+                else</code>
<code>+                        rm -fr /etc/ssh/ssh_host_ecdsa_key</code>
<code>+                fi</code>
<code>        fi</code>

**Comment by daniceexi** [comment] 2015-08-20 10:07
@immarvin Could take a look of the change?

@SStar1314 Generally, we require all contributor submit code change by pull request. https://help.github.com/articles/using-pull-requests/

**Comment by immarvin** [comment] 2015-09-23 08:38
@SStar1314 has checked in the code:

commit 745cf10422f66cfedee5ccec1a5abcae338a58ac
Author: SStar1314 <1010133787@qq.com>
Date:   Wed Sep 2 09:20:28 2015 +0800

    Add comments to the remoteshell ecdsa key generate produrce.

commit 229ee3966c1e79b24d28d075e39bd8cdae8f07ac
Author: SStar1314 <1010133787@qq.com>
Date:   Tue Aug 25 22:25:24 2015 +0800

    Update remoteshell

commit d6df4819499ca0c39743c698292308218e94b59e
Author: SStar1314 <1010133787@qq.com>
Date:   Thu Aug 20 20:57:44 2015 +0800

    xCAT provision Sles11.2 will hang-on when excuting remoteshell script
    
    xCAT provision Sles11.2 will hang-on and wait for input passphrase when executing "ssh-keygen -y -f /etc/ssh
    
    Root Cause: Sles11.2 install openssh-5.1p1-41.57.1 build-in package, and this version openssh don't support 
    So there needs a openssh support check before ecdsa key generation. In remoteshell script, line 283, we will

**Closed by immarvin** 2015-09-23 08:38 UTC
Labels: priority:normal, type:bug
