### ISSUE TITLE
`chdef -t network` fails without `net=` and `mask=` parameters

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#4085] opened 2017-10-11 10:45 UTC
xCAT version
```
[VNDC samveen@xcatmn1 scripts][master ?]$ lsxcatd -v
Version 2.13.7 (git commit 9ec6d0c0cce9f61a078a4dcd044927f5a65a606f, built Fri Sep 22 02:16:45 EDT 2017)
```
Node type:
```
[VNDC samveen@xcatmn1 scripts][master ?]$ lsxcatd -t
This is a Management Node
```
Network definition (typo: `vbdc` should be `vndc`)
```
[VNDC samveen@xcatmn1 scripts][master ?]$ lsdef -t network VNDC-NET-00116-IPv4  -i net,mask,domain
Object name: VNDC-NET-00116-IPv4
    domain=vbdc
    mask=255.255.255.0
    net=10.1.116.0
```

`chdef` for correction (worked for `xCAT-2.13.2`, haven't tried after that)
```
[VNDC samveen@xcatmn1 scripts][master ?]$ chdef -t network VNDC-NET-00116-IPv4 domain=vndc
Error: Attribute 'net' is not specified for network entry 'VNDC-NET-00116-IPv4', skipping.
Error: One or more errors occured when attempting to create or modify xCAT 
object definitions.
[VNDC samveen@xcatmn1 scripts][master ?]$ chdef -t network VNDC-NET-00116-IPv4 domain=vndc net=10.1.116.0
Error: Attribute 'mask' is not specified for network entry 'VNDC-NET-00116-IPv4', skipping.
Error: One or more errors occured when attempting to create or modify xCAT
object definitions.
[VNDC samveen@xcatmn1 scripts][master ?]$ chdef -t network VNDC-NET-00116-IPv4 domain=vndc mask=255.255.255.0
Error: Attribute 'net' is not specified for network entry 'VNDC-NET-00116-IPv4', skipping.
Error: One or more errors occured when attempting to create or modify xCAT 
object definitions.
```
It only succeeds after both `net=` and `mask=` values are passed.
```
[VNDC samveen@xcatmn1 scripts][master ?]$ chdef -t network VNDC-NET-00116-IPv4 domain=vndc net=10.1.116.0  mask=255.255.255.0
1 object definitions have been created or modified.
```

**Comment by whowutwut** [comment] 2017-10-11 23:23
@samveen  we had made some changes in this area because we found that the name of the network in the networks was not unique unless we had a netmask associated with it. I can try and find the issue

@bybai can you provide more details here?

**Comment by bybai** [comment] 2017-10-12 01:15
Hi @samveen ,
Both net and mask are keys for `networks` table, it only suceeds after both `net=` and `mask=` values are passed, it is as expected as design.
In `chdef` for `networks` table, there are following rules:
a. When `netname` does not exists, `net` or `mask` is not set in `chdef`, since `net` and `mask` are both key for `networks` table, they should not be empty, so return error.
b. When `netname` does not exists, another netwok entry contains the same `net` and `mask`, it is duplicate, return error.
c. When `netname` exists, there is `net` or `mask` missing from this network entry in networks table, `chdef` should add `net` or `mask` into this entry, or else, return error.
Thanks.

**Comment by bybai** [comment] 2017-10-12 01:26
refer to https://github.com/xcat2/xcat-core/issues/3571 and https://github.com/xcat2/xcat-core/issues/3927; 
hi @hu-weihua, #3571, #3927 and this issue are testcase_request for `makenetworks`, `mkdef` and `chdef`, examples are in pull request #3667 and #3928

**Comment by bybai** [comment] 2017-10-12 01:50
hi @samveen ,
I re-run your steps as following, I do not hit your issue:
```
[root@byrhmn ~]# lsdef -t network -l
Object name: 10_0_0_0-255_0_0_0
    gateway=10.5.106.2
    mask=255.0.0.0
    mgtifname=eth0
    mtu=1500
    net=10.0.0.0
    tftpserver=<xcatmaster>
[root@byrhmn ~]# chdef -t network 10_0_0_0-255_0_0_0 domain=vbdc
1 object definitions have been created or modified.
[root@byrhmn ~]# chdef -t network 10_0_0_0-255_0_0_0 domain=vndc
1 object definitions have been created or modified.
[root@byrhmn ~]# lsdef -t network -l
Object name: 10_0_0_0-255_0_0_0
    domain=vndc
    gateway=10.5.106.2
    mask=255.0.0.0
    mgtifname=eth0
    mtu=1500
    net=10.0.0.0
    tftpserver=<xcatmaster>
[root@byrhmn ~]# lsxcatd -v
Version 2.13.7 (git commit 9ec6d0c0cce9f61a078a4dcd044927f5a65a606f, built Fri Sep 22 02:16:45 EDT 2017)
```

**Comment by samveen** [comment] 2017-10-13 07:18
@bybai @whowutwut I understand that both `net` and `mask` are keys for the network object, and thus required. However, for the network I was trying to modify, the network object already existed, and had both these fields set. Why should this warning trigger?
Once I modified the object with `chdef -t network VNDC-NET-00116-IPv4 domain=vndc net=10.1.116.0 mask=255.255.255.0`, and then tried to modify another field, I still got the same error, and had to pass `net` and `mask` as parameters again:

```
[VNDC samveen@xcatmn1 custom][master]$ chdef -t network VNDC-NET-00116-IPv4 ntpservers=xcatsn-id.infra.vndc
Error: Attribute 'net' is not specified for network entry 'VNDC-NET-00116-IPv4', skipping.
Error: One or more errors occured when attempting to create or modify xCAT 
object definitions.
```

**Comment by bybai** [comment] 2017-10-13 07:58
Hi @samveen,
I cannot reproduce your issue on xcat2.13.7, the same version with you.
I cannot reproduce it in latest xcat develop build as following. Could you restart your xcatd using `service xcatd restart` in xcat MN to see if some changes do not take effect?   
```
 ~]# lsdef -t network -l
Object name: VNDC-NET-00116-IPv4
    gateway=10.0.0.103
    mask=255.0.0.0
    mgtifname=eth0
    mtu=1500
    net=10.0.0.0
    tftpserver=<xcatmaster>
[root@c910f02c08p05 ~]# chdef -t network VNDC-NET-00116-IPv4 ntpservers=ntp1.infra.vndc
1 object definitions have been created or modified.
[root@c910f02c08p05 ~]# lsxcatd -v
Version 2.13.8 (git commit 6b39720bd22bc11ad02a23f5f4459a947af16f09, built Thu Oct 12 06:15:38 EDT 2017) 
```

**Comment by bybai** [comment] 2017-10-16 05:52
@samveen , could you have any good progress about this issue?

**Comment by bybai** [comment] 2017-10-18 02:31
Hi @samveen, since we cannot reproduce this issue, will close it now, if it reproduce in the future, can open it then. Thanks.

**Closed by bybai** 2017-10-18 02:31 UTC
Labels: sprint2, status:cannot_recreate, test:testcase_requested
