### ISSUE TITLE
unknown nic type for br_pub

### ISSUE THREAD

**Issue by dombrowa** [xcat2/xcat-core#2940] opened 2017-04-25 14:53 UTC
```
Version 2.13.3 (git commit 7f9e0b57554c3a1975b83308935b7d183c632a9d, built Thu Apr 13 01:56:07 EDT 2017)
installation of Watson Power 8 cluster
```
In http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskful/customize_image/cfg_network.html and example states
```
chdef cn1 nictypes.br1=bridge \
          nicdevices.br1=bond0.1 \
          nicips.br1=10.0.0.1 \
          nicnetworks.br1="net10"
```
which I applied such to the compute node
```
chdef mingb001 \
nictypes.enP1p4s0f1=Ethernet \
nictypes.br_pub=bridge \
nicdevices.br_pub=enP1p4s0f1 \
nicips.br_pub=9.2.133.199 \
nicnetworks.br_pub="public00" \
nictypes.enP9p7s0f0=Ethernet \
nicnetworks.enP9p7s0f0=provision \
nicips.enP9p7s0f0=10.1.3.1 

```
When using bridge as nictype in an Ubuntu 16.04 diskful compute node install we end up with  "unknown nic type for br_pub"

The postscript confignics does not have a path for bridge in its if statement, only ethernet and infiniband are supported which does not correlate to the doc.

```
         if [ "$str_nic_type" = "ethernet" ];then
             logger -t xcat -p local4.info "confignics: call 'configeth $key ${array_temp[0]} $str_network'"
             echo "confignics on $NODE: call 'configeth $key ${array_temp[0]} $str_network'"
             configeth $key ${array_temp[0]} $str_network
        elif [ "$str_nic_type" = "infiniband" ];then
            if [ $str_ib_nics ];then
                str_ib_nics=$str_ib_nics","$key
            else
                str_ib_nics=$key
            fi
        else
            logger -t xcat -p local4.info "confignics: unknown type $str_nic_type for NIC: $key"
            echo "confignics on $NODE: unknown type $str_nic_type for NIC: $key"
        fi
 ```
Either the documentation is wrong or code is missing in xCAT to support it

**Comment by dombrowa** [comment] 2017-04-25 15:24
adding Ralph @ralphbellofatto

**Comment by dombrowa** [comment] 2017-04-25 15:43
In addition the xcat doc states:
Use the following command to add confignetwork into postscript list to execute on reboot:

chdef cn1 -p postscripts=confignetwork

but fails to mention that confignetworks is not supported on Ubuntu as using this postscript ends with
mingb001: [E]: Only supports RHEL

**Comment by bybai** [comment] 2017-04-26 03:37
Hi @dombrowa ,
confignetwork is not supported on Ubuntu. If you want to configure bridge, you can use this script `xHRM`;
We will refine the workflow and documentation on the network management in xCAT in inssue : https://github.com/xcat2/xcat-core/issues/2931 , thanks.

**Comment by robin2008** [comment] 2017-04-26 05:48
@dombrowa  Thanks for your feedback to use xCAT.

Currently, confignetwork is only supported on RHEL. We are sorry that the document may not be clear enough for it.

It is currently design behavior of chdef. It cannot complain the incompatible as it will not look into the script itself to see what's inside. You can only get the error in log file.

And what's you real requirement here, to configure a bridge on Ubuntu 16.04.x?  As you know,  new features on Ubuntu supporting is on our backlog, but may not be high priority.
xCAT still has other built-in postscript to do it, like xHRM. You can take a look to see if it meet your requirement.

**Comment by bybai** [comment] 2017-05-11 06:55
Hi @dombrowa，
Since my last mail, could `updatenode mingb001 -P "xHRM bridgeprereq enP1p4s0f1:br_pub"` work well for you?

I want to double check,  there is `[E]: Only supports RHEL` error message for ubuntu 16.04 os in my environment, it works well as following example;
Could it not work in your Ubuntu 16.04 ?  Is there "/etc/debian_version" file in your compute node mingb001 ?
```
pts# updatenode c910f04x35v04 confignetwork
c910f04x35v04: xcatdsklspost: downloaded postscripts successfully
c910f04x35v04: Thu May 11 02:51:23 EDT 2017 Running postscript: confignetwork
c910f04x35v04: [E]: Only supports RHEL
c910f04x35v04: postscript: confignetwork exited with code 255
c910f04x35v04: Running of postscripts has completed.

root@c910f04x35v02:/install/postscripts# xdsh c910f04x35v04 "more /etc/*release"
c910f04x35v04: ::::::::::::::
c910f04x35v04: /etc/lsb-release
c910f04x35v04: ::::::::::::::
c910f04x35v04: DISTRIB_ID=Ubuntu
c910f04x35v04: DISTRIB_RELEASE=16.04
c910f04x35v04: DISTRIB_CODENAME=xenial
c910f04x35v04: DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
c910f04x35v04: ::::::::::::::
c910f04x35v04: /etc/os-release
c910f04x35v04: ::::::::::::::
c910f04x35v04: NAME="Ubuntu"
c910f04x35v04: VERSION="16.04.1 LTS (Xenial Xerus)"
c910f04x35v04: ID=ubuntu
c910f04x35v04: ID_LIKE=debian
c910f04x35v04: PRETTY_NAME="Ubuntu 16.04.1 LTS"
c910f04x35v04: VERSION_ID="16.04"
c910f04x35v04: HOME_URL="http://www.ubuntu.com/"
c910f04x35v04: SUPPORT_URL="http://help.ubuntu.com/"
c910f04x35v04: BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
c910f04x35v04: UBUNTU_CODENAME=xenial

```

**Comment by bybai** [comment] 2017-05-12 06:16
Can not reproduce the issue. closed it first.

**Closed** 2017-05-12 06:16 UTC
