### ISSUE TITLE
xCAT 2.14.5/2.14.6 makentp failed if chronyd is installed on RHELS 6.10

### ISSUE THREAD

**Issue by DeLaJSR** [xcat2/xcat-core#6247] opened 2019-04-19 01:45 UTC
xCAT 2.14.5/2.14.6 makentp failed if chronyd is installed on RHELS 6.10, maybe chronyd cause xCAT use RHEL 7 command?

##with chronyd
[root@sghwmn01 ~]# makentp 
configuring management node: sghwmn01.
Will configure chronyd instead.
Calling ... /install/postscripts/setupntp 
Error from command: /install/postscripts/setupntp 
    Command "systemctl" not found.
Command "timedatectl" not found.
setupntp: Above listed required command(s) not found.

#without chronyd
[root@sghwmn01 ~]# makentp 
configuring management node: sghwmn01.

**Comment by immarvin** [comment] 2019-04-19 05:55
hi @neo954 , is this issue caused by the code for rh8?

**Comment by neo954** [comment] 2019-04-19 06:59
Okay. I will look into this one.

**Comment by robin2008** [comment] 2019-04-21 00:36
@DeLaJSR `chronyd` supporting on xcat is only for RH7+,  and there is no plan to support it on RH6.

And if you really want `chronyd` working on RH6, xCAT is an open community, it is welcome for you to contribute your patch for it. 

BTW: You can still use `setupntp.traditional` to enable `ntpd` instead.

**Comment by DeLaJSR** [comment] 2019-04-21 10:02
@robin2008 chrony is provided with the ISO image since RHEL 6.8, a "fully installation"(I don't recommend this but many customers like to do that) 6.8+ will easily encounter this issue, if there is no plan to support chrony on RH6, I think adding a reminder like pls uninstall chrony etc is also acceptable

**Comment by immarvin** [comment] 2019-04-22 03:06
255     # Handle chronyd here,
256     if (-f "/usr/sbin/chronyd") {
257         send_msg(\%request, 0, "Will configure chronyd instead.");
258
259         my $cmd = "/install/postscripts/setupntp " .
260             join(' ', split(',', $ntp_servers));
261         send_msg(\%request, 0, "Calling ... " . $cmd);
262
263         my $result = xCAT::Utils->runcmd($cmd, 0);
264         if ($::RUNCMD_RC != 0) {
265             send_msg(\%request, 1, "Error from command: $cmd\n    $result");
266             return 1;
267         }
268
269         send_msg(\%request, 0, "Daemon chronyd configured.");
270
271         # Cannot find a better way other than use goto statement :-/
272         goto HANDLE_MAKENTP_A;
273     }
274

**Comment by neo954** [comment] 2019-04-22 09:21
Would like to call `setupntp.traditional` when `systemctl` is not available.

**Comment by immarvin** [comment] 2019-04-23 07:18
hi @DeLaJSR , the fix is merged, please patch and try with https://github.com/xcat2/xcat-core/pull/6257

**Closed** 2019-04-30 02:07 UTC
Labels: sprint2, status:pending
