### ISSUE TITLE
[FVT]install xcat failed for when install xCAT-server Requires: perl(HTTP::Async)

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#765] opened 2016-03-03 02:12 UTC
Env : ppc64 ,x86_64
xcatbuild:latest xcat build
How to reproduce:
```
then 
[root@c910f03fsp03v02 ~]# yum install xCAT
...
--> Processing Dependency: perl(HTTP::Async) for package: 4:xCAT-server-2.12-snap201603021531.noarch
--> Finished Dependency Resolution
Error: Package: 4:xCAT-server-2.12-snap201603021531.noarch (xcat-2-core)
           Requires: perl(HTTP::Async)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@c910f03fsp03v02 ~]# 
```

**Comment by zet809** [comment] 2016-03-03 02:47
I am sorry for not mention the message that the dependency pkg http-async-perl and perlnet-https-nb are unavailable yet.
To work around this issue, you may need to install them manually from the links below, pls note that those pkg are noarch, so they can be used both on ppc64, ppc64le and x86_64.
1. For RH:
http-async-perl:    ftp://rpmfind.net/linux/mageia/distrib/cauldron/x86_64/media/core/release/perl-HTTP-Async-0.300.0-2.mga6.noarch.rpm
perlnet-https-nb:    ftp://rpmfind.net/linux/mageia/distrib/cauldron/x86_64/media/core/release/perl-Net-HTTPS-NB-0.140.0-2.mga6.noarch.rpm
2. For ubuntu: 
http-async-perl:    http://security.ubuntu.com/ubuntu/pool/universe/libh/libhttp-async-perl/libhttp-async-perl_0.30-1_all.deb
perlnet-https-nb:      http://security.ubuntu.com/ubuntu/pool/universe/libn/libnet-https-nb-perl/libnet-https-nb-perl_0.14-1_all.deb

**Comment by tingtli** [comment] 2016-03-03 03:31
We need to fix this defect ASAP since we run automation test everyday. We could not manually run the installation of the package in the automation environment. This will block our automation test.

**Comment by daniceexi** [comment] 2016-03-03 05:28
@zet809 We can not require automation framework to add these Async package automation. Please remove the require of this dep in xCAT intstall before the Async ready.

**Comment by zet809** [comment] 2016-03-04 03:51
Have modify our code to require HTTP::Async when running, keep this defect opening to trace the dependency packages status.

**Comment by daniceexi** [comment] 2016-03-05 08:16
@zet809 The fix was done in the commit 5fa692543da9b30a52f76305f8565877b6d7d6c8 and 59f44ee423e4ff1a159335dbe2e0b2869039cb03, but the message for commit was too simple and not meaningful.

**Comment by whowutwut** [comment] 2016-03-10 15:26
@zet809 @daniceexi  it looks like those two commits above was directly made to the xcat-core master branch instead of using a pull request... since it partly resolved an issue, would it have made sense to have a pull request, because otherwise without your comment above, it is hard to know when thing were committed that is related to this issue..

**Comment by daniceexi** [comment] 2016-03-11 01:55
@whowutwut I have reviewed the change made by @zet809. I think the thing was @zet809 wanted save the time to made a pull request process since the change was minor. Then I think @zet809 should add the commit for this issue to make the owner and wacher of this issue to know the defect had been fixed.

**Comment by whowutwut** [comment] 2016-03-11 03:34
Yea, thanks...  something to notify the watchers of this issue that something changed would be fine.

**Comment by gurevichmark** [comment] 2016-03-11 18:18
I tried downloading and installing the 2 RH rpms specified above, on c910f02c06p23, RH 7.2.
It appears some dependencies are missing:

> [root@c910f02c06p23 gurevich]# rpm -i perl-Net-HTTPS-NB-0.140.0-2.mga6.noarch.rpm
warning: perl-Net-HTTPS-NB-0.140.0-2.mga6.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID 80420f66: NOKEY
error: Failed dependencies:
 perl(Test::More) >= 0.880.0 is needed by perl-Net-HTTPS-NB-0.140.0-2.mga6.noarch
 perl-base >= 2:5.22.1 is needed by perl-Net-HTTPS-NB-0.140.0-2.mga6.noarch
[root@c910f02c06p23 gurevich]#

and

> [root@c910f02c06p23 gurevich]# rpm -i perl-HTTP-Async-0.300.0-2.mga6.noarch.rpm
warning: perl-HTTP-Async-0.300.0-2.mga6.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID 80420f66: NOKEY
error: Failed dependencies:
 perl(HTTP::Server::Simple::CGI) is needed by perl-HTTP-Async-0.300.0-2.mga6.noarch
 perl(Net::EmptyPort) is needed by perl-HTTP-Async-0.300.0-2.mga6.noarch
 perl(Net::HTTPS::NB) >= 0.130.0 is needed by perl-HTTP-Async-0.300.0-2.mga6.noarch
 perl(Test::Fatal) is needed by perl-HTTP-Async-0.300.0-2.mga6.noarch
 perl(Test::HTTP::Server::Simple) is needed by perl-HTTP-Async-0.300.0-2.mga6.noarch
 perl-base >= 2:5.22.1 is needed by perl-HTTP-Async-0.300.0-2.mga6.noarch
[root@c910f02c06p23 gurevich]#

Do I need to download some additional rpms ?

**Comment by zet809** [comment] 2016-03-14 09:16
@gurevichmark I have downloaded the src package perl-HTTP-Async-0.300.0-2.mga6.src.rpm and find that those dependency packages mentioned above are caused by the testing scripts include in the rpm package. I think they can be removed when build our own dependency.
I have tried to build tmp dependency pkgs and put it under /tmp/gurevich/. With those 2 pkgs, you can run mkdocker or other docker lifecycle management command.
-rw-r--r-- 1 root root 29272 Mar 14 05:00 perl-HTTP-Async-0.30-2.noarch.rpm
-rw-r--r-- 1 root root 12244 Mar 14 05:00 perl-Net-HTTPS-NB-0.14-2.noarch.rpm

**Comment by zet809** [comment] 2016-03-24 08:35
@junxiawang Pls close this defect if verified.

**Closed** 2016-03-28 07:39 UTC
Labels: component:docker, priority:normal, status:pending, type:bug
