### ISSUE TITLE
yum install xCAT returns dependency errors with latest devel online repositories

### ISSUE THREAD

**Issue by pdlun92** [xcat2/xcat-core#1569] opened 2016-07-21 15:36 UTC
Running `yum install xCAT` on PowerKVM VM machine with RH7.2 installed, the following errors are observed
```
Error downloading packages:
  perl-HTTP-Async-0.30-2.noarch: [Errno 256] No more mirrors to try.
  perl-Net-Telnet-3.03-19.el7.noarch: [Errno 256] No more mirrors to try.
  1:net-snmp-perl-5.7.2-20.ael7b.ppc64le: [Errno 256] No more mirrors to try.
  perl-IO-Stty-0.03-1.noarch: [Errno 256] No more mirrors to try.
  perl-IO-Tty-1.07-1.ppc64le: [Errno 256] No more mirrors to try.
  perl-HTML-Form-6.03-6.el7.noarch: [Errno 256] No more mirrors to try.
  grub2-xcat-2.02-0.16.el7.snap201506090204.noarch: [Errno 256] No more mirrors to try.
  perl-SOAP-Lite-0.710.08-1.noarch: [Errno 256] No more mirrors to try.
  perl-Net-HTTPS-NB-0.14-2.noarch: [Errno 256] No more mirrors to try.
  perl-Crypt-Rijndael-1.09-2.ael7a.ppc64le: [Errno 256] No more mirrors to try.
  perl-Expect-1.21-1.noarch: [Errno 256] No more mirrors to try.
  conserver-xcat-8.1.16-10.ppc64le: [Errno 256] No more mirrors to try.
  perl-Crypt-CBC-2.33-2.el7.noarch: [Errno 256] No more mirrors to try.
```
additionally the following error message was observed for each of the above rpms
```
perl-Net-Telnet-3.03-19.el7.no FAILED
http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le/perl-Net-Telnet-3.03-19.el7.noarch.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=xcat-dep clean metadata
```

I believe the issue is with `xCAT-dep.repo` pointing to online development repo.  For the above errors, `xCAT-dep.repo` contains:
```
[xcat-dep]
name=xCAT 2 depedencies
baseurl=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le
enabled=1
gpgcheck=1
gpgkey=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le/repodata/repomd.xml.key
``` 
When switching to local repo, one expected error was observed, since currently xCAT-genesis-base needs to be rebuilt to include changes from Pull Request #1531 

I am not certain if xCAT-genesis-base need to be rebuilt is causing the dependency errors for online repository, though I think they are not related issues.

**Comment by whowutwut** [comment] 2016-07-21 17:30
I rebuilt the xcat-dep with the changes in #1531.. but results in the same issue with the public yum repo for xcat-dep
```
Error downloading packages:
  perl-HTTP-Async-0.30-2.noarch: [Errno 256] No more mirrors to try.
  perl-Net-Telnet-3.03-19.el7.noarch: [Errno 256] No more mirrors to try.
  grub2-xcat-2.02-0.16.el7.snap201506090204.noarch: [Errno 256] No more mirrors to try.
  perl-IO-Stty-0.03-1.noarch: [Errno 256] No more mirrors to try.
  perl-IO-Tty-1.07-1.ppc64le: [Errno 256] No more mirrors to try.
  perl-HTML-Form-6.03-6.el7.noarch: [Errno 256] No more mirrors to try.
  1:net-snmp-perl-5.7.2-20.ael7b.ppc64le: [Errno 256] No more mirrors to try.
  perl-SOAP-Lite-0.710.08-1.noarch: [Errno 256] No more mirrors to try.
  perl-Net-HTTPS-NB-0.14-2.noarch: [Errno 256] No more mirrors to try.
  perl-Crypt-Rijndael-1.09-2.ael7a.ppc64le: [Errno 256] No more mirrors to try.
  perl-Expect-1.21-1.noarch: [Errno 256] No more mirrors to try.
  conserver-xcat-8.1.16-10.ppc64le: [Errno 256] No more mirrors to try.
  perl-Crypt-CBC-2.33-2.el7.noarch: [Errno 256] No more mirrors to try.

```
Downloading that xcat-dep and running as a local repo, we get past these issues and xCAT installs.   So something is wrong with the public repo that is sync'ed onto xcat.org....

**Comment by immarvin** [comment] 2016-07-22 01:46
hi @whowutwut @pdlun92 ,

I tried to install xcat via online repo on xcat.org, did not see any errors

````

[root@c910f03c05k27-pub yum.repos.d]# yum repoinfo
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Repo-id      : local-rhels7.2-ppc64le-ppc64le
Repo-name    : xCAT configured yum repository for rhels7.2/ppc64le/ppc64le
Repo-revision: 1446216199
Repo-updated : Fri Oct 30 10:43:20 2015
Repo-pkgs    : 3,398
Repo-size    : 2.6 G
Repo-baseurl : http://10.3.5.21/install/rhels7.2/ppc64le/
Repo-expire  : 21,600 second(s) (last: Thu Jul 21 21:35:54 2016)
Repo-filename: /etc/yum.repos.d/local-repository.repo

Repo-id      : xcat-2-core
Repo-name    : xCAT 2 Core packages
Repo-revision: 1469096201
Repo-updated : Thu Jul 21 06:16:42 2016
Repo-pkgs    : 13
Repo-size    : 3.4 M
Repo-baseurl : http://xcat.org/files/xcat/repos/yum/devel/core-snap
Repo-expire  : 21,600 second(s) (last: Thu Jul 21 21:35:54 2016)
Repo-excluded: 6
Repo-filename: /etc/yum.repos.d/xCAT-core.repo

Repo-id      : xcat-dep
Repo-name    : xCAT 2 depedencies
Repo-revision: 1469116876
Repo-updated : Thu Jul 21 10:30:06 2016
Repo-pkgs    : 32
Repo-size    : 74 M
Repo-baseurl : http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le
Repo-expire  : 21,600 second(s) (last: Thu Jul 21 21:35:54 2016)
Repo-filename: /etc/yum.repos.d/xCAT-dep.repo

repolist: 3,443
[root@c910f03c05k27-pub yum.repos.d]# 
````

**Comment by immarvin** [comment] 2016-07-22 01:47
[root@c910f03c05k27-pub yum.repos.d]# lsxcatd -v 
Version 2.12.2 (git commit aa840eb1074fd7bb8557105d18eec632325114d8, built Thu Jul 21 06:16:00 EDT 2016)

**Comment by whowutwut** [comment] 2016-07-22 15:31
@immarvin  thanks for taking a look.  Did you install from scratch?  The issue seems to happen on a brand new install of xCAT.

**Comment by junxiawang** [comment] 2016-07-25 08:17
I verified no errors .
[root@c910f03fsp03v142 yum.repos.d]# yum repoinfo
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Repo-id      : xCAT-rhels7.2-path0
Repo-name    : xCAT-rhels7.2-path0
Repo-revision: 1446216199
Repo-updated : Fri Oct 30 10:43:20 2015
Repo-pkgs    : 3,398
Repo-size    : 2.6 G
Repo-baseurl : http://c910f03fsp03v140/install/rhels7.2/ppc64le
Repo-expire  : 21,600 second(s) (last: Mon Jul 25 03:51:27 2016)
Repo-filename: /etc/yum.repos.d/xCAT-rhels7.2-path0.repo

Repo-id      : xcat-core
Repo-name    : xCAT 2 Core packages
Repo-revision: 1469355399
Repo-updated : Sun Jul 24 06:16:39 2016
Repo-pkgs    : 13
Repo-size    : 3.4 M
Repo-baseurl : http://xcat.org/files/xcat/repos/yum/devel/core-snap
Repo-expire  : 21,600 second(s) (last: Mon Jul 25 03:53:36 2016)
Repo-excluded: 6
Repo-filename: /etc/yum.repos.d/xCAT-core.repo

Repo-id      : xcat-dep
Repo-name    : xCAT 2 depedencies
Repo-revision: 1469199836
Repo-updated : Fri Jul 22 09:32:45 2016
Repo-pkgs    : 32
Repo-size    : 101 M
Repo-baseurl : http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le
Repo-expire  : 21,600 second(s) (last: Mon Jul 25 03:51:27 2016)
Repo-filename: /etc/yum.repos.d/xCAT-dep.repo

repolist: 3,443
[root@c910f03fsp03v142 yum.repos.d]# 

[root@c910f03fsp03v142 yum.repos.d]# lsxcatd -v
Version 2.12.2 (git commit 0c9cb53fd4490b29b479649a092addb0c5c9ac53, built Sun Jul 24 06:15:58 EDT 2016)
[root@c910f03fsp03v142 yum.repos.d]#

**Comment by immarvin** [comment] 2016-07-25 08:52
hi @whowutwut ,  the installation I mentioned was on the newly installed redhat7.2 ppc64le system. @junxiawang and I made several test on our nodes separately this afternoon, xCAT can be installed successfully. Can this problem be recreated  everytime in the node of you and @pdlun92 ?  I found an official tech note from Redhat on this problem: https://access.redhat.com/solutions/203603 

````

Environment

    Red Hat Enterprise Linux 5 and later
    Red Hat Network (RHN)
    Subscription Management (RHSM)

Issue

    yum update fails with the error : [Errno 256] No more mirrors to try
    yum update fails with :-
Error Downloading Packages:
InstallMedia: [Errno 256] No more mirrors to try.

    yum fails with :
Error Downloading Packages:
ftp-0.17-35.el5.x86_64:failure:ftp-0.17-35.el5.x86_64.rpm from Red5repo55:[Errno 256] No more mirrors to try. [[6]]" (code -1) Packages Scheduled

    yum fails with :
Downloading Packages:
https://cdn.redhat.com/content/dist/rhel/server/6/6Server/x86_64/supplementary/os/Packages/java-1.6.0-ibm-1.6.0.15.0-1jpp.1.el6_4.x86_64.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error Downloading Packages:
  1:java-1.6.0-ibm-1.6.0.15.0-1jpp.1.el6_4.x86_64: failure: Packages/java-1.6.0-ibm-1.6.0.15.0-1jpp.1.el6_4.x86_64.rpm from rhel-6-server-supplementary-rpms: [Errno 256] No more mirrors to try.

Resolution

    Check what files are present under /etc/yum.repos.d directory by:-
# ll /etc/yum.repos.d

    If the system is registered to RHN Classic, only rhel-source.repo should be present under /etc/yum.repos.d/.
    If the system is registered to subscription-manager (RHSM), rhel-source.repo and 'redhat.repo' are present.
    If any local repositories, or any other media repositories are present, remove them by :-
# rm -rf /etc/yum.repos.d/<local or other repository name>

    Remove old yum cache from system by running following commands:
# rm -fr /var/cache/yum/*
# yum clean all

  Check if you can list the valid repositories by :-
# yum repolist

    Check the network connectivity as well.

Root Cause

    This issue persist due to following reasons:
        Corrupted yum cache.
        Inaccessibility of a repository URL from the system due to network related issues.
        Presence of customized or other media repositories.

````

**Comment by whowutwut** [comment] 2016-07-25 17:35
Very strange, I am unable to reproduce this today, so I will close this issue and re-open it if I see it in the future.  

The only thing changed was I updated the mgmt node creating my VM to 2.12.2 but I don't think this has anything to do with the compute node that was being created where I was trying the install of xCAT from the online repo.  The online repo still looks to have the timestamp of July 22, so there's nothing changed there.

**Closed by whowutwut** 2016-07-25 17:35 UTC
Labels: component:packaging, xCAT 2.12.2 Sprint 1
