### ISSUE TITLE
[FVT]2.11 fireware update  failed on some of the Firestone  machine when concurrently do rflash

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#471] opened 2015-11-25 09:08 UTC
xCAT 2.11 on rh7.2
[root@c910f03c05k23 xcat-dep]# lsxcatd -v
Version 2.11 (git commit 9885d9acba568e21137ca1be624d0ba8b1655091, built Tue Nov 24 03:05:32 EST 2015)
[root@c910f03c05k23 firmware]# rflash c910f05c37,c910f05c33 8335_810.1549.20151116c.hpm
c910f05c37: rflash started, please wait.......
c910f05c33: rflash started, please wait.......
c910f05c33: Error: Running ipmitool command /opt/xcat/bin/ipmitool-xcat -H 50.5.33.10 -I lanplus -U ADMIN -P passw0rd -z 30000 hpm upgrade /firmware/8335_810.1549.20151116c.hpm force failed.
c910f05c37: rflash completed.

**Comment by chenglch** [comment] 2015-11-25 12:49
When I set the sleep time to 120s @tingtli has success to update 3 Firestone machines  concurrently.
I haven't found the root cause, so I prepare to  add a timeout option to set the sleep time for rflash command  at first

**Comment by whowutwut** [comment] 2015-11-25 13:29
@chenglch , yeah this is the concern when adding sleep time... It would be best if we could query for some status (say.. every 5-10 seconds)  then continue if we can detect some status change.... Otherwise we are always guessing the right timeout.. which won't work every time..

**Comment by chenglch** [comment] 2015-12-09 03:02
The root cause for this issue is from internal of ipmitool. ``rflash`` is not stable enough and a workaround is provided. We'd better not to use  ``concurrently`` to describe this issue as ``rflash`` also fails in some case with only one node.

**Comment by whowutwut** [comment] 2016-04-15 19:10
@tingtli , @pdlun92 made pull request #818 which should improve the stability of rflash.

**Comment by whowutwut** [comment] 2016-04-21 13:53
Closing this issue for now and I think xCAT is doing the right thing for the ``rflash`` command with the pull requests associated with this issue.  

Will open new issues if we see them on the large systems when running rflash with 2.11.1 build.

**Closed by whowutwut** 2016-04-21 13:53 UTC
Labels: priority:normal, status:pending, type:bug
