### ISSUE TITLE
invalid output from xcatprobe discovery 

### ISSUE THREAD

**Issue by thilo-maurer** [xcat2/xcat-core#5488] opened 2018-08-09 15:44 UTC
xCAT was setup to discover multiple nodes. Predefined nodes are in group `discovered_nodes`.
Discovery process is started using `rsetboot bmc net; rpower bmc on`
Now probing MTMS discovery: 
```
$> date
Thu Aug 9 17:10:45 CEST 2018
$> xcatprobe discovery -n discovered_nodes -m mtms
All pre_defined nodes are valid                                   [ OK ]
Attribute 'master' in 'site' table is configured                  [ OK ]
DHCP dynamic range is configured                                  [ OK ]
Genesis files are avaliable                                       [ OK ]

-------------------------------------------------------------
                               ___
        ____    _  _____   _.-|   |          |\__/,|   (`\
 __  __/ ___|  / \|_   _| {   |   |          |x x  |__ _) )
 \ \/ / |     / _ \ | |    "-.|___|        _.( T   )  `  /
  >  <| |___ / ___ \| |    .--'-`-.     _((_ `^--' /_<  \
 /_/\_\\____/_/   \_\_|  .+|______|__.-||__)`-'(((/  (((/
-------------------------------------------------------------

Start capturing every message during discovery process......
```
but no further output (hanging until CTRL-C).

However, in a separate shell I see
```
$> journalctl -f | grep discovery
Aug 09 17:16:23 ubuntu xcat[42206]: xcatd: Processing discovery request from 10.0.0.75
Aug 09 17:16:23 ubuntu xcat[42206]: xcat.discovery.aaadiscovery: (40:f2:e9:d3:83:a0) Got a discovery request, attempting to discover the node...
Aug 09 17:16:23 ubuntu xcat[42206]: xcat.discovery.blade: (40:f2:e9:d3:83:a0) Warning: Could not find any nodes using blade-based discovery
Aug 09 17:16:23 ubuntu xcat[42206]: xcat.discovery.switch: (40:f2:e9:d3:83:a0) Warning: Could not find any nodes using switch-based discovery
Aug 09 17:16:23 ubuntu xcat[42206]: xcat.discovery.mtms: (40:f2:e9:d3:83:a0) Found node: node1
Aug 09 17:16:24 ubuntu xcat[42206]: xcat.discovery.nodediscover: remove gocons session for
Aug 09 17:16:24 ubuntu xcat[42206]: xcat.discovery.nodediscover: Removing discovered BMC nodes definition: ...
Aug 09 17:16:24 ubuntu xcat[42206]: xcat.discovery.nodediscover:  definition removed from xCAT
Aug 09 17:16:24 ubuntu xcat[42206]: xcat.discovery.nodediscover: node1 has been discovered
Aug 09 17:16:24 ubuntu xcat[42206]: xcat.discovery.zzzdiscovery: (40:f2:e9:d3:83:a0) Successfully discovered the node using mtms discovery method.
Aug 09 17:16:30 ubuntu xcat[42206]: xcatd: Processing discovery request from 10.0.0.76
Aug 09 17:16:30 ubuntu xcat[42206]: xcat.discovery.aaadiscovery: (40:f2:e9:d3:8e:90) Got a discovery request, attempting to discover the node...
Aug 09 17:16:30 ubuntu xcat[42206]: xcat.discovery.blade: (40:f2:e9:d3:8e:90) Warning: Could not find any nodes using blade-based discovery
Aug 09 17:16:30 ubuntu xcat[42206]: xcat.discovery.switch: (40:f2:e9:d3:8e:90) Warning: Could not find any nodes using switch-based discovery
Aug 09 17:16:30 ubuntu xcat[42206]: xcat.discovery.mtms: (40:f2:e9:d3:8e:90) Found node: node3
Aug 09 17:16:30 ubuntu xcat[42206]: xcat.discovery.nodediscover: remove gocons session for
Aug 09 17:16:30 ubuntu xcat[42206]: xcat.discovery.nodediscover: Removing discovered BMC nodes definition: ...
Aug 09 17:16:31 ubuntu xcat[42206]: xcat.discovery.nodediscover:  definition removed from xCAT
Aug 09 17:16:31 ubuntu xcat[42206]: xcat.discovery.nodediscover: node3 has been discovered
Aug 09 17:16:31 ubuntu xcat[42206]: xcat.discovery.zzzdiscovery: (40:f2:e9:d3:8e:90) Successfully discovered the node using mtms discovery method.
Aug 09 17:17:36 ubuntu xcat[42206]: xcatd: Processing discovery request from 10.0.0.74
Aug 09 17:17:36 ubuntu xcat[42206]: xcat.discovery.aaadiscovery: (98:be:94:06:dd:dc) Got a discovery request, attempting to discover the node...
Aug 09 17:17:36 ubuntu xcat[42206]: xcat.discovery.blade: (98:be:94:06:dd:dc) Warning: Could not find any nodes using blade-based discovery
Aug 09 17:17:36 ubuntu xcat[42206]: xcat.discovery.switch: (98:be:94:06:dd:dc) Warning: Could not find any nodes using switch-based discovery
Aug 09 17:17:36 ubuntu xcat[42206]: xcat.discovery.mtms: (98:be:94:06:dd:dc) Found node: node2
Aug 09 17:17:37 ubuntu xcat[42206]: xcat.discovery.nodediscover: remove gocons session for node-8335-gtb-783567a
Aug 09 17:17:37 ubuntu xcat[42206]: xcat.discovery.nodediscover: Removing discovered BMC nodes definition: node-8335-gtb-783567a...
Aug 09 17:17:38 ubuntu xcat[42206]: xcat.discovery.nodediscover: node-8335-gtb-783567a definition removed from xCAT
Aug 09 17:17:38 ubuntu xcat[42206]: xcat.discovery.nodediscover: node2 has been discovered
Aug 09 17:17:38 ubuntu xcat[42206]: xcat.discovery.zzzdiscovery: (98:be:94:06:dd:dc) Successfully discovered the node using mtms discovery method.
```

**Comment by whowutwut** [comment] 2018-08-09 15:56
@hu-weihua  can you take  a look? thanks

**Comment by hu-weihua** [comment] 2018-08-10 02:51
hi @thilo-maurer, could you please attach below information for me? They will be helpful.

* The discovered_nodes.stanza file
   ```
    lsdef discovered_nodes -z > discovered_nodes.stanza
   ```

Please rerun ``xcatprobe discovery -n discovered_nodes -m mtms`` then attach new generated below 3 log files. thanks
*  /var/log/messages
*  /var/log/xcat/cluster.log
*  /var/log/xcat/computes.log

**Comment by thilo-maurer** [comment] 2018-08-10 09:28
Here's the stanza file immediately after power-on and running xcatprobe: [discovered_nodes.stanza.txt](https://github.com/xcat2/xcat-core/files/2277357/discovered_nodes.stanza.txt)

- /var/log/messages - no content since my ubuntu 16.04 uses journalctl
- /var/log/xcat/cluster.log - not existing
- /var/log/xcat/computes.log - not existing
- /var/log/xcat/commands.log - existing, but not requested
- journalctl: [journalctl.txt](https://github.com/xcat2/xcat-core/files/2277389/journalctl.txt)

**Comment by thilo-maurer** [comment] 2018-08-13 07:26
I left xCAT configuration standard.

`/var/log/messages` only contains a tiny subset of messages from the dhcp daemon.

How to enable the logging? - Is it http://xcat-docs.readthedocs.io/en/stable/troubleshooting/os_installation/log_to_mn_cn.html

From this document, It seems that `site.xcatdebugmode=0` should be enough. Since I don't get any logs, maybe the value 0 is not the default value?

**Comment by thilo-maurer** [comment] 2018-08-13 09:44
Now set `site.xcatdebugmode=0`, since default is unset.

However, no new output in `/var/log/messages` or `/var/log/xcat/computes.log`, and therefore still no output from `xcatprobe discovery`.

Do I need to restart xcatd for changes to take effect?

**Comment by hu-weihua** [comment] 2018-08-16 07:29
@thilo-maurer, sorry to replay later.
I think the log has nothing to do with ``site.xcatdebugmode``.

Could you paste me below information, thanks.

* The output of ``ps axu|grep rsyslog``?  normally there is a daemon ``rsyslogd`` running. 

*  The content of below files:
```
cat /etc/rsyslog.conf
cat /etc/rsyslog.d/50-default.conf
cat /etc/rsyslog.d/xcat-cluster.conf
cat /etc/rsyslog.d/xcat-compute.conf
```

**Comment by robin2008** [comment] 2018-08-20 03:41
@thilo-maurer 
I think you are using ubuntu for xCAT mn,  and the default `rsyslog` configuration is log to `/var/log/syslog`, instead of `/var/log/messages`.

For example,  in `/etc/rsyslog.d/50-default.conf`, you may find the below line
```
*.*;auth,authpriv.none         -/var/log/syslog
```
you can change it to `*.*;auth,authpriv.none         -/var/log/messages` and restart rsyslog by
`systemctl restart rsyslog`

After the it restated, check `/var/log/messages` again.

**Comment by thilo-maurer** [comment] 2018-08-20 21:52
@hu-weihua 
-  Yes, rsyslogd is running:
```
root@node0:~# ps axu|grep rsyslog
syslog     2924  0.0  0.0 394112  7104 ?        Ssl  09:18   0:01 /usr/sbin/rsyslogd -n
root     129206  0.0  0.0   6272  1920 pts/2    S+   23:39   0:00 grep --color=auto rsyslog
```
Here are the files [syslogs.tar.gz](https://github.com/xcat2/xcat-core/files/2304041/syslogs.tar.gz): (ignore everything before Aug 20 23:20:34)
```
/etc/rsyslog.conf
/etc/rsyslog.d/*
/var/log/syslog
```
syslog contains quite some discovery events:
```
root@node0:~#  grep discovery --text /var/log/syslog
Aug 20 23:27:29 10.1.0.10 [localhost] xcat.genesis.doxcat: Running dodiscovery...
Aug 20 23:27:29 10.1.0.10 [localhost] xcat.genesis.dodiscovery: Beginning node discovery process...
Aug 20 23:27:29 10.1.0.10 [localhost] xcat.genesis.dodiscovery: Waiting for nics to get addresses
Aug 20 23:27:38 10.2.0.3 [localhost] xcat.genesis.dodiscovery: Network configuration complete, commencing transmit of discovery packets
Aug 20 23:27:38 10.2.0.3 [localhost] xcat.genesis.dodiscovery: Beginning echo information to discovery packet file...
Aug 20 23:27:39 10.2.0.3 [localhost] xcat.genesis.dodiscovery: Discovery packet file is ready.
Aug 20 23:27:39 10.2.0.3 [localhost] xcat.genesis.dodiscovery: Sending the discovery packet to xCAT (10.2.0.1:3001)...
Aug 20 23:27:39 10.2.0.3 [localhost] xcat.genesis.dodiscovery: Sleeping 5 seconds...
Aug 20 23:27:42 node0 xcat[79440]: xcatd: Processing discovery request from 10.2.0.3
Aug 20 23:27:42 node0 xcat[79440]: xcat.discovery.aaadiscovery: (98:be:94:06:dd:dc) Got a discovery request, attempting to discover the node...
Aug 20 23:27:42 node0 xcat[79440]: xcat.discovery.blade: (98:be:94:06:dd:dc) Warning: Could not find any nodes using blade-based discovery
Aug 20 23:27:42 node0 xcat[79440]: xcat.discovery.switch: (98:be:94:06:dd:dc) Warning: Could not find any nodes using switch-based discovery
Aug 20 23:27:42 node0 xcat[79440]: xcat.discovery.mtms: (98:be:94:06:dd:dc) Found node: node2
Aug 20 23:27:43 node0 xcat[79440]: xcat.discovery.nodediscover: remove gocons session for node-8335-gtb-783567a
Aug 20 23:27:43 node0 xcat[79440]: xcat.discovery.nodediscover: Removing discovered BMC nodes definition: node-8335-gtb-783567a...
Aug 20 23:27:44 node0 xcat[79440]: xcat.discovery.nodediscover: node-8335-gtb-783567a definition removed from xCAT
Aug 20 23:27:44 node0 xcat[79440]: xcat.discovery.nodediscover: node2 has been discovered
Aug 20 23:27:44 node0 xcat[79440]: xcat.discovery.zzzdiscovery: (98:be:94:06:dd:dc) Successfully discovered the node using mtms discovery method.
Aug 20 23:27:44 10.2.0.3 [localhost] xcat.genesis.dodiscovery: Restart network interfaces...
Aug 20 23:28:01 node2 xcat.genesis.doxcat: dodiscovery - Complete.
```

This is the output of 
```
root@node0:~# xcatprobe xcatmn -i enP5p9s0f0
All pre_defined nodes are valid                                           [ OK ]
Attribute 'master' in 'site' table is configured                          [ OK ]
DHCP dynamic range is configured                                          [ OK ]
Genesis files are avaliable                                               [ OK ]

-------------------------------------------------------------
                               ___
        ____    _  _____   _.-|   |          |\__/,|   (`\
 __  __/ ___|  / \|_   _| {   |   |          |x x  |__ _) )
 \ \/ / |     / _ \ | |    "-.|___|        _.( T   )  `  /
  >  <| |___ / ___ \| |    .--'-`-.     _((_ `^--' /_<  \
 /_/\_\\____/_/   \_\_|  .+|______|__.-||__)`-'(((/  (((/
-------------------------------------------------------------

Start capturing every message during discovery process......
```

@robin2008 
Yes, I can see this line. I will try to change it to log to messages and see if xcatprobe then reads the discovery messages.

**Comment by thilo-maurer** [comment] 2018-08-20 22:19
@robin2008 Yes, with your suggested change to rsyslog config, `xcatprobe xcatmn` now shows discovery messages, ending in
```
==================discovery_probe_report=================
All nodes matched successfully                                            [ OK ]
```
Awesome progress!

In order to fix this, should
A. `xcatprobe xcatmn` also read from `/var/log/syslog*`
B. `rsyslog` write to `/var/log/messages`

I think A, since RHEL systems don't have `/var/log/messages` messages any longer?

**Comment by robin2008** [comment] 2018-08-21 02:06
For RHEL,  its rsyslog will default log into `/var/log/message`,  while it is `/var/log/syslog` in ubuntu.

In many releases before,  xCAT changed default `rsyslog` settings to make them all to `/var/log/message` both for RHEL and Ubuntu, and it causes some side impacts.

So xCAT now will not touch the default settings in `/etc/rsyslog.conf`, but the `xcatprobe` does not  change accordingly. 

And yes, we need to fix it,  I prefer the option A.
- xcatprobe need to cover /var/log/syslog*
- check `xcat-debug.conf` to see if it is still required on ubuntu,  if yes,  it needs to in  /var/log/syslog for ubuntu.

@hu-weihua @neo954

**Comment by hu-weihua** [comment] 2018-08-21 06:14
@thilo-maurer , I have opened a task to enhance ``xcatprobe discovery`` in xcat 2.14.4 development cycle. If you think the workaround offered by @robin2008 have fixed you problem, could you close this issue? Or if you want to wait for xCAT 2.14.4 release, verify the fix in 2.14.4 then close this issue, that is also ok. Thanks for your try against xcatprobe. Any further suggestion about xcatprobe are welcome.

**Comment by thilo-maurer** [comment] 2018-08-21 11:13
Actually, no.
I think that `xcatprobe` watching `/var/log/messages` is actually the wrong way.

Here's why:

xCAT already comes with `rsyslog` config file `/etc/rsyslog.d/xcat-cluster.conf` to reroute xcat messages to `/var/log/xcat/cluster.log` which in turn would be picked up by `xcatprobe`:
```
root@node0:~# ll /etc/rsyslog.d/
total 40
drwxr-xr-x   2 root root  4096 Aug 21 12:53 ./
drwxr-xr-x 107 root root 12288 Aug 21 12:35 ../
-rw-r--r--   1 root root   314 Sep  8  2015 20-ufw.conf
-rw-r--r--   1 root root  1657 Aug 21 11:45 50-default.conf
-rw-r--r--   1 root root   101 Jul  3 12:26 srp_daemon.conf
-rw-r--r--   1 root root   293 Aug 21 12:53 xcat-cluster.conf
-rw-r--r--   1 root root   221 Jul 11 13:16 xcat-compute.conf
-rw-r--r--   1 root root   136 Jul 11 13:16 xcat-debug.conf
```

Unfortunately `rsyslog` has issues writing those files, and that's why xcatprobe cannot pick them up:
```
2455.589292499:main Q:Reg/w0  : file '/var/log/xcat/cluster.log' opened as #-1 with mode 416
2455.589300155:main Q:Reg/w0  : strm 0x3fff80004130: open error 13, file '/var/log/xcat/cluster.log': Permission denied
```

Here's the reason for that: `/var/log/xcat` has wrong permissions
```
root@node0:~# ll /var/log/messages
-rw-r--r-- 1 syslog adm 150944 Aug 21 11:11 /var/log/messages
root@node0:~# ll /var/log/xcat/
total 11160
drwx------  4 root root      4096 Aug 21 06:25 ./
drwxrwxr-x 13 root syslog    4096 Aug 21 06:25 ../
-rw-------  1 root root     21677 Aug 21 11:07 commands.log
-rw-------  1 root root   7281436 Aug 21 00:12 commands.log.1
-rw-------  1 root root   4094270 Aug 12 00:47 commands.log.2
drwxr-xr-x  2 root root      4096 Aug  6 13:14 dump/
drwx------  2 root root      4096 Aug  6 13:14 rflash/
```

And here's how to solve that (for ubuntu16.04)
```
chown syslog:adm /var/log/xcat
chmod 750 /var/log/xcat
```

Now `cluster.log` gets written:
```
root@node0:# ll /var/log/xcat/
total 11248
drwxr-x---  4 syslog adm       4096 Aug 21 12:25 ./
drwxrwxr-x 13 root   syslog    4096 Aug 21 06:25 ../
-rw-r-----  1 syslog adm        505 Aug 21 12:25 cluster.log
-rw-------  1 root   root    103622 Aug 21 12:25 commands.log
-rw-------  1 root   root   7281436 Aug 21 00:12 commands.log.1
-rw-------  1 root   root   4094270 Aug 12 00:47 commands.log.2
drwxr-xr-x  2 root   root      4096 Aug  6 13:14 dump/
drwx------  2 root   root      4096 Aug  6 13:14 rflash/
```

So, the right way is to set proper permissions for `/var/log/xcat`, depending on the OS.
I suggest to remove #284, and to instead implement above.

**Comment by robin2008** [comment] 2018-08-22 01:51
@thilo-maurer   only the log tagged with `xcat` or `xcat.*` will be in `cluster.log`, `xcatprobe` might still needs other logs, like `dhcp` or `tftp`, and  those will not be in `cluster.log`.

**Comment by hu-weihua** [comment] 2018-10-12 07:47
@thilo-maurer Could you verify this fix in your environment? thanks

For the  permission of ``/var/log/xcat/`` problem, I did not reproduced in my environment. After xcat default installation in ubuntu18.04.1 which has ``/var/log/syslog``, I got below permission:

```
root@f6u13k13:/var/log# ll /var/log/xcat/
total 7128
drwxr-xr-x  4 syslog adm       4096 Oct 11 07:54 ./
drwxrwxr-x 14 root   syslog    4096 Oct 11 07:51 ../
-rw-r--r--  1 root   root       294 Oct 11 07:42 autotest.log
-rw-r-----  1 syslog adm     347796 Oct 12 00:31 cluster.log
-rw-------  1 root   root   6303401 Oct 12 00:31 commands.log
-rw-r-----  1 syslog adm     606530 Oct 12 03:17 computes.log
drwxr-xr-x  2 root   root      4096 Oct 11 07:44 dump/
drwx------  2 root   root      4096 Oct 11 07:44 rflash/
-rw-r--r--  1 root   root      5411 Oct 11 07:38 xcat.log
```

**Comment by thilo-maurer** [comment] 2018-10-12 08:47
I was using ubuntu16.04.5, so it might be different there.
How to verify? Is there a deb that I should install or should I just apply https://github.com/xcat2/xcat-core/pull/5696/commits/f3f7890225efe689e3c16b12e7a0fc5eb87bb75b ?

**Comment by hu-weihua** [comment] 2018-10-15 03:06
xCAT builds a package for development and regression test every day.  You can download the latest daily build through below links.

* [RPM build]( https://xcat.org/files/xcat/xcat-core/devel/Linux/core-snap/core-rpms-snap.tar.bz2) 
* [DEB build](https://xcat.org/files/xcat/xcat-core/devel/Ubuntu/core-snap/core-debs-snap.tar.bz2)

**Comment by hu-weihua** [comment] 2018-10-18 06:07
@thilo-maurer, since we have verified this fix in our environment, I closed this issue first. If you find it can not work at your environment, feel free to reopen it again. thanks.

**Closed by hu-weihua** 2018-10-18 06:07 UTC
Labels: component:xcatprobe, sprint2, status:pending
