### ISSUE TITLE
[OpenBMC] rflash unattended problems - generic issue

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4454] opened 2017-12-06 19:15 UTC
This function is not yet avail for mainstream use, running it at small scale does prove to be problematic... so I would not recommend to run it yet..  

Creating a generic issue to track some things that I find. 

1) There needs to be a timeout (my wish is to have the value configurable) so after 30 minutes or so.... we should return control to the user.   Started a flash shortly before noon... and the last message I see is...    
```
state/host0/attr/RequestedHostTransition
Wed Dec  6 12:02:58 2017 mid05tor12cn05: [openbmc_debug] rpower_on_response 200 OK
mid05tor12cn05: reset

```
The above is hung and will remain hung forever and it doesn't seem to be moving anymore, so somewhere in the code we have stopped polling. 

My debug is captured here: 
[rflash.unattended.2.txt](https://github.com/xcat2/xcat-core/files/1536549/rflash.unattended.2.txt)

Filtering out the debug messages shows: 
```
[root@briggs01 910.1746.20171116b_1742Ed]# rflash p9up -d /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed
mid05tor12cn13: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.83 (ID: 82087175)
mid05tor12cn13: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r9-0-gecda565 (ID: 608e9ebe)
mid05tor12cn18: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.83 (ID: 82087175)
mid05tor12cn18: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r9-0-gecda565 (ID: 608e9ebe)
mid05tor12cn02: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.83 (ID: 82087175)
mid05tor12cn02: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r9-0-gecda565 (ID: 608e9ebe)
mid05tor12cn16: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.83 (ID: 82087175)
mid05tor12cn16: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r9-0-gecda565 (ID: 608e9ebe)
mid05tor12cn05: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.83 (ID: 82087175)
mid05tor12cn05: Firmware upload successful. Attempting to activate firmware: ibm-v2.0-0-r9-0-gecda565 (ID: 608e9ebe)
mid05tor12cn18: Firmware IBM-witherspoon-ibm-OP9_v1.19_1.83 activation successful.
mid05tor12cn18: Firmware ibm-v2.0-0-r9-0-gecda565 activation successful.
mid05tor12cn18: BMC reboot
mid05tor12cn05: Firmware IBM-witherspoon-ibm-OP9_v1.19_1.83 activation successful.
mid05tor12cn05: Firmware ibm-v2.0-0-r9-0-gecda565 activation successful.
mid05tor12cn05: BMC reboot
mid05tor12cn18: Retry BMC state, wait for 15 seconds ...
mid05tor12cn05: Retry BMC state, wait for 15 seconds ...
mid05tor12cn18: Retry BMC state, wait for 15 seconds ...
mid05tor12cn05: Retry BMC state, wait for 15 seconds ...
mid05tor12cn18: Retry BMC state, wait for 15 seconds ...
mid05tor12cn13: Retry BMC state, wait for 15 seconds ...
mid05tor12cn16: Retry BMC state, wait for 15 seconds ...
mid05tor12cn02: Retry BMC state, wait for 15 seconds ...
mid05tor12cn13: BMC Ready
mid05tor12cn16: BMC Ready
mid05tor12cn05: Retry BMC state, wait for 15 seconds ...
mid05tor12cn02: BMC Ready
mid05tor12cn18: Retry BMC state, wait for 15 seconds ...
mid05tor12cn16: reset
mid05tor12cn02: reset
mid05tor12cn18: BMC Ready
mid05tor12cn13: reset
mid05tor12cn18: reset
mid05tor12cn05: reset
```

**Comment by bybai** [comment] 2017-12-07 02:05
Hi @whowutwut,
For current design, after the "bmcreboot", it will reboot the host using all machine states the same with "rpower boot", then rflash command exit.
Do you mean: after "rpower boot", it should wait and check the "rpower state" for minutes until the host state is on or off else, then ``rflash`` command exit?

**Comment by bybai** [comment] 2017-12-07 02:27
Hi @whowutwut ,
From your log:
Only mid05tor12cn18 and mid05tor12cn05 are flashed. Other nodes do nothing only "bmcreboot" and "rpower boot". So let me check .

**Comment by whowutwut** [comment] 2017-12-07 04:13
@bybai Yes, adding it for more details. When I looked at the end.... here's the results. 

Target was flashing to BMC -r9 and PNOR .83

```
[root@briggs01 ~]# rflash p9up -l  | egrep "\*|\+" | xcoll
====================================
mid05tor12cn05,mid05tor12cn18
====================================
82087175 Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.83
608e9ebe BMC     Active(*)  ibm-v2.0-0-r9-0-gecda565

====================================
mid05tor12cn13,mid05tor12cn16,mid05tor12cn02
====================================
82087175 Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.83
608e9ebe BMC     Active(+)  ibm-v2.0-0-r9-0-gecda565
3a7f1407 BMC     Active(*)  ibm-v2.0-0-r13-0-g3a160ac

====================================
mid05tor12cn15
====================================
7c4d7d61 Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.87
3a7f1407 BMC     Active(*)  ibm-v2.0-0-r13-0-g3a160ac
```

* cn05 and cn18 are GOOD!
* cn15 didn't get anything done on it....
* cn13,cn16,cn02 looks like PNOR was flashed, but BMC didn't get flashed..

**Comment by bybai** [comment] 2017-12-07 08:53
Hi @whowutwut ,
Based on my debug, I think rflash "upload" image many times can affect the BMC state, and may cause curious results, even cause cannot login BMC. Another is that flashing from higher firmware to lower version may have problem in my testing, like flashing from Ef to Ed.  
I used p9up(including cn02, cn05, cn15, cn16, cn18) to do test. cn05 failed to login bmc at the begging. It is hard to reproduce above issues, we need more testing to find a way to produce it.
I tried the following scenarios several times.

**scenario 1** I used ''--delete" to delete unused image from all CN. Then I flashed from Ed to Ee, cn02,cn15,cn16 and cn18 are all GOOD.

 **scenario 2** I flashed Ee to Ef,  cn02,cn15,cn16 and cn18 are all GOOD.
```
[root@briggs01 xCAT_plugin]# rflash p9up -l| egrep "\*|\+" | xcoll
mid05tor12cn05: Error: [500] Login to BMC failed: 500 Can't connect to mid05tor12cn05-bmc:443 (No route to host).
mid05tor12cn05: Error: BMC did not respond. Validate BMC configuration and retry the command.
====================================
mid05tor12cn16,mid05tor12cn15,mid05tor12cn02,mid05tor12cn18
====================================
3a7f1407 BMC     Active(*)  ibm-v2.0-0-r13-0-g3a160ac
78abd177 Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.88
```
**scenario 3**, flashing Ef to Ed, cn02,cn15 and cn18 are GOOD, but  cn16 PNOR was flashed while BMC didn't get flashed. It seems it reproduced. But I got the different log from yours.
From debug log, I can see ``rflash`` send ``bmcreboot`` and the cn16 bmc is reboot, and after bmc is ready, host cn16 is booted too.  An interesting thing is that others picked up the cn16 under sn02 at that moment, so I did not know if it was affected. Then I used "rflash mid05tor12cn16 -d /mnt/xcat/iso/openbmc/910.1746.20171116b_1742Ed/ --no-host-reboot" , mid05tor12cn16 bmc and pnor are both flashed well again.  I guess that flashing from higher firmware to lower version may have problem, like flashing from Ef to Ed.

**Comment by whowutwut** [comment] 2017-12-12 16:23
@bybai Ee to Ef doesn't trigger a bmc flash... that could be one reason it's more successful. 
http://pfd.austin.ibm.com/releasenotes/indexop910.html 

Oh, but I see scenario 1->2->does have a BMC flash in scenario 1..    

So for cn16, it reboot bmc and reboot host, but it didn't reflect the new version of BMC?  

Seems strange that it would work on most nodes and not on others..

**Comment by bybai** [comment] 2017-12-13 03:05
Hi @whowutwut, I checked at that time, some member in our team change cn16 under sn, so during my testing, cn16 was disconnected with MN by coincidence, I think it may be the reason. I think FVT will cover multiple CNs testing for ``rflash -d`` function later.

**Comment by bybai** [comment] 2017-12-14 05:24
Cannot reproduce it, close it now, if it is reproduced in future, can open it again.

**Closed by bybai** 2017-12-14 05:24 UTC
Labels: component:openbmc, sprint2, type:bug
