### ISSUE TITLE
[FVT]confignetwork returns 0 when there are error in the script

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#3429] opened 2017-07-11 07:13 UTC
xCAT 2.13.5 
1. config network table and nics table
```
[root@c910f02c01p22 /]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"10_0_0_0-255_0_0_0","10.0.0.0","255.0.0.0","eth1","10.0.0.103",,"10.2.1.22",,,,,,,,,,,,,
"autotest_ent","192.168.10.0","255.255.255.0",,"192.168.10.3",,,,,,,,,,,,,,,
"testnetwork","100.100.100.0","255.255.255.0","!remote!eth0","100.100.100.1",,,,,,,,,,,,,,,
"11_1_0_0-255_255_0_0","11.1.0.0","255.255.0.0","eth2",,,,,,,,,,,,,,"1500",,
"12_1_0_0-255_255_0_0","12.1.0.0","255.255.0.0","eth0",,,,,,,,,,,,,,"1500",,
"30_5_0_0-255_255_0_0","30.5.0.0","255.255.0.0",,,,,,,,,,,,,,,"1500",,
"40_5_0_0-255_255_0_0","40.5.0.0","255.255.0.0",,,,,,,,,,,,,,,"1500",,
[root@c910f02c01p22 /]# tabdump nics
#node,nicips,nichostnamesuffixes,nichostnameprefixes,nictypes,niccustomscripts,nicnetworks,nicaliases,nicextraparams,nicdevices,nicsadapter,comments,disable
"c910f02c01p23","bond0.3!40.5.106.8,eth2!11.1.0.100,bond0.2!30.5.106.8,eth0!12.1.0.100",,,"bond0.3!vlan,eth2!ethernet,bond0.2!vlan,bond0!bond,eth0!ethernet",,"bond0.3!40_5_0_0-255_255_0_0,eth2!11_1_0_0-255_255_0_0,bond0.2!30_5_0_0-255_255_0_0,eth0!12_1_0_0-255_255_0_0",,,"bond0.3!bond0,bond0.2!bond0,bond0!eth2|eth0",,,
```

2. run updatenode -P confignetwork and get the error
```
RUN:updatenode c910f02c01p23 -P confignetwork [Tue Jul 11 02:57:49 2017]
ElapsedTime:22 sec
RETURN rc = 0
OUTPUT:
c910f02c01p23: xcatdsklspost: updating VPD database
c910f02c01p23: xcatdsklspost: downloaded postscripts successfully
c910f02c01p23: Tue Jul 11 02:58:01 EDT 2017 Running postscript: confignetwork
c910f02c01p23: [I]: All valid nics and device list:
c910f02c01p23: [I]: bond0 eth2@eth0
c910f02c01p23: [I]: bond0.2 bond0
c910f02c01p23: [I]: bond0.3 bond0
c910f02c01p23: [I]: NetworkManager is inactive.
c910f02c01p23: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c910f02c01p23: configure nic and its device : bond0 eth2@eth0
c910f02c01p23: [I]: create_bond_interface ifname=bond0 slave_ports=eth2,eth0
c910f02c01p23: [I]: Pickup xcatnet, "", from NICNETWORKS for interface "bond0".
c910f02c01p23: [I]: ip link set bond0 down
c910f02c01p23: [I]: [bond.down] >> 257889: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN
c910f02c01p23: [I]: [bond.down] >>     link/ether 8e:30:5f:a0:54:df brd ff:ff:ff:ff:ff:ff
c910f02c01p23: [I]: [bond.slavesAft] >>
c910f02c01p23: [I]: ip link set eth2 down
c910f02c01p23: [I]: [slave]: >> 4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
c910f02c01p23: [I]: [slave]: >>     link/ether e6:d4:d2:3a:ad:04 brd ff:ff:ff:ff:ff:ff
c910f02c01p23: [I]: create_persistent_ifcfg ifname=eth2 inattrs=ONBOOT=yes,NM_CONTROLLED=no,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none,MTU=[E]: Fail to get "" for network "mtu"
c910f02c01p23: ./nicutils.sh: line 437: Fail: command not found
c910f02c01p23: ['ifcfg-eth2']
c910f02c01p23: [I]: >> DEVICE="eth2"
c910f02c01p23: [I]: >> BOOTPROTO="static"
c910f02c01p23: [I]: >> NAME="eth2"
c910f02c01p23: [I]: >> HWADDR="e6:d4:d2:3a:ad:04"
c910f02c01p23: [I]: >> "
c910f02c01p23: [I]: ip link set eth0 down
c910f02c01p23: [I]: [slave]: >> 2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN qlen 1000
c910f02c01p23: [I]: [slave]: >>     link/ether 00:21:5e:a9:a3:36 brd ff:ff:ff:ff:ff:ff
c910f02c01p23: [I]: create_persistent_ifcfg ifname=eth0 inattrs=ONBOOT=yes,NM_CONTROLLED=no,USERCTL=no,TYPE=Ethernet,SLAVE=yes,MASTER=bond0,BOOTPROTO=none,MTU=[E]: Fail to get "" for network "mtu"
c910f02c01p23: ./nicutils.sh: line 437: Fail: command not found
c910f02c01p23: ['ifcfg-eth0']
c910f02c01p23: [I]: >> DEVICE="eth0"
c910f02c01p23: [I]: >> BOOTPROTO="static"
c910f02c01p23: [I]: >> NAME="eth0"
c910f02c01p23: [I]: >> HWADDR="00:21:5e:a9:a3:36"
c910f02c01p23: [I]: >> "
c910f02c01p23: [I]: [bond.slavesNew] >> eth2 eth0
c910f02c01p23: Error: argument "[E]:" is wrong: Invalid "mtu" value
c910f02c01p23: [I]: ip link set bond0 up
c910f02c01p23: [I]: State of "bond0" was "DOWN" instead of expected "UP". Wait 0 of 200 with interval 1.
c910f02c01p23: [I]: [ip.link] >> 257889: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
c910f02c01p23: [I]: [ip.link] >>     link/ether e6:d4:d2:3a:ad:04 brd ff:ff:ff:ff:ff:ff
c910f02c01p23: [I]: create_persistent_ifcfg ifname=bond0 xcatnet= inattrs=ONBOOT=yes,NM_CONTROLLED=no,USERCTL=no,TYPE=Bond,BONDING_MASTER=yes,BONDING_OPTS='mode=802.3ad miimon=100',BOOTPROTO=none,DHCLIENTARGS='-timeout 200',MTU=[E]: Fail to get "" for network "mtu"
c910f02c01p23: ./nicutils.sh: line 437: Fail: command not found
c910f02c01p23: ['ifcfg-bond0']
c910f02c01p23: [I]: >> DEVICE="bond0"
c910f02c01p23: [I]: >> BOOTPROTO="static"
c910f02c01p23: [I]: >> NAME="bond0"
c910f02c01p23: [I]: >> BONDING_MASTER="yes"
c910f02c01p23: [I]: >> "
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 5: unexpected EOF while looking for matching `"'
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 6: syntax error: unexpected end of file
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 5: unexpected EOF while looking for matching `"'
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 6: syntax error: unexpected end of file
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 5: unexpected EOF while looking for matching `"'
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 6: syntax error: unexpected end of file
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 6: warning: syntax errors in . or eval will cause future versions of the shell to abort as Posix requires
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 5: unexpected EOF while looking for matching `"'
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 6: syntax error: unexpected end of file
c910f02c01p23: /etc/sysconfig/network-scripts/ifcfg-bond0: line 6: warning: syntax errors in . or eval will cause future versions of the shell to abort as Posix requires
c910f02c01p23: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c910f02c01p23: configure nic and its device : bond0.2 bond0
c910f02c01p23: [I]: create_vlan_interface ifname=bond0 vlanid=2
c910f02c01p23: [I]: Pickup xcatnet, "30_5_0_0-255_255_0_0", from NICNETWORKS for interface "bond0".
c910f02c01p23: [I]: ip link add link bond0 name bond0.2 type vlan id 2
c910f02c01p23: [I]: ip link set bond0.2 up
c910f02c01p23: [I]: create_persistent_ifcfg ifname=bond0.2 xcatnet=30_5_0_0-255_255_0_0 inattrs=ONBOOT=yes,NM_CONTROLLED=no,USERCTL=no,TYPE=Ethernet,VLAN=yes,MTU=1500
c910f02c01p23: ['ifcfg-bond0.2']
c910f02c01p23: [I]: >> DEVICE="bond0.2"
c910f02c01p23: [I]: >> BOOTPROTO="static"
c910f02c01p23: [I]: >> IPADDR="30.5.106.8"
c910f02c01p23: [I]: >> NETMASK="255.255.0.0"
c910f02c01p23: [I]: >> MTU="1500"
c910f02c01p23: [I]: >> NAME="bond0.2"
c910f02c01p23: [I]: >> VLAN="yes"
c910f02c01p23: [I]: >> ONBOOT="yes"
c910f02c01p23: [I]: >> NM_CONTROLLED="no"
c910f02c01p23: [I]: >> USERCTL="no"
c910f02c01p23: [I]: >> TYPE="Ethernet"
c910f02c01p23: Cannot find device "bond0.2"
c910f02c01p23: [W]: ifup bond0.2 failed with return code equals to 1
c910f02c01p23: [I]: >> Failed to bring up bond0.2.
c910f02c01p23: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
c910f02c01p23: configure nic and its device : bond0.3 bond0
c910f02c01p23: [I]: create_vlan_interface ifname=bond0 vlanid=3
c910f02c01p23: [I]: Pickup xcatnet, "40_5_0_0-255_255_0_0", from NICNETWORKS for interface "bond0".
c910f02c01p23: [I]: ip link add link bond0 name bond0.3 type vlan id 3
c910f02c01p23: [I]: ip link set bond0.3 up
c910f02c01p23: [I]: create_persistent_ifcfg ifname=bond0.3 xcatnet=40_5_0_0-255_255_0_0 inattrs=ONBOOT=yes,NM_CONTROLLED=no,USERCTL=no,TYPE=Ethernet,VLAN=yes,MTU=1500
c910f02c01p23: ['ifcfg-bond0.3']
c910f02c01p23: [I]: >> DEVICE="bond0.3"
c910f02c01p23: [I]: >> BOOTPROTO="static"
c910f02c01p23: [I]: >> IPADDR="40.5.106.8"
c910f02c01p23: [I]: >> NETMASK="255.255.0.0"
c910f02c01p23: [I]: >> MTU="1500"
c910f02c01p23: [I]: >> NAME="bond0.3"
c910f02c01p23: [I]: >> VLAN="yes"
c910f02c01p23: [I]: >> ONBOOT="yes"
c910f02c01p23: [I]: >> NM_CONTROLLED="no"
c910f02c01p23: [I]: >> USERCTL="no"
c910f02c01p23: [I]: >> TYPE="Ethernet"
c910f02c01p23: postscript: confignetwork exited with code 0
c910f02c01p23: Running of postscripts has completed.
```

**Comment by bybai** [comment] 2017-07-14 06:20
@tingtli , this bug is duplicate with #3455 .  The root cause is that : if there is no mtu configured in networks table, the ifcfg-* files have wrong labels, that cause some error messages print out. So the fix is in #3455.

**Closed** 2017-07-14 06:21 UTC
Labels: component:network, status:duplicate, type:bug
