### ISSUE TITLE
rflash failed when trying to update PNOR on Witherspoon 1742C'' -> 1742Ef

### ISSUE THREAD

**Issue by moralesj** [xcat2/xcat-core#4394] opened 2017-11-30 00:08 UTC
When updating a rack of Witherspoons to 1742Ef, rflash got stuck for ~10 minutes and then failed. 
 Node a01n14 got held up with defect SW387409, which held rflash hostage.  All Witherspoons except for a01n14 were updated correctly.  After a power cycle I was able to rflash the PNOR for that node.

``` # rflash -a a01 witherspoon.pnor.squashfs.tar 
Attempting to upload witherspoon.pnor.squashfs.tar, please wait...
a01n04: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n08: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n10: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n03: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n05: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n11: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n06: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n07: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n12: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n13: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n15: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n02: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n17: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n01: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n09: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n16: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n18: Firmware upload successful. Attempting to activate firmware: IBM-witherspoon-ibm-OP9_v1.19_1.88 (ID: 78abd177)
a01n06: Firmware activation successful.
a01n13: Firmware activation successful.
a01n08: Firmware activation successful.
a01n15: Firmware activation successful.
a01n02: Firmware activation successful.
a01n17: Firmware activation successful.
a01n18: Firmware activation successful.
a01n07: Firmware activation successful.
a01n10: Firmware activation successful.
a01n04: Firmware activation successful.
a01n03: Firmware activation successful.
a01n05: Firmware activation successful.
a01n11: Firmware activation successful.
a01n09: Firmware activation successful.
a01n16: Firmware activation successful.
a01n12: Firmware activation successful.
a01n01: Firmware activation successful.

Error: openbmc plugin bug, pid 3442, process description: 'xcatd SSL: rflash for mgmt1.xxxx.xxx.xxx.xxx@mgmt1: openbmc instance' with error 'malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /opt/xcat/lib/perl/xCAT_plugin/openbmc.pm line 2904.
' while trying to fulfill request for the following nodes: a01n01,a01n02,a01n03,a01n04,a01n05,a01n06,a01n07,a01n08,a01n09,a01n10,a01n11,a01n12,a01n13,a01n14,a01n15,a01n16,a01n17,a01n18

```

**Comment by whowutwut** [comment] 2017-11-30 00:43
@moralesj  Looks like you are running: `Version 2.13.8 (git commit e4f452a44d417e2f9c64b6dd064e3fc316046ac4, built Sat Nov  4 07:15:42 EDT 2017)` 

@xuweibj can you do some investigation about this today? They are running the GA of 2.13.8 build, have we fixed some plugin bugs since then?

**Comment by whowutwut** [comment] 2017-11-30 00:45
@xuweibj  I've uploaded 1742Ef to `/mnt/xcat/iso/openbmc`

**Comment by xuweibj** [comment] 2017-11-30 01:47
I checked the code of 2.13.8, there is no 2904 line in openbmc.pm. So I think this is not 2.13.8, @moralesj could you help to check the xCAT version? 
From the output it looks like we tried to decode json data, but the data is not json format. But I am not sure which line error and what data we received. I will try to reproduce today and debug it.

**Comment by xuweibj** [comment] 2017-11-30 09:48
Not sure the exact error line, guess that received empty when uploading file. So create pull request #4396 first.

**Comment by mattaezell** [comment] 2017-11-30 13:02
Our openbmc.pm is [this](https://github.com/mattaezell/xcat-core/blob/27efccdb721787a7822557fc7d61b6cc9d33674b/xCAT-server/lib/xcat/plugins/openbmc.pm) from #4332.  I didn't expect us to be flashing anything until we upgraded all of xCAT together, I hope I didn't create an incompatibility.

**Comment by whowutwut** [comment] 2017-11-30 13:50
@xuweibj They are running 2.13.8 GA (well... GA + documentation) . 

@moralesj  Not a big deal but just for completeness...  You maybe picked up the build from the wrong location or not using the one that we point to on the release notes..  In this case it's not a big deal because the changes made after the GA tested build is just documentation that I wanted to be tagged on the 2.13.8 RTD release , but noticed this because your build date is 11/4 and we GA a 11/2 build version. 

Release notes points here: https://github.com/xcat2/xcat-core/wiki/XCAT_2.13.8_Release_Notes
and is this version:
```
xcat@sense:/var/www/xcat.org/files/xcat/xcat-core/2.13.x_Linux/core-snap$ sum ../xcat-core/xcat-core-2.13.8-linux.tar.bz2
54853  4324
```

I think you got from the core-snap dir...
```
xcat@sense:/var/www/xcat.org/files/xcat/xcat-core/2.13.x_Linux/core-snap$ sum 201711*
24929  4314 20171102.0530-core-rpms-snap.tar.bz2
52696  4330 20171102.0538-core-rpms-snap.tar.bz2
54853  4324 20171102.0715-core-rpms-snap.tar.bz2
42480  4328 20171104.0715-core-rpms-snap.tar.bz2  <==== you are running this one
```

It should be identical but I had made some commits to 2.13 branch after we GA, but those we were all doc changes.

**Comment by mattaezell** [comment] 2017-11-30 14:05
Oops, sorry, what I posted earlier was only true for our management node.  Our service nodes (where this openbmc call would have come from) is running: 
```
[root@sn1 ~]# lsxcatd -v
Version 2.13.9 (git commit 6315852abd388baeaff4883628ff23693bf1373e, built Wed Nov 22 06:15:46 EST 2017)
```

**Comment by moralesj** [comment] 2017-11-30 15:54
Ran in to this issue once more, and there is a missmatch of xCat MM and SN 
``` Warning: xCAT Version mismatch!
         sn1: Version 2.13.9 (git commit 6315852abd388baeaff4883628ff23693bf1373e, built Wed Nov 22 06:15:46 EST 2017)
         mgmt1: Version 2.13.9 (git commit db20025558aed1822cd8a45b81b8c3673485f043, built Tue Nov 28 21:56:18 EST 2017 ```

**Comment by mattaezell** [comment] 2017-11-30 16:01
@moralesj, @whowutwut asked us to upgrade.  The MN has been upgraded and the new SN image is being built now.

**Comment by whowutwut** [comment] 2017-11-30 16:48
@mattaezell , we had a patch for this that has not yet been merged in that 11/28 build... It allows us to handle the malformed JSON which we have not seen in the past... ( https://github.com/xcat2/xcat-core/pull/4396 ) so the xCAT plugin does not die if we hit this bad data response from the FW, will follow up with FW team about that...

**Comment by whowutwut** [comment] 2017-11-30 18:25
Opened Internal Defect: https://w3.rchland.ibm.com/projects/bestquest/?verb=view&id=SW409839

**Comment by whowutwut** [comment] 2017-12-20 20:31
This one is being handled by fixes in Firmware, we have also added protection against the plugin bug, closing out, re-open if issues still exist.

**Closed by whowutwut** 2017-12-20 20:31 UTC
Labels: component:coral, component:openbmc, priority:severity, sprint2
