### ISSUE TITLE
[FVT] CN powering-on not booted on virtual machines (both x86_64 and ppc64le)

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#2443] opened 2017-01-24 02:25 UTC
Test ENV.: sles12.2 p8le with latest build
```
c910f03c17k22:~ # lsxcatd -v
Version 2.13.2 (git commit 69d893cefa52bb4e1e2bb51e61b1a9aec0392830, built Mon Jan 23 06:15:36 EST 2017)

```
Test Case: packimage_m_tar_c_gzip
Details: Failed to boot the CN while running in autotest daily run. but can be passed when rerun.
This can be reproduced, so just submit an issue to track?
As these packimage test cases are run after the diskless installation cases in other arch: ppc64, x86.  Not sure if it is the same reason.
Steps:
```
genimage ubuntu16.04.1-ppc64el-netboot-compute
packimage ubuntu16.04.1-ppc64el-netboot-compute -m tar -c gzip
nodeset c910f03fsp03v07 osimage=ubuntu16.04.1-ppc64el-netboot-compute
rpower c910f03fsp03v07 boot
```
Result:

```
RUN:lsdef -l c910f03c17k24 | grep status

[lsdef -l c910f03c17k24 | grep status] Running Time:0 sec
RETURN rc = 0
OUTPUT:
    status=powering-on
    statustime=01-23-2017 17:29:41
CHECK:rc == 0	[Pass]
CHECK:output =~ booted	[Failed]
```

**Comment by immarvin** [comment] 2017-01-24 02:49
please make sure the steps to reproduce manually is clear or hold the environment so that we can grab more information, otherwise, just opening an issue with the information mentioned in your mail does not help  to solve the issue
------------------------------------------------------------------------------YANG Song (杨嵩)IBM China System Technology LaboratoryTel: 86-10-82452903Email: yangsbj@cn.ibm.comAddress: Building 28, ZhongGuanCun Software Park,No.8, Dong Bei Wang West Road, Haidian District Beijing 100193, PRC北京市海淀区东北旺西路8号中关村软件园28号楼邮编: 100193
 
 
----- Original message -----From: caomengmeng <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [xcat2/xcat-core] [FVT] packimage_m_tar_c_gzip cases failed for CN powering-on not booted (#2443)Date: Tue, Jan 24, 2017 10:26 AM 
Test ENV.: sles12.2 p8le with latest build
c910f03c17k22:~ # lsxcatd -vVersion 2.13.2 (git commit 69d893cefa52bb4e1e2bb51e61b1a9aec0392830, built Mon Jan 23 06:15:36 EST 2017) 
Test Case: packimage_m_tar_c_gzipDetails: Failed to boot the CN while running in autotest daily run. but can be passed when rerun.This can be reproduced, so just submit an issue to track?As these packimage test cases are run after the diskless installation cases in other arch: ppc64, x86. Not sure if it is the same reason.
RUN:lsdef -l c910f03c17k24 | grep status[lsdef -l c910f03c17k24 | grep status] Running Time:0 secRETURN rc = 0OUTPUT:    status=powering-on    statustime=01-23-2017 17:29:41CHECK:rc == 0 [Pass]CHECK:output =~ booted [Failed]

**Comment by daniceexi** [comment] 2017-01-24 03:21
I agree with yangsong. 
 
 Using IBM Verse, send from my iPhone.
 
 在 2017年1月24日，上午10:50:12，notifications@github.com 写道：

**Comment by caomengmeng** [comment] 2017-01-24 03:40
@immarvin @daniceexi Add the steps above. 
 I am debugging it now, in the ubuntu test environment to make sure if it is the test order problem.
Please read the description and label,  don't think it is necessary now to let others out of FVT to be involved.

**Comment by tingtli** [comment] 2017-02-14 06:38
@caomengmeng  I think this is not a case problem. This  is an issue for power 8 le virtual machine. I will work with er tao to trace this problem.

**Comment by whowutwut** [comment] 2017-02-16 20:53
@tingtli @zet809 Can you post some investigation progress here..  Do we need to put some more resources into this? This affects the autobuild and we need to resolve it quickly.  Can @gurevichmark  help?   Can you send us the ppc64le VM environment for RHELS 7.3?

**Comment by tingtli** [comment] 2017-02-24 09:32
Here is some information summary for this issue
1.
Machines always powering on:
c910f03c17k27 c910f03c17k28 c910f03c17k29
c910f03c17k22 c910f03c17k23 c910f03c17k24
c910f04x12v02 c910f04x12v03 c910f04x12v04
c910f04x14v02 c910f04x14v03 c910f04x14v04
2.
On kvmhost:
root@c910f03c17k27 ~]# ssh c910f03c17
Last login: Fri Feb 24 00:56:41 2017 from c910f03c17k27
[root@c910f03c17 ~]# df
Filesystem                                   1K-blocks    Used Available Use% Mounted on
/dev/mapper/ibmpkvm_rootvg-ibmpkvm_lv_system  20511312 1848164  17598188  10% /
devtmpfs                                     126663488       0 126663488   0% /dev
tmpfs                                        130706624       0 130706624   0% /dev/shm
tmpfs                                        130706624 4286144 126420480   4% /run
tmpfs                                        130706624       0 130706624   0% /sys/fs/cgroup
/dev/sdb2                                       499656  133244    329716  29% /boot
/dev/mapper/ibmpkvm_rootvg-ibmpkvm_lv_var     10190100 2165448   7483980  23% /var
/dev/mapper/ibmpkvm_rootvg-ibmpkvm_lv_data   509229792 7713928 475625256   2% /var/lib/libvirt/images
[root@c910f03c17 ~]# cat /proc/meminfo
MemTotal:       261413248 kB
 
[root@c910f04x12 ~]# df
Filesystem              1K-blocks     Used Available Use% Mounted on
/dev/mapper/system-root 239404840 32582812 206822028  14% /
devtmpfs                  8024372        0   8024372   0% /dev
tmpfs                     8035420        0   8035420   0% /dev/shm
tmpfs                     8035420   115876   7919544   2% /run
tmpfs                     8035420        0   8035420   0% /sys/fs/cgroup
/dev/sda2                  255724   110412    145312  44% /boot
/dev/sda1                   51082     9610     41472  19% /boot/efi
tmpfs                     1607088        0   1607088   0% /run/user/0
[root@c910f04x12 ~]# cat /proc/meminfo
MemTotal:       16070844 kB
MemFree:        10518836 kB
MemAvailable:   10714400 kB
 
[root@c910f04x14 ~]# df
Filesystem              1K-blocks      Used Available Use% Mounted on
/dev/mapper/system-root 403328600 253290128 150038472  63% /
devtmpfs                 24542652         0  24542652   0% /dev
tmpfs                    24553892         0  24553892   0% /dev/shm
tmpfs                    24553892   2491940  22061952  11% /run
tmpfs                    24553892         0  24553892   0% /sys/fs/cgroup
/dev/sda2                  258732    109732    149000  43% /boot
/dev/sda1                   51082      9674     41408  19% /boot/efi
[root@c910f04x14 ~]# cat /proc/meminfo
MemTotal:       49107788 kB
MemFree:        14351596 kB
MemAvailable:   22212656 kB

**Comment by hu-weihua** [comment] 2017-03-28 06:50
After fix bug #2668, have reduce most ``powering_on`` problem in automation environment.  

there is still ``powering_on`` problem rarely. After first debug, we found few time CN will failed to connect MN through tftp( without any tftp log during this time) .   But the strange thing is we have right tftp logs in the previous installation case and also have right tftp logs in the latter installation case. When we rerun the ``powering_on`` cases, every thing is fine.

Could anyone bring up any idea which situation will trigger this problem?

**Comment by neo954** [comment] 2017-03-30 09:12
Based on @hu-weihua's discovery, I collected the logs below from different servers. It is clearly a DHCPNAK packet was sent from `c910f03c17k27`.

It is weird that 10.4.35.4 sent a DHCPREQUEST via 42:f3:0a:03:11:1d.

    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPOFFER on 10.3.17.29 to 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth1: lease 10.4.35.4 unavailable.
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPNAK on 10.4.35.4 to 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:41 c910f03c17k27 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:41 c910f03c17k27 dhcpd: DHCPACK on 10.3.17.29 to 42:f3:0a:03:11:1d via eth1
----
    Mar 28 14:12:17 c910f04x35v02 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f04x35v02 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:41 c910f04x35v02 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.
----
    Mar 28 14:12:17 c910f02c03p27 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f02c03p27 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:41 c910f02c03p27 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.

**Comment by neo954** [comment] 2017-03-31 06:19
Mar 28 14:12:17 c910f02c01p13 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth1: network eth1: no free leases
    Mar 28 14:12:17 c910f02c01p13 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth1: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f02c08p05 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f02c08p05 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f03c17k22 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth1: network eth1: no free leases
    Mar 28 14:12:17 c910f03c17k22 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth1: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f03c17k23 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f03c17k23 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPNAK on 10.4.35.4 to 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPOFFER on 10.3.17.29 to 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth1: lease 10.4.35.4 unavailable.
    Mar 28 14:12:17 c910f04x12v02 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f04x12v02 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f04x12v03 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f04x12v03 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f04x14v02 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f04x14v02 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f04x14v03 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f04x14v03 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f04x35v02 dhcpd: DHCPDISCOVER from 42:f3:0a:03:11:1d via eth0: network eth0: no free leases
    Mar 28 14:12:17 c910f04x35v02 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth0: unknown lease 10.4.35.4.
    Mar 28 14:12:41 c910f02c01p13 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth1: unknown lease 10.3.17.29.
    Mar 28 14:12:41 c910f02c08p05 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.
    Mar 28 14:12:41 c910f03c17k22 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth1: unknown lease 10.3.17.29.
    Mar 28 14:12:41 c910f03c17k23 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.
    Mar 28 14:12:41 c910f03c17k27 dhcpd: DHCPACK on 10.3.17.29 to 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:41 c910f03c17k27 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:41 c910f04x12v02 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.
    Mar 28 14:12:41 c910f04x12v03 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.
    Mar 28 14:12:41 c910f04x14v02 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.
    Mar 28 14:12:41 c910f04x14v03 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.
    Mar 28 14:12:41 c910f04x35v02 dhcpd: DHCPREQUEST for 10.3.17.29 from 42:f3:0a:03:11:1d via eth0: unknown lease 10.3.17.29.

**Comment by neo954** [comment] 2017-03-31 08:37
Mar 28 14:12:13 c910f03c17k27 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:d7:0a:04:23:04 via eth1: unknown lease 10.4.35.4.
    Mar 28 14:12:14 c910f03c17k27 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:d7:0a:04:23:04 via eth1: unknown lease 10.4.35.4.
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:f3:0a:03:11:1d via eth1: lease 10.4.35.4 unavailable.
    Mar 28 14:12:17 c910f03c17k27 dhcpd: DHCPNAK on 10.4.35.4 to 42:f3:0a:03:11:1d via eth1
    Mar 28 14:12:22 c910f03c17k27 dhcpd: DHCPREQUEST for 10.4.35.4 (10.4.35.2) from 42:d7:0a:04:23:04 via eth1: unknown lease 10.4.35.4.
    Mar 28 14:12:33 c910f03c17k27 dhcpd: DHCPREQUEST for 10.4.35.4 from 42:d7:0a:04:23:04 via eth1: unknown lease 10.4.35.4.

**Comment by neo954** [comment] 2017-07-13 08:55
After upgrade all the KVM host to RHEL 7.3+RHV 4.1, I think the problem is solved. For now, I intend to close this issue.

Please feel free the reopen this issue if someone hit this problem again. But I believe upgrade PowerKVM 2.x/3.x to RHEL 7.3+RHV4.1 is the key point.

**Closed by neo954** 2017-07-13 08:55 UTC
Labels: component:automation, priority:high, sprint2
