### ISSUE TITLE
Compute nodes fail to get provisioned

### ISSUE THREAD

**Issue by moralesj** [xcat2/xcat-core#4411] opened 2017-11-30 22:44 UTC
When booting up multiple compute nodes a small fraction of the nodes do not get provisioned, and are stuck here
```
[root@mgmt1 ~]# rcons a03n16
[Enter '^Ec?' for help]
[    9.148863] mlx5_core 0003:01:00.1: Port module event: module 1, Cable plugged
[    9.193602] mlx5_core 0033:01:00.0: Using 64-bit DMA iommu bypass
[    9.240259] mlx5_core 0033:01:00.0: capi_init:1736:(pid 1161): capi is NOT supported
[    9.240496] mlx5_core 0033:01:00.0: firmware version: 16.21.116
[   11.906019] mlx5_core 0033:01:00.0: Port module event: module 0, Cable plugged
[   11.993244] mlx5_core 0033:01:00.1: Using 64-bit DMA iommu bypass
[   12.040255] mlx5_core 0033:01:00.1: capi_init:1736:(pid 1161): capi is NOT supported
[   12.040448] mlx5_core 0033:01:00.1: firmware version: 16.21.116
[   14.708054] mlx5_core 0033:01:00.1: Port module event: module 1, Cable plugged
[   14.757023] mlx5_ib: Mellanox Connect-IB Infiniband driver v4.1-4.1.5 (01 Nov 2017)
[  131.996861] dracut-initqueue[1549]: awk: /tmp/updateflag:15: fatal: remote host and port information (sn1, 3002) invalid
[  188.062831] dracut-initqueue[1549]: wget: unable to resolve host address 'sn1' 
```

Looking at the osimage provided I do see 
`/etc/hosts -> /etc/hosts` 
is part of the `synclist-compute` file.

Rebooting the node will resolve the issue, and also changing the `xcatmaster=ip_address_of_sn1` will resolve the issue, but I don't see them as a suitable fix.

**Comment by whowutwut** [comment] 2017-12-01 01:52
@robin2008 @immarvin  Can you take a look here?

**Comment by robin2008** [comment] 2017-12-01 02:37
It seems `noderes.xcatmaster` is set to `sn1`, and the value will be set in `mypostscritps`

```
grep "MASTER" mypostscript.mid05tor12cn01
SITEMASTER='172.10.253.27'
export SITEMASTER
MASTER='sn01'
export MASTER
MASTER_IP=172.10.254.1
export MASTER_IP
MONMASTER='sn01'
export MONMASTER
```
And check the `mypostscript`, there are MASTER and MASTER_IP for it. Now xCAT codes is using `MASTER` to communicate with master, if using `MASTER_IP` for communication with the master, then it would not have the naming issue.

**Comment by mattaezell** [comment] 2017-12-01 03:29
This works most of the time, and only fails intermittently.  `initrd-stateless.gz` doesn't contain an /etc/hosts, so how does this normally work?

**Comment by mattaezell** [comment] 2017-12-01 03:39
Update: DHCP is sending nameservers and a search domain, so my guess is that dracut is using this information to setup the resolver and query DNS.  I don't see any reason that this would fail intermittently though.

**Comment by mattaezell** [comment] 2017-12-01 04:21
I switched to IP addresses for `servicenode` so we can make progress.

**Comment by robin2008** [comment] 2017-12-01 06:32
Sorry, I realize that the failure is related  to a stateless provision. 
@mattaezell  You are right,  the DNS should be okay when dracut-init, and the name should be resolvable.

@moralesj Could you help to give more information?

1, Are there multiple DHCP server running on the provisioning network?
`xcatprobe detect_dhcpd -i <The interface facing the target network> -m <mac of cn>`

2, And make sure if the domain-seach and dns server is configured rightly in their /etc/dhcp/dhcpd.conf:
```
grep domain /etc/dhcp/dhcpd.conf 
    option domain-name "pok.stglabs.ibm.com";
    option domain-name-servers  172.12.253.27;
    option domain-search  "pok.stglabs.ibm.com";
```
if not, run `makedhcp -n` accordingly. 

3, Make sure the `sn1` is resolvable:
`nslookup sn1.<domain-search> <domain-name-servers>`
if not, run `makedns sn1` to generate the DNS records.

**Comment by mattaezell** [comment] 2017-12-01 06:46
Hi @robin2008.  I can provide copy/paste output tomorrow, but here are some thoughts for now:

1. There shouldn't be.  They are getting the right IP address, and only xCAT knows the correct IP address for the compute nodes (our site DHCP server does NOT have all of our compute nodes configured).  Good thing to check though.

2. I turned on dracut debugging and caught a node in this state.  I looked at the DHCP lease information it had, and the domain-search and nameservers appeared to be correct.  I think I saved this output, I can check tomorrow.

3. All of our management and service nodes were manually defined in our site DNS.  We don't use `makedns`, but the fact that it works most of the time implies that this should be OK.

It sounds like our options are:
- Root cause why this sometimes works and sometimes does not, leave configs as-is
- Use IPs instead of hostnames for `xcatmaster` (our current workaround)
- Come up with a method to allow putting an /etc/hosts in the initrd-stateless.gz so we don't need to depend on DNS
- Other ideas?

**Comment by robin2008** [comment] 2017-12-01 07:16
@mattaezell Thanks for that. 
Just as you point out, it is weird that why it failed to do the DNS lookup in dracut.
Not sure if it work when we passing `nameserver=x.x.x.x` explicitly in append line.

Another method is that when nodeset, xCAT could resolve the `xcatmaster` first and put the IP into append line, so there is not required the DNS when booting.

I'm not sure it is a good idea to put the /etc/hosts into image, because xCAT assume that the osimage should be only the OS, softwares, and no relation to the real environment.

**Comment by mattaezell** [comment] 2017-12-06 03:50
@robin2008 I suppose this is similar to #4059 and #4274 and may be a good path forward.  As I mentioned above, we are currently using IP addresses so we can drop the severity of this issue.

**Comment by immarvin** [comment] 2017-12-07 05:59
fixed in https://github.com/xcat2/xcat-core/pull/4462

**Comment by robin2008** [comment] 2017-12-07 06:23
Fix it for RHEL first, we will use IP address of master in /proc/cmdline.  For SLES and Ubuntu is loweer priority.

**Comment by whowutwut** [comment] 2017-12-08 03:19
Let's close this issue, and re-open if we continue to see it with the code patched.

**Closed by whowutwut** 2017-12-08 03:19 UTC
Labels: component:coral, component:os_provision, priority:severity, sprint2, status:pending
