### ISSUE TITLE
[FVT]:some errors when execute syslog on Ubuntu16.04

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1159] opened 2016-05-19 14:54 UTC
xCAT 2.12 on Ubuntu16.04
```
 Thu May 19 10:53:39 EDT 2016 Running postscript: syslog
 2547 grep: /etc/rsyslog.d/remote.conf: No such file or directory
 2548 grep: /etc/rsyslog.d/remote.conf: No such file or directory
 2549 cp: cannot stat '/etc/rsyslog.d/remote.conf': No such file or directory
 2550 cp: cannot stat '/etc/rsyslog.d/remote.conf': No such file or directory
```

**Comment by immarvin** [comment] 2016-05-20 05:58
The rsyslog shipped in ubuntu 16.04 is:
````
root@c910f03c17k27:/xcatpost# rsyslogd -v
rsyslogd 8.16.0, compiled with:
        PLATFORM:                               powerpc64le-unknown-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
````
The rsyslogd 8.16.0 will not install ``/etc/rsyslog.d/remote.conf`` on package installation and the configuration for UDP/TCP reception is commented out in rsyslog.conf. However, the syslog postscript suppose configuration for UDP/TCP reception is included in``/etc/rsyslog.d/remote.conf`` ,which is shipped by rsyslog package.

**Comment by immarvin** [comment] 2016-05-20 06:03
This is caused by the packaging change from rsyslog 8.16.
````
root@c910f03c17k27:/xcatpost# rsyslogd -v
rsyslogd 8.16.0, compiled with:
        PLATFORM:                               powerpc64le-unknown-linux-gnu
        PLATFORM (lsb_release -d):
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.

root@c910f03c17k27:/xcatpost# dpkg -L rsyslog 
/.
/usr
/usr/lib
/usr/lib/rsyslog
/usr/lib/rsyslog/lmstrmsrv.so
/usr/lib/rsyslog/mmutf8fix.so
/usr/lib/rsyslog/imklog.so
/usr/lib/rsyslog/imtcp.so
/usr/lib/rsyslog/lmnetstrms.so
/usr/lib/rsyslog/imuxsock.so
/usr/lib/rsyslog/lmtcpsrv.so
/usr/lib/rsyslog/immark.so
/usr/lib/rsyslog/lmnet.so
/usr/lib/rsyslog/mmjsonparse.so
/usr/lib/rsyslog/lmzlibw.so
/usr/lib/rsyslog/lmnsd_ptcp.so
/usr/lib/rsyslog/mmanon.so
/usr/lib/rsyslog/pmcisconames.so
/usr/lib/rsyslog/imjournal.so
/usr/lib/rsyslog/imudp.so
/usr/lib/rsyslog/imfile.so
/usr/lib/rsyslog/omuxsock.so
/usr/lib/rsyslog/lmregexp.so
/usr/lib/rsyslog/pmlastmsg.so
/usr/lib/rsyslog/ommail.so
/usr/lib/rsyslog/impstats.so
/usr/lib/rsyslog/mmsequence.so
/usr/lib/rsyslog/omprog.so
/usr/lib/rsyslog/pmaixforwardedfrom.so
/usr/lib/rsyslog/lmtcpclt.so
/usr/lib/rsyslog/mmexternal.so
/usr/lib/rsyslog/imptcp.so
/usr/lib/rsyslog/mmpstrucdata.so
/usr/lib/rsyslog/omjournal.so
/usr/lib/rsyslog/imkmsg.so
/usr/lib/rsyslog/pmsnare.so
/usr/lib/tmpfiles.d
/usr/lib/tmpfiles.d/00rsyslog.conf
/usr/share
/usr/share/rsyslog
/usr/share/rsyslog/50-default.conf
/usr/share/doc
/usr/share/doc/rsyslog
/usr/share/doc/rsyslog/changelog.Debian.gz
/usr/share/doc/rsyslog/examples
/usr/share/doc/rsyslog/examples/rsyslog.d
/usr/share/doc/rsyslog/examples/rsyslog.d/xconsole.conf
/usr/share/doc/rsyslog/examples/rsyslog.d/console.conf
/usr/share/doc/rsyslog/examples/tmpfiles.d
/usr/share/doc/rsyslog/examples/tmpfiles.d/xconsole.conf
/usr/share/doc/rsyslog/NEWS.Debian.gz
/usr/share/doc/rsyslog/AUTHORS
/usr/share/doc/rsyslog/copyright
/usr/share/doc/rsyslog/README.Debian
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/rsyslog
/usr/share/man
/usr/share/man/man5
/usr/share/man/man5/rsyslog.conf.5.gz
/usr/share/man/man8
/usr/share/man/man8/rsyslogd.8.gz
/usr/share/man/man1
/usr/sbin
/usr/sbin/rsyslogd
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/rsyslog.service
/var
/var/spool
/var/spool/rsyslog
/etc
/etc/init
/etc/init/rsyslog.conf
/etc/rsyslog.conf
/etc/apparmor.d
/etc/apparmor.d/local
/etc/apparmor.d/disable
/etc/apparmor.d/usr.sbin.rsyslogd
/etc/apparmor.d/force-complain
/etc/rsyslog.d
/etc/logcheck
/etc/logcheck/ignore.d.server
/etc/logcheck/ignore.d.server/rsyslog
/etc/init.d
/etc/init.d/rsyslog
/etc/logrotate.d
/etc/logrotate.d/rsyslog
/etc/default
/etc/default/rsyslog
````

As a comparision, the rsyslog 8.4 shipped in sles12.1 includes remote.conf
````

c910f04x18v05:~ # rsyslogd -v
rsyslogd 8.4.0, compiled with:
        FEATURE_REGEXP:                         Yes
        GSSAPI Kerberos 5 support:              Yes
        FEATURE_DEBUG (debug build, slow code): No
        32bit Atomic operations supported:      Yes
        64bit Atomic operations supported:      Yes
        memory allocator:                       system default
        Runtime Instrumentation (slow code):    No
        uuid support:                           Yes
        Number of Bits in RainerScript integers: 64

See http://www.rsyslog.com for more information.
c910f04x18v05:~ # rpm -ql rsyslog
/etc/apparmor
/etc/apparmor/profiles
/etc/apparmor/profiles/extras
/etc/apparmor/profiles/extras/rsyslog.d
/etc/apparmor/profiles/extras/usr.sbin.rsyslogd
/etc/rsyslog.conf
/etc/rsyslog.d
/etc/rsyslog.d/remote.conf
/run/rsyslog
/run/rsyslog/additional-log-sockets.conf
/sbin/rsyslogd
/usr/lib/systemd/system/rsyslog.service
/usr/lib64/rsyslog
/usr/lib64/rsyslog/im3195.so
/usr/lib64/rsyslog/imfile.so
/usr/lib64/rsyslog/imjournal.so
/usr/lib64/rsyslog/imklog.so
/usr/lib64/rsyslog/imkmsg.so
/usr/lib64/rsyslog/immark.so
/usr/lib64/rsyslog/impstats.so
/usr/lib64/rsyslog/imptcp.so
/usr/lib64/rsyslog/imtcp.so
/usr/lib64/rsyslog/imttcp.so
/usr/lib64/rsyslog/imudp.so
/usr/lib64/rsyslog/imuxsock.so
/usr/lib64/rsyslog/lmnet.so
/usr/lib64/rsyslog/lmnetstrms.so
/usr/lib64/rsyslog/lmnsd_ptcp.so
/usr/lib64/rsyslog/lmregexp.so
/usr/lib64/rsyslog/lmstrmsrv.so
/usr/lib64/rsyslog/lmtcpclt.so
/usr/lib64/rsyslog/lmtcpsrv.so
/usr/lib64/rsyslog/lmzlibw.so
/usr/lib64/rsyslog/mmanon.so
/usr/lib64/rsyslog/mmcount.so
/usr/lib64/rsyslog/mmexternal.so
/usr/lib64/rsyslog/mmfields.so
/usr/lib64/rsyslog/mmpstrucdata.so
/usr/lib64/rsyslog/mmrfc5424addhmac.so
/usr/lib64/rsyslog/mmsequence.so
/usr/lib64/rsyslog/mmutf8fix.so
/usr/lib64/rsyslog/omjournal.so
/usr/lib64/rsyslog/ommail.so
/usr/lib64/rsyslog/omprog.so
/usr/lib64/rsyslog/omruleset.so
/usr/lib64/rsyslog/omstdout.so
/usr/lib64/rsyslog/omtesting.so
/usr/lib64/rsyslog/omuxsock.so
/usr/lib64/rsyslog/pmaixforwardedfrom.so
/usr/lib64/rsyslog/pmcisconames.so
/usr/lib64/rsyslog/pmlastmsg.so
/usr/lib64/rsyslog/pmrfc3164sd.so
/usr/lib64/rsyslog/pmsnare.so
/usr/sbin/rcrsyslog
/usr/sbin/rsyslog-service-prepare
/usr/sbin/rsyslogd
/usr/share/doc/packages/rsyslog
/usr/share/doc/packages/rsyslog/AUTHORS
/usr/share/doc/packages/rsyslog/COPYING
/usr/share/doc/packages/rsyslog/COPYING.ASL20
/usr/share/doc/packages/rsyslog/COPYING.LESSER
/usr/share/doc/packages/rsyslog/ChangeLog
/usr/share/doc/packages/rsyslog/README
/usr/share/man/man5/rsyslog.conf.5.gz
/usr/share/man/man8/rsyslogd.8.gz
/var/adm/fillup-templates/sysconfig.syslog-rsyslog
/var/spool/rsyslog
````

**Comment by immarvin** [comment] 2016-05-20 06:24
fixed in https://github.com/xcat2/xcat-core/pull/1163

**Comment by neo954** [comment] 2016-05-20 09:23
Verified with xCAT 2.12-snap201605200311

**Closed by neo954** 2016-05-20 09:23 UTC
Labels: component:postscripts, status:pending, type:bug
