### ISSUE TITLE
[Test case] refine sles migration test cases

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#2835] opened 2017-04-07 08:12 UTC

**Comment by neo954** [comment] 2017-04-17 09:00
This test case calls `go-xcat`. The problem described in the issue is fixed in commit d13f6f0f5be2e3d950a69cf6f27d14f48c110c3a. See pull request #2876.

**Comment by neo954** [comment] 2017-04-18 05:06
Test cases updated with pull request #2878

**Closed** 2017-04-21 09:36 UTC
Labels: component:test, priority:high, sprint1
