### ISSUE TITLE
xCAT daemon stuck for months and cause problem when xCAT upgrading

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#2859] opened 2017-04-13 01:56 UTC
The testing environment is a SLES 11.4 x86-64 machine. It was run xCAT version 2.12.2 for months, and upgraded to 2.13.2 recently.

Below is an interesting result I observed. Clearly, processes with PID `13561`, `13562`, `13563`, `13564`, `13565`, `13566`, `17003`, `17004`, `17040`, `17041`, `17790`, `17791`, `21242`, `21243`, `25869` and `25870` belong to xCAT version 2.13.2. But processes with PID `15978`, `15979`, `18872`, `18873` and `18884` belong to xCAT version 2.12.2.

    c910f04x31:~ # ps -Aef | grep -v grep | grep -i xcatd
    root     13561     1  0 Apr11 ?        00:00:03 xcatd: SSL listener
    root     13562 13561  0 Apr11 ?        00:03:01 xcatd: DB Access
    root     13563 13561  0 Apr11 ?        00:00:09 xcatd: UDP listener
    root     13564 13561  0 Apr11 ?        00:00:02 xcatd: install monitor
    root     13565 13563  0 Apr11 ?        00:00:00 xcatd: Discovery worker
    root     13566 13561  0 Apr11 ?        00:00:00 xcatd: Command log writer
    root     15978     1  0  2016 ?        00:50:57 xcatd: SSL listener
    root     15979 15978  0  2016 ?        1-07:19:59 xcatd: DB Access
    root     17003 13561  0 05:38 ?        00:00:01 xcatd SSL: xdsh to c910f02c01p14 for root@local
    root     17004 17003  0 05:38 ?        00:00:00 xcatd SSL: xdsh to c910f02c01p14 for root@local
    root     17040 13561  0 05:39 ?        00:00:01 xcatd SSL: xdsh to c910f03c17k22 for root@local
    root     17041 17040  0 05:39 ?        00:00:00 xcatd SSL: xdsh to c910f03c17k22 for root@local
    root     17790 13561  0 05:42 ?        00:00:01 xcatd SSL: xdsh to c910f04x35v05 for root@local
    root     17791 17790  0 05:42 ?        00:00:00 xcatd SSL: xdsh to c910f04x35v05 for root@local
    root     18872 15978  0 Jan23 ?        00:52:55 xcatd SSL: rpower to c910f04x14v02 for root@loc
    root     18873 18872  0 Jan23 ?        00:00:00 xcatd SSL: rpower to c910f04x14v02 for root@loc
    root     18884 18873  0 Jan23 ?        00:00:00 xcatd SSL: rpower to c910f04x14v02 for root@loc
    root     21242 13561  0 06:02 ?        00:00:00 xcatd SSL: xdsh to c910f04x35v02 for root@local
    root     21243 21242  0 06:02 ?        00:00:00 xcatd SSL: xdsh to c910f04x35v02 for root@local
    root     25869 13561  0 06:34 ?        00:00:00 xcatd SSL: xdsh to c910f03c17k27 for root@local
    root     25870 25869  0 06:34 ?        00:00:00 xcatd SSL: xdsh to c910f03c17k27 for root@local

These two xCAT versions were running at the same time. It was around 6AM Apr 12 when I get the output above. Please notice the fifth column of the output. Processes come from xCAT 2.13.2 have the start time shown as `Apr11`, which is the correct time when the xCAT upgrading was performed, around 9PM Apr 11. The most interesting part, the start time of processes come from xCAT 2.12.2, are shown as `2016` :-O That is a year before. And please also notice processes `18872`, `18873` and `18884` have the start time shown as `Jan23`. That is Jan 23 of this year. Those three processes were stuck at there for around three and half months :-/

**Comment by neo954** [comment] 2017-04-13 02:10
The main impact of this problem is that, while process `15979` was still running, mixed xCAT parts from different xCAT version are running together. xCAT has no mechanism to handle this kind of situation. For example, two `xcatd: DB Access` processes come from different xCAT version read and write the database at the same time.

**Comment by neo954** [comment] 2017-04-13 02:14
I think xCAT does need a timeout mechanism for its commands. An `rpower` command runs for over three months is not reasonable.

**Comment by neo954** [comment] 2017-04-13 02:19
This problem may also caused by the xCAT *fast-restart* mechanism along with the xCAT upgrading. I think when do xCAT upgrading, it maybe better to make sure all the *old* `xcatd` processes are die and then start up the *new* `xcatd` after that.

**Comment by whowutwut** [comment] 2017-04-13 02:20
When xCAT is upgraded, what is the flow, does it stop the process before upgrading? or does it upgrade while process is running and somehow reload?

**Comment by neo954** [comment] 2017-04-13 02:24
@whowutwut, I think xCAT just do the normal `service xcatd restart`. Which means, the normal xCAT *fast-restart* mechanism is involved. In that case, if the *old* `xcatd` process is stuck there, no facility to make sure it will quit at last.

**Comment by zet809** [comment] 2017-04-13 06:06
Hi, @chenglch , @robin2008 and @immarvin , any idea for this issue?

**Comment by robin2008** [comment] 2017-04-13 10:06
While upgrading, it will restart xcatd.  (In some of the spec,  xcatd might be restarted many times during the upgrade)

During the restart,  xcatd will always start a new process and fork its child.
The key is that the new daemon does not kill the former one, and I don't see kill -9 is used in xcatd. Then in some unexpected situation, the INT and TERM signal may not kill the former one  successfully.

**Comment by chenglch** [comment] 2017-04-17 01:21
Actually, from xcatd side this is early design of xcatd which is used to serve the **interactive** command mode. If the client side( like rpower command) do not exit ( completed or terminated by `ctrl + c`), there is no signal propagated to the `plugin processes` even if `service stop xcatd` is called. The signal handler of xcatd  just makes `xcatd listener` refuse to serve a new command connection and then exit until all the child processes completed.

**Comment by robin2008** [comment] 2017-04-17 06:35
You mentioned is only for 'restart' case.
Now in /etc/init.d/xcatd stop,  after send TERM signal, it will send kill -9 to the "SSL listener" process and all children in the same Process Group.

And I think If we want fastrest, we can introduce new action for it. It could be used in normal restart.  And in upgrade, it is better to have a cold restart as there might be big difference.

**Comment by immarvin** [comment] 2017-04-17 06:48
during restarting xcatd on some old os releases without systemd, ``service xcatd restart`` will run "xcatd -p /var/run/xcatd.pid",During this, all the pids of children processes spawned by xcatd are saved under "/var/run/xcat/", xcatd will send "SIGUSR2" to these processes on the creation of each new children process

**Comment by immarvin** [comment] 2017-04-17 06:50
once the children process of xcatd become zombie process, the later xcatd restart has no chance to kill it

**Comment by neo954** [comment] 2017-04-18 04:34
I agree with @robin2008, we definitely need an old-fashioned clean method of "restart" when perform xCAT upgrading. Which is `kill -KILL` after `kill -TERM`. In this way, we can make sure everything belongs to the old version of xCAT are going to die before the new version of xCAT are launching.

**Comment by hu-weihua** [comment] 2017-04-28 05:15
This is a problem, but now we have not had root cause and solution, compare with other work item in 2.13.4 sprint2, it has lower priority, so move it to 2.13.5 sprint1

**Comment by neo954** [comment] 2017-06-15 06:43
I tried to recreate this bug on a ppc64le environment with RHEL7.3 and latest xCAT stable version 2.13.4 GA edition.

Here are the steps of how to recreate this bug. Launch a `sleep 99` jobs on any of the compute node, and then restart `xcatd` immediately.

    xdsh c910f03c01p10 'sleep 99' &
    service xcatd restart

After `xcatd` restarted, as the output shown below, there was an `xcatd SSL` process stuck there, in order to handle the `xdsh` jobs started up earlier.

    # ps -Aef | grep -v grep | grep -i xcatd
    root      3233     1  0 01:29 ?        00:00:00 xcatd SSL: xdsh to c910f03c01p10 for root@localhost: xdsh instance
    root      3442     1  0 01:29 ?        00:00:00 xcatd: SSL listener
    root      3443  3442  0 01:29 ?        00:00:01 xcatd: DB Access
    root      3444  3442  0 01:29 ?        00:00:00 xcatd: UDP listener
    root      3445  3444  0 01:29 ?        00:00:00 xcatd: Discovery worker
    root      3446  3442  0 01:29 ?        00:00:00 xcatd: install monitor
    root      3447  3442  0 01:29 ?        00:00:00 xcatd: Command log writer

Here is the interesting part, after the `sleep 99` jobs exited on the compute node, The following error message was printed from the previous `xdsh` jobs. 

    Error: A fatal error was encountered, the following information may help identify a bug: not a valid file descriptor at /opt/xcat/sbin/xcatd line 2407.
    ERROR/WARNING: communication with the xCAT server seems to have been ended prematurely

    [1]+  Exit 1                  xdsh c910f03c01p10 'sleep 20'

**Comment by neo954** [comment] 2017-06-15 06:46
From the example above, It is clear that the feature of xCAT fast-restart is not tested/verified properly. It is not work as end user expect.

**Comment by neo954** [comment] 2017-06-15 08:31
Here is the testing of another scenario.

Run `copycds` against an ISO file.

    # copycds /path/to/RHEL-7.3-Server-ppc64le-dvd1-stable.iso
    Copying media to /install/rhels7.3/ppc64le
    3.38%

And, while the `copycds` command above was running, restart `xcatd` from another terminal.

    # service xcatd restart
    Restarting xcatd (via systemctl):                          [  OK  ]

After the `xcatd` was restarted, change back to the terminal, which has been running `copycds`.

    # copycds /path/to/RHEL-7.3-Server-ppc64le-dvd1-stable.iso
    Copying media to /install/rhels7.3/ppc64le
    ERROR/WARNING: communication with the xCAT server seems to have been ended prematurely

The `copycds` command broke and no `osimage` definitions were created.

    # lsdef -t osimage
    Could not find any object definitions to display.

**Comment by neo954** [comment] 2017-06-15 08:42
Conclusion, the feature of `xcatd` fast-restart does not work as expect. In some situations, it does cause trouble.

I suggest we abandon the xCAT fast-restart feature, since it cause more problems than it solved. I suggest we move to `systemd` with the pull request #2648 @robin2008 made.

**Comment by daniceexi** [comment] 2017-06-16 02:39
@robin2008 please take a look of the behaviour that found by @neo954 and figure out the root cause, then we can discuss the final decision.

**Comment by robin2008** [comment] 2017-07-26 06:50
Now new distro will use systemd,  there is no restart, but stop and start.
In stop action, all daemons are killed by systemd.

**Comment by robin2008** [comment] 2017-07-27 09:03
For upgrade,  I would suggest to restart xCAT fully,  we can document that customer need to pay attention to the running jobs before he upgrade xCAT.

Then we can kill xcatd and its children safely.

**Comment by robin2008** [comment] 2018-06-19 10:01
won't fix

**Closed by robin2008** 2018-06-19 10:01 UTC
Labels: component:xcatd, priority:low, type:bug
