### ISSUE TITLE
When running synclists, an error occurs but reason doesn't help user, xCAT plugin bug? 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#5954] opened 2019-01-15 21:35 UTC
Synclist failed with XCAT problem, from cluster.log

```
Jan 15 16:19:00 mid05tor12cn03 xcat.deployment.postbootscript: INFO  syncfiles: the OS name = Linux
Jan 15 16:19:00 briggs01 xcat[54940]: INFO xCAT: Allowing syncfiles from mid05tor12cn03
Jan 15 16:19:02 briggs01 xcat[54943]: ERR Not an ARRAY reference at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 6320.
Jan 15 16:19:02 briggs01 xcat[54943]: INFO xcatd: syncfiles plugin bug, pid 54943, process description: 'xcatd SSL: syncfiles for mid05tor12cn03: syncfiles instance' with error 'Died at /opt/xcat/sbin/xcatd line 2100.#012'
Jan 15 16:19:15 briggs01 xcat[55039]: INFO xCAT: Allowing syncfiles from mid05tor12cn03
Jan 15 16:19:17 briggs01 xcat[55042]: ERR Not an ARRAY reference at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 6320.
Jan 15 16:19:17 briggs01 xcat[55042]: INFO xcatd: syncfiles plugin bug, pid 55042, process description: 'xcatd SSL: syncfiles for mid05tor12cn03: syncfiles instance' with error 'Died at /opt/xcat/sbin/xcatd line 2100.#012'
Jan 15 16:19:22 briggs01 xcat[55117]: INFO xCAT: Allowing lsdef -t node mid05tor12cn03 -i status for root from localhost
Jan 15 16:19:22 briggs01 xcat[55123]: INFO xCAT: Allowing xdsh to mid05tor12cn03 grep return with /var/log/xcat/xcat.log for root from localhost
Jan 15 16:19:28 briggs01 xcat[55163]: INFO xCAT: Allowing syncfiles from mid05tor12cn03
Jan 15 16:19:32 briggs01 xcat[55206]: INFO xCAT: Allowing xdsh to mid05tor12cn03 grep checknode /var/log/xcat/xcat.log for root from localhost
Jan 15 16:19:34 briggs01 xcat[55166]: ERR Not an ARRAY reference at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 6320.
Jan 15 16:19:34 briggs01 xcat[55166]: INFO xcatd: syncfiles plugin bug, pid 55166, process description: 'xcatd SSL: syncfiles for mid05tor12cn03: syncfiles instance' with error 'Died at /opt/xcat/sbin/xcatd line 2100.#012'
Jan 15 16:19:49 briggs01 xcat[55322]: INFO xCAT: Allowing syncfiles from mid05tor12cn03
Jan 15 16:19:51 briggs01 xcat[55325]: ERR Not an ARRAY reference at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 6320.
Jan 15 16:19:51 briggs01 xcat[55325]: INFO xcatd: syncfiles plugin bug, pid 55325, process description: 'xcatd SSL: syncfiles for mid05tor12cn03: syncfiles instance' with error 'Died at /opt/xcat/sbin/xcatd line 2100.#012'
Jan 15 16:20:02 briggs01 xcat[55413]: INFO xCAT: Allowing syncfiles from mid05tor12cn03
Jan 15 16:20:04 briggs01 xcat[55419]: ERR Not an ARRAY reference at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 6320.
Jan 15 16:20:04 briggs01 xcat[55419]: INFO xcatd: syncfiles plugin bug, pid 55419, process description: 'xcatd SSL: syncfiles for mid05tor12cn03: syncfiles instance' with error 'Died at /opt/xcat/sbin/xcatd line 2100.#012'
Jan 15 16:20:15 briggs01 xcat[55506]: INFO xCAT: Allowing syncfiles from mid05tor12cn03
Jan 15 16:20:17 briggs01 xcat[55509]: ERR Not an ARRAY reference at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 6320.
Jan 15 16:20:17 briggs01 xcat[55509]: INFO xcatd: syncfiles plugin bug, pid 55509, process description: 'xcatd SSL: syncfiles for mid05tor12cn03: syncfiles instance' with error 'Died at /opt/xcat/sbin/xcatd line 2100.#012'
Jan 15 16:20:17 mid05tor12cn03 xcat.deployment.postbootscript: ERR  syncfiles: Perform Syncing File action encountered error
Jan 15 16:20:17 mid05tor12cn03 xcat.deployment.postbootscript: INFO  postbootscript end...:syncfiles return with 1
```

So i expect this to fail because i don't have the files on the MGMT node that are part of the synclist, but the error message doesn't help the user figure out what went wrong.

**Comment by robin2008** [comment] 2019-01-16 02:22
I think there are two issues:
1, not doing error handling well in `/opt/xcat/lib/perl/xCAT/DSHCLI.pm` and `syncfiles` plugin, there should be sensible error message
2, `INFO  postbootscript end...:syncfiles return with 1`, does this should be error level too? @bybai

**Comment by immarvin** [comment] 2019-01-16 02:36
seems the `ERR Not an ARRAY reference at /opt/xcat/lib/perl/xCAT/DSHCLI.pm line 6320. ` is caused by the incompatible syntax among different perl versions. What is the Linux version and perl version?

seems @cxhong processed similar issues in PR https://github.com/xcat2/xcat-core/pull/5906, would you please take a look at this? @cxhong   thanks

**Comment by immarvin** [comment] 2019-01-16 02:37
`Jan 15 16:19:02 briggs01 xcat[54943]: INFO xcatd: syncfiles plugin bug, pid 54943, process description: 'xcatd SSL: syncfiles for mid05tor12cn03: syncfiles instance' with error 'Died at /opt/xcat/sbin/xcatd line 2100.#012'` is a critical error, i suggest to raise the priority of this ticket to fix the syntax issue

**Comment by whowutwut** [comment] 2019-01-16 02:57
Yea @cxhong suggest that I update xcat to latest build. I will try this tomorrow

**Comment by zet809** [comment] 2019-02-25 07:57
Hi, @whowutwut , any updates?

**Comment by zet809** [comment] 2019-03-26 06:23
Let's close this issue and reopen if encounter it again.

**Comment by cxhong** [comment] 2019-03-26 18:57
can't recreate it,  will close this issue.

**Closed by cxhong** 2019-03-26 18:57 UTC
Labels: component:file_sync, sprint2, type:usability

**Comment by zet809** [comment] 2019-03-27 01:13
Thank you, @cxhong
