### ISSUE TITLE
xcat : imgcapture sysclone problem

### ISSUE THREAD

**Issue by TRF123** [xcat2/xcat-core#2796] opened 2017-04-01 19:41 UTC
Greetings ;

I have a vagrant environment which contains one master node and another node called the golden client (both are using Centos 6.5), 

I tried to make an image capture of the OS of the Golden client  using xcat and deploy the captured image to another vm created by xcat and KVM using this tutorial

http://xcat-docs.readthedocs.io/en/stable/advanced/sysclone/sysclone.html

unfortunately, I had an error  when I execute the command "imgcapture mynode  -t sysclone -o myimage" which is :

Error: systemimager-client is not installed on the mynode.
Error: Can not prepare Golden Client on mynode

I tried to solve the errors using the suggested solution in the tutorial but it did not work for me,
it seems that the systemimager-client is not activated and I don't know how to do that.

could anyone help me to solve this issue please since I am a new xcat user   !!!! .

**Comment by gurevichmark** [comment] 2017-04-03 17:44
Most likely this error is dislayed because `systemimager` is not installed on MN or "golden client".
However, keeping this issue opened, because even after installing `systemimager` on both MN and "golden client", running the `imgcapture` command results in this error:

```
[root@fs2vm102 rhels7.3]# imgcapture imgcapture_vm_test1 -t sysclone -o rhels7.3-ppc64le-MG-install-compute
Checking if systemimager packages are installed on fs2vm102.
Checking if systemimager packages are installed on imgcapture_vm_test1.
Preparing osimage rhels7.3-ppc64le-MG-install-compute on imgcapture_vm_test1_test1.
Error: export PERL5LIB=/usr/lib/perl5/site_perl/;LANG=C si_prepareclient --server fs2vm102 --no-uyok --yes failed on the imgcapture_vm_test1.
Error: Can not prepare Golden Client on imgcapture_vm_test1.
```

**Comment by gurevichmark** [comment] 2017-04-04 13:12
Duplicate of #2737

**Closed** 2017-04-24 07:42 UTC
Labels: component:os_provision, status:duplicate
