### ISSUE TITLE
goconserver malformed HTTP response

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#5313] opened 2018-06-21 23:30 UTC
`congo` commands fail with "malformed HTTP response":

```
# congo list
Could not list resources, Get http://127.0.0.1:12429/nodes: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

```
# congo version
Version: 0.2.2, BuildTime: 2018-03-29T21:46:21-0400
 Commit: 75077f1e64efb5ec56e70185b4aa0787f4d498a4
```

Remote console works fine otherwise:
```
# rcons sh-hn02
[Enter `^Ec?' for help]
goconserver(2018-06-21T16:29:17-07:00): Hello 10.10.0.1:49152, welcome to the session of sh-hn02

CentOS Linux 7 (Core)
Kernel 3.10.0-862.3.2.el7.x86_64 on an x86_64

sh-hn02 login:
```

**Comment by kcgthb** [comment] 2018-06-22 22:11
Oh I see, thanks for the pointer.

Defining those environment variables seem a bit redundant, though. Wouldn't it be better if `congo` could parse `/etc/goconserver/server.conf` directly and use its information directly, since everything is already defined there?

**Comment by zet809** [comment] 2018-06-25 02:11
In fact, server.conf is just for the goconserver itself, but congo is a client, it shall not read server configuration directly.
And in your case, rcons works, since rcons use xCAT default configuration for congo. 
Maybe we can enhance congo to look for keys in an assignable directory.

**Comment by zet809** [comment] 2018-06-25 09:48
BTW, @kcgthb , I notice that you use `congo` directly, how do you want to use with goconserver?

**Comment by kcgthb** [comment] 2018-06-25 17:09
@zet809 I see, thanks! It just seems a bit redundant to have to provide the same information about certificates in multiple places.

As for using `congo` directly, I don't really have a use case, I was just trying to test the functionality I was asking for in #5134 (https://github.com/xcat2/goconserver/pull/45). But I'd love not to have to use `congo` for this. :)

**Comment by zet809** [comment] 2018-06-26 01:46
Got it, thx!
For the function broadcast mode, pls reference https://github.com/xcat2/goconserver/releases for more information.

**Comment by kcgthb** [comment] 2018-06-27 15:21
Thank you! 
I'm not seeing any reference to the broadcast mode in https://github.com/xcat2/goconserver/releases. Is there a way to use it with `rcons`/`wcons` directly, without invoking `congo`?

**Comment by zet809** [comment] 2018-07-09 07:34
The `rcons` will go into broadcast mode automatically if you specify multiple node for it. The `ctrl+e c l ?` will be send to all the nodes specified.
Since we haven't have change to verify this function, it is not included in the 0.3.0 release, you have to build file by yourself.

**Comment by chuckbrazie** [comment] 2018-07-09 10:01
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
goconserver malformed HTTP response (#5313)" sent on 7/9/18 7:34:40 AM.

This is the only notification you will receive while this person is away.

**Comment by kcgthb** [comment] 2018-07-11 15:07
@zet809 
> Since we haven't have change to verify this function, it is not included in the 0.3.0 release, you have to build file by yourself.

All right, I'll wait for the next release, then. Thank you!

**Comment by chuckbrazie** [comment] 2018-07-11 16:02
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
goconserver malformed HTTP response (#5313)" sent on 7/11/18 3:07:30 PM.

This is the only notification you will receive while this person is away.

**Comment by zet809** [comment] 2018-07-13 02:20
OK, @kcgthb , I will move this defect forward and let you know when we release new goconser with broadcast enabled. Thx!

**Comment by zet809** [comment] 2018-07-13 02:40
hi, @kcgthb , I will move this defect forward and let you know when  we release new goconserver with broadcast  enabled. Thx!

**Comment by zet809** [comment] 2018-08-21 08:13
Hi, @kcgthb , the goconserver [v0.3.1](https://github.com/xcat2/goconserver/releases/tag/v0.3.1) include the broadcast function, pls take a try and feel free to let us know the result. Thx!

**Comment by zet809** [comment] 2018-08-23 06:50
HI, @kcgthb , for the 1st question, after we investigate the broadcast function of https://github.com/dun/conman, it also output nothing. So, we just keep it.
For the 2nd issue, can you show me the output of `makegocons -q`? 
Thx!

**Comment by kcgthb** [comment] 2018-08-23 15:26
Hi @zet809 
1. I see, and that's true. Still makes it a bit counter-intuitive, though. Maybe a note in the documentation would be helpful, to mention that no output will be displayed, but that one can use `wcons` in parallel to actually see what's happening on the consoles?
2. Sure
```
# makegocons -q sh-101-[59-60]

NODE                             SERVER                           STATE
sh-101-59                        sh-hn02.SUNet                    avaiable
sh-101-60                        sh-hn02.SUNet                    avaiable
```
`sh-hn02.SUNet` is the FQDN of that SN (which is required for other reasons), but all xCAT references to this nodes are done with the shortname:
```
# lsdef -c sh-101-[59-60] -i servicenode,conserver
sh-101-59: conserver=sh-hn02
sh-101-59: servicenode=sh-hn02
sh-101-60: conserver=sh-hn02
sh-101-60: servicenode=sh-hn02
```

**Comment by neo954** [comment] 2018-08-24 09:29
Hello @kcgthb,

Unfortunately, I cannot reproduce your problem in my test environment. Based on your comments above, it seems you are facing DNS resolving problem. Can both the short hostnames and the FQDNs be resolved on all the nodes in your cluster? It seems that is the problem. Can you verify that in your environment?

**Comment by kcgthb** [comment] 2018-08-24 15:27
@neo954 thanks for looking into this. I'll double check the DNS config on our end, but I think the question is: why is `goconserver` trying to get the FQDN of the console servers instead of using the name that is provided in the `nodehm` table?

**Comment by kcgthb** [comment] 2018-08-24 15:40
And I checked, and yes, both the SN/Console server's FQDN and short name can be properly resolved on both the CN itself, and the compute nodes:

```
# clush -w sh-101-[59-60],sh-hn02 host sh-hn02.SUNet
sh-101-59: sh-hn02.SUNet has address 10.102.2.202
sh-101-60: sh-hn02.SUNet has address 10.102.2.202
sh-hn02: sh-hn02.SUNet has address 10.102.2.202

# clush -w sh-101-[59-60],sh-hn02 host sh-hn02
sh-101-59: sh-hn02.int has address 10.10.0.2
sh-101-60: sh-hn02.int has address 10.10.0.2
sh-hn02: sh-hn02.int has address 10.10.0.2
```

And yet:
```
rcons sh-101-59,sh-101-60
bash: sh-hn02: command not found
Error: could not get the short hostname for sh-hn02
sh-hn02.
```

The `bash: sh-hn02: command not found` part especially makes me think that there's more than just DNS resolution at play here, it looks like an issue with the parsing of some command output, because that sure looks like the result of trying to execute a hostname.

**Comment by kcgthb** [comment] 2018-08-24 16:54
Also, I think you're discussing similar findings in https://github.com/xcat2/goconserver/issues/48 :)

**Comment by zet809** [comment] 2018-08-28 07:37
hi, @kcgthb , the error msg below seems to me that the Management Node from which running rcons can not resolve `sh-hn02`, will you pls check that? 
```
bash: sh-hn02: command not found
Error: could not get the short hostname for sh-hn02
```

**Comment by kcgthb** [comment] 2018-08-28 17:37
@zet809 the Management Node from which the `rcons` command is called can perfectly resolve `sh-hn02`: it's in both DNS and `/etc/hosts`:

```
# rcons sh-101-59,sh-101-60
bash: sh-hn02: command not found
Error: could not get the short hostname for sh-hn02
sh-hn02.

# host sh-hn02
sh-hn02.int has address 10.10.0.2

# ping -c1 sh-hn02
PING sh-hn02.int (10.10.0.2) 56(84) bytes of data.
64 bytes from sh-hn02-em1.int (10.10.0.2): icmp_seq=1 ttl=64 time=0.179 ms

--- sh-hn02.int ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.179/0.179/0.179/0.000 ms
```

**Comment by zet809** [comment] 2018-08-30 10:01
yes, @kcgthb , you are right the rcons doesn't work with hierarchical.
For nodes with same conserver, connect to the goconserver on it directly.
But for different conserver, we need to enhance current rcons and goconserver to support it. So, I will quickly fix the scenario that have same conserver.

**Comment by zet809** [comment] 2018-10-10 10:04
We have https://github.com/xcat2/goconserver/issues/48 opened to trace the issue that goconserver broadcast function can not support the hierarchical structure.

**Comment by zet809** [comment] 2018-10-23 06:02
hi, @kcgthb , since the xcat2/goconserver#48 can be used to trace the broadcast function, I will close this issue. Thx!

**Closed by zet809** 2018-10-23 06:02 UTC
Labels: component:goconserver, sprint2
