### ISSUE TITLE
bmcdiscover needs to use Model instead of PartNumber again.... 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3691] opened 2017-08-16 01:14 UTC
This is crazy.  

Today, running a more later build of OpenBMC, I saw there was a problem with `bmcdiscover` when we did know the model type and serial number of the host...

```
[root@fs2vm110 ~]# rinv frame6u05 serial
frame6u05: SYSTEM SerialNumber : 1318C4A
[root@fs2vm110 ~]# rinv frame6u05 model
frame6u05: SYSTEM Model : 8335-GTC
```

But then running `bmcdiscover` we have this behavior...

```
[root@fs2vm110 ~]# bmcdiscover --range 9.114.120.110 -z -w
node-:
        objtype=node
        groups=all
        bmc=9.114.120.110
        cons=openbmc
        mgt=openbmc
        serial=1318C4A
```

Then we are able to write this to the DB as well. 
```
[root@fs2vm110 ~]# nodels
frame6u05
node-
...
```

Looks like the Model is not in `PartNumber` but in `Model` Field.  Was originally changed in #3206 

Two issues: 

- [x] Should use Model Number in bmcdiscover code 
- [ ] Should we prevent -w option from writing invalid node definitions to the xCAT database... (non unique ones)

**Comment by whowutwut** [comment] 2017-08-16 01:18
Link to #3205

**Comment by whowutwut** [comment] 2017-08-16 01:19
@zet809 @xuweibj What are your thoughts about the 2nd issue posted above?

**Comment by zet809** [comment] 2017-08-16 09:43
Yes, @whowutwut , seems to be we need to use REST interface to get BMC MAC if no mac can be get with nmap.

**Comment by whowutwut** [comment] 2017-08-17 11:05
@zet809. I think this is a case where we got something for serial number and nothing for model and we did not fall back on the MAC address if it's not complete?

**Comment by whowutwut** [comment] 2017-08-17 11:06
@zet809. I think this is a case where we got something for serial number and nothing for model and we did not fall back on the MAC address if it's not complete?

**Comment by zet809** [comment] 2017-08-21 02:31
No, in fact, the BMC node will use MAC address if either model or serial number does not exist.
The root cause for this issue is, we can not get MAC address directly through nmap or ping for the target node that is outside of local subnet, we can only get BMC MAC through ipmi or RESTful interface. Seems we need to enhance our bmcdiscover command.

**Comment by whowutwut** [comment] 2017-08-27 14:29
@zet809  Can you or @xuweibj Investigate the 2nd problem discussed above?

**Comment by zet809** [comment] 2017-08-28 03:31
Hi, @whowutwut , you are right we shall not write invalid entries into xCAT db. And also plan to add ipmitool or RESTful command to retrieve BMC mac if nmap can not get.

**Comment by zet809** [comment] 2017-09-13 09:27
A little low priority, move to next release.

**Comment by zet809** [comment] 2017-12-14 07:40
Seems no one concern this issue, so move away.

**Comment by zet809** [comment] 2017-12-14 08:28
I think we can cover this issue in PR #4496

**Comment by zet809** [comment] 2018-03-09 03:57
Let's close this issue.

**Closed by zet809** 2018-03-09 03:57 UTC
Labels: component:openbmc, type:bug
