### ISSUE TITLE
Unable to execute configonie as non-root user

### ISSUE THREAD

**Issue by kkvtran** [xcat2/xcat-core#5411] opened 2018-07-18 16:11 UTC
/opt/xcat/share/xcat/scripts/configonie --switches $SWITCH --ntp
Failed to connect to nodelist table after retrying 3 times: DBI connect('/etc/xcat/nodelist.sqlite','',...) failed: unable to open database file at /opt/xcat/lib/perl/xCAT/Table.pm line 972.

Can't call method "prepare" on an undefined value at /opt/xcat/lib/perl/xCAT/Table.pm line 998.

I could do 
updatenode $SWITCH -P enablesnmp     
$SWITCH: trying to download postscripts...
$SWITCH: postscripts downloaded successfully
$SWITCH: trying to get mypostscript from 192.168.224.6...
$SWITCH: Wed Jul 18 16:02:13 UTC 2018 Running postscript: enablesnmp
$SWITCH: postscript: enablesnmp exited with code 0
$SWITCH: Running of postscripts has completed.

I chatted with Casandra.  She asked me to open the issue for her to look in to the issue.  Thanks Casandra.

**Comment by robin2008** [comment] 2018-07-19 01:41
If it wants to operate DB and other privilege commands,  it is better to use it as a plugin.   
Here, you can try to use `lsdef` and parse the data for using as a workaround.

**Comment by immarvin** [comment] 2018-07-23 03:07
hi @kkvtran , any update on this?

**Comment by cxhong** [comment] 2018-07-25 13:38
I can recreate this on our test system.  I will add error message if ran by non-root user.  
In the near future, we should move `configonie` code to onie plugin.

**Comment by cxhong** [comment] 2018-07-26 17:44
if switch has passwordlesss enabled for root user.  the updatenode command to the switch will work too for non-root users.

**Comment by kkvtran** [comment] 2018-07-26 18:01
Yes, updatenode works for non-root user, i.e. tran58.

**Comment by immarvin** [comment] 2018-07-27 02:54
hi @kkvtran , if the issue is resolved and you are ok with @cxhong 's fix, please close this ticket, thanks

**Closed** 2018-07-27 03:56 UTC
