### ISSUE TITLE
after os installation, the system will enter into genesis, on garrison node. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1422] opened 2016-06-28 10:19 UTC
I will write this issue down, since it's difficult to recreate it. 
```
[root@c712ems4 ~]# lsxcatd -v
Version 2.12 (git commit 5df15f39216da9c64759d61b19fbabad1674727d, built Wed May 18 07:30:41 EDT 2016)
[root@c712ems4 ~]# uname -a
Linux c712ems4 3.10.0-327.13.1.el7.openpower3.ppc64le #1 SMP Thu Apr 28 13:22:48 EDT 2016 ppc64le ppc64le ppc64le GNU/Linux
```
```
[root@c712ems4 tools]# lsdef node-8335-gtb-100585a
Object name: node-8335-gtb-100585a
    bmc=192.168.130.214
    cons=ipmi
    groups=all
    hwtype=bmc
    mgt=ipmi
    mtm=8335-GTB
    nodetype=mp
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=100585A
    statustime=06-28-2016 01:47:23

[root@c712ems4 tools]# ping 192.168.130.214
PING 192.168.130.214 (192.168.130.214) 56(84) bytes of data.
64 bytes from 192.168.130.214: icmp_seq=1 ttl=64 time=0.345 ms
^C
--- 192.168.130.214 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
```

```
[root@c712ems4 tools]# lsdef node-8335-gtb-100585a
Object name: node-8335-gtb-100585a
    bmc=192.168.130.214
    cons=ipmi
    groups=all
    hwtype=bmc
    mgt=ipmi
    mtm=8335-GTB
    nodetype=mp
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=100585A
    status=booting
    statustime=06-28-2016 02:22:02
[root@c712ems4 tools]# ping 192.168.130.214
PING 192.168.130.214 (192.168.130.214) 56(84) bytes of data.
From 192.168.130.1 icmp_seq=1 Destination Host Unreachable
```

then I see the 100585a 's mac has been added into c712f9n01 . 
```
[root@c712ems4 tools]#  tabdump mac|grep 70:e2:84:14:0f:0c
"c712f9n01-pvt",,"70:e2:84:14:0f:0c",,

[root@c712ems4 tools]# lsdef c712f9n01-pvt
Object name: c712f9n01-pvt
    arch=ppc64
    bmc=10.128.130.171
    chain=runcmd=bmcsetup
    cons=ipmi
    cpucount=160
    cputype=POWER8NVL (raw), altivec supported
    disksize=sda:1000GB,sdb:1000GB
    groups=all,f9,compute
    initrd=xcat/genesis.fs.ppc64.gz
    installnic=mac
    ip=192.168.130.171
    kcmdline=quiet xcatd=192.168.130.1:3001 destiny=runcmd=bmcsetup
    kernel=xcat/genesis.kernel.ppc64
    mac=70:e2:84:14:0f:0c
    memory=261493MB
    mgt=ipmi
    mtm=8335-GTB
    netboot=petitboot
    nicips.ib0=172.17.0.171
    nicips.ib1=172.17.1.171
    nicips.enP5p7s0f1=9.114.75.171
    nicnetworks.ib0=c712ib0
    nicnetworks.ib1=c712ib1
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
    nodetype=mp
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignics -s,confignics --iba=2,setroute
    primarynic=mac
    routenames=v2094gw9
    serial=100585A
    status=bmcready
    statustime=06-28-2016 02:31:04
    supportedarchs=ppc64
    switch=c712f11u30vc
    switchport=1/0/0

[root@c712ems4 tools]# nodeset c712f9n01-pvt osimage=rh72openpower4diskfull
c712f9n01-pvt: install rhels7.2-ppc64le-compute

[root@c712ems4 tools]# rsetboot c712f9n01-pvt net
c712f9n01-pvt: Error: timeout
```
```
[root@c712ems4 tools]# lsdef c712f9n01-pvt
Object name: c712f9n01-pvt
    arch=ppc64
    bmc=10.128.130.171
    chain=runcmd=bmcsetup
    cons=ipmi
    cpucount=160
    cputype=POWER8NVL (raw), altivec supported
    disksize=sda:1000GB,sdb:1000GB
    groups=all,f9,compute
    initrd=xcat/osimage/rh72openpower4diskfull1625/initrd.img
    installnic=mac
    ip=192.168.130.171
    kcmdline=quiet inst.repo=http://!myipfn!:80/install/rhels7.2/ppc64le_panst.ks=http://!myipfn!:80/install/autoinst/c712f9n01-pvt BOOTIF=70:e2:84:14c  ip=dhcp
    kernel=xcat/osimage/rh72openpower4diskfull1625/vmlinuz
    mac=70:e2:84:14:0f:0c
    memory=261493MB
    mgt=ipmi
    mtm=8335-GTB
    netboot=petitboot
    nicips.ib0=172.17.0.171
    nicips.ib1=172.17.1.171
    nicips.enP5p7s0f1=9.114.75.171
    nicnetworks.ib0=c712ib0
    nicnetworks.ib1=c712ib1
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
    nodetype=mp
    os=rhels7.2
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignics -s,confignics --iba=2,setroute
    primarynic=mac
    profile=compute
    provmethod=rh72openpower4diskfull1625
    routenames=v2094gw9
    serial=100585A
    status=bmcready
    statustime=06-28-2016 02:31:04
    supportedarchs=ppc64
    switch=c712f11u30vc
    switchport=1/0/0
[root@c712ems4 tools]# ping 10.128.130.171
PING 10.128.130.171 (10.128.130.171) 56(84) bytes of data.
From 10.128.130.1 icmp_seq=1 Destination Host Unreachable
[root@c712ems4 tools]# rsetboot c712f9n01-pvt net
c712f9n01-pvt: Network
[root@c712ems4 tools]# rpower c712f9n01-pvt boot
c712f9n01-pvt: reset
```

after a long time , I tried to ssh to it, I found I entered into the genesis.
```
[root@c712f9n10-pvt ~]# ssh c712f9n01-pvt
Warning: Permanently added 'c712f9n01-pvt,192.168.130.171' (ECDSA) to the lf known hosts.
[xCAT Genesis running on c712f9n01-pvt /]# exit
logout
```

then : 
```
[root@c712ems4 tools]# lsdef c712f9n01-pvt
Object name: c712f9n01-pvt
    arch=ppc64
    bmc=10.128.130.171
    chain=runcmd=bmcsetup
    cons=ipmi
    cpucount=160
    cputype=POWER8NVL (raw), altivec supported
    currchain=runcmd=bmcsetup
    currstate=runcmd=bmcsetup
    disksize=sda:1000GB,sdb:1000GB
    groups=all,f9,compute
    initrd=xcat/genesis.fs.ppc64.gz
    installnic=mac
    ip=192.168.130.171
    kcmdline=quiet xcatd=192.168.130.1:3001 destiny=runcmd=bmcsetup
    kernel=xcat/genesis.kernel.ppc64
    mac=70:e2:84:14:0f:0c
    memory=261493MB
    mgt=ipmi
    mtm=8335-GTB
    netboot=petitboot
    nicips.ib0=172.17.0.171
    nicips.ib1=172.17.1.171
    nicips.enP5p7s0f1=9.114.75.171
    nicnetworks.ib0=c712ib0
    nicnetworks.ib1=c712ib1
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
    nodetype=mp
    os=rhels7.2
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignics -s,confignics --iba=2,setroute
    primarynic=mac
    profile=compute
    provmethod=rh72openpower4diskfull1625
    routenames=v2094gw9
    serial=100585A
    status=configuring
    statustime=06-28-2016 02:50:30
    supportedarchs=ppc64
    switch=c712f11u30vc
    switchport=1/0/0
```

**Comment by daniceexi** [comment] 2016-06-28 10:38
@wwzhubj You should not set ``chain=runcmd=bmcsetup`` for a node if you don't want to do the bmcsetup. If you set ``chain=runcmd=bmcsetup``, xcat would try to run it after the current task (os deployment)

**Comment by whowutwut** [comment] 2016-06-28 14:45
@daniceexi  running `bmcsetup` script in the chain should just configure the bmc back to the same IP address, no?

**Comment by whowutwut** [comment] 2016-06-28 14:47
@wwzhubj  I formatted your initial post, please try and use the markdown to format the code so that it's easier to read. Thanks

**Comment by daniceexi** [comment] 2016-06-29 01:00
@whowutwut rerun ``bmcsetup`` should be OK, it just reconfigure the same IP for the bmc. But @wwzhubj concerned why the compute node got into genesis. Since the last task in the ``chain`` was bmcsetup, then genesis hung there to wait for next task after running of ``bmcsetup``.

**Comment by wwzhubj** [comment] 2016-06-29 07:30
This story happened when using switch discovery. 
In this issue, including  another issue:
after boot the bmc node, the node information has been input into the predefined node, then I ran 
nodeset nodename osimage=rh72openpower4diskfull1625, 
after nodeset exit with no error, 
lsdef show the node information, there is no currchain and currstate.
```
[root@c712ems4 tmp]# nodeset c712f6n01-pvt osimage=rh72openpower4diskfull1625
c712f6n01-pvt: install rhels7.2-ppc64le-compute
```
```
[root@c712ems4 tmp]# lsdef c712f6n01-pvt
Object name: c712f6n01-pvt
    arch=ppc64
    bmc=10.128.130.211
    chain=runcmd=bmcsetup
    cons=ipmi
    cpucount=160
    cputype=POWER8NVL (raw), altivec supported
    disksize=sda:1000GB,sdb:1000GB
    groups=all,f6,compute
    initrd=xcat/osimage/rh72openpower4diskfull1625/initrd.img
    installnic=mac
    ip=192.168.130.211
    kcmdline=quiet inst.repo=http://!myipfn!:80/install/rhels7.2/ppc64le_patch i                                                               nst.ks=http://!myipfn!:80/install/autoinst/c712f6n01-pvt BOOTIF=70:e2:84:14:0c:f                                                               3  ip=dhcp
    kernel=xcat/osimage/rh72openpower4diskfull1625/vmlinuz
    mac=70:e2:84:14:0c:f3
    memory=261493MB
    mgt=ipmi
    mtm=8335-GTB
    netboot=petitboot
    nicips.ib0=172.17.0.211
    nicips.ib1=172.17.1.211
    nicips.enP5p7s0f1=9.114.75.211
    nicnetworks.ib0=c712ib0
    nicnetworks.ib1=c712ib1
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
    nodetype=mp
    os=rhels7.2
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignics -s,confignics --ibaports                                                               =2,setroute
    primarynic=mac
    profile=compute
    provmethod=rh72openpower4diskfull1625
    routenames=v2094gw9
    serial=1005DDA
    supportedarchs=ppc64
    switch=c712f11u30vc
    switchport=2/0/0
```

**Comment by daniceexi** [comment] 2016-06-30 08:55
@zet809 mentioned he recreated the issue on @wwzhubj 's env that ``nodeset <node> osimage`` did not update the ``currchain and currstate``. I think this is the root cause of this issue.

But @zet809 could not recreate this issue on his env, so he will try to recreate it on @wwzhubj and to see whether we could find the defect in the code.

**Comment by daniceexi** [comment] 2016-07-05 05:21
We will try to recreate this issue and fix it in 2.12.2.

**Comment by whowutwut** [comment] 2016-07-05 10:44
@wwzhubj @immarvin  One thing to notice is now the genesis files in `/tftpboot` directory also contain the name of the xCAT server and network that is serving genesis.  This will show up in the petitboot menu as `xCAT Genesis (<ip address>)`.  This could help to determine whether the network configuration is correct and/or the intended behavior.

**Comment by immarvin** [comment] 2016-08-09 02:03
hi @wwzhubj , does this issue still exist ?

**Comment by zet809** [comment] 2016-08-12 02:19
Talking with @wwzhubj shows that this issue can not be reproduced easily at present, so move to next release.

**Comment by whowutwut** [comment] 2016-08-16 00:08
We might need to consider how to debug these issues at scale.  Whether or not we can replay the console like what @hu-weihua  just added.  Maybe these things will occur more frequently when we are discovering a large set up nodes so it would be helpful if we had the logs needed to debug.

**Comment by zet809** [comment] 2016-08-16 07:30
The root cause is nodeset doesn't write currchain and currstate when doing OS deployment. It is a little hard to use replaying to debug the issue since there is no log recording this expect running lsdef manually. 
A possible solution may be to check those 2 attributes (currchain and currstate) of a node before nodeset <node> osimage=<image_obj> return.

**Comment by zet809** [comment] 2016-09-19 06:12
@wwzhubj Hi, wei wei, will you pls verify with our latest document that append osimage=<xxx> after runcmd=bmcsetup for chain to make sure whether this issue can be reproduced?

**Comment by whowutwut** [comment] 2016-10-25 18:14
Closing out, @wwzhubj  Please open new issues if you hit this again

**Closed by whowutwut** 2016-10-25 18:14 UTC
Labels: component:os_provision, priority:normal, status:pending, type:bug
