### ISSUE TITLE
read the docs usability - workflow guide page

### ISSUE THREAD

**Issue by NickyDaB** [xcat2/xcat-core#6419] opened 2019-09-05 13:45 UTC
# Summary 

on page: https://xcat-docs.readthedocs.io/en/latest/guides/get-started/workflow_guide.html

> 3. Start to use xCAT management node
Refer to the doc: xCAT Admin Guide.

admin guide should have a hyper link. What is this 1962?

# Expected behavior:

> 3. Start to use xCAT management node
Refer to the doc: [xCAT Admin Guide](https://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/index.html). 

# Suggestion Comments: 

My assumption is https://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/index.html is the correct link? but i could be mistaken. but by a developer of xcat actually hyperlinking to the doc you mention, it will eliminate ambiguity of this situation. 

i wouldnt use a static link. i think read the docs supports tags and relative links. use those.

**Comment by NickyDaB** [comment] 2019-09-05 13:47
same with `Refer to the doc: xCAT discovery Guide` in step 4

**Comment by NickyDaB** [comment] 2019-09-05 13:51
like i cant even guess as to where `xCAT discovery guide` is. It's not in the main tabs to the left. and if it takes more that 5 seconds to find, then, In my opinion, that's too long.

**Comment by gurevichmark** [comment] 2019-09-05 13:58
There are other entries in that list (2-7) have a `Refer to the doc` entry with a broken link.

Looking at the source, there is an attempt to create a link for each one of them, but the path is probably wrong:

![image](https://user-images.githubusercontent.com/16106630/64348712-aaa4a500-cfc3-11e9-839c-5c11abc9bc0a.png)

**Comment by gurevichmark** [comment] 2019-09-05 14:05
This issue is a duplicate of #6383

**Comment by NickyDaB** [comment] 2019-09-05 14:17
> This issue is a duplicate of #6383

oh that it is. didnt notice. sorry.

**Comment by NickyDaB** [comment] 2019-09-05 14:19
> Looking at the source, there is an attempt to create a link for each one of them, but the path is probably wrong:

Maybe "relative path" was the wrong term. we did something is CAST read the docs. let me go find it, and ill share it here and on the other issue. but i probably wont get to that until tomorrow.

**Comment by gurevichmark** [comment] 2019-09-05 14:31
Out documentation guide https://xcat-docs.readthedocs.io/en/stable/developers/guides/docs/doc_guidelines.html gives some ideas on how to handle links in the docs in "Hyperlinks -> Internal Links -> External Links" section.

**Comment by NickyDaB** [comment] 2019-09-06 18:13
yeah we used the `Link Target` method on that page.   i think its good because they wont break when you change your page dir structure. 

```
.. _CSM:

Cluster System Management (CSM) 
===============================

.. image:: https://user-images.githubusercontent.com/4662139/49670811-e958ff00-fa33-11e8-92c2-3bf00e8d1001.png
    :height: 200px

CSM is a cognitive self learning system for managing and overseeing a HPC cluster. CSM interacts with a variety of open source IBM tools for supporting and maintaining a cluster, such as:
```

highlight: 
```
.. _CSM:
```


then actually with the link

```
.. _CSM_APIs:

APIs
====

:ref:`CSM` uses Application Programming Interfaces (APIs) to communicate between its sub systems and to external programs. 
This section is a general purpose guide for interacting with CSM APIs. 

This section is divided into the following subsections:
```

highlight: 
```
:ref:`CSM` 
```

**Comment by gurevichmark** [comment] 2019-10-09 17:45
Closing as a duplicate of #6383

**Closed by gurevichmark** 2019-10-09 17:45 UTC
Labels: status:duplicate
