### ISSUE TITLE
[DEV]sles12.1 hang on "Failed to add add-on product" during diskful  provision on p8le kvm

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#586] opened 2016-01-12 07:08 UTC
The diskful installation hang with error "Failed to add add-on product" at the beginning.

system info :
```
root@xcat2-11mn:~# lsdef -t osimage -o sles12.1-ppc64le-install-compute
Object name: sles12.1-ppc64le-install-compute
    imagetype=linux
    osarch=ppc64le
    osdistroname=sles12.1-ppc64le
    osname=Linux
    osvers=sles12.1
    otherpkgdir=/install/post/otherpkgs/sles12.1/ppc64le
    pkgdir=/install/source/sles12.1/ppc64le
    pkglist=/opt/xcat/share/xcat/install/sles/compute.sles12.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/sles/compute.sles12.ppc64le.tmpl

root@xcat2-11mn:~# lsxcatd -v
Version 2.11 (git commit 9ea36ca6163392bf9ab684830217f017193815be, built Mon Nov 30 05:49:07 EST 2015)
```
the /var/log/apache2/access_info on MN:
```
10.5.33.102 - - [12/Jan/2016:06:58:59 +0000] "GET /install/source/sles12.1/ppc64le/1/media.1/info.txt HTTP/1.1" 404 484 "-" "-"
10.5.33.102 - - [12/Jan/2016:06:58:59 +0000] "GET /install/source/sles12.1/ppc64le/1/part.info HTTP/1.1" 404 477 "-" "-"
10.5.33.102 - - [12/Jan/2016:06:58:59 +0000] "GET /install/source/sles12.1/ppc64le/1/autoinst.xml HTTP/1.1" 404 480 "-" "-"
10.5.33.102 - - [12/Jan/2016:06:58:59 +0000] "GET /install/source/sles12.1/ppc64le/1/driverupdate HTTP/1.1" 404 480 "-" "-"
10.5.33.102 - - [12/Jan/2016:06:59:22 +0000] "HEAD /install/source/sles12.1/ppc64le/1/repodata/repomd.xml HTTP/1.1" 404 139 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:24 +0000] "GET /install/source/sles12.1/ppc64le/1/add_on_products.xml HTTP/1.1" 404 487 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:24 +0000] "GET /install/source/sles12.1/ppc64le/1/add_on_products HTTP/1.1" 404 483 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:49 +0000] "GET /install/source/sles12.1/ppc64le/1/docu/directory.yast HTTP/1.1" 404 487 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:50 +0000] "GET /install/source/sles12.1/ppc64le/1/docu/directory.yast HTTP/1.1" 404 487 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:50 +0000] "GET /install/source/sles12.1/ppc64le/1/docu/directory.yast HTTP/1.1" 404 487 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:51 +0000] "HEAD /install/source/sles12.1/ppc64le/repodata/repomd.xml HTTP/1.1" 404 139 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:51 +0000] "HEAD /install/source/sles12.1/ppc64le/content HTTP/1.1" 404 139 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:51 +0000] "HEAD /install/source/sles12.1/ppc64le/repodata/repomd.xml HTTP/1.1" 404 139 "-" "ZYpp 15.19.5 (curl 7.37.0)"
10.5.33.102 - - [12/Jan/2016:06:59:51 +0000] "HEAD /install/source/sles12.1/ppc64le/content HTTP/1.1" 404 139 "-" "ZYpp 15.19.5 (curl 7.37.0)"
```

**Comment by immarvin** [comment] 2016-01-12 07:10
can FvT try to recreate this in the autotest?

**Comment by whowutwut** [comment] 2016-01-18 23:24
Is anything special in the postscripts or they are using the default shipped with xCAT?

**Comment by whowutwut** [comment] 2016-01-18 23:24
Another question, what is the mgmt node OS/ARCH?

**Comment by whowutwut** [comment] 2016-01-18 23:25
@pdlun92  Did we see any issues launching SLES 12.1 on our pkvm machine?

**Comment by cxhong** [comment] 2016-01-20 15:25
I successfully provisioned a sles12.1 diskfull compute node on p8le kvm.  I didn't see "Failed to add add-on product" message.   
the /var/log/apache2/access_log on MN:
````
10.3.31.35 - - [20/Jan/2016:10:21:19 -0500] "GET /install/sles12.1/ppc64le/1/content.key HTTP/1.1" 200 972 "-" "ZYpp 15.19.2 (curl 7.37.0)"
10.3.31.35 - - [20/Jan/2016:10:21:19 -0500] "GET /install/sles12.1/ppc64le/1/content HTTP/1.1" 200 11822 "-" "ZYpp 15.19.2 (curl 7.37.0)"
10.3.31.35 - - [20/Jan/2016:10:21:19 -0500] "GET /install/sles12.1/ppc64le/1/add_on_products.xml HTTP/1.1" 404 981 "-" "ZYpp 15.19.2 (curl 7.37.0)"
10.3.31.35 - - [20/Jan/2016:10:21:19 -0500] "GET /install/sles12.1/ppc64le/1/add_on_products HTTP/1.1" 404 981 "-" "ZYpp 15.19.2 (curl 7.37.0)"
10.3.31.35 - - [20/Jan/2016:10:21:53 -0500] "HEAD /install/sles12.1/ppc64le/1/repodata/repomd.xml HTTP/1.1" 404 - "-" "ZYpp 15.19.2 (curl 7.37.0)"
``````
are those messages mean add-on product failed to install?

**Comment by daniceexi** [comment] 2016-01-21 01:33
@cxhong From the doc of sles: http://doc.opensuse.org/documentation/html/openSUSE_114/opensuse-reference/cha.add-ons.html
Looks like the addon packages mostly are not in the install iso that user need to select them from cd, or usb media. I don't think we have add_on_products.* dir or file in the install iso, if so, that's the correct action that no add_on will be installed.

**Comment by tingtli** [comment] 2016-04-29 06:38
i think autotest cover this test.  @caomengmeng , please confirm. Thank!

**Comment by caomengmeng** [comment] 2016-04-29 06:41
Yes, we run this diskful installation on p8le kvm in daily regression, and it works well.
So close this issue.

**Closed by caomengmeng** 2016-04-29 06:41 UTC
Labels: priority:normal, type:bug
