### ISSUE TITLE
discoverydata  method incorrectly set to `undef` after MTMS discovery

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#3901] opened 2017-09-12 08:59 UTC
xCAT details:
```
[samveen@xcatmn ~]$ lsxcatd -t
This is a Management Node
[samveen@xcatmn ~]$ lsxcatd -v
Version 2.13.6 (git commit 0ee33b536bc3c95e7537e8fb097c9ee43e34d0f9, built Tue Aug  8 07:15:43 EDT 2017)
```

I'm in the process of doing discovery for a 100 odd servers in our new DC using MTMS. During discovery, half the servers correctly get the discovery method as MTMS, however the other half get the discovery method reset back to `undef`:
```
[samveen@xcatmn ~]$ nodediscoverls |grep -v METHOD |wc -l
21
[samveen@xcatmn ~]$ nodediscoverls |grep undef |wc -l
11
[samveen@xcatmn ~]$ nodediscoverls |grep mtms |wc -l
10
```

Details and logs of one such node: 
```
[samveen@xcatmn ~]$ nodediscoverls |grep undef |head -n1 
  00000000-0000-0000-0000-AC1F6B09E568    vndc-srv-01106      undef          Supermicro:PIO-128U-E1CR-TS018A282135X7716208
[samveen@xcatmn ~]$ lsdef vndc-srv-01106 -i chain
Object name: vndc-srv-01106
    chain=runcmd=bmcsetup,runimage=http://10.209.110.110/install/custom/runimage/d42_s_level_Discovered.tgz,runimage=http://10.209.110.110/install/custom/runimage/glpi_update.tgz,standby,shell
[samveen@xcatmn ~]$ sudo journalctl -u xcatd |egrep '00000000-0000-0000-0000-AC1F6B09E568|vndc-srv-01106|Supermicro:PIO-128U-E1CR-TS018\*A282135X7716208'
Sep 12 07:40:01 xcatmn.vndc xcat[4760]: xCAT: Allowing chdef -t node -o vndc-srv-01106 serial=A282135X7716208 ip=10.209.120.22 mtm=Supermicro:PIO-128U-E1CR-TS018 height=1 unit=21 rack=G11 groups=all,compute,testing,supermicro mgt=ipmi bmc=10.223.121.22 for xcatws from localhost 
Sep 12 07:40:01 xcatmn.vndc xcat[4763]: xCAT: Allowing makehosts to vndc-srv-01106 for xcatws from localhost 
Sep 12 07:40:02 xcatmn.vndc xcat[4766]: xCAT: Allowing rsetboot to vndc-srv-01106 net for xcatws from localhost 
Sep 12 08:38:25 xcatmn.vndc xcat[3724]: xcat.discovery.aaadiscovery: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Got a discovery request, attempting to discover the node...
Sep 12 08:38:25 xcatmn.vndc xcat[3724]: xcat.discovery.blade: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Warning: Could not find any nodes using blade-based discovery
Sep 12 08:38:25 xcatmn.vndc xcat[3724]: xcat.discovery.switch: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Warning: Could not find any nodes using switch-based discovery 
Sep 12 08:38:25 xcatmn.vndc xcat[3724]: xcat.discovery.mtms: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Found node: vndc-srv-01106
Sep 12 08:38:27 xcatmn.vndc xcat[3724]: xcat.discovery.nodediscover: vndc-srv-01106 has been discovered
Sep 12 08:38:27 xcatmn.vndc xcat[3724]: xcat.discovery.zzzdiscovery: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Successfully discovered the node using mtms discovery method.
Sep 12 08:38:42 xcatmn.vndc xcat[13413]: xCAT: Allowing getcredentials x509cert from vndc-srv-01106
Sep 12 08:38:43 xcatmn.vndc xcat[13478]: xCAT: Allowing nextdestiny from vndc-srv-01106
Sep 12 08:38:44 xcatmn.vndc xcat[3724]: xcat.discovery.aaadiscovery: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Got a discovery request, attempting to discover the node...
Sep 12 08:38:44 xcatmn.vndc xcat[3724]: xcat.discovery.blade: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Warning: Could not find any nodes using blade-based discovery 
Sep 12 08:38:44 xcatmn.vndc xcat[3724]: xcat.discovery.switch: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Warning: Could not find any nodes using switch-based discovery 
Sep 12 08:38:44 xcatmn.vndc xcat[3724]: xcat.discovery.mtms: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Found node: vndc-srv-01106
Sep 12 08:38:45 xcatmn.vndc xcat[3724]: xcat.discovery.nodediscover: Failed to notify 10.209.120.220 that it's actually vndc-srv-01106.
Sep 12 08:38:45 xcatmn.vndc xcat[3724]: xcat.discovery.zzzdiscovery: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Successfully discovered the node using mtms discovery method.
Sep 12 08:38:48 xcatmn.vndc xcat[14015]: xCAT: Allowing getbmcconfig from vndc-srv-01106
Sep 12 08:39:02 xcatmn.vndc xcat[3724]: xcat.discovery.aaadiscovery: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Got a discovery request, attempting to discover the node...
Sep 12 08:39:02 xcatmn.vndc xcat[3724]: xcat.discovery.blade: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Warning: Could not find any nodes using blade-based discovery 
Sep 12 08:39:02 xcatmn.vndc xcat[3724]: xcat.discovery.switch: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Warning: Could not find any nodes using switch-based discovery 
Sep 12 08:39:02 xcatmn.vndc xcat[3724]: xcat.discovery.mtms: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Found node: vndc-srv-01106
Sep 12 08:39:03 xcatmn.vndc xcat[3724]: xcat.discovery.nodediscover: Failed to notify 10.209.120.220 that it's actually vndc-srv-01106.
Sep 12 08:39:03 xcatmn.vndc xcat[3724]: xcat.discovery.zzzdiscovery: (Supermicro:PIO-128U-E1CR-TS018*A282135X7716208) Successfully discovered the node using mtms discovery method.
Sep 12 08:39:38 xcatmn.vndc xcat[3723]: vndc-srv-01106 status: bmcready statustime: 09-12-2017 08:39:38
Sep 12 08:39:38 xcatmn.vndc xcat[16951]: xCAT: Allowing nextdestiny from vndc-srv-01106
Sep 12 08:39:39 xcatmn.vndc xcat[17131]: xCAT: Allowing nextdestiny from vndc-srv-01106
Sep 12 08:39:45 xcatmn.vndc xcat[17467]: xCAT: Allowing getbmcconfig from vndc-srv-01106
Sep 12 08:40:05 xcatmn.vndc xcat[3723]: vndc-srv-01106 status: bmcready statustime: 09-12-2017 08:40:05
Sep 12 08:40:05 xcatmn.vndc xcat[18230]: xCAT: Allowing nextdestiny from vndc-srv-01106
Sep 12 08:40:06 xcatmn.vndc xcat[18379]: xCAT: Allowing nextdestiny from vndc-srv-01106
Sep 12 08:41:07 xcatmn.vndc xcat[19112]: vndc-srv-01106 status: standingby statustime: 09-12-2017 08:41:07
Sep 12 08:41:50 xcatmn.vndc xcat[19155]: vndc-srv-01106 status: standingby statustime: 09-12-2017 08:41:50
Sep 12 08:43:08 xcatmn.vndc xcat[19265]: vndc-srv-01106 status: standingby statustime: 09-12-2017 08:43:08
```
As you can see that the discovery process completed successfully, followed by discovery requests multiple times, which seems to reset `discoverydata.method` back to undef. 

Maybe a queuing system is needed for discovery 😆 ?

**Comment by immarvin** [comment] 2017-09-12 09:13
duplicate with https://github.com/xcat2/xcat-core/issues/3408?

**Comment by samveen** [comment] 2017-09-12 09:19
@immarvin Solution for #3408 is #3601 which is part of the `2.13.6` tag, yet the bug is still there. If a duplicate, then #3601 doesn't solve the problem.

**Comment by immarvin** [comment] 2017-09-12 10:01
hi @samveen , the PR https://github.com/xcat2/xcat-core/pull/3694 is merged after Aug  8 07:15:43

````
commit fc07c02e7403d30a7ab6218da539faa0bc2d08b4
Merge: c798d4d02 39c4e7081
Author: zet809 <ertaozh@cn.ibm.com>
Date:   Thu Aug 17 16:43:55 2017 +0800

    Merge pull request #3694 from immarvin/ondiscovery

    fix issue xCAT install failed on sles11.4 & rhels6.9 in automation #3693;move send_tcp_msg from Utils.pm to NetworkUtils.pm

````

**Comment by immarvin** [comment] 2017-09-12 10:11
so please try the latest build if convenient

**Comment by samveen** [comment] 2017-09-12 10:14
@immarvin that is my production environment, so I cannot update to anything other than stable upstream releases, unfortunately.

**Comment by immarvin** [comment] 2017-09-12 10:31
is it possible to port the related files to the env?

**Comment by samveen** [comment] 2017-09-13 02:58
@immarvin I'll try cherry-picking that commit against the `2.13.6` tag, and check if it integrates successfully. If so onlyt then will I be able to port it.

**Comment by samveen** [comment] 2017-09-13 03:06
@immarvin The cherrypick failed against the 2.13.6 tag, so I cannot port the files easily to my environment. Looks like I'll need to `chtab` the `discoverydata.method` to the correct value till the `2.13.7` release.

**Comment by immarvin** [comment] 2017-10-23 03:33
close this ticker first, please reopen this if the issue is still in your env

**Comment by samveen** [comment] 2017-10-23 12:27
@immarvin Apologies on the late reply. `xCAT-2.13.7` fixed this issue. Can you add this to the `2.13.7` milestone?

**Closed** 2017-10-24 03:11 UTC

**Comment by samveen** [comment] 2017-10-24 07:43
@immarvin The milestone is still not set 🤣
