### ISSUE TITLE
[FVT] File 98-mlx.rules in package xcat-genesis-scripts conflict with the same file in package xcat-genesis-base

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1025] opened 2016-05-04 02:12 UTC
env: rh7.2 (x86_64,ppc64),ubuntu14.04.4 x86_64
build:latest build
How to reproduce:
```
================================================================================
Install  2 Packages (+105 Dependent packages)

Total download size: 73 M
Installed size: 293 M
Downloading packages:
warning: /xcat-dep/rh5/ppc64/conserver-xcat-8.1.16-10.ppc64.rpm: Header V4 DSA/SHA1 Signature, key ID c6565bc9: NOKEY
Public key for conserver-xcat-8.1.16-10.ppc64.rpm is not installed
Public key for perl-xCAT-2.12-snap201605030930.noarch.rpm is not installed
--------------------------------------------------------------------------------
Total                                               32 MB/s |  73 MB  00:02
Retrieving key from file:///xcat-dep/rh7/ppc64/repodata/repomd.xml.key
Importing GPG key 0xC6565BC9:
 Userid     : "xCAT Security Key <xcat@cn.ibm.com>"
 Fingerprint: f75b 1bf6 78b6 44fd f3aa cfc8 60a3 e9ac c656 5bc9
 From       : /xcat-dep/rh7/ppc64/repodata/repomd.xml.key
Running transaction check
Running transaction test


Transaction check error:
  file /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/etc/udev/rules.d/98-mlx.rules conflicts between attempted installs of xCAT-genesis-scripts-ppc64-1:2.12-snap201605030931.noarch and xCAT-genesis-base-ppc64-1:2.11-snap201511160819.noarch
  file /opt/xcat/share/xcat/netboot/genesis/ppc64/fs/sbin/loadmlxeth conflicts between attempted installs of xCAT-genesis-scripts-ppc64-1:2.12-snap201605030931.noarch and xCAT-genesis-base-ppc64-1:2.11-snap201511160819.noarch

Error Summary
-------------

```

**Comment by junxiawang** [comment] 2016-05-04 02:21
in x86_64 install_xcat.log:
```
Install  2 Packages (+110 Dependent packages)

Total download size: 64 M
Installed size: 190 M
Downloading packages:
warning: /xcat-dep/rh5/x86_64/conserver-xcat-8.1.16-10.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID c6565bc9: NOKEY
Public key for conserver-xcat-8.1.16-10.x86_64.rpm is not installed
Public key for perl-xCAT-2.12-snap201605030930.noarch.rpm is not installed
--------------------------------------------------------------------------------
Total                                               17 MB/s |  64 MB  00:03
Retrieving key from file:///xcat-dep/rh7/x86_64/repodata/repomd.xml.key
Importing GPG key 0xC6565BC9:
 Userid     : "xCAT Security Key <xcat@cn.ibm.com>"
 Fingerprint: f75b 1bf6 78b6 44fd f3aa cfc8 60a3 e9ac c656 5bc9
 From       : /xcat-dep/rh7/x86_64/repodata/repomd.xml.key
Running transaction check
Running transaction test


Transaction check error:
  file /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/etc/udev/rules.d/98-mlx.rules conflicts between attempted installs of xCAT-genesis-scripts-x86_64-1:2.12-snap201605030931.noarch and xCAT-genesis-base-x86_64-1:2.9-snap201504212134.noarch
  file /opt/xcat/share/xcat/netboot/genesis/x86_64/fs/sbin/loadmlxeth conflicts between attempted installs of xCAT-genesis-scripts-x86_64-1:2.12-snap201605030931.noarch and xCAT-genesis-base-x86_64-1:2.9-snap201504212134.noarch

Error Summary
-------------

```

**Comment by junxiawang** [comment] 2016-05-04 03:20
x86_64 ubuntu install_xcat.log:
```
dpkg: error processing archive /xcat-core/pool/main/x/xcat-genesis-scripts/xcat-genesis-scripts_2.12-snap201605030931_amd64.deb (--unpack):
 trying to overwrite '/opt/xcat/share/xcat/netboot/genesis/x86_64/fs/etc/udev/rules.d/98-mlx.rules', which is also in package xcat-genesis-base-amd64 2.9-snap201503230106
Selecting previously unselected package xcat-buildkit.
Preparing to unpack .../xcat-buildkit_2.12-snap201605030931_all.deb ...
Unpacking xcat-buildkit (2.12-snap201605030931) ...
Selecting previously unselected package xcat.
Preparing to unpack .../xcat_2.12-snap201605030931_amd64.deb ...
Unpacking xcat (2.12-snap201605030931) ...
Selecting previously unselected package xcat-test.
Preparing to unpack .../xcat-test_2.12-snap201605030931_all.deb ...
Unpacking xcat-test (2.12-snap201605030931) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for ufw (0.34~rc-0ubuntu2) ...
Processing triggers for install-info (5.2.0.dfsg.1-2) ...
Errors were encountered while processing:
 /xcat-core/pool/main/x/xcat-genesis-scripts/xcat-genesis-scripts_2.12-snap201605030931_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

**Comment by neo954** [comment] 2016-05-04 04:30
I saw the same problem on ppc64el. 

<tt>dpkg: error processing archive /install/xcat/xcat-core/pool/main/x/xcat-genesis-scripts/xcat-genesis-scripts_2.12-snap201605030931_ppc64el.deb (--unpack):
 trying to overwrite '<b>/opt/xcat/share/xcat/netboot/genesis/ppc64/fs/etc/udev/rules.d/98-mlx.rules</b>', which is also in package xcat-genesis-base-ppc64 2.11-snap201511160819</tt>

The problem is due to file conflict.
See the original output below.

    Unpacking perl-xcat (2.12-snap201605030931) over (2.12-snap201604250931) ...
    Reloading xcatd  *
    Preparing to unpack .../xcat-client_2.12-snap201605030931_all.deb ...
    Unpacking xcat-client (2.12-snap201605030931) over (2.12-snap201604250931) ...
    Preparing to unpack .../xcat-server_2.12-snap201605030931_all.deb ...
    Unpacking xcat-server (2.12-snap201605030931) over (2.12-snap201604250931) ...
    Preparing to unpack .../xcat-genesis-scripts_2.12-snap201605030931_ppc64el.deb ...
    Unpacking xcat-genesis-scripts (2.12-snap201605030931) over (2.12-snap201604250931) ...
    dpkg: error processing archive /install/xcat/xcat-core/pool/main/x/xcat-genesis-scripts/xcat-genesis-scripts_2.12-snap201605030931_ppc64el.deb (--unpack):
     trying to overwrite '/opt/xcat/share/xcat/netboot/genesis/ppc64/fs/etc/udev/rules.d/98-mlx.rules', which is also in package xcat-genesis-base-ppc64 2.11-snap201511160819
    Preparing to unpack .../xcat-buildkit_2.12-snap201605030931_all.deb ...
    Unpacking xcat-buildkit (2.12-snap201605030931) over (2.12-snap201604250931) ...
    Preparing to unpack .../xcat_2.12-snap201605030931_ppc64el.deb ...
    Unpacking xcat (2.12-snap201605030931) over (2.12-snap201604250931) ...
    Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
    Processing triggers for ureadahead (0.100.0-16) ...
    Errors were encountered while processing:
     /install/xcat/xcat-core/pool/main/x/xcat-genesis-scripts/xcat-genesis-scripts_2.12-snap201605030931_ppc64el.deb

**Comment by neo954** [comment] 2016-05-04 04:41
The problem is due to pull request #1019.

**Comment by neo954** [comment] 2016-05-04 04:54
I did a quick search in the source code,

    $ find . -name 98-mlx.rules -print
    ./xCAT-genesis-builder/98-mlx.rules
    ./xCAT-genesis-scripts/etc/udev/rules.d/98-mlx.rules
    ./xCAT-nbroot2/98-mlx.rules

We need to do something to avoid file conflict.

    $ find . -name 98-mlx.rules -print | xargs head -n 999
    ==> ./xCAT-genesis-builder/98-mlx.rules <==
    SUBSYSTEM=="pci", ATTRS{subsystem_vendor}=="0x15b3", ATTRS{class}=="0x020000", RUN+="/sbin/loadmlxeth"

    ==> ./xCAT-genesis-scripts/etc/udev/rules.d/98-mlx.rules <==
    SUBSYSTEM=="pci", ATTRS{subsystem_vendor}=="15b3", ATTRS{subsystem_device}=="4010", RUN+="/sbin/loadmlxeth"

    ==> ./xCAT-nbroot2/98-mlx.rules <==
    SUBSYSTEM=="pci", ATTRS{subsystem_vendor}=="0x15b3", ATTRS{class}=="0x020000", RUN+="/sbin/loadmlxeth"

**Comment by daniceexi** [comment] 2016-05-04 08:29
I reverted the issue #1019.

If we want to put the files in genesis-script, they should be removed from genesis-base first.

And I am also a little concern for Jarrod's fix, is the changed file common to replace the default one?

**Comment by daniceexi** [comment] 2016-05-04 09:35
I created a pull request #1034 to remove the mlx files which added by Jarrod. After we fixed the issue in genesis-base, the pull request can be revert to take back the files.

**Comment by whowutwut** [comment] 2016-05-04 10:22
@daniceexi  Right, we can't provide the same two files in different rpms because they will conflict.... @gurevichmark FYI.  So the concept of having xCA-genesis-scripts should not be able to overwrite the base.   So we should probably look at how we can redesign this.  I don't think the best solution is to manually build xCAT-genesis-base and ship with xcat-deps.  This causes the build to be too manual whenever we make any changes to xCAT-genesis-scripts

**Comment by daniceexi** [comment] 2016-05-04 11:23
Right, so we should remove the xCAT added files from genesis-base and add them to genesis-script.

**Comment by whowutwut** [comment] 2016-05-05 23:53
Set this to pending and closing this since @daniceexi resolved the RPM conflict by pulling out some of the commits.

**Closed by whowutwut** 2016-05-05 23:53 UTC
Labels: component:infiniband, component:packaging, priority:high, status:pending, type:bug
