### ISSUE TITLE
［Customer］[LS] No login prompt for rcons provisioning with local repo on Ubuntu 14.04.2 PowerNV

### ISSUE THREAD

**Issue by lcham** [xcat2/xcat-core#138] opened 2015-08-31 21:21 UTC
Following the xCAT installation procedures, rcons will not show login prompt after OS provisioning with local repo mirror on Ubuntu 14.04.2 PowerNV systems.
This issue was found by Jack (Xiao Guang) Liu.

**Comment by daniceexi** [comment] 2015-09-01 01:06
@zet809 knows this issue. It might be an issue of OS itself.

**Comment by zet809** [comment] 2015-09-01 05:27
The cause is that the console starting process is break by updating pkg bistro or installing some new pkgs after node reboot.
To workaround this issue, the simplest method is reboot the node.
Or we need ubuntu developers to help to find out how is the process break.

**Comment by daniceexi** [comment] 2015-09-01 05:42
@zet809 Did you open bug to Ubuntu?

**Comment by zet809** [comment] 2015-09-10 07:10
For the pkgs that are included in on-line or local(copied from on-line mirror) ubuntu mirror, we suggest to put them into pkglist other than otherpkglist, and add the mirror for pkgdir not otherpkgdir. Pls try again with the modification I mentioned and let me know the result.

**Comment by zet809** [comment] 2015-10-22 07:36
Open a defect to LTC (build-ubunturepo) to get the formal answer.

**Comment by zet809** [comment] 2015-11-09 07:43
Move to 2.12.

**Comment by whowutwut** [comment] 2015-11-09 12:58
@lcham  Is this related to the problem you were mentioning where the Ubuntu kernel updates to 14.04.3 version automatically?   @neo954 , can you tell Linda how to stay at the 14.04.2 version when doing an update, what we discussed on the call.

**Comment by lcham** [comment] 2015-11-09 13:59
@whowutwut Correct.  This is when the base is at 14.04.2 and the repo mirror update will move it up to 14.04.3.

**Comment by tingtli** [comment] 2016-03-23 03:25
@zet809 do we get the formal answer for the bugzilla defect 132141?

**Comment by zet809** [comment] 2016-04-11 09:11
@tingtli Will you pls verify updating 14.04.2 to 14.04.3, and 14.04.3 to 14.04.4. Thx!

**Comment by daniceexi** [comment] 2016-04-12 02:43
@zet809 @gurevichmark also saw this issue for Ubuntu 16.04, What was the response from LTC?

**Comment by gurevichmark** [comment] 2016-04-12 17:11
For me, with Ubuntu 14.04, I get the prompt with rcons, but with Ubuntu 15.04, 15.10 and 16.04, I do not get a prompt.

**Comment by daniceexi** [comment] 2016-05-05 09:22
@junxiawang Could you verify the 14.04.4 and 16.04 against ppc64le and x86_64?

**Comment by daniceexi** [comment] 2016-05-06 09:39
@junxiawang has verified the 14.04.4 on ppc64le and x86_64, no problem was found. She will verify the 16.04 later.

**Comment by daniceexi** [comment] 2016-05-16 03:13
@junxiawang has verified this issue for 16.04 on ppc64le and x86_64, could not recreate it. So close it now. 

For @gurevichmark 's finding that could not get the promote might be caused by the console issue #731. @junxiawang said if applying the workaround in #731, then the rcons worked well for 16.04.

**Closed by daniceexi** 2016-05-16 03:13 UTC
Labels: priority:normal, type:bug
