### ISSUE TITLE
mkdef fails to create osimage definition when a "." is in the image name

### ISSUE THREAD

**Issue by ceckhoff** [xcat2/xcat-core#2549] opened 2017-02-24 03:33 UTC
Currently unable to create any osimage definition that contains a "." in the object type name.  This was not an issue in earlier releases but now can not import or create new deifintions that matches object types that are used by the copycds command.

root@xcat ~]# cat rhels6.8-rescue 
# <xCAT data object stanza file>

rhels6.8-rescue:
    objtype=osimage
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.exlist
    imagetype=linux
    osarch=x86_64
    osdistroname=rhels6.8-x86_64
    osname=Linux
    osvers=rhels6.8
    otherpkgdir=/install/post/otherpkgs/rhels6.8/x86_64
    pkgdir=/install/rhels6.8/x86_64
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels6.8/x86_64/compute
[root@xcat ~]# cat rhels6.8-rescue |mkdef -z
Error: The object name 'rhels6.8-rescue' is invalid, please refer to "man xcatdb" for the valid "xCAT Object Name Format"
[root@xcat ~]# vi rhels6.8-rescue 
[root@xcat ~]# cat rhels6.8-rescue 
# <xCAT data object stanza file>

rhels6_8-rescue:
    objtype=osimage
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.exlist
    imagetype=linux
    osarch=x86_64
    osdistroname=rhels6.8-x86_64
    osname=Linux
    osvers=rhels6.8
    otherpkgdir=/install/post/otherpkgs/rhels6.8/x86_64
    pkgdir=/install/rhels6.8/x86_64
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels6.8/x86_64/compute
[root@xcat ~]# cat rhels6.8-rescue |mkdef -z
1 object definitions have been created or modified.
lsdef -v
lsdef - Version 2.12.4 (git commit 64ec2d41285d9a8770d8d9ef909f251ecbb5100b, built Thu Nov 10 23:59:02 EST 2016)

Unable to create new osimage definition based upon names created by copycds that includes "."
 [root@xcat ~]# lsdef -t osimage
rhels6.8-x86_64-install-compute  (osimage)
rhels6.8-x86_64-install-service  (osimage)
rhels6.8-x86_64-netboot-compute  (osimage)
rhels6.8-x86_64-stateful-mgmtnode  (osimage)
rhels6_8-rescue  (osimage)  "This name should be rhels6.8-rescue for consistency"

**Comment by immarvin** [comment] 2017-02-24 03:51
seems duplicate with https://github.com/xcat2/xcat-core/issues/2131

**Comment by immarvin** [comment] 2017-02-27 09:01
hi @tingtli , https://github.com/xcat2/xcat-core/issues/2131 shows that this issue has been fixed in 2.12.4, but seems @ceckhoff mentioned this issue still exists in 2.12.4, can someone in FVT try to recreate this in our environment? thanks

**Comment by whowutwut** [comment] 2017-02-27 23:50
It looks like that issue was closed without any comment showing that the fix was validated and working.  @tingtli @daniceexi  I think we should try and enforce this instead of just simply closing without any comment, at least a comment should be added.

**Comment by tingtli** [comment] 2017-02-28 07:02
@whowutwut  Yes, i agree. We asked the one who verified should paste the verification steps and paste out the proof that the bugs are fixed.

**Comment by tingtli** [comment] 2017-02-28 07:11
@immarvin  I could recreate the issue on 2.12.4. Here is the environment
```
[root@c910f02c02p12 ~]# cat /rhels6.8-rescue
rhels6.8-rescue:
objtype=osimage
exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.exlist
imagetype=linux
osarch=x86_64
osdistroname=rhels6.8-x86_64
osname=Linux
osvers=rhels6.8
otherpkgdir=/install/post/otherpkgs/rhels6.8/x86_64
pkgdir=/install/rhels6.8/x86_64
pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.pkglist
postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.postinstall
profile=compute
provmethod=netboot
rootimgdir=/install/netboot/rhels6.8/x86_64/compute

[root@c910f02c02p12 ~]# cat /rhels6.8-rescue |mkdef -z
Error: The object name 'rhels6.8-rescue' is invalid, please refer to "man xcatdb" for the valid "xCAT Object Name Format"

```
But for bug #2131. Seems it is fixed on the same code. So, i guess the root cause is not the same. 
```
[root@c910f02c02p12 ~]# mkdef -t osimage -o sles12.1-x86_64-statelite-compute -u profile=compute provmethod=statelite osvers=sles12.1
1 object definitions have been created or modified.
[root@c910f02c02p12 ~]# lsdef -t osimage -o sles12.1-x86_64-statelite-compute
Object name: sles12.1-x86_64-statelite-compute
    exlist=/opt/xcat/share/xcat/netboot/sles/compute.exlist
    imagetype=linux
    osarch=ppc64
    osdistroname=sles12.1-ppc64
    osname=Linux
    osvers=sles12.1
    otherpkgdir=/install/post/otherpkgs/sles12.1/ppc64
    pkgdir=/install/sles12.1/ppc64
    pkglist=/opt/xcat/share/xcat/netboot/sles/compute.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/sles/compute.postinstall
    profile=compute
    provmethod=statelite
    rootimgdir=/install/netboot/sles12.1/ppc64/compute
```

**Comment by immarvin** [comment] 2017-03-03 09:23
hi @whowutwut , @ceckhoff , this issue has been fixed in 2.13 in PR https://github.com/xcat2/xcat-core/pull/2160/files , the fix is not in 2.12.4 yet. 

do we need to cherry-pick the fix to 2.12 branch? is there any plan to release new 2.12.x release? what do you think? @whowutwut

**Comment by immarvin** [comment] 2017-03-03 09:24
the commit hash is b0791921bb0b07cef558a55fe10618cca5d9cb15

**Comment by zet809** [comment] 2017-04-05 06:09
hi, @hu-weihua , will you pls have someone verify this defect? Thx!

**Comment by hu-weihua** [comment] 2017-04-06 01:57
@tingtli could you help to verify this fix? thanks

**Comment by tingtli** [comment] 2017-04-06 07:31
i have verified this.
```
[root@c910f02c01p13 /]# lsxcatd -v
Version 2.13.3 (git commit 84a3758090cd97253319348dd8ce0887e42e4d17, built Thu Mar 30 22:15:38 EDT 2017)

[root@c910f02c01p13 /]# cat rhels6.8-rescue
rhels6.8-rescue:
objtype=osimage
exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.exlist
imagetype=linux
osarch=x86_64
osdistroname=rhels6.8-x86_64
osname=Linux
osvers=rhels6.8
otherpkgdir=/install/post/otherpkgs/rhels6.8/x86_64
pkgdir=/install/rhels6.8/x86_64
pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.pkglist
postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.postinstall
profile=compute
provmethod=netboot
rootimgdir=/install/netboot/rhels6.8/x86_64/compute
[root@c910f02c01p13 /]# cat rhels6.8-rescue |mkdef -z
[root@c910f02c01p13 /]# lsdef -t osimage -o rhels6.8-rescue
Object name: rhels6.8-rescue
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.exlist
    imagetype=linux
    osarch=x86_64
    osdistroname=rhels6.8-x86_64
    osname=Linux
    osvers=rhels6.8
    otherpkgdir=/install/post/otherpkgs/rhels6.8/x86_64
    pkgdir=/install/rhels6.8/x86_64
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels6.x86_64.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels6.8/x86_64/compute
```

**Closed by tingtli** 2017-04-06 07:31 UTC
Labels: component:obj_db_cmds, component:test, priority:high, status:pending, type:bug
