### ISSUE TITLE
Add check for xCAT-genesis based on Fedora 26 in "xcatprobe xcatmn"

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3526] opened 2017-07-21 17:52 UTC
While we figure out the details about how to incorporate a new xCAT-genesis base....  One way to ensure we have the correct xCAT-genesis base is to add a check to xcatprobe....

Use Case: 

If running on RHEL 7.4 OS, when we run `xcatprobe xcatmn`, print an error if the xCAT-genesis base for ppc64le is NOT at the Fedora 26 beta level.

**Comment by whowutwut** [comment] 2017-07-21 17:54
@gurevichmark If you have some time to quickly implement this, feel free to take it...  

@zet809 FYI. 

The files are here:  http://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/
```
  | xCAT-genesis-base-ppc64-2.13.5-snap201706220300.noarch.rpm | 2017-06-22 01:15 | 51M |  
-- | -- | -- | -- | --
  | xCAT-genesis-base-ppc64-2.13.6-snap201707120359.noarch.rpm | 2017-07-12 02:31 | 47M |  
  | xCAT-genesis-base-ppc64-2.13.6-snap201707190550.noarch.rpm | 2017-07-20 01:29 | 47M |  
```
Problem here is that we can't tell from the name..... investigating...

**Comment by whowutwut** [comment] 2017-07-21 17:56
No way to tell from query...
```
[vhu@victorvm7 Downloads]$ rpm -qip ./xCAT-genesis-base-ppc64-2.13.6-snap201707190550.noarch.rpm 
Name        : xCAT-genesis-base-ppc64
Epoch       : 2
Version     : 2.13.6
Release     : snap201707190550
Architecture: noarch
Install Date: (not installed)
Group       : System/Utilities
Size        : 196367729
License     : Various (see individual packages for details)
Signature   : (none)
Source RPM  : xCAT-genesis-base-ppc64-2.13.6-snap201707190550.src.rpm
Build Date  : Wed 19 Jul 2017 05:50:56 AM EDT
Build Host  : c910f03c05k03.pok.stglabs.ibm.com
Relocations : /opt/xcat 
Packager    : IBM Corp.
Vendor      : IBM Corp.
URL         : https://xcat.org/
Summary     : xCAT Genesis netboot image
Description :
xCAT genesis (Genesis Enhanced Netboot Environment for System Information and Servicing) is a small, embedded-like environment for xCAT's use in discovery and management actions when interaction with an OS is infeasible.
This package comprises the base platform with most of the xCAT specific behavior left to xCAT-genesis-scripts package.
```

**Comment by daniceexi** [comment] 2017-07-23 14:03
I am a little concern of check the version of genesis base on the version of the OS of xCAT MN. xCAT genesis is used for CN.

**Comment by whowutwut** [comment] 2017-07-23 15:49
Isn't the purpose of the probe to try to determine problem in configuration? It can be a warning instead of error..... We can also lump together multiple checks before we come up with the conclusion for the probe check 

Another one is to look for openbmc mgt defined in the compute nodes.  This means at least p9 or newer.   But none of this is fool proof because if no compute nodes are defined yet, we cannot tell... 

This issues is opened because I'm not yet sure if we should change the genesis base to be official in 2.13.6... since it's missing some drivers. But we need fedora26 for p9 discovery....so if some installation error or didn't update to the beta genesis. We will have problems...

**Comment by daniceexi** [comment] 2017-07-24 01:18
I understand your points. And I agree we must do something to reduce the potential error especially that caused by the configuration error. This is why we added the story to precheck the configuration of discovery base on the failures that we encountered or customer's.

**Comment by samveen** [comment] 2017-07-24 04:06
Maybe add in a check against the rpm macro `%dist` ?

**Comment by whowutwut** [comment] 2017-07-26 15:49
@samveen  Thanks! let me try that out... or @zet809  can you try it out if i can't get to it today... 

@cxhong  hit this problem when running through the E2E and the result is that the naming of the devices in `lspci` and genesis discovery won't match RHEL 7.4 ...

**Comment by whowutwut** [comment] 2017-07-28 01:48
Trying on a spec file:
```
[vhu@victorvm7 xcat-core]$ git diff xCAT-vlan/xCAT-vlan.spec
diff --git a/xCAT-vlan/xCAT-vlan.spec b/xCAT-vlan/xCAT-vlan.spec
index 487dbcb..919789a 100755
--- a/xCAT-vlan/xCAT-vlan.spec
+++ b/xCAT-vlan/xCAT-vlan.spec
@@ -21,6 +21,8 @@ Requires: xCAT-client = 4:%{version}-%{release}
 %description
 xCAT-vlan provides the xCAT vlan confiuration.
 
+Built in environment "%dist" on %{_arch}
+
 %prep
 %setup -q -n xCAT-vlan
 %build
```

Results in: 
```
[vhu@victorvm7 xcat-core]$ rpm -qip /home/vhu/rpmbuild/RPMS/noarch/xCAT-vlan-2.13.6-snap000000000000.noarch.rpm  | grep Built
Built in environment ".el7" on x86_64
```


This is on RHEL 7.0 x86_64.. so doesn't really have the effect that we want...  @zet809 can you ping me your fedora26 build machine?

**Comment by zet809** [comment] 2017-07-28 06:36
Hi, @whowutwut , the build server for Fedora 26 is 10.3.5.3
I had added the info above to the xCAT-genesis-base.spec file within PR #3514 
The rpm information looks like this right now:
```
# rpm -qpi xCAT-genesis-base-ppc64-2.13.6-snap201707280206.noarch.rpm
Name        : xCAT-genesis-base-ppc64
Epoch       : 2
Version     : 2.13.6
Release     : snap201707280206
Architecture: noarch
Install Date: (not installed)
Group       : System/Utilities
Size        : 196367729
License     : Various (see individual packages for details)
Signature   : (none)
Source RPM  : xCAT-genesis-base-ppc64-2.13.6-snap201707280206.src.rpm
Build Date  : Fri 28 Jul 2017 02:06:19 AM EDT
Build Host  : c910f03c05k03.pok.stglabs.ibm.com
Relocations : /opt/xcat
Packager    : IBM Corp.
Vendor      : IBM Corp.
URL         : https://xcat.org/
Summary     : xCAT Genesis netboot image
Description :
xCAT genesis (Genesis Enhanced Netboot Environment for System Information and Servicing) is a small, embedded-like environment for xCAT's use in discovery and management actions when interaction with an OS is infeasible.
This package comprises the base platform with most of the xCAT specific behavior left to xCAT-genesis-scripts package.
Built in environment ".fc26" on ppc64.
```

**Comment by zet809** [comment] 2017-07-28 07:04
Since the genesis-base will be deployed on CN, I suggest we check whether genesis-base is based on Fedora 26 in `xcatprobe discovery` subcommand. What is your idea?
Task #3554 planed to include this checking.

**Comment by zet809** [comment] 2017-08-04 09:58
The `xcatprobe discovery` have include the verification about genesis-base, so I plan to close this issue.

**Closed by zet809** 2017-08-04 09:58 UTC
