### ISSUE TITLE
[DEV] "virsh dumpxml <kvm node>" failed to pass "virt-xml-validate" checking

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#560] opened 2015-12-28 09:06 UTC
this is reported by customer.

xCAT provides an interface for running virtual machines.  We do the basics for managing the VM, like create the VM definition, power on/off the VM, switch VMs to run on different hosts. etc... 
Under the covers we are making calls to the libvirt API.  libvirt is the virtualization API. The virt-xml-validate (http://linux.die.net/man/1/virt-xml-validate) is a command that can be used to validate XML against the schema.  

XML is just a markup language used to store data. It can be in any form you want... .. 
	<id>
	    <name>tom</name>
	    <address>
	        <street> my street </street>
	       <city> my city </city>
	      <state> my state </state>
	    </address> 
	</id> 

The above is valid XML, but say I have defined a schema for the XML (some format that I require if you want to pass XML to my program..)  and i require the zip code to be part of the address. 
 I can create a schema file and users can run their xml code against my schema as validation to see whether the XML they wrote can be used with my program.  
This is a very high level example, but essentially that's the concept behind validating XML.   You can search "XML validation" and find articles that describe this process. virt-xml-validate is just a tool that is provided to validate XML for the VMs.

So when you say documentation, you are referring to xCAT documentation, correct?  Up until now, we just test that VMs support under xCAT works well.  It's not in our process to document all the management utilities that libvirt provides to the user...  So yes, there is no documentation about running virt-xml-validate...  but that doesn't mean that it's a user error. They are allowed to run any libvirt command they want.  Are we chasing a non problem?   I don't know.   I guess this is what we are trying to figure out. 

From this page: http://wiki.libvirt.org/page/Common_XML_errors , Under Validating XML against libvirt schemas, 
It says: 
If that passes then chances are that libvirt will understand all constructs from your XML, though that is not an absolute guarantee, for example the schemas cannot detect options which are valid only for a given hypervisor, but that should help pinpointing problems. Any XML generated by libvirt for example as a result of a virsh dump command should validate without error (and failure to do so should be reported to the developers for fixing, thanks !) 

So xml generated by "virsh dumplxml" should validate without any error, otherwise we should bring it up to libvirt :-)

**Comment by immarvin** [comment] 2015-12-29 06:57
the error is caused by 1 line in 
````
  <devices>
    <emulator>/usr/bin/qemu-kvm</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' cache='none'/>
      <source file='/var/lib/xcat/pools/4566c4e9-7296-5c82-45c0-ad8782df6c37/kvm1.sda.qcow2'>
        <seclabel model='selinux' relabel='yes'/>
      </source>
      <backingStore/>
      <target dev='sda' bus='scsi'/>
      <alias name='scsi0-0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
````
The line ``        <seclabel model='selinux' relabel='yes'/> `` failed to pass the virt-xml-validate, according to http://libvirt.org/formatdomain.html#seclabel,  
````
 With "file", "block", and "volume", one or more optional sub-elements seclabel, described below (and since 0.9.9), can be used to override the domain security labeling policy for just that source file. (NB, for "volume" type disk, seclabel is only valid when the specified storage volume is of 'file' or 'block' type). 
````

**Comment by immarvin** [comment] 2015-12-30 09:00
The problem might be a bug of virt-xml-validate that the RELAX NG schema is not compatible with libvirt tools shipped in PowerKVM, opened a defect to LTC:https://bugzilla.linux.ibm.com/show_bug.cgi?id=134403

**Comment by immarvin** [comment] 2015-12-30 09:53
The problematic line is not specified by xCAT, it's generated by virsh create/define 
opened a defect to LTC:https://bugzilla.linux.ibm.com/show_bug.cgi?id=134403

**Comment by whowutwut** [comment] 2016-04-25 15:54
@immarvin  LTC seemed to close this bug as "NOT A BUG" Should we pursue this any longer or simply close?

**Comment by immarvin** [comment] 2016-06-23 03:15
hi @whowutwut , since theI suggest to close this bug

**Comment by immarvin** [comment] 2016-07-04 07:47
hi @whowutwut , I suggest close this bug.

**Closed** 2016-08-16 00:24 UTC
Labels: priority:normal
