### ISSUE TITLE
[FVT]Failed to run rmvm when setup  SN in x86_64 for rh7.3 and rh6.8

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1958] opened 2016-10-13 03:28 UTC
Using latest daily build to install SN, when run below command, case failed.

```
RUN:if [ "x86_64" != "ppc64"  -a  "kvm" != "ipmi" ];then if [[ "dir:///var/lib/libvirt/images/" =~ "phy" ]]; then rmvm c910f04x18v03 -f -p  &&  mkvm c910f04x18v03; else rmvm c910f04x18v03 -f -p  &&  mkvm c910f04x18v03 -s 20G; fi;fi

[if [ "x86_64" != "ppc64"  -a  "kvm" != "ipmi" ];then if [[ "dir:///var/lib/libvirt/images/" =~ "phy" ]]; then rmvm c910f04x18v03 -f -p  &&  mkvm c910f04x18v03; else rmvm c910f04x18v03 -f -p  &&  mkvm c910f04x18v03 -s 20G; fi;fi] Running Time:1 sec
RETURN rc = 1
OUTPUT:
c910f04x18v03: Error: Cannot remove guest vm, no such vm found
```

**Comment by tingtli** [comment] 2016-10-13 05:53
@caomengmeng  As i comments on defect ＃1872. we need to give a steps for how to reproduce this defect. Not only the logs in our test environment. 
Please reference to https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/Defect%20process for the how to open a valid defect. Thanks!

**Comment by gurevichmark** [comment] 2016-10-13 12:56
I can see now that the code I put under pull request #1942 is being executed. That code was put in to fix issue #1747.
From what I can see here, when `rmvm` is called, the vm is not there anymore.
Now the question is how the vm was removed ?

**Comment by tingtli** [comment] 2016-10-14 08:14
I followed this defect and didn't find the reason why it was deleted before we execute the rmvm. In all the test cases, we always run rmvm and mkvm at the same time to make sure we have a fresh vm. My guess is since the vm is reused, it is probably that something went wrong(mkvm fails??). @gurevichmark Let me first find some trace and give you the reproduced steps.

**Comment by whowutwut** [comment] 2016-10-17 14:29
Is it possible that before the rmvm execution line, for the case where the storage `!= "phy"`, we list out the contents of `/var/lib/libvirt/images`?   Like: 

```
if [[ "__GETNODEATTR($$CN,vmstorage)__" =~ "/var/lib/libvirt/images" ]]; then
    xdsh $$CN ls -l /var/lib/libvirt/images/
fi 
```

Then it's easier to debug these kind of errors in the automation...

**Comment by gurevichmark** [comment] 2016-10-17 14:44
Yes, this will help to prove the theory that vm was removed without the use of `-p` flag, but still, we need to find a place where that is being done.

**Comment by whowutwut** [comment] 2016-10-18 14:40
@caomengmeng @junxiawang  can you add the additional debug to the test case ASAP so we can have a better idea of what the environment looks like at the time of this issue?

**Comment by tingtli** [comment] 2016-11-04 01:52
After add more debug information, It seems it is not a code problem of rmvm. Will move to next release to see if this is a test environment problem.

**Comment by whowutwut** [comment] 2016-11-11 03:39
Let's close this and re-open if it occurs again?

**Comment by tingtli** [comment] 2016-11-17 08:04
This occurs in the autotest environment. I reopen to trace this issue

**Comment by tingtli** [comment] 2016-11-17 08:05
@zet809 Please take a look

**Comment by tingtli** [comment] 2017-01-05 06:30
Reference to #PR2349
i will close this bug. If there is any problem, will reopen it.

**Closed by tingtli** 2017-01-05 06:30 UTC
Labels: component:automation, priority:high
