### ISSUE TITLE
[FVT]Failed to install diskful rh7.2 on x86_64

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1247] opened 2016-06-03 03:13 UTC
Test ENV:
Using Jun. 2nd build on x86 rh7.2 MN, to install diskful CN, it is still installing status after more then 10 hours.
```
[root@c910f04x27v autotest]# lsxcatd -v
Version 2.12.1 (git commit 2794ca51b4165ccd1353fc9f557b6f94974c6239, built Thu Jun  2 09:30:41 EDT 2016)
[root@c910f04x27v autotest]# cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```
It is still installing status after more then 10 hours
```
[root@c910f04x27v autotest]# lsdef c910f04x27v0 | grep status
    status=installing
    statustime=06-02-2016 13:42:39
```
After rcons CN:
```
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................









                                                     ....

```

**Comment by daniceexi** [comment] 2016-06-03 11:38
I put some effort to debug this issue but found the anaconda was running but did not start to install packages. Since we did not open the xcatdebugmode by default, I could not guess where it hung.

@caomengmeng Please enable the ``xcatdebugmode=1`` by default to ease the debug.

**Comment by caomengmeng** [comment] 2016-06-06 02:49
Reproduced with latest daily build.
And not the same result: the CN is not installing, it is still the booted status for last installation.
```
[root@c910f04x27v02 result]# lsxcatd -a
Version 2.12.1 (git commit fbd9abfdf212c1381b166fb3e402eb982c09c0d3, built Sun Jun  5 06:45:48 EDT 2016)
This is a Management Node
dbengine=SQLite
[root@c910f04x27v02 result]# lsdef c910f04x27v04 | grep status
    status=booted
    statustime=06-05-2016 13:25:56
[root@c910f04x27v02 result]# xdsh c910f04x27v04 "ls"
c910f04x27v04: ssh: connect to host c910f04x27v04 port 22: Connection refused

[root@c910f04x27v02 result]# ping c910f04x27v04
PING c910f04x27v04.pok.stglabs.ibm.com (10.4.27.4) 56(84) bytes of data.
64 bytes from c910f04x27v04.pok.stglabs.ibm.com (10.4.27.4): icmp_seq=1 ttl=64 time=0.434 ms
64 bytes from c910f04x27v04.pok.stglabs.ibm.com (10.4.27.4): icmp_seq=2 ttl=64 time=0.275 ms
64 bytes from c910f04x27v04.pok.stglabs.ibm.com (10.4.27.4): icmp_seq=3 ttl=64 time=0.288 ms
^C
--- c910f04x27v04.pok.stglabs.ibm.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.275/0.332/0.434/0.073 ms

```

**Comment by daniceexi** [comment] 2016-06-06 05:33
Please enable the ``xcatdebugmode=1`` for the case so that I can debug it when it hangs.

**Comment by caomengmeng** [comment] 2016-06-15 02:40
@daniceexi xcatdebugmode value  is 1 in daily run test environment.
And it is reproduced today. After more than 60 minutes, it is still installing status for CN with latest build.
```
[root@c910f04x27v02 result]# rpm -qa | grep -i xCAT
grub2-xcat-2.02-0.16.el7.snap201506090204.noarch
perl-xCAT-2.12.1-snap201606140645.noarch
xCAT-server-2.12.1-snap201606140645.noarch
elilo-xcat-3.14-4.noarch
syslinux-xcat-3.86-2.noarch
conserver-xcat-8.1.16-10.x86_64
xCAT-genesis-base-x86_64-2.12-snap201605051534.noarch
xCAT-client-2.12.1-snap201606140645.noarch
xCAT-2.12.1-snap201606140646.x86_64
xCAT-buildkit-2.12.1-snap201606140646.noarch
ipmitool-xcat-1.8.15-1.x86_64
xCAT-genesis-scripts-x86_64-2.12.1-snap201606140646.noarch
xCAT-test-2.12.1-snap201606140646.noarch
[root@c910f04x27v02 result]# cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```

**Comment by daniceexi** [comment] 2016-06-22 08:52
The issue was recreated, the symptom was:

CN: Red Hat Enterprise Linux Server 7.2 (Maipo)

-----------

When issue happens I saw the installation has done but the the node hung when reboot.
~~~~
[    1.455954] input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input3^M
[    1.480170] tsc: Refined TSC clocksource calibration: 2399.967 MHz^M
[  240.513340] INFO: task systemd-udevd:244 blocked for more than 120 seconds.^M
[  240.515215] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.^M
[  240.517164] systemd-udevd   D ffffffffa01a2540     0   244    241 0x00000004^M
[  240.518870]  ffff880078fa7d10 0000000000000082 ffff880036d1dc00 ffff880078fa7fd8^M
[  240.520758]  ffff880078fa7fd8 ffff880078fa7fd8 ffff880036d1dc00 ffffffffffffffff^M
[  240.522598]  0000000000000000 0000000000000001 ffff880078fa7ef0 ffffffffa01a2540^M
[  240.524348] Call Trace:^M
[  240.525128]  [<ffffffff8163a909>] schedule+0x29/0x70^M
[  240.526240]  [<ffffffff810ad105>] async_synchronize_cookie_domain+0x85/0x150^M
[  240.528087]  [<ffffffff810a6ae0>] ? wake_up_atomic_t+0x30/0x30^M
[  240.529399]  [<ffffffff810ad207>] async_synchronize_full+0x17/0x20^M
[  240.530559]  [<ffffffff810ed509>] load_module+0x13a9/0x1b50^M
[  240.531115]  [<ffffffff81316880>] ? ddebug_proc_write+0xf0/0xf0^M
[  240.531753]  [<ffffffff810e9743>] ? copy_module_from_fd.isra.42+0x53/0x150^M
[  240.532564]  [<ffffffff810ede66>] SyS_finit_module+0xa6/0xd0^M
[  240.533134]  [<ffffffff81645909>] system_call_fastpath+0x16/0x1b^M
[  360.533218] INFO: task systemd-udevd:244 blocked for more than 120 seconds.^M
[  360.534727] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.^M
[  360.535674] systemd-udevd   D ffffffffa01a2540     0   244    241 0x00000004^M
....
Warning: /dev/mapper/system-root does not exist^M
Warning: /dev/system/root does not exist^M
~~~~

After I reboot the CN, it could reboot from disk successfully
~~~~
[    1.499143] tsc: Refined TSC clocksource calibration: 2399.970 MHz^M
[^[[32m  OK  ^[[39m] Found device /dev/mapper/system-root.^M
         Starting File System Check on /dev/mapper/system-root...^M
[^[[32m  OK  ^[[39m] Started dracut initqueue hook.^M
[^[[32m  OK  ^[[39m] Reached target Remote File Systems (Pre).^M
[^[[32m  OK  ^[[39m] Reached target Remote File Systems.^M
[^[[32m  OK  ^[[39m] Started File System Check on /dev/mapper/system-root.^M
         Mounting /sysroot...^M
[    1.848214] SGI XFS with ACLs, security attributes, no debug enabled^M
[    1.851824] XFS (dm-0): Mounting V4 Filesystem^M
[    1.995663] XFS (dm-0): Ending clean mount^M

~~~~

Another clue was I saw the CN started with -m 2048 when issue happens.  But when I reboot, the CN was boot with -m 4096. So I am afraid the issue might be caused by lacking of memory. @caomengmeng will change the CN to have 4096M memory by default.
~~~~
LC_ALL=C PATH=/sbin:/usr/sbin:/bin:/usr/bin QEMU_AUDIO_DRV=none /usr/libexec/qemu-kvm -name c910f04x27v08 -S -M rhel6.5.0 -enable-kvm -m 2048 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 4e7a1a06-9ad7-e411-9471-421022e3641c -nodefconfig -nodefaults -device sga -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/c910f04x27v08.monitor,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -drive file=/var/lib/libvirt/images/c910f04x27v08.hda.qcow2,if=none,id=drive-ide0-0-0,format=qcow2,cache=none -device ide-drive,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=2 -drive if=none,media=cdrom,id=drive-ide0-0-1,readonly=on,format=raw -device ide-drive,bus=ide.0,unit=1,drive=drive-ide0-0-1,id=ide0-0-1 -netdev tap,fd=22,id=hostnet0,vhost=on,vhostfd=25 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=42:b7:0a:04:1b:08,bus=pci.0,addr=0x3,bootindex=1 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0 -vnc 0.0.0.0:2,password -vga std -device AC97,id=sound0,bus=pci.0,addr=0x4 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5
char device redirected to /dev/pts/19
qemu: terminating on signal 15 from pid 2855
2016-06-22 08:14:51.353+0000: shutting down
2016-06-22 08:14:51.538+0000: starting up
LC_ALL=C PATH=/sbin:/usr/sbin:/bin:/usr/bin QEMU_AUDIO_DRV=none /usr/libexec/qemu-kvm -name c910f04x27v08 -S -M rhel6.5.0 -enable-kvm -m 4096 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 4e7a1a06-9ad7-e411-9471-421022e3641c -nodefconfig -nodefaults -device sga -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/c910f04x27v08.monitor,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -drive file=/var/lib/libvirt/images/c910f04x27v08.hda.qcow2,if=none,id=drive-ide0-0-0,format=qcow2,cache=none -device ide-drive,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=2 -drive if=none,media=cdrom,id=drive-ide0-0-1,readonly=on,format=raw -device ide-drive,bus=ide.0,unit=1,drive=drive-ide0-0-1,id=ide0-0-1 -netdev tap,fd=22,id=hostnet0,vhost=on,vhostfd=25 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=42:b7:0a:04:1b:08,bus=pci.0,addr=0x3,bootindex=1 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -device usb-tablet,id=input0 -vnc 0.0.0.0:2,password -vga std -device AC97,id=sound0,bus=pci.0,addr=0x4 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x5
~~~~

**Comment by caomengmeng** [comment] 2016-06-23 08:52
@daniceexi 
This problem reproduced today, and I updated the configure files to make CN vmmemory as 4096, and will track this issue continually

**Comment by daniceexi** [comment] 2016-06-30 00:38
Since I think it's a configuration issue, move it to 2.12.2 to track it. If cannot create before 2.12.2 release when assign enough resources for the CN, will close it.

**Comment by immarvin** [comment] 2016-08-09 02:06
close this issue, please reopen it if be recreated

**Closed by immarvin** 2016-08-09 02:07 UTC
Labels: component:os_provision, priority:high, type:bug
