### ISSUE TITLE
[FVT]bmcdiscover could not get the bmc information

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#1065] opened 2016-05-06 14:36 UTC
env:rhels7
build:lastest build
How to reproduce: 
```
[root@c910f02c01p13 ~]#  bmcdiscover -s nmap --range 10.4.30.254
Error: BMC username is incorrect for node-0a041efe

```

**Comment by junxiawang** [comment] 2016-05-06 14:41
Build:
lsdef - Version 2.12 (git commit 241e879d6340e3f4c6f89034325644808c3493e9, built Thu May  5 20:44:19 EDT 2016)

**Comment by whowutwut** [comment] 2016-05-06 15:20
@junxiawang  I changed the behavior for bmcdiscover in pull request https://github.com/xcat2/xcat-core/pull/704.   It now does the following:

* Takes the default user/pass from the passwd table for the ipmi entry, then user can override with -u and -p options for bmcdiscover
* If there is issue with user/pass, do not allow the discovery to work 

The 2nd bullet is what you are hitting above.  

The reason behind this change is that before the code change, we provide a response for the bmc even if the user name and password is incorrect.  The problem here is outlined below... 

```
[root@c910f02c05p03 ~]# bmcdiscover --range 50.5.33.10 -z
Warning: bmc password is incorrect for node-3205210a
node-3205210a:
	objtype=node
	groups=all
	bmc=50.5.33.10
	cons=ipmi
	mgt=ipmi

[root@c910f02c05p03 ~]# bmcdiscover --range 50.5.33.10 -z -p passw0rd
Warning: bmc username is incorrect for node-3205210a
node-3205210a:
	objtype=node
	groups=all
	bmc=50.5.33.10
	cons=ipmi
	mgt=ipmi

[root@c910f02c05p03 ~]# bmcdiscover --range 50.5.33.10 -z -p passw0rd -u ADMIN
node-8335-gta-1210532:
	objtype=node
	groups=all
	bmc=50.5.33.10
	cons=ipmi
	mgt=ipmi
	mtm=8335-GTA
	serial=1210532
	bmcusername=ADMIN
	bmcpassword=passw0rd
```

With the incorrect user/pass, a node definition is returned with name: **node-3205210a**
But with the correct user/pass, it's returned with a different generated name: **node-8335-gta-1210532**

The stanza without the right information does not contain any MTMS information.  Also if the password is incorrect in the default passwd table, hardware control cannot be executed on the discovered node... so my thought is, why return any stanza when the user/password is incorrect to get the details we need from the bmc....      @zet809  do you agree? 

I did find a bug in the bmcdiscover code while investigating this.. 
```
[vhu@victorvm7 xcat-core]$ git diff ./xCAT-server/lib/xcat/plugins/bmcdiscover.pm
diff --git a/xCAT-server/lib/xcat/plugins/bmcdiscover.pm b/xCAT-server/lib/xcat/plugins/bmcdiscover.pm
index 5b96a7a..f23fe5f 100644
--- a/xCAT-server/lib/xcat/plugins/bmcdiscover.pm
+++ b/xCAT-server/lib/xcat/plugins/bmcdiscover.pm
@@ -206,11 +206,11 @@ sub bmcdiscovery_processargs {
     #
     ($bmc_user, $bmc_pass) = bmcaccount_from_passwd();
     # overwrite the default user/pass with what is passed in
+    if ($::opt_U) {
+        $bmc_user = $::opt_U;
+    }
     if ($::opt_P) {
         $bmc_pass = $::opt_P;
-        if ($::opt_U) {
-            $bmc_user = $::opt_U;
-        }
     }
 
     #########################################
``` 
I could fix the above in the pull request.  Only if we specify -p do we also look at the -u option, that is a bug...

**Comment by daniceexi** [comment] 2016-05-07 10:16
I am OK with the current behaviour that just give an error message for failed node. But message might be changed.

Current message is:
~~~~
Error: BMC username is incorrect for node-0a041efe
~~~~

For the access-failed bmc, only useful information from ``bmcdiscover`` command is the ip of the bmc, so  I'd like the message should specify the IP of bmc instead of a fake name made by xcat.

**Comment by whowutwut** [comment] 2016-05-07 13:38
Yes, good suggestion in the output msg, that would make more sense...  Let me make sure that if we pass in a range, the output message is expected.

**Comment by junxiawang** [comment] 2016-05-11 07:02
1.[root@c910f02c01p13 ~]# bmcdiscover --range  10.4.25.1 -p passw0rd -u ADMIN
[root@c910f02c01p13 ~]# echo $?
0
---------------------> no error message but return value still 0
2.root@c910f03c05k05:/new212/xcat-dep# bmcdiscover --range 50.5.33.10 
Warning: bmc username is incorrect for node-3205210a
50.5.33.10
-------------------------> I do not think there should be warning info here

**Comment by whowutwut** [comment] 2016-05-11 12:39
@junxiawang 

For 1, you are running `bmcdiscover` against a range that is NOT a BMC, it's a Juniper Switch.  
```
[root@c910f02c01p13 ~]# ssh 10.4.25.1
root@10.4.25.1's password: 
pam_unix: pam_sm_authenticate: UNIX authentication refused

--- JUNOS 12.3R8.7 built 2014-09-19 15:47:21 UTC

[root@c910f02c01p13 ~]# switchdiscover --range 10.4.25.1
Discovering switches using nmap for 10.4.25.1. It may take long time...
ip          	name                	vendor                                            	mac         
------------	------------        	------------                                      	------------
10.4.25.1   	switch-10-4-25-1    	Juniper networks                                  	2C:6B:F5:37:45:7F
```

I feel this behavior is "working as designed".  

There is no error printed out in `bmcdiscover` because there is no error when we did not find a BMC in the range provided.  By default, we should not print anything because it does not scale well.  If we are discovering bmcs over a range of 10k IP addresses, we don't want 10k messages to come out saying "This IP is not a BMC".  Do you agree? 

For 2,  You need to provide the version of the command, i can't recreate on your test machine:
```
[root@c910f02c01p13 ~]# bmcdiscover -v
bmcdiscover - xCAT Version 2.12 (git commit 43305d3fffac120338aa5d501f0e74d38c9eff4e, built Tue May 10 09:30:51 EDT 2016)
[root@c910f02c01p13 ~]# bmcdiscover --range 50.5.33.10 
[root@c910f02c01p13 ~]# 
```

Let's talk about this scenario in the meeting tonight.

**Comment by daniceexi** [comment] 2016-05-11 12:54
@whowutwut 

You can use the node 10.3.5.5

It can be recreated:
~~~~
# bmcdiscover --range 50.5.33.10
Warning: bmc username is incorrect for node-3205210a
50.5.33.10
~~~~

**Comment by whowutwut** [comment] 2016-05-11 13:05
Thanks @daniceexi! Sorry, I was on the wrong machine, I didn't notice the different hostname in @junxiawang's post ..  So on 10.3.5.5, the code is not updated..  I'm not exactly sure why...

```
root@c910f03c05k05:~# bmcdiscover -v
bmcdiscover - xCAT Version 2.12 (git commit 43305d3fffac120338aa5d501f0e74d38c9eff4e, 
built Tue May 10 09:32:08 EDT 2016)
```

Notice the Nov 19 timestamp....
```
root@c910f03c05k05:/opt# ls -ltr /opt/xcat/lib/perl/xCAT_plugin/bmcdiscover.pm
-rw-r--r-- 1 nobody nogroup 28071 Nov 19 18:03 /opt/xcat/lib/perl/xCAT_plugin/bmcdiscover.pm

root@c910f03c05k05:/opt# grep Warning /opt/xcat/lib/perl/xCAT_plugin/bmcdiscover.pm
            xCAT::MsgUtils->message("I", {data=>["Warning: bmc username is incorrect for $node"]}, $::CALLBACK);
            xCAT::MsgUtils->message("I", {data=>["Warning: bmc password is incorrect for $node"]}, $::CALLBACK);

```

But if you look at d82e14b56656482279d58e38295a9900e82ba056, merged already... I changed the Warning to an Error. . This code is not matching what is in Git.. 

Maybe another problem with the Ubuntu build?

**Comment by junxiawang** [comment] 2016-05-12 01:55
@whowutwut I will try again for it

**Comment by daniceexi** [comment] 2016-05-12 07:18
@whowutwut 
@junxiawang mentioned another concern that there was no any output when no bmc was found for a range. Then user did not know whether the ``bmcdiscovery`` has been run properly.

I talked with @zet809 , we may add a message like **Cannot find any BMC.** when no BMC was found. What do you think?

**Comment by junxiawang** [comment] 2016-05-12 07:24
@whowutwut 
c910f02c01p14:~ # bmcdiscover --range "10.4.30-40.254" -u USERID -p PASSW0RD -z
c910f02c01p14:~ #  bmcdiscover --range "10.4.30-40.254" -u USERID -p PASSW0RD -z
c910f02c01p14:~ # echo $?
0
c910f02c01p14:~ # lsdef -v
lsdef - Version 2.12 (git commit 5ee31c9200bc980cdaeeb94ce0a256dfd83e96d6, built Wed May 11 09:30:34 EDT 2016)
c910f02c01p14:~ # 
--------------------------------> using this command could not get any bmc info
But before the code change:
root@c910f03c05k10:~# bmcdiscover --range "10.4.30-40.254" -u USERID -p PASSW0RD
10.4.30.254,7912AC1,06VAG36,USERID,PASSW0RD
10.4.31.254,7912AC1,06VAE26,USERID,PASSW0RD
10.4.32.254,7912AC1,06VAD90,USERID,PASSW0RD
10.4.33.254,7912AC1,06VAE52,USERID,PASSW0RD
10.4.34.254,7912AC1,06VAF01,USERID,PASSW0RD
10.4.35.254,7912AC1,06CGTR0,USERID,PASSW0RD
10.4.36.254,7912AC1,06VAG60,USERID,PASSW0RD
10.4.37.254,7912AC1,06CGTR6,USERID,PASSW0RD
10.4.38.254,7912AC1,06VAG62,USERID,PASSW0RD
10.4.39.254,7912AC1,06BPKK9,USERID,PASSW0RD
10.4.40.254,7912AC1,06VCM35,USERID,PASSW0RD
root@c910f03c05k10:~#

**Comment by zet809** [comment] 2016-05-12 08:45
@whowutwut A quick investigation shows that the nmap running on c910f02c01p14 is much older(Nmap 4.75) than on c910f03c05k10(Nmap 6.40), then it cause the nmap command "nmap -sn -n $range" doesn't work on  c910f02c01p14.

**Comment by daniceexi** [comment] 2016-05-12 12:40
Then we need to do the similar thing in the ``switchdiscover`` that check the version of ``nmap``, use the corresponding parameters for the nmap and check the output base on the version of the nmap.

**Comment by whowutwut** [comment] 2016-05-13 00:45
@daniceexi @zet809 what about having a verbose mode or having a warning message print out to stderr, this way if the user does not care, they can redirect to /dev/null?  but then also the error messages would go to stderr....

**Closed** 2016-05-16 09:17 UTC
Labels: priority:high, status:pending, type:bug
