### ISSUE TITLE
rflash does not display any output or progress

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#1849] opened 2016-09-16 16:50 UTC
```
Version 2.12.2 (git commit 6fff020a905c64cabe31896e653aebc942ee0694, built Thu Sep  1 06:18:21 EDT 2016)
[root@c712ems4 ppc64le]# rpm -qa | grep xcat | grep ipmi
ipmitool-xcat-1.8.17-0.ppc64le
[root@c712ems4 ppc64le]# ipmitool-xcat -V
ipmitool-xcat version 1.8.17
```

rflash against Garrison node does not display any output or indicate progress. 
Also, I am not sure if the rflash is will continue if the session is disconnected. If not, it would be good to have this. On some earlier hardware, rflash would write to the screen and  a log (/var/log/xcat/rflash/<hostname> or something similar) and continue if the console disconnected.  Status could then be obtained from the log when reconnected.
Would like some output to the screen indicating progress and a log file.

**Comment by whowutwut** [comment] 2016-09-16 18:49
@pdlun92  Please work with @zet809  to see if there's a good way to provide some status during the update of the firmware.

**Comment by pdlun92** [comment] 2016-09-26 14:52
Moving to milestone 2.12.4

Thinking this will have to be added as an option to `rflash` as default behavior could become very messy/ineffective with scale up

**Comment by pdlun92** [comment] 2016-09-27 21:22
Talked to @markprez about this today.  I think the end goal here is to make sure that rflash will continue running even through terminal disconnects and other similar interruptions, as if it was running through a `screen` session, allowing admin/user to issue command and check back in on progress as they please

**Comment by chenglch** [comment] 2016-09-28 06:03
I think running command in `screen` is acceptable. Do we need to record more information like `verbose` debug message from the ipmitool command?  The original output of `ipmitool hpm update` is tty-based message and not accurate, it's hard to make use of this result.

**Comment by markprez** [comment] 2016-10-04 18:48
I usually run: (nohup rflash  Pf2,Pf3 8335GTB_820.1634.20160917a.hpm 2>&1 | tee -a 1634i.install.f1 & ) which will keep running if my connection drops... but if I forget screen or to start it in the background with nohup I am stuck at the terminal until it completes. Firmware flash is a dangerous process to have exit abnormally. On a large system, this will cause undo inconvenience. Once a system is stable, flashing will most likely be infrequent. You are asking an admin to remember to run it from screen or have the confidence to nohup a process they do not often do.
In my latest run of 36 nodes, 3 nodes failed, without the tee of the output, this may have scrolled by:
nohup: ignoring input
ray52: Error: Running ipmitool command /opt/xcat/bin/ipmitool-xcat -H 192.168.0.52 -I lanplus -U ADMIN -P admin -z 15000 hpm upgrade /root/hpm/8335GTB_820.1634.20160917a.hpm force failed.
ray38: Error: Running ipmitool command /opt/xcat/bin/ipmitool-xcat -H 192.168.0.38 -I lanplus -U ADMIN -P admin -z 15000 hpm upgrade /root/hpm/8335GTB_820.1634.20160917a.hpm force failed.
ray29: Error: Running ipmitool command /opt/xcat/bin/ipmitool-xcat -H 192.168.0.29 -I lanplus -U ADMIN -P admin -z 15000 hpm upgrade /root/hpm/8335GTB_820.1634.20160917a.hpm force failed.
ray27: rflash started, please wait.......
ray31: rflash started, please wait.......
ray25: rflash started, please wait.......
ray30: rflash started, please wait.......
ray45: rflash started, please wait.......
ray58: rflash started, please wait.......
ray37: rflash started, please wait.......
ray33: rflash started, please wait.......
ray24: rflash started, please wait.......
ray42: rflash started, please wait.......
ray29: rflash started, please wait.......
ray55: rflash started, please wait.......
ray28: rflash started, please wait.......
ray48: rflash started, please wait.......
ray56: rflash started, please wait.......
ray38: rflash started, please wait.......
ray52: rflash started, please wait.......
ray36: rflash started, please wait.......
ray51: rflash started, please wait.......
ray44: rflash started, please wait.......
ray53: rflash started, please wait.......
ray35: rflash started, please wait.......
ray34: rflash started, please wait.......
ray47: rflash started, please wait.......
ray57: rflash started, please wait.......
ray40: rflash started, please wait.......
ray32: rflash started, please wait.......
ray49: rflash started, please wait.......
ray41: rflash started, please wait.......
ray50: rflash started, please wait.......
ray54: rflash started, please wait.......
ray39: rflash started, please wait.......
ray43: rflash started, please wait.......
ray26: rflash started, please wait.......
ray46: rflash started, please wait.......
ray59: rflash started, please wait.......
ray58: rflash completed.
ray25: rflash completed.
ray24: rflash completed.
ray40: rflash completed.
ray26: rflash completed.
ray54: rflash completed.
ray53: rflash completed.
ray42: rflash completed.
ray51: rflash completed.
ray34: rflash completed.
ray55: rflash completed.
ray57: rflash completed.
ray30: rflash completed.
ray31: rflash completed.
ray44: rflash completed.
ray32: rflash completed.
ray35: rflash completed.
ray56: rflash completed.
ray45: rflash completed.
ray50: rflash completed.
ray46: rflash completed.
ray37: rflash completed.
ray41: rflash completed.
ray36: rflash completed.
ray39: rflash completed.
ray28: rflash completed.
ray27: rflash completed.
ray49: rflash completed.
ray33: rflash completed.
ray43: rflash completed.
ray48: rflash completed.
ray59: rflash completed.
ray47: rflash completed.
[root@ray1 hpm]#
Also, not much info on the error.
Thanks.

**Comment by whowutwut** [comment] 2016-10-06 00:41
I think this was closed by accident.

**Comment by immarvin** [comment] 2016-11-07 08:11
hi @pdlun92 ,any update?

**Comment by pdlun92** [comment] 2016-11-21 21:01
@zet809 can someone in china look in to this with POK vacation coming up?  Thanks

**Comment by chenglch** [comment] 2016-11-22 07:45
If there is some machine can be used to run `rflash`, I can add  some debug message and make the main process running in the background.

**Comment by whowutwut** [comment] 2016-11-22 18:24
@chenglch  You can run this on any of the machines under fs1 or fs4..  just do not interrupt the rflahs process, we still have not gotten the machine back from when we bricked the BMC.  :)  @pdlun92  can we flash on and off the same firmware levels?

**Comment by pdlun92** [comment] 2016-11-30 20:50
Working to verify this now.  Don't think it is necessary for FVT to spend time on this issue.

**Comment by caomengmeng** [comment] 2016-12-01 08:34
run rflash node /path and below logs are created:

```
[root@fs4 ~]# tail -f /var/log/xcat/rflash/frame23cn18.log

----------------------------------------------------------------                                                ---------------
|ID  | Name        |                     Versions                                                                        | %  |
|    |             |      Active     |      Backup     |      Fi                                                le       |    |
|----|-------------|-----------------|-----------------|--------                                                ---------|----|
|*  2|BIOS         |   1.11 00000013 | ---.-- -------- |   1.12                                                 21000000 |100%|
|    |Upload Time: 00:49             | Image Size: 33554584 byte                                                s              |
|*  0|BOOT         |   2.13 3A000000 | ---.-- -------- |   2.13                                                 3B000000 |100%|
|    |Upload Time: 00:00             | Image Size:  262296 bytes                                                              |
|*  1|APP          |   2.13 3A000000 | ---.-- -------- |   2.13                                                 3B000000 |100%|
|    |Upload Time: 00:33             | Image Size: 33292440 byte                                                s              |
----------------------------------------------------------------                                                ---------------
(*) Component requires Payload Cold Reset

Firmware upgrade procedure successful
```
After the rflash is completed:
```
[root@fs4 firm]# lsdef frame23cn18 | grep status
    status=success to update firmware
    statustime=11-30-2016 22:19:35

```
Then rpower on the node, within 5 minutes, try to rerun the rflash command, error messages return.
``` 
[root@fs4 firm]# rpower frame23cn18 on
frame23cn18: on
[root@fs4 firm]# rflash frame23cn18 /firm/8335GTB_820.1642.20161108n_update.hpm
frame23cn18: rflash started, please wait.......
frame23cn18: Error: Unknown FRU header version 0x00
frame23cn18: Error: failed to update firmware
```
When rflash is running, stop the screen, then rflash will continue to executed, and successfully.
But when rflash is running, do the Ctrl+C , then rflash is stopped, @chenglch will fix it.

**Comment by whowutwut** [comment] 2016-12-01 17:12
@caomengmeng   Can you clarify the last step... 

* When rflash is running, stop the screen, then rflash will continue to executed, and successfully.
* But when rflash is running, do the Ctrl+C , then rflash is stopped, @chenglch will fix it.

What does the first point mean? 

Regarding the 2nd doing the ctrl-c, let's remove this from the process..  I don't think we should do this and possibly maybe the solution is to have an output message asking users to NOT ctrl-c out of a firmware update until we can understand or confirm with the firmware team that this is supported.    I fear that we have bricked another box. ....

**Comment by whowutwut** [comment] 2016-12-01 21:07
@caomengmeng  OK, with the help of the Firmware team we were able to recover cn18 by re-flashing the PNOR side of the firmware.  Uma said that we may have also been able to recover this by re-flashing the firmware again but this required a physical power cable reset on the BMC after it's done.   It was most likely caused by the ctrl-c and probably should not be doing this... cn17 and cn18 are back up and running. 

I think we are able to close this.  It seems we can see progress for the rflash in `/var/log/xcat/rflash`.    

Using https://github.com/xcat2/xcat-core/issues/2245 to continue investigation of other potential other issues with rflash

**Comment by chenglch** [comment] 2016-12-02 02:16
@whowutwut , with my last patch, `ctrl-c` has been ignored at xcatd side and mengmeng will test this today. When the user runs `rflash` at client side, maybe `ctrl-c` will be sent by accident, with the patch, xcat client process is terminated, but the `rflash processes` at xcatd side will continue.

**Comment by caomengmeng** [comment] 2016-12-02 04:20
Verified with latest build
```
[root@fs1 ~]# lsxcatd -v
Version 2.13 (git commit c44f3c60d6a6f57cda9e1c58a285c294dfe4ca26, built Thu Dec  1 21:55:34 EST 2016)
```
Steps:
1. run ``flash node /npm-path``
2. after the node is being ``updating firmware`` status
3. do ``Ctrl+C`` to close the process
4. confirm that the rflash is being running, and firmware will successfully update.
```
[root@fs1 ppc64le]# rflash frame45cn02 /firm/8335GTB_820.1642.20161108n_update.hpm
frame45cn02: rflash started, please wait.......
frame45cn02: rflashing ... See the detail progress : "tail -f /var/log/xcat/rflash/frame45cn02.log"
^C[root@fs1 ppc64le]#  lsdef frame45cn02 | grep status
    status=updating firmware
    statustime=12-01-2016 03:47:33
    updatestatus=synced
    updatestatustime=11-07-2016 04:10:53
[root@fs1 ppc64le]#  lsdef frame45cn02 | grep status
    status=success to update firmware
    statustime=12-01-2016 03:47:33
    updatestatus=synced
    updatestatustime=11-07-2016 04:10:53
```

**Closed by caomengmeng** 2016-12-02 04:20 UTC
Labels: component:hw_control, priority:high, status:pending, xCAT 2.13
