### ISSUE TITLE
rflash -d <dir> option fails to reboot Node Host/OS that is up/running

### ISSUE THREAD

**Issue by marksmit-ibm** [xcat2/xcat-core#5454] opened 2018-08-01 21:05 UTC
> lsxcatd -a
Version 2.14.2 (git commit f2090565b1d1b8efa7558d034de0478456c38e4c, built Wed Jul 11 07:15:53 EDT 2018)

Using rflash -d <dir> option against 12 nodes that have the OS/Host up/running during the test.
1. Hit one instance of #5410 issue addressed in future 2.14.3.  Worked around by manually powering on.
2. Hit four instances of this new problem.  Other 8 nodes rebooted the Host as designed.
These 4 failures, claimed success in `rflash -d`  but when I checked the Host uptime, I see that they were never rebooted.  It is as if the Host reset did not power off or power on.
Also `rflash -l ` is properly reporting (+) indicating the Host firmware was installed, but is pending the (should be automatic) Host reboot to complete.

**Comment by bybai** [comment] 2018-08-02 01:49
Hi @marksmit-ibm, Could you have a try PR #5410?  I think this PR fix  "rflash -d <dir> option fails to reboot Node Host/OS that is up/running". In #5410, if ``rpower reset`` state is always off, ``rflash -d`` will try 5 times to ``rpower on`` it.

**Comment by bybai** [comment] 2018-08-02 02:05
@marksmit-ibm, You mentioned: "Attaching details of recreate. Important here, I think, is that I am intentionally using ``the rflash -d <dir>`` option when only the pnor is changing. The BMC level remains the same as what is running. This may be introducing an unusual use-case for the code to handle. ".
Yes, it is an new use-case require for ``rflash -d``,  and current function always upload and activate both BMC and PNOR, this new require may be a process optimize, so let me look into it as our release sprint planned. Thanks.

**Comment by whowutwut** [comment] 2018-08-02 03:50
@bybai  I don't think #5410 is related, @marksmit-ibm  says... 

> when I checked the Host uptime, I see that they were never rebooted.

So that means the host never rebooted, so the reset never got sent.  We may want to communicate with the OpenBMC team to see if we can validate whether or not a REST API command got through to the bmc... 

This should not be a new use case, if the bmc file is not in the directory, it should not get flashed...  maybe a bug?

**Comment by marksmit-ibm** [comment] 2018-08-02 04:28
Clarifying @vhu,  currently 2.14.2-GA will prevent running (fails to start) if either BMC or PNOR image is missing.  That is working as designed.   
My point is that only the pnor image is newer/different in this use case.  In order for -d <dir> to work, I copy the BMC image to the dir, but it is the same level as Fx-Rev7-Rev12.   This matches what is presented in the IBM/AFS dir for testing.

2nd clarifying point, @bybai , I am not first powering off system before running rflash -d <dir>.  This is not "best practice", but since permitted, I am testing  that way.  It minimizes node downtime, but also tests both a power off and power on  (or `rpower node boot`)

**Comment by bybai** [comment] 2018-08-02 06:26
@whowutwut, the first:
 just as @marksmit-ibm described, ``rflash -d`` is working as designed "both BMC and PNOR are flashed". The "unusual" use case is: "when both BMC and PNOR are in directory, BMC was already flashed (for example, by rflash -a), now ``rflash -d`` only flash PNOR since BMC is already latest and no need to be re-flashed. Our current solution is re-flash and activate BMC".  It is not a bug.

**Comment by bybai** [comment] 2018-08-02 06:54
The 2nd @marksmit-ibm and @whowutwut：
``rflash -d`` ``reset`` use the same request and response with ``rpower boot`` during ``reset`` the node. I reproduced above issue in mid05tor12cn13 before,  ``rflash`` sent ``power reset`` to mid05tor12cn13, but mid05tor12cn13 is only ``off``, openbmc does not handle ``power on`` for mid05tor12cn13. The workaround is to manually ``rpower <node> on`` . I saw it was just the same with @marksmit-ibm described.

In order to deduce the manual work around ``rpower <host> on`` and let ``rflash -d`` whole process works, in PR #5410,  I added check for ``rflash -d`` to check: after ``reset`` the host, 5 seconds later, if the host power state is still ``off``, send the ``rpower on`` request to let host  become ``on`` to resolve the ``reset`` only ``off`` the host problem.
This issue is sometimes only reproduced in ``mid05tor12cn13`` in xCAT env. It seems after BMC is flashed and rebooted ready with specific BMC version, need seconds delay to execute ``rpower reset`` the host. Or else, ``reset`` only ``off`` the host, I captured the ``rpower <host> reset`` manually as following, I remembered that this ``rpower reset`` error message were known before, ping @gurevichmark :
```
[root@briggs01 ~]# rpower mid05tor12cn13 reset
mid05tor12cn13: Error: Received wrong format response: {u'/xyz/openbmc_project/state/chassis0': {u'CurrentPowerState': u'xyz.openbmc_project.State.Chassis.PowerState.Off', u'RequestedPowerTransition': u'xyz.openbmc_project.State.Chassis.Transition.Off'}, u'/xyz/openbmc_project/state/bmc0': {u'CurrentBMCState': u'xyz.openbmc_project.State.BMC.BMCState.NotReady', u'RequestedBMCTransition': u'xyz.openbmc_project.State.BMC.Transition.None'}}
```

**Comment by whowutwut** [comment] 2018-08-02 10:54
@bybai if we wait long enough for the power state to change to off. Then send the on and BMC does not react. It’s an openbmc issue you need to take to their team 

@gurevich let’s discuss today

**Comment by gurevichmark** [comment] 2018-08-02 15:14
I was able to recreate on f5u16 from stratton01 with latest development xCAT build. At the end of `rflash -d` we send "rpower reset", but the host is not rebooted.
```
[root@stratton01 yum.repos.d]# lsxcatd -a
Version 2.14.3 (git commit fc1c23285ef61045465ffca844c531b88c0208d6, built Thu Aug  2 06:15:56 EDT 2018)
This is a Management Node
dbengine=SQLite
[root@stratton01 yum.repos.d]#
```

I think the problem is with "reset", calling it by itself does not appear to reboot the host
```
[root@stratton01 yum.repos.d]# uptime f5u16
 10:55:18 up 9 days, 22:20,  3 users,  load average: 0.07, 0.15, 0.21

[root@stratton01 yum.repos.d]# rpower f5u16 reset
Thu Aug  2 10:59:49 2018 f5u16: [openbmc_debug] login curl -k -c cjar -b cjar -X POST -H "Content-Type: application/json" https://10.5.16.100/login -d '{"data": ["root", "xxxxxx"]}'
Thu Aug  2 10:59:49 2018 f5u16: [openbmc_debug] login 200 OK
Thu Aug  2 10:59:49 2018 f5u16: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.5.16.100/xyz/openbmc_project/state/enumerate
Thu Aug  2 10:59:50 2018 f5u16: [openbmc_debug] list_power_states 200 OK
Thu Aug  2 10:59:50 2018 f5u16: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.5.16.100/xyz/openbmc_project/state/chassis0/attr/RequestedPowerTransition -d '{"data": "xyz.openbmc_project.State.Chassis.Transition.Off"}'
Thu Aug  2 10:59:50 2018 f5u16: [openbmc_debug] set_power_state 200 OK
Thu Aug  2 10:59:50 2018 f5u16: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.5.16.100/xyz/openbmc_project/state/enumerate
Thu Aug  2 10:59:55 2018 f5u16: [openbmc_debug] list_power_states 200 OK
Thu Aug  2 10:59:57 2018 f5u16: [openbmc_debug] list_power_states curl -k -c cjar -b cjar -X GET -H "Content-Type: application/json" https://10.5.16.100/xyz/openbmc_project/state/enumerate
Thu Aug  2 11:00:01 2018 f5u16: [openbmc_debug] list_power_states 200 OK
Thu Aug  2 11:00:01 2018 f5u16: [openbmc_debug] set_power_state curl -k -c cjar -b cjar -X PUT -H "Content-Type: application/json" https://10.5.16.100/xyz/openbmc_project/state/host0/attr/RequestedHostTransition -d '{"data": "xyz.openbmc_project.State.Host.Transition.On"}'
Thu Aug  2 11:00:02 2018 f5u16: [openbmc_debug] set_power_state 200 OK
f5u16: reset

[root@stratton01 yum.repos.d]# uptime f5u16
 11:00:56 up 9 days, 22:25,  3 users,  load average: 0.18, 0.12, 0.18
[root@stratton01 yum.repos.d]#
```

**Comment by marksmit-ibm** [comment] 2018-08-02 16:32
@whowutwut wrote: >if we wait long enough for the power state to change to off...

I believe I captured on the OpenBMC SEL list that corresponding error.  Matt Spinler is discussing in CQ defect: > cn10 Proc.FSI.Error.MasterDetectionFailure||I2C after rflash update
https://w3.rchland.ibm.com/projects/bestquest/?defect=SW440656  (also mirrored to Bugz for those w/o CQ: LTCBug170131
Let me be clear; cn10 was the instance that recreated #5410 - the reset successfully powered it off from running but did not power it  back on.  

Thank you @bybai for clarifying that the Host reset at the end of rflash -d <dir> is the same as `rpower boot`
For my issue #5454, here, none of the 4 nodes ever powered off - it was as if the reset command was missed for both power off and power on.   Unfortunately, I see no OpenBMC SEL error events for those nodes.

**Comment by gurevichmark** [comment] 2018-08-02 17:18
@marksmit-ibm Is this something that you can recreate ? Run `rflash -d` against the same 12 nodes and see some of the hosts not reboot ?
If you do try, can you turn on debugging with `chdef -t site clustersite xcatdebugmode=1` before running `rflash -d` and also use `-V` for verbose output ?

**Comment by bybai** [comment] 2018-08-03 01:50
Hi @gurevichmark , let me reproduce it on ``f6u13`` from ``stratton01``. Different firmware version may response different results that we should enhance. Thanks

**Comment by bybai** [comment] 2018-08-03 06:56
Hi @marksmit-ibm, 
1.  ``rflash -d`` sometimes does not reset the hosts issue be fixed in PR #5461
2.  we will use https://github.com/xcat2/xcat-core/issues/5459 to trace new ``rflash -d`` enhancements
Thanks.

**Comment by bybai** [comment] 2018-08-08 02:44
H @marksmit-ibm, could you verify this "`rflash -d` sometimes does not reset the hosts issue"?  hope you can get better results.

**Comment by geissonator** [comment] 2018-08-09 12:26
Hi, I added a comment to the openbmc defect related to this - https://w3.rchland.ibm.com/projects/bestquest/?defect=SW440656#nle8

```
Based on the traces Matt collected above, the main issue is that a host reboot was requested of the BMC before it had completed the previous request (power off).

Mark, does XCAT not have code in place to ensure the BMC has processed the previous command (i.e. chassis state is off and host state is off) before requesting the host reboot?

We could maybe add some code to reject a chassis/host state change request if one is ongoing but would prefer if the caller just ensured the previous state request was complete before requesting a new one.

We've made a lot of performance improvement in our 920 code base for this path so that 13s to power off would have been much faster with the new code (~5s).
```

I see a lot of talk of hard coded delays above but if xcat could just query the BMC states to ensure it's achieved the requested state, before requesting a new state change, all would be good.  Is this bug addressing this or would you prefer openbmc look into rejecting new state requests when it's still processing old one's?

**Comment by whowutwut** [comment] 2018-08-09 18:01
@geissonator I'm pretty sure that we query power status to make sure it's  'off' before turning the node back on.  But in the past with firmware, we have seen cases where in our scripted process, we go too fast and have been asked to add a sleep in between.  Could this be another one of those cases where when we run it by hand, we would never issue the "on" quick enough to get into this situation. 

@bybai Can you confirm that we do wait for a  "off" status before sending the on.  Is there a way we can log this to prove that we are getting a "off" response?

**Comment by bybai** [comment] 2018-08-10 02:00
Hi @whowutwut, In latest code, it does wait for BMC and host including "off" status before sending the "on". 
After BMC is reboot, it does wait for BMC becomes ready, here needs retry and wait. After host is reset, it does check/retry and wait it to "off" state, then sending it to "on" state, if the "on" request is failed the node state is still "off", it re-tries 5 times to re-send "on" to let host "on".

**Comment by whowutwut** [comment] 2018-08-10 02:08
@bybai yea this is what I thought. Is there anyway that we can log proof of this status? I’m thinking this is a firmware issue where we get back “off” and send “on” too quickly and fw can’t handle it. But I have no way to prove this and so I don’t think it will be accepted by fw team...

@geissonator is there any way on the bmc journalctl logs to show rest api request coming in and response. And if it’s dropped.. we check the 200 OK but that’s just the rest  server response how do we know that the software is actually doing anything with it ?

**Comment by whowutwut** [comment] 2018-08-10 03:29
@bybai. Is there anything we can add to the code base to get some more logs saved to file instead of command output..  the problem is that we can’t easily recreate so we need to change something so that If it happens we have some proof of the situation.

**Comment by bybai** [comment] 2018-08-10 11:06
Hi @whowutwut,
I added some code to capture `rflash -d` some debug info into rflash log in PR #5495 . 
Based on my new code, I tried `mid05tor12cn05` using firmware under `/root/baiyuan/fw/`, from log, after `power reset` and state is off, sent `power on` request and waited 13 seconds, to check `power state`, it was still `off`, waited for another 12 seconds, retry to set RPOWER_CHECK_ON_REQUEST, the `power state` became on. You can adjust the wait time and log to help reproduce the issue. I think this PR can be used in our development env to debug first.

**Comment by geissonator** [comment] 2018-08-10 12:56
Yeah...from the traces Matt had in the defect I saw this:

# Chassis power off request
Wed Aug  1 14:38:00 2018|1401|phosphor-chassis-state-manager|Change to Chassis Requested Power State  (OFF!)

# Host reboot request 13 sec later
Wed Aug  1 14:38:13 2018|1466|phosphor-host-state-manager|Host State transaction request (Reboot)

# Power off actually completed here (3 seconds after a host reboot was requested)
Wed Aug  1 14:38:16 2018|1401|phosphor-chassis-state-manager|Received signal that power OFF is complete

So really looks like for some reason xcat came in and requested a host reboot before the power off had completed.  Anyway that could happen?  I see lots of talk of On and Off but this was a host reboot request before the off had completed.  

It totally shouldn't take this long to power off, we fixed that in our most recent firmware.

**Closed** 2018-08-21 09:08 UTC
Labels: component:hw_control, sprint2
