### ISSUE TITLE
[Customer] xcatd service can not be started automatically after reboot for RHEL7.2

### ISSUE THREAD

**Issue by fenggaobj** [xcat2/xcat-core#492] opened 2015-11-30 07:39 UTC
We find that there is no link to "/etc/init.d/xcatd" under "/etc/rcX.d/" directory for RHEL7.2 after installing xCAT-server(xCAT-server-2.11-snap201511100307.noarch.rpm). It leads to that xcatd service can not be started automatically after reboot. 
Reinstall xcat-server package manually, the result is the same.

But for ubuntu14.04.3 we find that this function works well.  when we install it, the log shows that

root@ubuntu:/mnt/packages/repos/kit-pcm-4.2.1-ubuntu-14-ppc64el# dpkg -i xcat-server_2.11-snap201510260426_all.deb
Selecting previously unselected package xcat-server.
(Reading database ... 127545 files and directories currently installed.)
Preparing to unpack xcat-server_2.11-snap201510260426_all.deb ...
Unpacking xcat-server (2.11-snap201510260426) ...
Setting up xcat-server (2.11-snap201510260426) ...
update-rc.d: warning: default start runlevel arguments (2 3 4 5) do not match xcatd Default-Start values (3 4 5)
update-rc.d: warning: default stop runlevel arguments (0 1 6) do not match xcatd Default-Stop values (none)
Adding system startup for /etc/init.d/xcatd ...
   /etc/rc0.d/K20xcatd -> ../init.d/xcatd
   /etc/rc1.d/K20xcatd -> ../init.d/xcatd
   /etc/rc6.d/K20xcatd -> ../init.d/xcatd
   /etc/rc2.d/S20xcatd -> ../init.d/xcatd
   /etc/rc3.d/S20xcatd -> ../init.d/xcatd
   /etc/rc4.d/S20xcatd -> ../init.d/xcatd
   /etc/rc5.d/S20xcatd -> ../init.d/xcatd
Processing triggers for ureadahead (0.100.0-16) ...

**Comment by bybai** [comment] 2015-11-30 09:14
Hi @fenggaobj , In our environment, I can find the link to ../init.d/xcatd. Could you check your steps or how reproduce it ?
```
[root@c910f03c05k23 etc]# ls -l rc0.d/K60xcatd
lrwxrwxrwx 1 root root 15 Sep 24 05:11 rc0.d/K60xcatd -> ../init.d/xcatd
[root@c910f03c05k23 etc]# lsxcatd -v
Version 2.11 (git commit 9885d9acba568e21137ca1be624d0ba8b1655091, built Tue Nov 24 03:05:32 EST 2015)
 ```

**Comment by fenggaobj** [comment] 2015-11-30 09:32
The steps to reproduce:

[root@rhel72mn xcat-core]# rpm -qa | grep xCAT-server
[root@rhel72mn xcat-core]# ls /etc/rc3.d/
K50netconsole  K60pcm  K60pcmamq  S10network  S40perf  S92conserver  S96pmc  S97rhnsd
[root@rhel72mn xcat-core]# chkconfig

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

conserver      	0:off	1:off	2:on	3:on	4:on	5:on	6:off
netconsole     	0:off	1:off	2:off	3:off	4:off	5:off	6:off
network        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
pcmamq         	0:off	1:off	2:off	3:off	4:off	5:off	6:off
perf           	0:off	1:off	2:off	3:on	4:on	5:on	6:off
pmc            	0:off	1:off	2:off	3:on	4:on	5:on	6:off
rhnsd          	0:off	1:off	2:on	3:on	4:on	5:on	6:off
[root@rhel72mn xcat-core]# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 Beta (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:beta:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2 Beta"
[root@rhel72mn xcat-core]# rpm -ivh xCAT-server-2.11-snap201511240305.noarch.rpm
warning: xCAT-server-2.11-snap201511240305.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID c6565bc9: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:xCAT-server-4:2.11-snap2015112403################################# [100%]
[root@rhel72mn xcat-core]# ls /etc/rc3.d/
K50netconsole  K60pcm  K60pcmamq  S10network  S40perf  S92conserver  S96pmc  S97rhnsd
[root@rhel72mn xcat-core]# chkconfig

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

conserver      	0:off	1:off	2:on	3:on	4:on	5:on	6:off
netconsole     	0:off	1:off	2:off	3:off	4:off	5:off	6:off
network        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
pcmamq         	0:off	1:off	2:off	3:off	4:off	5:off	6:off
perf           	0:off	1:off	2:off	3:on	4:on	5:on	6:off
pmc            	0:off	1:off	2:off	3:on	4:on	5:on	6:off
rhnsd          	0:off	1:off	2:on	3:on	4:on	5:on	6:off

**Comment by whowutwut** [comment] 2015-11-30 21:10
Maybe we should look into implementing a ``systemd`` replacement for xcatd...  @pdlun92

**Comment by bybai** [comment] 2015-12-01 08:57
@fenggaobj ， In our FVT daily build environment, this cannot be reproduced in redhat7.2 ppc64le MN.

**Comment by fenggaobj** [comment] 2015-12-01 09:00
@bybai Verified in RHEL7.2 GA, the issue can not be reproduced. It's the reason of OS(7.2 Beta) system call.

**Comment by fenggaobj** [comment] 2015-12-22 03:00
When redhat-lsb-core is installed, the issue is reproduced in RHEL7.2 GA.
we checked the xCAT-server.spec file, we find that if redhat-lsb-core is installed,  xCAT-server.spec will take "/usr/lib/lsb/install_initd  /etc/init.d/xcatd" to add xcatd to rc. but it does not work.

[root@mn19 lsb]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
[root@mn19 lsb]#
[root@mn19 lsb]# chkconfig

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

conserver       0:off   1:off   2:on    3:on    4:on    5:on    6:off
netconsole      0:off   1:off   2:off   3:off   4:off   5:off   6:off
network         0:off   1:off   2:on    3:on    4:on    5:on    6:off
pcm             0:off   1:off   2:on    3:on    4:on    5:on    6:off
pcmamq          0:off   1:off   2:off   3:off   4:off   5:off   6:off
perf            0:off   1:off   2:off   3:off   4:off   5:off   6:off
pmc             0:off   1:off   2:off   3:off   4:off   5:off   6:off
rhnsd           0:off   1:off   2:on    3:on    4:on    5:on    6:off
xcatpostinit1   0:off   1:off   2:on    3:on    4:on    5:on    6:off
[root@mn19 lsb]# /usr/lib/lsb/install_initd /etc/init.d/xcatd
[root@mn19 lsb]# chkconfig

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

conserver       0:off   1:off   2:on    3:on    4:on    5:on    6:off
netconsole      0:off   1:off   2:off   3:off   4:off   5:off   6:off
network         0:off   1:off   2:on    3:on    4:on    5:on    6:off
pcm             0:off   1:off   2:on    3:on    4:on    5:on    6:off
pcmamq          0:off   1:off   2:off   3:off   4:off   5:off   6:off
perf            0:off   1:off   2:off   3:off   4:off   5:off   6:off
pmc             0:off   1:off   2:off   3:off   4:off   5:off   6:off
rhnsd           0:off   1:off   2:on    3:on    4:on    5:on    6:off
xcatpostinit1   0:off   1:off   2:on    3:on    4:on    5:on    6:off

**Comment by immarvin** [comment] 2015-12-22 06:40
``/usr/lib/lsb/install_initd `` is a tool shipped by ``redhat-lsb-core`` ,

````
[root@c910f03c05k21 ~]# rpm -qf /usr/lib/lsb/install_initd 
redhat-lsb-core-4.1-27.el7.ppc64le
````
it's manpage mentions:
````
Installation and removal of init.d files

An init.d file is installed by copying it into /etc/init.d (which may be a symlink to another location). This can be done by the package installer. During the package's postinstall script, the program "/usr/lib/lsb/install_initd" configures the distribution's boot script system to call the package's init.d file at the appropriate time.

The install_initd program takes a single argument, the pathanme to the /etc/init.d file. For example:

	/usr/lib/lsb/install_initd /etc/init.d/example.com-coffeed

When a software package is removed, the package's preuninstall script shall call /usr/lib/lsb/remove_initd and pass the pathname to the /etc/init.d file. The package manager is still responsible for removing the /etc/init.d file; the remove_initd program is provided in case the distribution needs to clean up any other modifications in the distribution's boot script system that might have been made by the install_initd program. For example:

	/usr/lib/lsb/remove_initd /etc/init.d/example.com-coffeed

There should be a tool available to the user (e.g., RedHat's chkconfig) which can be used by the system administrator to easily manipulate at which init levels a particular init.d script is started or stopped. This specification currently does not specify such an interface, however.
````

However, this command does not work in redhat7:

````
[root@c910f03c05k21 ~]# chkconfig

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

conserver       0:off   1:off   2:on    3:on    4:on    5:on    6:off
netconsole      0:off   1:off   2:off   3:off   4:off   5:off   6:off
network         0:off   1:off   2:on    3:on    4:on    5:on    6:off
rhnsd           0:off   1:off   2:on    3:on    4:on    5:on    6:off
xcatd           0:off   1:off   2:off   3:off   4:off   5:off   6:off
xcatpostinit1   0:off   1:off   2:off   3:off   4:off   5:off   6:off
[root@c910f03c05k21 ~]# /usr/lib/lsb/install_initd /etc/init.d/xcatd
[root@c910f03c05k21 ~]# chkconfig

Note: This output shows SysV services only and does not include native
      systemd services. SysV configuration data might be overridden by native
      systemd configuration.

      If you want to list systemd services use 'systemctl list-unit-files'.
      To see services enabled on particular target use
      'systemctl list-dependencies [target]'.

conserver       0:off   1:off   2:on    3:on    4:on    5:on    6:off
netconsole      0:off   1:off   2:off   3:off   4:off   5:off   6:off
network         0:off   1:off   2:on    3:on    4:on    5:on    6:off
rhnsd           0:off   1:off   2:on    3:on    4:on    5:on    6:off
xcatd           0:off   1:off   2:off   3:off   4:off   5:off   6:off
xcatpostinit1   0:off   1:off   2:off   3:off   4:off   5:off   6:off
````
since ``lsb`` is not a base package and is poorly matained, I suggest not to use it in  spec file.

**Comment by tingtli** [comment] 2016-03-24 02:49
@fenggaobj  If this bug is fixed, would you please close it?

**Comment by fenggaobj** [comment] 2016-03-29 02:33
Close it first, if reproduced, reopen it.

**Comment by robin2008** [comment] 2016-04-02 11:46
I think the issue could be easily reproduced.

Obviously when redhat-lsb-core is installed, xcat-server does not handle the chkconfig well on rhel7.2 and cause that xcatd and perhaps other services are not enabled.

I'm not sure when xcatd will move to systemd, but now it is better to fix in spec first.

**Comment by immarvin** [comment] 2016-04-29 03:27
hi, after the redhat-lsb-core is installed, the "/usr/lib/lsb/install_initd" is a link to "../../../sbin/chkconfig"
````
[root@c910f03fsp03v140 ~]# ll //usr/lib/lsb/install_initd         
lrwxrwxrwx 1 root root 23 Apr 29 03:32 //usr/lib/lsb/install_initd -> ../../../sbin/chkconfig
````

**Comment by immarvin** [comment] 2016-04-29 03:28
can not be recreated

**Comment by daniceexi** [comment] 2016-04-29 06:52
@immarvin But the redhat-lsb-core is not installed by default. So that means for a customer, if using default configuration, the xcatd won't be started by default.

**Closed** 2016-05-04 02:46 UTC
Labels: status:invalid
