### ISSUE TITLE
xcat unmounting and mounting over ems /dev/pts

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#424] opened 2015-11-17 14:04 UTC
xCAT-server-2.11-snap201510281333.noarch
We have seen 2 occurrences of /dev/pts being unmounted. In a recent problems we found the /dev/pts of a diskless image mounted over our /dev/pts:
 Filesystem     1K-blocks  Used Available Use% Mounted on
devpts                 0     0         0    - /install/netboot/rhels7.2rc/ppc64le/xiaolu_diskless_image/rootimg/dev/pts
EMS is c712ems2

**Comment by tingtli** [comment] 2015-11-18 08:39
I tried but failed to reproduce this defect on FVT's environment.
Do we have steps to reproduce it?

**Comment by hu-weihua** [comment] 2015-11-20 08:50
I can't reproduce this defect either. below are what I found:

1. @markprez  mentioned there is a diskless image mount on ``/dev/pts``. xcat itself won't mount ``/dev/pts``  during ``genimage`` process. If it involved IB installation, IB does do a mount operation, but IB only mount  ``/dev``, ``/proc`` and ``/sys`` but won't mount ``/dev/pts``.  so I think it's not xcat leads to the diskless image mount over ``/dev/pts``, maybe some application installed by xcatd did this mount operation.

2. I got another description of this defect from @wwzhubj and xiaolu,  for some reason, @wwzhubj hit ``ctrl+c`` during genimage running  and xiaolu did ``rm -rf /install/netboot/rhels7.2rc/ppc64le/xiaolu_diskless_image/rootimg/``. then c712ems2's systemd core dumped and IST got below error::

         Nov 17 03:14:09 c712ems2 sshd: Couldn't open /dev/null: No such file or directory
         Nov 17 03:14:28 c712ems2 sshd: Couldn't open /dev/null: No such file or directory
         Nov 17 03:15:00 c712ems2 sshd: Couldn't open /dev/null: No such file or directory
     
  @neo954 offer a guess for this in a internal email ::

          When genimage was running, in some of the postscripts, like installing OFED, 
          it need to bind mount /dev, /proc and /sys to the chroot environment. But in some case, 
          these bind mounted directories did not umounted successfully.      
          Maybe the system administrator press Ctrl-C, or something went wrong, 
          and the cleanup did not finish. In this case, 
          directory /dev, /proc and /sys were still mounted in the chroot environment. 
          If the system administrator did not notice directory /dev was still mounted under the 
          chroot environment and try to delete the rootimg directory. 
          It will delete all the files and subdirectories under /dev. 
          It is due to /dev directory is bind mounted. And the systemd may crash in this situation.
          Since systemd needs /dev/initctl, and /dev/null.

    Yes, it's possible for IB installation script to umount ``/dev`` failed, but when IB installation script try to umount  ``/dev``, it will try 99 times. even it failed finally, one information "umount /install/.../dev failed" will be output.   so if IB installation script got terminal signal, it will do right things. 

    But refer to another defect#448, it's possible for IB installation script can't receive terminal signal when user terminated genimage by ``ctrl+c``, so the ``/dev`` was still mounted after that. at this time. if one delete diskless rootimg directory, the real ``/dev`` directory will be affected.

     Defect#448 will be handled in xcat2.12

**Comment by hu-weihua** [comment] 2015-11-21 08:26
@markprez, we can't resolve the root cause of this issue in xcat2.11, in order to don't affect your team's work, we strongly recommend your team using ``rmimage``  to delete diskless image instead of using ``rm -rf ....``
 when the pull request #451 is merged, this walk around can be used.

**Comment by hu-weihua** [comment] 2015-11-30 08:07
The pull request #451 has been merged, so @markprez  you can use this workaround now.  
For the root reason of this bug #448 will be fixed in xcat 2.12. if you need to follow this bug, please follow #448 , I close this bug now.

**Closed by hu-weihua** 2015-11-30 08:07 UTC
Labels: status:pending, type:bug
