### ISSUE TITLE
tabch and tabdump commands can not deal with invalid attribute names

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#5150] opened 2018-04-30 20:24 UTC
Both `tabdump` and `tabch` commands hang when given invalid attribute name.
For example, this works
```
[root@stratton01 xcat]# tabdump -w 'mask==255.0.0.0' networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"10_0_0_0-255_0_0_0","10.0.0.0","255.0.0.0","enP2p1s0f0","10.0.0.101",,"10.6.29.1",,,,,,,,,,,,"REST API TEST",
"50_0_0_0-255_0_0_0","50.0.0.0","255.0.0.0","enP2p1s0f2","<xcatmaster>",,"50.6.29.2",,,,,,,,,,,,"REST API TEST",
[root@stratton01 xcat]#
```

But this hangs:
```
[root@stratton01 xcat]# tabdump -w 'netmask==255.0.0.0' networks
^C
[root@stratton01 xcat]#
```

Similarly, this works:
```
[root@stratton01 xcat]# tabch netname='abcnetwork' networks.comments="ABC"

[root@stratton01 xcat]# tabdump networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
"10_0_0_0-255_0_0_0","10.0.0.0","255.0.0.0","enP2p1s0f0","10.0.0.101",,"10.6.29.1",,,,,,,,,,,,"REST API TEST",
"50_0_0_0-255_0_0_0","50.0.0.0","255.0.0.0","enP2p1s0f2","<xcatmaster>",,"50.6.29.2",,,,,,,,,,,,"REST API TEST",
"172_10_0_0-255_255_0_0","172.10.0.0","255.255.0.0","enP34p1s0f0",,,,,,,,,,,,,,,,
"172_11_0_0-255_255_0_0","172.11.0.0","255.255.0.0","enP34p1s0f1",,,,,,,,,,,,,,,,
"private_192","192.168.0.0","255.255.0.0",,,,,,,,,,,,,,,,,
"autotest_ent","192.168.10.0","255.255.255.0",,"192.168.10.3",,,,,,,,,,,,,,,
"abcnetwork",,,,,,,,,,,,,,,,,,"ABC",
[root@stratton01 xcat]#
```

But this hangs:
```
[root@stratton01 xcat]# tabch networkname='abcnetwork' networks.comments="ABC"
^C
[root@stratton01 xcat]#
```

**Comment by robin2008** [comment] 2018-05-09 06:05
See many  internal error logs related to such operations:
```
May  8 09:15:36 stratton01 xcat[49439]: xCAT: Allowing tabch -d masks=255.0.0.0 networks for root from localhost
May  8 09:15:36 stratton01 xcat[49440]: DEBUG xcatd: dispatch request 'tabch -d masks=255.0.0.0 networks' to plugin 'tabutils'
May  8 09:15:36 stratton01 xcat[49440]: DEBUG xcatd: handle request 'tabch' by plugin 'tabutils''s process_request
May  8 09:15:36 stratton01 xcat[6699]: xcatd: possible BUG encountered by xCAT DB worker Can't call method "execute" on an undefined value at /opt/xcat/lib/perl/xCAT/Table.pm line 3719.
```

And xcatd does not handle the plugin which is die, and will leave a zombie there.

**Comment by robin2008** [comment] 2018-05-09 07:25
And it seems the root cause by `delEntries`, as we don't find the hang on other MN.
```
root      36123  36121  0 5月08 ?       00:00:06 xcatd: UDP listener
root      36124  36123  0 5月08 ?       00:00:00 xcatd: Discovery worker
root      36125  36121  0 5月08 ?       00:00:00 xcatd: install monitor
root      36126  36121  0 5月08 ?       00:00:00 xcatd: Command log writer
root      48191   6698  0 5月08 ?       00:00:54 xcatd SSL: delEntries for root@localhost
root      48192  48191  0 5月08 ?       00:00:00 xcatd SSL: delEntries for root@localhost: tabutils instance
root      79925  74085  0 03:08 pts/33   00:00:00 vim sbin/xcatd
root      80057  36121  0 03:14 ?        00:00:00 xcatd: SSL listener
root      80079  79727  0 03:15 pts/37   00:00:00 grep --color=auto xcatd
[root@stratton01 xcat]# grep -r "delEntries" ./cluster*
./cluster.log:May  7 15:03:56 stratton01 xcat[14771]: xCAT: Allowing delEntries for wsuser from localhost
./cluster.log:May  8 09:12:05 stratton01 xcat[48191]: DEBUG xcatd: open new process : xcatd SSL: delEntries for root@localhost
./cluster.log:May  8 09:12:05 stratton01 xcat[48191]: xCAT: Allowing delEntries for root from localhost
./cluster.log:May  8 09:12:05 stratton01 xcat[48192]: DEBUG xcatd: dispatch request 'delEntries ' to plugin 'tabutils'
./cluster.log:May  8 09:12:05 stratton01 xcat[48192]: DEBUG xcatd: handle request 'delEntries' by plugin 'tabutils''s process_request
```

For example,
```
[root@c910f03c05k20 ~]# tabdump -w 'netmask==255.0.0.0' networks
#netname,net,mask,mgtifname,gateway,dhcpserver,tftpserver,nameservers,ntpservers,logservers,dynamicrange,staticrange,staticrangeincrement,nodehostname,ddnsdomain,vlanid,domain,mtu,comments,disable
[root@c910f03c05k20 ~]# tabch networkname='abcnetwork' networks.comments="ABC"
Error: [c910f03c05k20]: DB error ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

**Comment by robin2008** [comment] 2018-05-09 07:40
After I kill `48192`, all is fine, it might lock the Sqlite file when die due to some unexpected error in plugin.

**Comment by robin2008** [comment] 2018-05-09 09:30
So here are two issue:
1, run restapi will cause DB error
2, when DB error,  the plugin cannot be quit with error, and it cause the SSL listener stay after restartxcatd

**Comment by zet809** [comment] 2018-05-21 02:46
hi, @gurevichmark , will you pls check whether the tabch or tabdump still hung with Xu Bin's fix. It seems the build after "May 12" have include the fix.

**Comment by gurevichmark** [comment] 2018-05-21 15:52
@zet809  Running with May 16 build, I am still seeing problems:

1. For `tabch` using invalid attribute name like `networkxyz` used to hang, now it exits with no error and RC0:
```
[root@stratton01 ~]# tabch networkxyz='abcnetwork' networks.comments="ABC"
[root@stratton01 ~]# echo $?
0
[root@stratton01 ~]#
```
2. For `tabdump` using invalid attribute name like `netmaskxyz` used to hang, now it exits with a messy error message:
```
[root@stratton01 ~]# tabdump -w 'netmaskxyz==255.0.0.0' networks
Error: tabutils plugin bug, pid 21096, process description: 'xcatd SSL: tabdump for root@localhost: tabutils instance' with error 'Can't use string ("*XCATBUGDETECTED*:Can't call met"...) as a HASH ref while "strict refs" in use at /opt/xcat/lib/perl/xCAT_plugin/tabutils.pm line 1301.
'
[root@stratton01 ~]#
```

Looking at PR #5184, it states that this issue is only partially fixed. Is there another PR in the works ?

**Comment by zet809** [comment] 2018-05-22 05:35
OK, I see, it just fix the hung problem, not return a useful error message. 
Will try to fix it tomorrow

**Comment by zet809** [comment] 2018-11-28 09:54
hi, @gurevichmark , the issue mentioned in your comments above have been fixed with https://github.com/xcat2/xcat-core/pull/5846, pls review and verify. Thx!

**Comment by neo954** [comment] 2018-12-05 03:58
The fix of this issue is verified in xCAT version `2.14.5-snap201812040717`.

```
# tabch networkxyz='abcnetwork' networks.comments="ABC"
Error: [c910f03c01p09]: No column "networkxyz" in table "networks"
# tabdump -w 'netmaskxyz==255.0.0.0' networks
Error: [c910f03c01p09]: No column "netmaskxyz" in table "networks"
```

**Comment by neo954** [comment] 2018-12-05 03:59
I will close this one.

**Closed by neo954** 2018-12-05 03:59 UTC
Labels: component:obj_db_cmds, sprint3, status:pending
