### ISSUE TITLE
todays development version of xcat has a dramatically longer netboot time.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#1882] opened 2016-09-23 00:48 UTC
There is a dramatic increase in the time it takes to decompress the rootimg.cpio.gz with the development branch of xcat:

lsxcatd -v
Version 2.12.3 (git commit ee11ecddb7e3c323b11857826a072303ae5a7b20, built Thu Sep 22 06:16:00 EDT 2016)

we recently changed from the "latest" xcat core code to the development code to pick up some recent changes.

previous version:
```
	==> xCAT-latest/xcat-core.repo <==
	[xcat-core]
	name=xCAT 2 Core packages
	baseurl=http://xcat.org/files/xcat/repos/yum/latest/xcat-core
	enabled=1
	gpgcheck=1
	gpgkey=http://xcat.org/files/xcat/repos/yum/latest/xcat-core/repodata/repomd.xml.key
	
	==> xCAT-latest/xcat-dep.repo <==
	[xcat-dep]
	name=xCAT 2 depedencies
	baseurl=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le
	enabled=1
	gpgcheck=1
	gpgkey=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le/repodata/repomd.xml.key
```

and the new version:
[root@c460mgt01 yum.repos.d]# head xCAT-latest/*.repo
```
	==> xCAT-latest/xcat-core.repo <==
	[xcat-core]
	name=xCAT 2 Core packages
	baseurl=http://xcat.org/files/xcat/repos/yum/latest/xcat-core
	enabled=1
	gpgcheck=1
	gpgkey=http://xcat.org/files/xcat/repos/yum/latest/xcat-core/repodata/repomd.xml.key
	
	==> xCAT-latest/xcat-dep.repo <==
	[xcat-dep]
	name=xCAT 2 depedencies
	baseurl=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le
	enabled=1
	gpgcheck=1
	gpgkey=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/ppc64le/repodata/repomd.xml.key
```

We noticed a dramatic increase in the boot time of our production network boot image, due to the time it takes to decompress the rootimg.cpio.gz file.

If we boot a minimal image based on rhels7.2-ppc64le-netboot-compute. we see the following in the console log:

```
[Thu Sep 22 20:03:37 2016][   13.667160] dracut-initqueue[1475]: --2016-09-23 00:03:33--  http://10.1.0.1//install/netboot/rhels7.2/ppc64le/rh72-op5-garison-nb/rootimg.cpio.gz
[Thu Sep 22 20:03:37 2016][   13.667998] dracut-initqueue[1475]: Connecting to 10.1.0.1:80... connected.
[Thu Sep 22 20:03:37 2016][   13.668353] dracut-initqueue[1475]: HTTP request sent, awaiting response... 200 OK
[Thu Sep 22 20:03:37 2016][   13.668710] dracut-initqueue[1475]: Length: 225853776 (215M) [application/x-gzip]
[Thu Sep 22 20:03:37 2016][   13.669065] dracut-initqueue[1475]: Saving to: 'rootimg.cpio.gz'
[Thu Sep 22 20:03:37 2016][   13.669537] dracut-initqueue[1475]: 0K .......... ..........  0%  144M 1s
[Thu Sep 22 20:03:38 2016][   13.669925] dracut-initqueue[1475]: 50K .......... ..........  0%  114M 2s
[Thu Sep 22 20:03:38 2016][   13.670334] dracut-initqueue[1475]: 100K.......... ..........  0%  113M 2s
[Thu Sep 22 20:03:38 2016][   13.670724] dracut-initqueue[1475]: 150K.......... ..........  0%  113M 2s
[Thu Sep 22 20:03:38 2016][   13.671250] dracut-initqueue[1475]: 200K.......... ..........  0%  114M 2s
[Thu Sep 22 20:03:38 2016][   13.671642] dracut-initqueue[1475]: 250K.......... ..........  0% 66.8M 2s
[Thu Sep 22 20:03:38 2016][   13.672036] dracut-initqueue[1475]: 300K.......... ..........  0%  114M 2s
[Thu Sep 22 20:03:38 2016][   13.672547] dracut-initqueue[1475]: 350K.......... ..........  0%  113M 2s
[Thu Sep 22 20:03:38 2016][   13.672937] dracut-initqueue[1475]: 400K.......... ..........  0%  113M 2s
[Thu Sep 22 20:03:38 2016][   13.673331] dracut-initqueue[1475]: 450K.......... ..........  0%  113M 2s
[Thu Sep 22 20:03:38 2016][   13.673844] dracut-initqueue[1475]: 500K.......... ..........  0%  114M 2s
[Thu Sep 22 20:03:38 2016][   13.674231] dracut-initqueue[1475]: 550K.......... ..........  0%  113M 2s

...
[Thu Sep 22 20:08:07 2016][  281.170160] dracut-initqueue[1475]: 210200K .......... .......... 95%  319M 13s
[Thu Sep 22 20:08:07 2016][  281.260167] dracut-initqueue[1475]: 210250K .......... .......... 95%  368M 12s
[Thu Sep 22 20:08:07 2016][  281.320138] dracut-initqueue[1475]: 210300K .......... .......... 95%  353M 12s
[Thu Sep 22 20:08:07 2016][  281.360159] dracut-initqueue[1475]: 210350K .......... .......... 95%  373M 12s
[Thu Sep 22 20:08:07 2016][  281.393557] dracut-initqueue[  281.451400] dracut-initqueue[1475]: 210450K .......... .......... .......... .......... .......... 95%  372M 12s
[Thu Sep 22 20:08:07 2016][  281.451646] dracut-initqueue[1475]: 210500K .......... .......... 95%  371M 12s
[Thu Sep 22 20:08:07 2016][  285.520168] systemd-journald[1202]: Received SIGTERM from PID 1 (n/a).
```

So the decompression time went to 4m 30 seconds for 250MB.

however our production image is currently 10GB and the boot time goes up to hours...
```
[Thu Sep 22 19:37:37 2016][   23.487699] dracut-initqueue[1596]: --2016-09-22 23:37:22--  http://10.1.0.1//install/netboot/rhels7.2/ppc64le/rh72_op5_compute/rootimg.cpio.gz
[Thu Sep 22 19:37:37 2016][   23.488516] dracut-initqueue[1596]: Connecting to 10.1.0.1:80... connected.
[Thu Sep 22 19:37:37 2016][   23.488870] dracut-initqueue[1596]: HTTP request sent, awaiting response... 200 OK
[Thu Sep 22 19:37:37 2016][   23.489222] dracut-initqueue[1596]: Length: 8093812379 (7.5G) [application/x-gzip]
[Thu Sep 22 19:37:37 2016][   23.489571] dracut-initqueue[1596]: Saving to: 'rootimg.cpio.gz'
[Thu Sep 22 19:37:37 2016][   23.490064] dracut-initqueue[1596]: 0K .......... ..........  0%  139M 56s
[Thu Sep 22 19:37:37 2016][   23.490454] dracut-initqueue[1596]: 50K.......... ..........  0%  113M 62s
[Thu Sep 22 19:37:37 2016][   23.490844] dracut-initqueue[1596]: .......... .......... ..........  0%  113M 64s
[Thu Sep 22 19:37:37 2016][   23.491232] dracut-initqueue[1596]: 150K .......... ..........  0%  113M 65s
[Thu Sep 22 19:37:37 2016][   23.491787] dracut-initqueue[1596]: 200K .......... ..........  0%  113M 66s
[Thu Sep 22 19:37:37 2016][   23.492178] dracut-initqueue[1596]: 250K .......... ..........  0%  115M 66s
....
[Thu Sep 22 20:46:00 2016][ 4125.400339] dracut-initqueue[1596]: 3507800K .......... .......... .......... .......... .......... 44%  115M 85m15s                                                       
[Thu Sep 22 20:46:00 2016][ 4125.430316] dracut-initqueue[1596]: 3507850K .......... .......... .......... .......... .......... 44%  114M 85m15s                                                       
[Thu Sep 22 20:46:00 2016][ 4125.470331] dracut-initqueue[1596]: 3507900K .......... .......... .......... .......... .......... 44%  113M 85m15s                                                       
[Thu Sep 22 20:46:01 2016][ 4125.510326] dracut-initqueue[1596]: 3507950K .......... .......... .......... .......... .......... 44%  113M 85m15s                                                       
[Thu Sep 22 20:46:01 2016][ 4125.570356] dracut-initqueue[1596]: 3508000K .......... .......... .......... .......... .......... 44% 96.9M 85m15s                                 


and still going after over an hour... and only 1/2 done.

```

**Comment by daniceexi** [comment] 2016-09-23 01:17
@immarvin and @penguhyang 

Please take a look whether this caused by the change that we made to support ``tar`` to archive the osmage?

**Comment by ralphbellofatto** [comment] 2016-09-23 01:28
These look like they are wget progress messages.


Ralph Bellofatto
IBM TJ Watson Research
1-914-945-3321
ralphbel@us.ibm.com

**Comment by ralphbellofatto** [comment] 2016-09-23 02:46
while this may not be the cause of the change in behavior, I made an
experimental change to the following two files:

/opt/xcat/share/xcat/netboot/rh/dracut/xcatroot
/opt/xcat/share/xcat/netboot/rh/dracut_033/xcatrool

I changed:
                        logger "Getting $imgurl..."
                        echo Getting $imgurl...
                        if ! wget $imgurl; then
                [ "$xcatdebugmode" > "0" ] && logger -t xcat -p debug
"downloading $imgurl failed,retrying...."
                                rm -f $FILENAME
                                sleep 27
                        fi


to:
                        logger "Getting $imgurl..."
                        echo Getting $imgurl...
                        if ! wget -nv $imgurl; then
                [ "$xcatdebugmode" > "0" ] && logger -t xcat -p debug
"downloading $imgurl failed,retrying...."
                                rm -f $FILENAME
                                sleep 27
                        fi


Adding the "-nv" flag to wget to silence its output.,

This dramatically cut down the time for the small 250Mb image to just
seconds and for the 10GB load it went down to: ??


I think something caused wget have a default progress wget progress
indicator to change to somethihing that printed more often.


for the 250MB file... we now just see:
```
[Thu Sep 22 22:15:17 2016][   17.305230] sd 6:0:0:0: [sdg] Attached SCSI
removable disk
[Thu Sep 22 22:15:20 2016][   15.547816] dracut-initqueue[1480]: 2016-09-23
02:15:12 URL:
http://10.1.0.1//install/netboot/rhels7.2/ppc64le/rh72-op5-garison-nb/rootimg.cpio.gz
 [225840356/225840356] -> "rootimg.cpio.gz" [1]
[Thu Sep 22 22:15:26 2016][   22.055373] dracut-initqueue[1480]: 1417132
blocks
[Thu Sep 22 22:15:26 2016][[32m  OK  [0m] Started dracut initqueue hook.
```

and for 10GB file we see:
```
```

I think this change is actually desirable, as it improves the download time
from what it was before when wget printed messages less often..., the
console output still slowed things down.





Ralph Bellofatto
IBM TJ Watson Research
1-914-945-3321
ralphbel@us.ibm.com

**Comment by ralphbellofatto** [comment] 2016-09-23 03:07
just fyi,

our large 6GB compressed file was taking about 5.6 minutes to download and
now with the wget -nv option it takes 3.8 minutes...

So, i think the change is worth leaving in,....

If there are wget flags that can print out the download speed that would be
useful information that we are giving up here,

**Comment by immarvin** [comment] 2016-09-23 05:26
fixed in https://github.com/xcat2/xcat-core/pull/1884

**Closed** 2016-09-23 05:31 UTC
Labels: component:os_provision, priority:high
