### ISSUE TITLE
Need to fully understand rcons in openbmc environment

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3543] opened 2017-07-26 19:01 UTC
There's something that we don't quite understand with conserver and how it interacts with the openbmc ssh port...   I need someone to really understand if we are doing things correctly and when we need to re-run makeconservercf ....  

With OpenBMC ssh port to expose the console, we should be able to have multiple console sessions opened.   Here are some snips of what I have seen some issues with but really don't have the time to investigate.. 

Some questions: 
* [ ] what causes the: `console: connect(): 782@localhost: Connection refused`
* [x] When do we need to run makeconservercf: 
    It seems we don't need to run makeconsercf with sshpass or `-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null` fix
* [x] What happens when firmware is updated , can the console re-connect
* [ ] Can we do better in `rspconfig <> sshcfg` it seems to always append... 

### connection refused until after makeconservercf, can't re-create this... 
```
[root@fs2vm110 ~]# rspconfig p9euh01 sshcfg
[OpenBMC development support] Using this version of xCAT, ensure firware level is at v1.99.6-0-r1, or higher.
p9euh01: ssh keys copied to 10.6.7.254
[root@fs2vm110 ~]# rcons p9euh01
console: connect(): 782@localhost: Connection refused
[root@fs2vm110 ~]# rcons p9euh01
console: connect(): 782@localhost: Connection refused
[root@fs2vm110 ~]# makeconservercf p9euh01
[root@fs2vm110 ~]# rcons p9euh01
[Enter `^Ec?' for help]
[disconnect]
```

### After copying the ssh keys, still required password when doing ssh.... ???! 
```
[root@fs2vm110 ~]# rspconfig p9euh01 sshcfg
[OpenBMC development support] Using this version of xCAT, ensure firware level is at v1.99.6-0-r1, or higher.
p9euh01: ssh keys copied to 10.6.7.254
[root@fs2vm110 ~]# rcons p9euh01
[Enter `^Ec?' for help]



^A^?[disconnect]
[root@fs2vm110 ~]# ssh 10.6.7.254
Warning: Permanently added '10.6.7.254' (RSA) to the list of known hosts.
root@10.6.7.254's password:
```

### Does multiple rcons work from different servers defining the same machine?

**Comment by whowutwut** [comment] 2017-08-01 21:12
@zet809  who should look into this? We probably should understand this when we are doing firmware updates...    maybe @gurevichmark or @xuweibj ?

**Comment by zet809** [comment] 2017-08-02 06:47
Hi, @whowutwut , I'd like @chenglch to take a look at the rcons related issues.

**Comment by zet809** [comment] 2017-08-08 01:59
* [ ] Investigate the root cause for the issue above.

**Comment by cxhong** [comment] 2017-08-08 02:50
I am working on rcons issue for openbmc node also.  I am trying to add "sshpass" code back from 
PR #2511.   if we use sshpass command, need to add sshpass package to xcat-dep.  
@zet809 , is any reason we can't add ip address to bmc node definition?   if we can do that,  we can use rspconfig command to send ssh key over to bmc after bmcdiscover command 
````
[root@briggs01 ~]# bmcdiscover --range 172.12.140.102 --sn sn02 -w
node-70e28414291b:
        objtype=node
        groups=all
        bmc=172.12.140.102
        cons=openbmc
        mgt=openbmc
        serial=1318D3A
        servicenode=sn02
        conserver=sn02

[root@briggs01 ~]# chdef node-70e28414291b ip=172.12.140.102
1 object definitions have been created or modified.

[root@briggs01 ~]# lsdef node-70e28414291b
Object name: node-70e28414291b
    bmc=172.12.140.102
    cons=openbmc
    conserver=sn02
    groups=all
    hwtype=bmc
    ip=172.12.140.102
    mgt=openbmc
    nodetype=mp
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=1318D3A
    servicenode=sn02

[root@briggs01 ~]# rspconfig node-70e28414291b sshcfg
node-70e28414291b: ssh keys copied to 172.12.140.102

````
In this way, we can config bmc node as passwordless before rcons.

**Comment by chenglch** [comment] 2017-08-14 05:51
@whowutwut , @cxhong , I don't understand your problem clearly. Below is my steps to use `rcons` or `ssh`. At first, password is required with `rcons` command. After `rspconfig <node> sshcfg` against the node, there is no prompt for password anymore. 

```
[root@stratton01 ~]# rcons p9euh01
[Enter `^Ec?' for help]
Acquiring startup lock...done
If the console cannot connect, please verify whether ssh keys has been configured on the bmc for root user
root@10.6.7.254's password: [disconnect]
[root@stratton01 ~]#
[root@stratton01 ~]#
[root@stratton01 ~]#
[root@stratton01 ~]# rspconfig p9euh01 sshcfg
p9euh01: [openbmc_debug] POST https: //10.6.7.254/login -d { "data": [ "root", "0penBmc" ] }
p9euh01: [openbmc_debug] login_response 200 OK
p9euh01: [openbmc_debug] GET https: //10.6.7.254
p9euh01: [openbmc_debug] rspconfig_sshcfg_response 200 OK
p9euh01: ssh keys copied to 10.6.7.254
[root@stratton01 ~]# rcons p9euh01
[Enter `^Ec?' for help]
Acquiring startup lock...done
If the console cannot connect, please verify whether ssh keys has been configured on the bmc for root user

[xCAT Genesis running on p9euh01 /]#
[xCAT Genesis running on p9euh01 /]# [disconnect]
[root@stratton01 ~]# lsdef p9euh01
Object name: p9euh01
    addkcmdline=inst.sshd
    arch=ppc64le
    bmc=10.6.7.254
    cons=openbmc
    groups=all,compute,p9
    ip=10.6.7.1
    mac=70:e2:84:14:24:84
    mgt=openbmc
    netboot=petitboot
    os=rhels7.4-ea2-kernel-4.11.0-10-peags-by
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    profile=compute
    provmethod=rhels7.4-ea2-kernel-4.11.0-10-peags-by-ppc64le-install-compute
    status=powering-off
    statustime=07-26-2017 13:51:35
    updatestatus=synced
    updatestatustime=06-28-2017 02:13:46
[root@stratton01 ~]# ssh 10.6.7.254
root@witherspoon:~#
root@witherspoon:~#
root@witherspoon:~# exit
logout
Connection to 10.6.7.254 closed.
[root@stratton01 ~]#
```

**Comment by whowutwut** [comment] 2017-08-16 01:33
After the firmware is flashed, if we flash BMC,, the RSA keys change on the BMC OS, this requires us to rerun `makeconservercf` I believe...  otherwise we will not be able to connect. 

Or we might also need to clear out the keys in known_hosts...  does having `sshpass` simplify this? Or do we still have the issues with known_hosts.  Maybe we still have the issue because rcons is using ssh instead of going through ipmitool.

**Comment by chenglch** [comment] 2017-08-23 07:39
@whowutwut , I don't think `sshpass` can simplify this as the BMC could not notify the correct time for ssh client to reconnect automatically. This is also a limitation of conserver which do not allow to reconnect the console session for specified nodes, after `makeconserercf` or `conserver restart`, all of the session under the conserver will be reconnected.


For the error `console: connect(): 782@localhost: Connection refused` you mentioned above, I created 1000 fake nodes to run the ssh session within the conserver. This error message is recreated and the root cause is the conserver itself which could not create the session immediately as the workload is very heavy.

**Comment by chenglch** [comment] 2017-08-25 01:59
Maybe we could use `ssh -p 2200 -o PasswordAuthentication=no <bmcip>` in `/cons/openbmc` to disable the password prompt so that the ssh session can be reconnected automatically.

**Comment by whowutwut** [comment] 2017-08-28 14:15
Here's another example that I'm not sure what is going on...      On the left side, I'm trying to rcons to the node...  No password prompt is asked , on the right side, the password prompt is returned.... 

![image](https://user-images.githubusercontent.com/10049070/29777390-d5fcbefc-8bd9-11e7-8f92-2738c2f7fdf9.png)

I would expect at least the password prompt to be asked as well on the rcons side.

**Comment by whowutwut** [comment] 2017-08-28 14:33
Playing some more, it seems like the prompt for password does appear after you hit enter. 

So it's silently there, but the user cannot see it...

```

[root@briggs01 ~]# rcons node-70e28414280d
[Enter `^Ec?' for help]
  <----- Hit Enter here....  This gives it a bad password... result in the below.. 
Permission denied, please try again.
root@172.12.253.111's password:
```

Any idea why this has changed? ( @cxhong @chenglch )

**Comment by whowutwut** [comment] 2017-08-29 19:27
After Updating firmware to a dev build.... 

```
[root@briggs01 20170829_VLAN_DEV]# rcons node-70e28414280d
console: SSLVerifyCallback(): error with certificate at depth: 0
console: SSLVerifyCallback():  issuer  = /CN=xCAT CA
console: SSLVerifyCallback():  subject = /CN=briggs01.pok.stglabs.ibm.com
console: SSLVerifyCallback():  error #7: certificate signature failure
console: SSL negotiation failed
70367064202656:error:04067084:rsa routines:RSA_EAY_PUBLIC_DECRYPT:data too large for modulus:rsa_eay.c:738:
70367064202656:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:249:
70367064202656:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264:
```

That above means we have to rerun makeconservercf....  but is ugly....
```
[root@briggs01 20170829_VLAN_DEV]# makeconservercf node-70e28414280d
[root@briggs01 20170829_VLAN_DEV]# rcons node-70e28414280d
[Enter `^Ec?' for help]
root@172.12.253.119's password:

```

The password prompts immediately...   I think we have to see what happens with the OP910 driver target for Friday... 9/1

**Comment by zet809** [comment] 2017-09-18 05:52
Hi, @whowutwut , do you think we can close this task or move to next release?

**Comment by zet809** [comment] 2017-09-21 08:19
Move to 2.13.8 to trace the 1st and 4th question from @whowutwut

**Comment by chenglch** [comment] 2017-10-26 09:17
I hope we could take some effort to try https://github.com/chenglch/consoleserver which could solve the #4043 and the `sshpass` issue here together. As ssh library and goruntine are used, it may help save the server resource to connect to the openbmc console for a large amount of nodes.

**Comment by whowutwut** [comment] 2017-10-26 19:27
@chenglch How do we try this and how would we package this into xCAT?  I looked at your README, what changes would be needed in xCAT to do this? Any dependency rpms, how do we revert back?  

We could try this on briggs01 if we can switch back and forth easily to test it out.

**Comment by whowutwut** [comment] 2017-12-20 20:39
@chenglch 
Is this something we could close out for this 2.13.9 release? Or should we keep this issue open? I think we will start to test gocons and see if that is a viable solution for some of the issues with conserver...

**Comment by chenglch** [comment] 2017-12-21 02:29
@whowutwut , I think it's ok to close this as `gcons` use ssh library from golang instead of the ssh command.

**Closed** 2017-12-21 16:12 UTC
Labels: component:openbmc, priority:high, sprint2, type:feature
