### ISSUE TITLE
Conserver-xcat should be required to update to 8.2.1 after code change in PR #3252 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3286] opened 2017-06-19 14:15 UTC
With PR #3252 , we broke compatibility with older versions of conserver.   Using the new xCAT code with the older version of conserver results in this msg: 

```
console: SSL negotiation failed
70367486123328:error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1259:SSL alert number 48
```

The pull request should require a > 8.2.1 change in the spec file so we pull in the updated version of conserver when updating xCAT.

**Comment by whowutwut** [comment] 2017-06-19 14:18
@neo954 @hu-weihua  I don't think our migration testing catches this, does it?   Essentially, we are running a 2.13.4 base and pointing to the xcat-core and xcat-deps public repo.  Update xCAT and see if functions still run.  Here because conserver is not updated at the same time as #3252 , it breaks conserver...

**Comment by hu-weihua** [comment] 2017-06-20 03:32
@whowutwut , actually, we did not have any case against ``conserver`` and ``rflash``  in daily regression up to now. it belongs to totally manual case. Because it is hard for a automatic case to monitor console.  Not to mention the migration. You brought up a good question.  I will try to find out a way to automatically test it. maybe monitor ``/var/log/consoles/CN`` is a option

**Comment by neo954** [comment] 2017-06-20 10:23
@whowutwut,

Actually, xCAT team did not expect the end user to mix older version `xcat-core` and newer version `xcat-dep` or vice versa. xCAT team expect the end user use `xcat-core` and `xcat-dep` matching each other.

I do not think xCAT provides such forward/backward compatible by mixing old `xcat-dep` and new `xcat-core`.

In the old days, xCAT packages all have broken package dependency declarations. At that time, try to do xCAT upgrading with command `yum install xCAT` will get only one package, `xCAT` to be upgraded. That is before pull requests #2195 and #2198 were getting merged.

For this historical reason, all xCAT migration test cases covered this problem by not calling `yum install xCAT` along, but use a long list of `xcat-core` and `xcat-dep` package names. And `go-xcat` covered this problem as well.

We may need to improve our test case coverage if you do think this is a critical problem.

**Comment by whowutwut** [comment] 2017-06-20 11:10
@chenglch does the pull request fix the error message that is listed in the initial description?   It's not clear from the pull request information and I'm not familiar with that code. So does this mean any version of conserver should work?

So  in this issue I suggested to make a spec file change to pull in the updated version and your pull request Fixes a calculation errro. Is that the plan of action?

**Comment by whowutwut** [comment] 2017-06-20 11:23
@neo954 Would like to see @chenglch response to the question above... 

But... we support `yum update` and we support the ability to update from the daily build each day.  What had happened is we created a new xcat-dep package and made changes to conserver.  So the daily build of xcat-core without the updated `conserver-xcat` caused that problem above in the initial post. 

If that problem was unintentional and does not require xcat-core to be upgraded to 8.2.1 and PR #3291 fixes the bug, how would we have caught this bug during normal FVT? (I understand that these are extreme corner cases, but if we can add a few that we find, the testing will be stronger)   If we do need to sync up conserver version, then by adding a spec file change, it would force the package to be updated when users are upgrading from 2.13.4 -> 2.13.5. 
We support this upgrade path, correct?  We allow the repo file to be pointing to the development build. 

Even though you claim that users should always have the correct xcat-core and xcat-dep packages configured in their repo, I just made a change to add  another command to call `yum update '*xcat*'` because our documented step for updating is only using `'*xCAT*'` and this does not catch the `conserver-xcat` or `ipmitool-xcat` package.   

I think this is the issue I'm bringing up, not whether or not we support the combinations of software, but to make sure that the user gets the correct dependency package installed with a certain version of xCAT... I don't see how this is a bad thing.  I think we should also make a spec file change for ipmitool... if we are updating to a certain version we want to make sure it's install for the user is consistent.   I don't see how this is a bad thing.

**Comment by chenglch** [comment] 2017-06-20 11:23
@whowutwut , yes, from the pull request #3252, I check the `console/conserver` version at first and then keep or modify the `conserver.cf` or `console.rc` based on the version number. But I made a mistake whiling comparing the version numbers. This pull request fixed it. 

So If we just upgrade `xcat-core` separately, `conserver` should work correctly.

**Comment by whowutwut** [comment] 2017-06-20 11:26
@chenglch  Thanks, I  do still think we want to help the users get to the correct level or conserver and ipmitool.  Because the only way to do that today is with 2 commands

```
yum update "*xCAT*"
yum update "*xcat*"
```

I think it's error prone to have two commands executed to update the product.  Perhaps we need to find a way to get a package list that is case-insensitive and then install using that package list.. 

Why would we NOT want the user to be at the latest version of the xcat-deps if we provided it?

**Comment by chenglch** [comment] 2017-06-20 11:31
@whowutwut , We have some discussion for the two options in pull request #3252, most of us think it's more friendly to users.

**Comment by neo954** [comment] 2017-06-21 02:29
@whowutwut, Actually, you can do it in one command.

    yum update '*xCAT*' '*xcat*'

**Comment by whowutwut** [comment] 2017-06-22 03:56
Attempt to verify the issue... 

# Install earlier build of xCAT 2.13.4 and make sure rcons works...

```
[root@fs2vm112 ~]# makeconservercf frame5u39
[root@fs2vm112 ~]# rcons frame5u39
[Enter `^Ec?' for help]

Red Hat Enterprise Linux Server 7.4 Beta (Pegas)
Kernel 4.9.0-10.el7.ppc64le on an ppc64le

frame5u39 login: [disconnect]
```

### Then update to 6/19/17 build and re-create the problem 
```
[root@fs2vm112 xcat-core]# lsxcatd -v
Version 2.13.5 (git commit 54a1e38ddd12351b306d7eae3c495e33d81d9d91, built Mon Jun 19 06:15:40 EDT 2017)
[root@fs2vm112 xcat-core]# rpm -qa | grep conserver
conserver-xcat-8.1.16-10.ppc64le
[root@fs2vm112 xcat-core]# rcons frame5u39
console: SSL negotiation failed
70366558133568:error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1259:SSL alert number 48
```

### Update to 6/21/17 build 
```
[root@fs2vm112 xcat-core]# lsxcatd -v
Version 2.13.5 (git commit b8c402c86a23ce0203bcc8da8712f89ebd4eb305, built Wed Jun 21 06:15:37 EDT 2017)
[root@fs2vm112 xcat-core]# rpm -qa | grep conserver
conserver-xcat-8.1.16-10.ppc64le
```

## Does not seem to work...
```
[root@fs2vm112 xcat-core]# rcons frame5u39
console: SSL negotiation failed
70367197175104:error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1259:SSL alert number 48
[root@fs2vm112 xcat-core]# makeconservercf frame5u39
[root@fs2vm112 xcat-core]# rcons frame5u39
console: SSL negotiation failed
70366792949056:error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1259:SSL alert number 48
```

@chenglch Any ideas? 
You can access this machine 10.3.31.112

**Comment by chenglch** [comment] 2017-06-22 05:31
@whowutwut , I try to install 2.13.4 then upgrade to the latest build on my own env.
```
Version 2.13.5 (git commit b8c402c86a23ce0203bcc8da8712f89ebd4eb305, built Wed Jun 21 06:15:37 EDT 2017)
```
I do not encounter the problem like you mentioned.

I guess you install the stable xcat 2.13.4 at first , then upgrade to `6/19/17` build, at last upgrade to `6/21/17`.
If so, the step is wrong. Both `6/19/17` and `6/21/17` are development build, they are not stable. As `6/19/17` contains the bug that I have fixed in `6/21/17`, it  influence the migration result, `6/21/17` do not recover the mistake made by `6/19/17`.
The verify step should be installing `2.13.4` at first, then upgrade to `6/21/17` directly.

**Comment by zet809** [comment] 2017-06-23 08:04
Hi, @neo954 , had your test covered this scenario? If not, will you pls verify this defect? Thx!

**Closed** 2017-06-23 09:11 UTC
Labels: component:packaging, priority:high, status:pending

**Comment by neo954** [comment] 2017-06-25 06:11
@zet809, The only problem we still have is that the new xcat-dep, cannot support old xcat-core.

    xcat-core 2.13.5    can work with xcat-dep 2.13.5 which ships conserver-xcat-8.2.1
    xcat-core 2.13.5    can work with xcat-dep 2.13.4 which ships conserver-xcat-8.1.16
    xcat-core 2.13.4    can work with xcat-dep 2.13.4 which ships conserver-xcat-8.1.16
    xcat-core 2.13.4 CANNOT work with xcat-dep 2.13.5 which ships conserver-xcat-8.2.1

In the past, latest xcat-dep always support old xcat-core. This is the first time, newer version xcat-dep cannot support old xcat-core.
