### ISSUE TITLE
Record dhcp and tftp log twice in /var/log/messages when get these logs back in xcat 2.12

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#1325] opened 2016-06-17 02:46 UTC
When we got DHCP and TFTP logs back to ``/var/log/messages`` in xcat 2.12.  Every line log is recorded twice in ``/var/log/messages``.

Because this log is the input of xcat discovery probe, so it result in xcat discovery probe can't work well.

Below are some logs captured from rhels7.2:

    Jun 16 19:19:12 fs1 dhcpd: DHCPREQUEST for 192.168.5.169 from 42:2d:0a:03:1f:6e via enP4p1s0f2
    Jun 16 19:19:12 fs1 dhcpd: DHCPREQUEST for 192.168.5.169 from 42:2d:0a:03:1f:6e via enP4p1s0f2
    Jun 16 19:19:12 fs1 dhcpd: DHCPACK on 192.168.5.169 to 42:2d:0a:03:1f:6e (fs2vm110) via enP4p1s0f2
    Jun 16 19:19:12 fs1 dhcpd: DHCPACK on 192.168.5.169 to 42:2d:0a:03:1f:6e (fs2vm110) via enP4p1s0f2
    Jun 16 19:19:12 fs1 dhcpd: Added new forward map from fs2vm110.pok.stglabs.ibm.com to 192.168.5.169
    Jun 16 19:19:12 fs1 dhcpd: Added new forward map from fs2vm110.pok.stglabs.ibm.com to 192.168.5.169
    Jun 16 19:19:12 fs1 dhcpd: Added reverse map from 169.5.168.192.in-addr.arpa. to fs2vm110.pok.stglabs.ibm.com
    Jun 16 19:19:12 fs1 dhcpd: Added reverse map from 169.5.168.192.in-addr.arpa. to fs2vm110.pok.stglabs.ibm.com
    Jun 16 19:31:52 fs1 dhcpd: DHCPREQUEST for 192.168.5.167 from 42:20:0a:03:1f:c9 (mgXgeneratedvm1) via enP4p1s0f2
    Jun 16 19:31:52 fs1 dhcpd: DHCPREQUEST for 192.168.5.167 from 42:20:0a:03:1f:c9 (mgXgeneratedvm1) via enP4p1s0f2
    Jun 16 19:31:52 fs1 dhcpd: DHCPACK on 192.168.5.167 to 42:20:0a:03:1f:c9 (mgXgeneratedvm1) via enP4p1s0f2
    Jun 16 19:31:52 fs1 dhcpd: DHCPACK on 192.168.5.167 to 42:20:0a:03:1f:c9 (mgXgeneratedvm1) via enP4p1s0f2
    Jun 16 20:27:31 fs1 dhcpd: DHCPREQUEST for 192.168.5.31 from 70:e2:84:14:0a:29 via enP4p1s0f2
    Jun 16 20:27:31 fs1 dhcpd: DHCPREQUEST for 192.168.5.31 from 70:e2:84:14:0a:29 via enP4p1s0f2
    Jun 16 20:27:31 fs1 dhcpd: DHCPACK on 192.168.5.31 to 70:e2:84:14:0a:29 via enP4p1s0f2
    Jun 16 20:27:31 fs1 dhcpd: DHCPACK on 192.168.5.31 to 70:e2:84:14:0a:29 via enP4p1s0f2
    Jun 16 21:26:09 fs1 dhcpd: DHCPREQUEST for 192.168.5.29 from 70:e2:84:14:0a:05 via enP4p1s0f2
    Jun 16 21:26:09 fs1 dhcpd: DHCPREQUEST for 192.168.5.29 from 70:e2:84:14:0a:05 via enP4p1s0f2
    Jun 16 21:26:09 fs1 dhcpd: DHCPACK on 192.168.5.29 to 70:e2:84:14:0a:05 via enP4p1s0f2
    Jun 16 21:26:09 fs1 dhcpd: DHCPACK on 192.168.5.29 to 70:e2:84:14:0a:05 via enP4p1s0f2

**Comment by daniceexi** [comment] 2016-06-17 03:24
@neo954 is there anything wrong in our rsyslog cfg file?

**Comment by hu-weihua** [comment] 2016-06-17 07:08
It seems this test server has some specific configuration to rsyslog for some reason.
It isn't a common issue for xcat2.12 rsyslog default configuration.

Hi @whowutwut , Do you know why ``fs1`` has below setup:

    [root@fs1 rsyslog.d]# ll
    -rw-r--r--. 1 root root  49 Oct 12  2015 listen.conf
    -rw-r--r--  1 root root 176 Jun 15 05:14 xcat-cluster.conf
    -rw-r--r--  1 root root 183 Jun 15 05:14 xcat-compute.conf
    -rw-r--r--  1 root root 141 Jun 15 05:14 xcat-debug.conf
    -rw-r--r--  1 root root  53 Apr 25 14:41 xcat-management.conf

    [root@fs1 rsyslog.d]# cat xcat-debug.conf
    # By default, dhcpd use the ``daemon'' facility. Thus dhcp logs will go here.
    # ftp.* is for tftp log.
    daemon.debug;ftp.*		/var/log/messages

    [root@fs1 rsyslog.d]# cat xcat-management.conf
    :fromhost-ip, isequal, "127.0.0.1" /var/log/messages

``xcat-debug.conf`` is a conf shipped by xcat2.12 used to record ``dhcp`` and ``tftp`` log to ``/var/log/messages``.  but on ``fs1``, administrator added additional conf ``xcat-management.conf``, it will record log again.

**Comment by daniceexi** [comment] 2016-06-21 06:41
Since it's invalid, close it.

**Comment by whowutwut** [comment] 2016-06-22 12:21
@hu-weihua  I created that file before the code changed to get messages back into /var/log/messages. But we cannot control the log configuration that admins make to the mgmt node.. So maybe this issues should not be closed but see if we can work around?

**Comment by whowutwut** [comment] 2016-06-22 12:23
I'm also thinking we should make some changes to the rsyslog config files to put the discovery changes into separate logs in /var/log/xcat because the current way is difficult to debug hardware discovery in a very large scale.  Would that break the probe function?

**Comment by daniceexi** [comment] 2016-06-23 00:46
Put the discovery log in another log file should be ok for xcatprobe command, add the monitoring to that log file will work.
If the cluster.log has 1000lines and the discovery logs have 10,000 lines for a scaling cluster, does that help to move discovery log to another file? 
Even we known the benefit to have multiple logs, but the shortage is peoples have to look into all of them. This is inconvenience when we try to diagnostic a complicated problem. This is also hard for a new xCAT user.

**Comment by hu-weihua** [comment] 2016-06-27 06:50
@whowutwut ，If we need to extract dhcp and tftp logs to a new log file, that is ok, we need to change some xcat probe code, but not much. 

Extract these logs to a  separate log file. the one benefit I can think now is xcat probe will be less effect by the configuration in customer's environment. xcat probe will have stable input. 

But just as @daniceexi said, in a scaling cluster, there maybe are so many dhcp logs. maybe in customer's configuration, there are same logs are put into ``/var/log/messages``. so the result are 
1. it needs more space, 
2. pay more i/o expenses
That's acceptable for customer?

**Comment by daniceexi** [comment] 2016-07-06 02:59
since this is not a bug, close it.

**Closed by daniceexi** 2016-07-06 02:59 UTC
Labels: status:invalid, type:bug

**Comment by whowutwut** [comment] 2016-07-08 19:06
@hu-weihua @daniceexi sorry for the slow reply.  I am not talking about putting anything that is going to `/var/log/messages` into a separate log file.  That should stay there for things like dhcp, tftp, etc...  

I'm talking about the messages we are sending to `/var/log/xcat` directory using the logger command (rsyslog)... everything goes into the `computes.log` file.  xcatprobe currently only can probe running discovery, but we need it to probe ended discovery or failed discovery.  We can probe for certain messages that we print in the genesis kernel to report the "status" of the discovery...  "complete" or "inprogress" or "not responding"... etc...  

For example, if we want to discover 100 nodes at the same time, we cannot probe each one.. we will  want them to all run at the same time.  Then if we can only ping 60 machines after 5 hours.. .we know 40 have failed.. but we cannot figure out why.  If the xcatprobe command can identify the 40 failed machines using `computes.log` then no problem.  We don't need to move the logs out of that file. .  but if we cannot, it will be very difficult for a user to debug 40 failed machines. 


Just brainstorming ideas here.. not really saying we should do one thing or another...

**Comment by daniceexi** [comment] 2016-07-09 04:38
@whowutwut We are taking about to run ``xcatprobe discovery`` to run against a time point so that it can **replay** the discovery flow from the message logs. Do you think this feature can handle your request?

**Comment by whowutwut** [comment] 2016-08-16 00:54
Yes, i'm excited to give that function a try in the next few days.
