### ISSUE TITLE
/var/log/xcat/xcat.log has return code but no error messages to help debug postscript errors

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3701] opened 2017-08-16 15:54 UTC
When running postscripts, the logs in `/var/log/xcat/xcat.log`only contain a return code.  It doesn't contain any messages about what went wrong,  so we have to re-run a 2nd time with `updatenode` to figure it out. 

Why doesn't the log contain the errors? 

In log:
```
Wed Aug 16 08:25:43 UTC 2017 Running postscript: mlnxofed_ib_install
Wed Aug 16 08:25:43 UTC 2017 postscript mlnxofed_ib_install return with 1
```

Reason:
```
sn02: Wed Aug 16 08:47:43 UTC 2017 Running postscript: mlnxofed_ib_install
sn02: Mellanox OFED file path is /install/mlnxofed
sn02: Mellanox OFED file is MLNX_OFED_LINUX-4.1-4.0.0.1-rhel7.4-ppc64le.iso
sn02: Mellanox OFED options are --add-kernel-support
sn02: image root path is
sn02: NODESETSTATE is boot
sn02: Downloading Mellanox OFED file MLNX_OFED_LINUX-4.1-4.0.0.1-rhel7.4-ppc64le.iso form http://192.168.92.1//install/mlnxofed ..........
sn02: [Error] Downloading Mellanox OFED file MLNX_OFED_LINUX-4.1-4.0.0.1-rhel7.4-ppc64le.iso failed
sn02: postscript: mlnxofed_ib_install exited with code 1
```

**Comment by whowutwut** [comment] 2017-08-16 15:57
Then when it fails, the return code is 0...

```
sn02: Downloading Mellanox OFED file MLNX_OFED_LINUX-4.1-4.0.0.1-rhel7.4-ppc64le.iso form                      http://192.168.92.1//install/mlnxofed ..........
sn02: [OK]
sn02: Mounting Mellanox OFED file MLNX_OFED_LINUX-4.1-4.0.0.1-rhel7.4-ppc64le.iso ........                     .
sn02: mount: /dev/loop0 is write-protected, mounting read-only
sn02: [OK]
sn02: Start Mellanox OFED installation .........
sn02: TERM environment variable not set.
sn02: Detected rhel7u4 ppc64le. Disabling installing 32bit rpms...
sn02: Note: This program will create MLNX_OFED_LINUX TGZ for rhel7.4 under /tmp/MLNX_OFED_                     LINUX-4.1-4.0.0.1-4.11.0-10.el7a.ppc64le directory.
sn02: See log file /tmp/MLNX_OFED_LINUX-4.1-4.0.0.1-4.11.0-10.el7a.ppc64le/mlnx_ofed_iso.1                     9703.log
sn02: Required kernel (4.11.0-10.el7a.ppc64le) is already supported by MLNX_OFED_LINUX
sn02: Logs dir: /tmp/MLNX_OFED_LINUX-4.1-4.0.0.1.19676.logs
sn02: This program will install the MLNX_OFED_LINUX package on your machine.
sn02: Note that all other Mellanox, OEM, OFED, RDMA or Distribution IB packages will be re                     moved.
sn02: Those packages are removed due to conflicts with MLNX_OFED_LINUX, do not reinstall t                     hem.
sn02:
sn02: Do you want to continue?[y/N]:
sn02: Redirecting to /bin/systemctl restart openibd.service
sn02: Failed to restart openibd.service: Unit not found.
sn02: postscript: mlnxofed_ib_install exited with code 0  <------------------
```

**Comment by whowutwut** [comment] 2017-08-16 16:01
@bybai  Regarding why this failed.... If you take a look at the message, are we not handling the prompt?  Is this a new question prompt?

```
sn02: Those packages are removed due to conflicts with MLNX_OFED_LINUX, do not reinstall t                     hem.
sn02:
sn02: Do you want to continue?[y/N]:  <========================
sn02: Redirecting to /bin/systemctl restart openibd.service
sn02: Failed to restart openibd.service: Unit not found.
```

**Comment by whowutwut** [comment] 2017-08-16 16:13
@bybai  Resolved the above, we added `--force` as an option and it doesn't prompt anymore. But the issue with the status reporting incorrectly and more debug in the logs still applies.  I thought I had opened another issue about this but i can't find it.

**Comment by bybai** [comment] 2017-09-19 02:44
Hi @whowutwut ,  I do not find your mentioned issue about "always return 0 in mlnxofed_ib_install", we can use this issue to trace.
I think there are 2 thing need to do for this issue:
1, enhance doc about:  adding  "--force" as an option, so that it does not prompt anymore.
2, In `mlnxofed_ib_install` code, adding some more error check in some lines, for example, should check `service openibd restart` return code check and print related error messages.
```
        #force openibd load all modules in need, restart again
        sleep 1
        service openibd restart
    fi
```

**Comment by zet809** [comment] 2018-01-30 06:21
Hi, @whowutwut and @bybai , is this still a problem? If not, shall we close this issue? Thx!

**Comment by whowutwut** [comment] 2018-01-31 03:53
I think there are 2 things @bybai identified that have not yet been done, so i think we still need to leave this open.

**Comment by bybai** [comment] 2018-03-12 09:50
Hi @whowutwut, I tried to reproduce this issue on rhels7.4 ppc64le diskful today.
1, I found  "mlnxofed_ib_install always return 0", I will fix it later. 
2, But there is log during "Running postscript: mlnxofed_ib_install" in /var/log/xcat.log, it is different with your descriptions, as following:
```
Mon Mar 12 05:33:24 EDT 2018 [info]: xcat.mypostscript: Running postscript: mlnxofed_ib_install
Mellanox OFED file path is /install/mlnx
Mellanox OFED file is MLNX_OFED_LINUX-4.3-1.0.1.1-rhel7.5alternate-ppc64le.iso
Mellanox OFED options are --add-kernel-support
image root path is
NODESETSTATE is install
Downloading Mellanox OFED file MLNX_OFED_LINUX-4.3-1.0.1.1-rhel7.5alternate-ppc64le.iso form http://10.3.1.9//install/mlnx ..........
[OK]
Mounting Mellanox OFED file MLNX_OFED_LINUX-4.3-1.0.1.1-rhel7.5alternate-ppc64le.iso .........
mount: /dev/loop3 is write-protected, mounting read-only
[OK]
Before hack_uname(), -r=>'3.10.0-693.el7.ppc64le' -m=>'ppc64le'
After  hack_uname(), -r=>'3.10.0-693.el7.ppc64le', -m=>'ppc64le'
Start Mellanox OFED installation .........
TERM environment variable not set.
Detected rhel7u4 ppc64le. Disabling installing 32bit rpms...
^[[31mError: The current MLNX_OFED_LINUX is intended for rhel7.5alternate^[[0m
Redirecting to /bin/systemctl restart openibd.service
Running in chroot, ignoring request.
Mon Mar 12 05:33:26 EDT 2018 [info]: xcat.mypostscript: postscript mlnxofed_ib_install return with 0
```
3, I cannot reproduce "Do you want to continue?[y/N]:  ".

**Comment by whowutwut** [comment] 2018-03-20 13:28
@bybai Perhaps that message came out with version `MLNX_OFED_LINUX-4.1-4.0.0.1-rhel7.4-ppc64le.iso` but if you are looking at a later version, perhaps this behavior has changed?  We can keep going for now and see if it pops up again.

**Closed** 2018-03-21 09:33 UTC
Labels: component:coral, component:os_provision, sprint1, type:usability

**Comment by bybai** [comment] 2018-05-21 07:42
@whowutwut, I looked into  latest verion `MLNX_OFED_LINUX-4.3-1.0.1.1-rhel7.5alternate-ppc64le.iso`, cannot reproduce it, so I closed this issue. We can keep an eye at it later.
