### ISSUE TITLE
mysqlsetup does not work with SLES 12 SP2

### ISSUE THREAD

**Issue by john-d-williams** [xcat2/xcat-core#2658] opened 2017-03-17 09:32 UTC
The mysqlsetup script fails with SLES12 SP2 as it only checks for "SP1" and not "SP1 or greater".

Code fragment.
    # if == 12.1
    if (grep /VERSION_ID="12.1"/, @lines) {

        #$::linuxos == "sles12.1";
        $sp1flag = 1;
    }

As a result the script performs the wrong check to see if MariaDB is running or not. i.e.
Checking the output of "ps -ef | grep mysqld | grep -v grep" contains the string "--datadir" rather than "mysqld".

**Comment by cxhong** [comment] 2017-03-17 14:52
@john-d-williams , which release of xcat you are running?

**Comment by cxhong** [comment] 2017-03-17 17:42
u may hit this issue
https://github.com/xcat2/xcat-core/issues/2297
and fixed in the xcat 2.13.1

**Comment by cxhong** [comment] 2017-03-23 18:36
Closing for now, please feel free to re-open if the issue is existed in the 2.13.1 or later

**Closed by cxhong** 2017-03-23 18:36 UTC
Labels: component:database
