### ISSUE TITLE
[FVT]:go-xcat failed with Digest verification failed

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2286] opened 2016-12-07 08:20 UTC
xCAT 2.13 sles11.4 and ubuntu16.04.1 

```
c910f02c01p26:/ # ./go-xcat  install
Operating system:   linux
Architecture:       ppc64
Linux Distribution: sles
Version:            11.4

Reading repositories ...... done

xCAT is going to be installed.
Continue? [y/n] y
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following NEW packages are going to be installed:
  apache2 apache2-prefork apache2-utils bind bind-chrootenv conserver-xcat dhcp dhcp-server elilo-xcat grub2-xcat ipmitool-xcat libapparmor1 libapr-util1 libapr1 libcap-ng0 libdnet1 liblua5_1 libvirt-client libyajl1 net-snmp netcat-openbsd nfs-kernel-server nmap perl-Crypt-Blowfish perl-Crypt-CBC perl-Crypt-DES perl-Crypt-Rijndael perl-Crypt-SSLeay perl-DBD-SQLite perl-DBI perl-Expect perl-HTML-Parser perl-HTML-Tagset perl-HTTP-Async perl-IO-Socket-INET6 perl-IO-Socket-SSL perl-IO-Stty perl-IO-Tty perl-JSON perl-Net-DNS perl-Net-Daemon perl-Net-HTTPS-NB perl-Net-IP perl-Net-SSLeay perl-Net-Telnet perl-PlRPC perl-SNMP perl-SOAP-Lite perl-Socket6 perl-Sys-Virt perl-TermReadKey perl-libwww-perl perl-xCAT syslinux-xcat tftp xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-probe xCAT-server xnba-undi yaboot-xcat

The following recommended packages were automatically selected:
  apache2-prefork perl-IO-Socket-INET6 perl-IO-Socket-SSL

The following packages are not supported by their vendor:
  conserver-xcat elilo-xcat grub2-xcat ipmitool-xcat perl-Crypt-Blowfish perl-Crypt-CBC perl-Crypt-Rijndael perl-HTTP-Async perl-JSON perl-Net-HTTPS-NB perl-SOAP-Lite perl-Sys-Virt perl-xCAT syslinux-xcat xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-probe xCAT-server xnba-undi yaboot-xcat

66 new packages to install.
Overall download size: 87.7 MiB. After the operation, additional 315.3 MiB will be used.
Continue? [y/n/? shows all options] (y): y
Retrieving package bind-chrootenv-9.9.6P1-0.5.1.ppc64 (1/66), 16.0 KiB (2.0 KiB unpacked)
Retrieving: bind-chrootenv-9.9.6P1-0.5.1.ppc64.rpm [done]
Retrieving package dhcp-4.2.4.P2-0.22.1.ppc64 (2/66), 635.0 KiB (2.1 MiB unpacked)
Retrieving: dhcp-4.2.4.P2-0.22.1.ppc64.rpm [done]
Retrieving package libapparmor1-2.5.1.r1445-55.66.1.ppc64 (3/66), 26.0 KiB (68.0 KiB unpacked)
Retrieving: libapparmor1-2.5.1.r1445-55.66.1.ppc64.rpm [done]
Retrieving package libapr1-1.3.3-11.18.19.8.ppc64 (4/66), 131.0 KiB (381.0 KiB unpacked)
Retrieving: libapr1-1.3.3-11.18.19.8.ppc64.rpm [done]
Retrieving package libcap-ng0-0.6.3-1.7.1.ppc64 (5/66), 20.0 KiB (49.0 KiB unpacked)
Retrieving: libcap-ng0-0.6.3-1.7.1.ppc64.rpm [done]
Retrieving package libdnet1-1.11-87.17.ppc64 (6/66), 24.0 KiB (83.0 KiB unpacked)
Retrieving: libdnet1-1.11-87.17.ppc64.rpm [done]
Retrieving package liblua5_1-5.1.4-1.15.ppc64 (7/66), 87.0 KiB (291.0 KiB unpacked)
Retrieving: liblua5_1-5.1.4-1.15.ppc64.rpm [done]
Retrieving package libyajl1-1.0.11-6.5.103.ppc64 (8/66), 19.0 KiB (53.0 KiB unpacked)
Retrieving: libyajl1-1.0.11-6.5.103.ppc64.rpm [done]
Retrieving package netcat-openbsd-1.89-78.8.1.ppc64 (9/66), 23.0 KiB (41.0 KiB unpacked)
Retrieving: netcat-openbsd-1.89-78.8.1.ppc64.rpm [done]
Retrieving package nfs-kernel-server-1.2.3-18.38.43.1.ppc64 (10/66), 120.0 KiB (347.0 KiB unpacked)
Retrieving: nfs-kernel-server-1.2.3-18.38.43.1.ppc64.rpm [done]
Retrieving package perl-Crypt-DES-2.05-1.22.ppc64 (11/66), 20.0 KiB (44.0 KiB unpacked)
Retrieving: perl-Crypt-DES-2.05-1.22.ppc64.rpm [done]
Retrieving package perl-Crypt-SSLeay-0.57-1.15.1.ppc64 (12/66), 137.0 KiB (388.0 KiB unpacked)
Retrieving: perl-Crypt-SSLeay-0.57-1.15.1.ppc64.rpm [done]
Retrieving package perl-HTML-Tagset-3.20-1.22.ppc64 (13/66), 15.0 KiB (20.0 KiB unpacked)
Retrieving: perl-HTML-Tagset-3.20-1.22.ppc64.rpm [done]
Retrieving package perl-IO-Stty-.02-652.21.ppc64 (14/66), 11.0 KiB (23.0 KiB unpacked)
Retrieving: perl-IO-Stty-.02-652.21.ppc64.rpm [done]
Retrieving package perl-IO-Tty-1.07-118.22.ppc64 (15/66), 41.0 KiB (106.0 KiB unpacked)
Retrieving: perl-IO-Tty-1.07-118.22.ppc64.rpm [done]
Retrieving package perl-Net-Daemon-0.43-1.21.ppc64 (16/66), 40.0 KiB (88.0 KiB unpacked)
Retrieving: perl-Net-Daemon-0.43-1.21.ppc64.rpm [done]
Retrieving package perl-Net-IP-1.25-46.21.ppc64 (17/66), 29.0 KiB (80.0 KiB unpacked)
Retrieving: perl-Net-IP-1.25-46.21.ppc64.rpm [done]
Retrieving package perl-Net-SSLeay-1.64-0.3.1.ppc64 (18/66), 347.0 KiB (1.5 MiB unpacked)
Retrieving: perl-Net-SSLeay-1.64-0.3.1.ppc64.rpm [done]
Retrieving package perl-Net-Telnet-3.03-315.22.ppc64 (19/66), 54.0 KiB (155.0 KiB unpacked)
Retrieving: perl-Net-Telnet-3.03-315.22.ppc64.rpm [done]
Retrieving package perl-Socket6-0.22-1.24.1.ppc64 (20/66), 24.0 KiB (70.0 KiB unpacked)
Retrieving: perl-Socket6-0.22-1.24.1.ppc64.rpm [done]
Retrieving package perl-TermReadKey-2.30-135.22.ppc64 (21/66), 31.0 KiB (84.0 KiB unpacked)
Retrieving: perl-TermReadKey-2.30-135.22.ppc64.rpm [done]
Retrieving package tftp-0.48-101.31.27.ppc64 (22/66), 42.0 KiB (92.0 KiB unpacked)
Retrieving: tftp-0.48-101.31.27.ppc64.rpm [done]
Retrieving package bind-9.9.6P1-0.5.1.ppc64 (23/66), 383.0 KiB (1.4 MiB unpacked)
Retrieving: bind-9.9.6P1-0.5.1.ppc64.rpm [done]
Retrieving package dhcp-server-4.2.4.P2-0.22.1.ppc64 (24/66), 967.0 KiB (3.2 MiB unpacked)
Retrieving: dhcp-server-4.2.4.P2-0.22.1.ppc64.rpm [done]
Retrieving package libapr-util1-1.3.4-12.22.23.1.ppc64 (25/66), 99.0 KiB (277.0 KiB unpacked)
Retrieving: libapr-util1-1.3.4-12.22.23.1.ppc64.rpm [done]
Retrieving package nmap-4.75-1.30.1.ppc64 (26/66), 1.0 MiB (4.6 MiB unpacked)
Retrieving: nmap-4.75-1.30.1.ppc64.rpm [done]
Retrieving package libvirt-client-1.2.5-3.76.ppc64 (27/66), 6.0 MiB (30.3 MiB unpacked)
Retrieving: libvirt-client-1.2.5-3.76.ppc64.rpm [.done]
Retrieving package perl-HTML-Parser-3.56-1.18.1.ppc64 (28/66), 108.0 KiB (258.0 KiB unpacked)
Retrieving: perl-HTML-Parser-3.56-1.18.1.ppc64.rpm [done]
Retrieving package perl-Expect-1.21-1.15.ppc64 (29/66), 73.0 KiB (166.0 KiB unpacked)
Retrieving: perl-Expect-1.21-1.15.ppc64.rpm [done]
Retrieving package perl-PlRPC-0.2019-30.18.ppc64 (30/66), 33.0 KiB (69.0 KiB unpacked)
Retrieving: perl-PlRPC-0.2019-30.18.ppc64.rpm [done]
Retrieving package perl-Net-DNS-0.63-43.10.1.ppc64 (31/66), 248.0 KiB (566.0 KiB unpacked)
Retrieving: perl-Net-DNS-0.63-43.10.1.ppc64.rpm [done]
Retrieving package perl-IO-Socket-INET6-2.56-3.10.4.1.ppc64 (32/66), 18.0 KiB (29.0 KiB unpacked)
Retrieving: perl-IO-Socket-INET6-2.56-3.10.4.1.ppc64.rpm [done]
Retrieving package perl-SNMP-5.4.2.1-8.12.22.1.ppc64 (33/66), 167.0 KiB (673.0 KiB unpacked)
Retrieving: perl-SNMP-5.4.2.1-8.12.22.1.ppc64.rpm [done]
Retrieving package apache2-utils-2.2.12-1.51.52.1.ppc64 (34/66), 126.0 KiB (222.0 KiB unpacked)
Retrieving: apache2-utils-2.2.12-1.51.52.1.ppc64.rpm [done]
Retrieving package perl-Sys-Virt-1.2.5-2.100.ppc64 (35/66), 298.0 KiB (1.3 MiB unpacked)
Retrieving: perl-Sys-Virt-1.2.5-2.100.ppc64.rpm [done]
Retrieving package perl-libwww-perl-5.816-2.23.1.ppc64 (36/66), 367.0 KiB (809.0 KiB unpacked)
Retrieving: perl-libwww-perl-5.816-2.23.1.ppc64.rpm [done]
Retrieving package perl-DBI-1.607-1.16.ppc64 (37/66), 743.0 KiB (2.0 MiB unpacked)
Retrieving: perl-DBI-1.607-1.16.ppc64.rpm [done]
Retrieving package net-snmp-5.4.2.1-8.12.22.1.ppc64 (38/66), 368.0 KiB (1.1 MiB unpacked)
Retrieving: net-snmp-5.4.2.1-8.12.22.1.ppc64.rpm [done]
Retrieving package apache2-2.2.12-1.51.52.1.ppc64 (39/66), 790.0 KiB (2.7 MiB unpacked)
Retrieving: apache2-2.2.12-1.51.52.1.ppc64.rpm [done]
Retrieving package perl-IO-Socket-SSL-1.38-5.2.2.ppc64 (40/66), 64.0 KiB (128.0 KiB unpacked)
Retrieving: perl-IO-Socket-SSL-1.38-5.2.2.ppc64.rpm [done]
Retrieving package perl-DBD-SQLite-1.14-11.14.ppc64 (41/66), 46.0 KiB (133.0 KiB unpacked)
Retrieving: perl-DBD-SQLite-1.14-11.14.ppc64.rpm [done]
Retrieving package apache2-prefork-2.2.12-1.51.52.1.ppc64 (42/66), 293.0 KiB (859.0 KiB unpacked)
Retrieving: apache2-prefork-2.2.12-1.51.52.1.ppc64.rpm [done]
Retrieving package xCAT-probe-4:2.12.4-snap201611102359.noarch (43/66), 70.0 KiB (339.0 KiB unpacked)
Retrieving: xCAT-probe-2.12.4-snap201611102359.noarch.rpm [done]
Retrieving package xCAT-buildkit-4:2.12.4-snap201611102359.noarch (44/66), 68.0 KiB (303.0 KiB unpacked)
Retrieving: xCAT-buildkit-2.12.4-snap201611102359.noarch.rpm [done]
Retrieving package conserver-xcat-8.1.16-10.ppc64 (45/66), 203.0 KiB (555.0 KiB unpacked)
Retrieving: conserver-xcat-8.1.16-10.ppc64.rpm [done]

Warning: Digest verification failed for file 'conserver-xcat-8.1.16-10.ppc64.rpm'
[/var/cache/zypp/packages/xcat-dep/conserver-xcat-8.1.16-10.ppc64.rpm]

  expected 13ba89bc81ca71aa38fad4859f054a895afa6b0d
  but got  0e2386542592fe59a3159e0a899b9653bad4dac0

Accepting packages with wrong checksums can lead to a corrupted system and in extreme cases even to a system compromise.

However if you made certain that the file with checksum '0e23..' is secure, correct
and should be used within this operation, enter the first 4 characters of the checksum
to unblock using this file on your own risk. Empty input will discard the file.

Unblock or discard? [0e23/? shows all options] (discard): discard
Failed to provide Package conserver-xcat-8.1.16-10. Do you want to retry retrieval?

[xcat-dep|http://xcat.org/files/xcat/repos/yum/xcat-dep/sles11/ppc64] Can't provide file './conserver-xcat-8.1.16-10.ppc64.rpm' from repository 'xcat-dep'
History:
 - conserver-xcat-8.1.16-10.ppc64.rpm has wrong checksum

Abort, retry, ignore? [a/r/i] (a): a
Problem occured during or after installation or removal of packages:
Installation aborted by user

Please see the above error message for a hint.


Boo-boo
=======

Something went wrong. :(

Please check log file `/tmp/go-xcat.log' for more details.
```

**Comment by tingtli** [comment] 2016-12-07 08:21
@whowutwut @zet809 @neo954  Please take a look

**Comment by tingtli** [comment] 2016-12-07 09:21
Some errors on other platform
```
c910f03c17k24: Warning: Digest verification failed for file 'elilo-xcat-3.14-4.noarch.rpm'
c910f03c17k24: [/var/cache/zypp/packages/xcat-dep/elilo-xcat-3.14-4.noarch.rpm]
c910f03c17k24:
c910f03c17k24:   expected a30a987163aba950335473d3d903f62bffd31d3f
c910f03c17k24:   but got  7827ab5404f2d05aee18b4a3cb07e979ffa07945
c910f03c17k24:
c910f03c17k24: Accepting packages with wrong checksums can lead to a corrupted system and in extreme cases even to a system compromise.
c910f03c17k24:
c910f03c17k24: However if you made certain that the file with checksum '7827..' is secure, correct
c910f03c17k24: and should be used within this operation, enter the first 4 characters of the checksum
c910f03c17k24: to unblock using this file on your own risk. Empty input will discard the file.
c910f03c17k24:
c910f03c17k24: Unblock or discard? [7827/? shows all options] (discard): discard
c910f03c17k24: Abort, retry, ignore? [a/r/i] (a): a
c910f03c17k24: Failed to provide Package elilo-xcat-3.14-4. Do you want to retry retrieval?
c910f03c17k24:
c910f03c17k24: [xcat-dep|http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/ppc64le] Can't provide file './elilo-xcat-3.14-4.noarch.rpm' from repository 'xcat-dep'
c910f03c17k24: History:
c910f03c17k24:  - elilo-xcat-3.14-4.noarch.rpm has wrong checksum
c910f03c17k24: Problem occured during or after installation or removal of packages:
c910f03c17k24: Installation aborted by user
c910f03c17k24:
c910f03c17k24: Please see the above error message for a hint.
```

**Comment by tingtli** [comment] 2016-12-07 09:22
@neo954  As we discussed , please sync the xcat-dep to xcat.org. And we will rerun the test. Thanks!
I think both linux and Ubuntu should be rsynced.

**Comment by whowutwut** [comment] 2016-12-07 12:26
Is this resolved? I thought we saw this last time and it was caused by pointing to c910loginx03 and there is something wrong with that node.

**Comment by daniceexi** [comment] 2016-12-07 14:09
Now @zet809 and @neo954 though it caused by the sync failure when rsync dependencies from build server to xcat.org. Redo can fix this issue. @neo954 mentioned that add more options for 'rsync' command might help.

**Comment by immarvin** [comment] 2016-12-07 14:18
@neo954 has updated xcat-dep online repo under https://xcat.org/files/xcat/repos/yum/xcat-dep/ with the compressed xcat-dep tarball at about 17:00 CN time this afternoon, we verified that the sha1 hash of the package and the sha1 in the repodata xml have been the same now.

@whowutwut , you mentioned `` it was caused by pointing to c910loginx03 and there is something wrong with that node.``, how did it cause this issue?

**Comment by whowutwut** [comment] 2016-12-07 15:09
@immarvin @zet809 @neo954  I will re-send the email that I sent out 9/29 regarding this issue.  There's something that is different between loginx01 and loginx03, I believe it's caused by whatever is installed by the team on loginx03 where we do not have those changes on loginx01... 

On @tingtli node, I ran `go-xcat` to make sure I can hit the same digest problem... 
```
c910f02c01p26:/ # ./go-xcat install
Operating system:   linux
Architecture:       ppc64
Linux Distribution: sles
Version:            11.4
....
...
Please see the above error message for a hint.


Boo-boo
=======

Something went wrong. :(

Please check log file `/tmp/go-xcat.log' for more details.
```

Then changed the default gateway...

```
c910f02c01p26:/ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         c910loginx03    0.0.0.0         UG    0      0        0 eth0   <=============
10.0.0.0        *               255.0.0.0       U     0      0        0 eth0
loopback        *               255.0.0.0       U     0      0        0 lo
link-local      *               255.255.0.0     U     0      0        0 eth0

c910f02c01p26:/ # route del default gw c910loginx03
c910f02c01p26:/ # route add default gw c910loginx01

c910f02c01p26:/ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         c910loginx01    0.0.0.0         UG    0      0        0 eth0
10.0.0.0        *               255.0.0.0       U     0      0        0 eth0
loopback        *               255.0.0.0       U     0      0        0 lo
link-local      *               255.255.0.0     U     0      0        0 eth0
```

Then running `go-xcat` was successful...

```
....


xCAT has been installed!
========================

If this is the very first time xCAT has been installed, run the following
commands to set environment variables into your PATH:

    for sh,
        `source /etc/profile.d/xcat.sh'
    or csh,
        `source /etc/profile.d/xcat.csh'
c910f02c01p26:/ #
```

**Comment by whowutwut** [comment] 2016-12-13 14:05
Rejected Issue, closing out

**Closed by whowutwut** 2016-12-13 14:05 UTC
Labels: priority:high, status:rejected, xCAT 2.13
