### ISSUE TITLE
[FVT]Failed to show the installing status after rnetboot CN even after 5 minutes.

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1166] opened 2016-05-20 06:57 UTC
Test ENV:
```
[root@c910f result]# rpm -qa | grep -i xCAT
xCAT-server-2.12-snap201605190710.noarch
xCAT-test-2.12-snap201605190711.noarch
syslinux-xcat-3.86-2.noarch
xCAT-genesis-base-x86_64-2.12-snap201605051534.noarch
ipmitool-xcat-1.8.15-1.x86_64
xCAT-client-2.12-snap201605190710.noarch
xCAT-buildkit-2.12-snap201605190711.noarch
xCAT-2.12-snap201605190711.x86_64
elilo-xcat-3.14-4.noarch
conserver-xcat-8.1.16-10.x86_64
grub2-xcat-2.02-0.16.el7.snap201506090204.noarch
perl-xCAT-2.12-snap201605190710.noarch
xCAT-genesis-scripts-x86_64-2.12-snap201605190711.noarch
[root@c910f result]# cat /etc/*release
Red Hat Enterprise Linux Server release 6.7 (Santiago)
Red Hat Enterprise Linux Server release 6.7 (Santiago)
```
Description: Install CN with autotest case, case begin at 1:07PM, 5 minutes later after rnetboot CN, check the CN status, it is booted, but the time is 00:20PM, this is the last booted time, that means 5 minutes later, the CN status is not changed to show this installation. Then the case failed at 1:19PM, rcons CN, it shows that the CN is still being installed.
```
------START:reg_linux_diskfull_installation_flat::Time:Fri May 20 01:07:20 2016------
RUN:lsdef -l c9 | grep status

[lsdef -l c910 | grep status] Running Time:0 sec
RETURN: rc = 0
OUTPUT:
    status=booted
    statustime=05-20-2016 00:20:17
------END::reg_linux_diskfull_installation_flat::Failed::Time:Fri May 20 01:15:19 2016 ::Duration::479 sec------
```
At 1:27 PM this OS is installed successfully.
```
[root@c910f0 result]# lsdef c910f04x20 | grep status
    status=booted
    statustime=05-20-2016 01:27:26
```

**Comment by daniceexi** [comment] 2016-05-20 07:20
We already had a story to track this issue that showing the ``power on`` status after running the ``rpower on``.

**Comment by caomengmeng** [comment] 2016-05-25 02:15
@daniceexi  This reproduced in ppc64le rh7.2 test environment when install diskful CN in today's autotest enviroment.
So if it is duplicated issue with the story before, would you please send me the number, I will add comments to that story and close this one.

**Comment by daniceexi** [comment] 2016-05-25 02:31
Refer to the bug #980

**Comment by immarvin** [comment] 2016-05-25 02:32
There is no guarantee that the installation will be finished after "rnetboot" 5 minutes later, so please do not assume this in your test cases, you can set a maximum wait time such as 30 minutes, then if the status does not change before this ,your cases can report this as a failure.

**Comment by daniceexi** [comment] 2016-05-25 02:33
@immarvin Here, I think @caomengmeng want to check the whether the installation has been started. If the status is not change in 5m, there might be problem happened.

**Comment by immarvin** [comment] 2016-05-25 02:37
The status should be "installing" if the installation begin, so the problem is that why the "installing" status is missing

**Comment by immarvin** [comment] 2016-05-25 02:40
the status chain is "installing-->booting-->booted", the time between "booting" and "booted" might be quite short, there is possibility that the "booting" status can not be caught by the test cases.

**Comment by caomengmeng** [comment] 2016-05-25 05:28
@immarvin in our test cases, we don't check the middle status, only check if it is booted successfully or not. We wait 5 minutes using sleep 600, then using a loop to check if the status is booted or not, it is more than 30 in total for every installation cases. 

And I was told that after rnetboot or rpowe rest, the status should be powering-off/on then others, so please make this clearly. And I see powering off on x86 multi disk machine. not as you say the status chain is "installing-->booting-->booted"? So I am not sure if the problem is installing is missing or not, or powering-of is missing or not, but why after 5 minutes the CN status is not changed, still the status last time.

**Comment by caomengmeng** [comment] 2016-05-30 03:59
On ppc64, failed to install the MN, even after change the status to be null.
Then there isn't any status updated.
```
[root@c910f02c01p12 log]# lsdef c910f02c01p13 | grep status
    statustime=05-29-2016 11:05:16
    updatestatus=synced
    updatestatustime=04-22-2015 05:31:50
[root@c910f02c01p12 xcat]# lsdef c910f02c01p14 | grep status
    statustime=05-29-2016 11:05:19
    updatestatus=synced
    updatestatustime=06-30-2015 06:51:03
```

**Comment by caomengmeng** [comment] 2016-05-31 05:09
On ppc64le, failed to reinstall CN after rpower boot commands;
```
RUN:lsdef -l c910f03fsp03v07 | grep status

[lsdef -l c910f03fsp03v07 | grep status] Running Time:1 sec
RETURN rc = 0
OUTPUT:
    status=booted
    statustime=05-30-2016 13:02:28
CHECK:output =~ booted  [Pass]
```
This automation test case started at 
```
------START:ubuntu_migration2_p8le::Time:Mon May 30 13:20:36 2016------
FILENAME:/opt/xcat/share/xcat/tools/autotest/testcase/migration/ubuntule_migration2_p8le

```
So the status is the last one, rpower boot doesn't work.

**Comment by daniceexi** [comment] 2016-06-17 08:40
The ``rsetboot`` issue has been fixed in another issue. The status change issue will be covered by #980. So close this one.

**Closed by daniceexi** 2016-06-17 08:40 UTC
Labels: component:os_provision, priority:normal, type:bug, xCAT 2.12.1 Sprint 1
