### ISSUE TITLE
syncfiles fails during stateful deployment but updatenode -F works

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#5252] opened 2018-05-25 17:03 UTC
Hi, 

I'm seeing some resurgence of #4455 / #4484 when deploying a node in hierarchical mode. The weird thing is that the `synfiles` postscript (silently) fails during deployment, but `updatenode <node> -F` works perfectly fine once the node has been deployed.

Here are some logs. I'm deploying `sh-ln01` from a service node (`sh-hn02`, `10.10.0.2`). The management node is `sh-hn01` (`10.10.0.1`). xCAT version is `xCAT-2.14-snap201804190715`

During deployment, here's what is logged from `syncfiles`:
```
+ logger -t xcat -p local4.info 'Performing syncfiles postscript'
++ uname
+ osname=Linux
+ xcatpostdir=/xcatpost
+ logger -t xcat -p local4.info './syncfiles: the OS name = Linux'
+ quit=no
+ count=5
+ returncode=0
+ '[' no = no ']'
+ '[' Linux = Linux ']'
++ /xcatpost/startsyncfiles.awk
+ returncode=0
+ '[' 0 -eq 0 ']'
+ quit=yes
+ let count=count-1
+ '[' yes = no ']'
+ '[' 0 -eq 0 ']'
+ logger -t xcat -p local4.info './syncfiles: Perform Syncing File action successfully'
```
so it appears to have worked, but none of the files in the synclist is actually copied over, and the `sshd` daemon on the deployed node logs this:
```
May 25 09:26:24 sh-ln01 xcat: Performing syncfiles postscript
May 25 09:26:24 sh-ln01 xcatpostinit1: ++ uname
May 25 09:26:24 sh-ln01 xcatpostinit1: + osname=Linux
May 25 09:26:24 sh-ln01 xcatpostinit1: + xcatpostdir=/xcatpost
May 25 09:26:24 sh-ln01 xcatpostinit1: + logger -t xcat -p local4.info './syncfiles: the OS name = Linux'
May 25 09:26:24 sh-ln01 xcat: ./syncfiles: the OS name = Linux
May 25 09:26:24 sh-ln01 xcatpostinit1: + quit=no
May 25 09:26:24 sh-ln01 xcatpostinit1: + count=5
May 25 09:26:24 sh-ln01 xcatpostinit1: + returncode=0
May 25 09:26:24 sh-ln01 xcatpostinit1: + '[' no = no ']'
May 25 09:26:24 sh-ln01 xcatpostinit1: + '[' Linux = Linux ']'
May 25 09:26:24 sh-ln01 xcatpostinit1: ++ /xcatpost/startsyncfiles.awk
May 25 09:26:30 sh-ln01 sshd[14901]: Invalid user sh-hn01.SUNet from 10.10.0.2 port 40020
May 25 09:26:30 sh-ln01 sshd[14901]: input_userauth_request: invalid user sh-hn01.SUNet [preauth]
May 25 09:26:30 sh-ln01 sshd[14901]: Connection closed by 10.10.0.2 port 40020 [preauth]
May 25 09:26:30 sh-ln01 sshd[15038]: Invalid user sh-hn01.SUNet from 10.10.0.2 port 40022
May 25 09:26:30 sh-ln01 sshd[15038]: input_userauth_request: invalid user sh-hn01.SUNet [preauth]
May 25 09:26:30 sh-ln01 sshd[15038]: Connection closed by 10.10.0.2 port 40022 [preauth]
May 25 09:26:30 sh-ln01 sshd[15146]: Invalid user sh-hn01.SUNet from 10.10.0.2 port 40024
May 25 09:26:30 sh-ln01 sshd[15146]: input_userauth_request: invalid user sh-hn01.SUNet [preauth]
May 25 09:26:30 sh-ln01 sshd[15146]: Connection closed by 10.10.0.2 port 40024 [preauth]
May 25 09:26:30 sh-ln01 sshd[15254]: Invalid user sh-hn01.SUNet from 10.10.0.2 port 40026
[...]
May 25 09:26:33 sh-ln01 xcatpostinit1: + returncode=0
May 25 09:26:33 sh-ln01 xcatpostinit1: + '[' 0 -eq 0 ']'
May 25 09:26:33 sh-ln01 xcatpostinit1: + quit=yes
May 25 09:26:33 sh-ln01 xcatpostinit1: + let count=count-1
May 25 09:26:33 sh-ln01 xcatpostinit1: + '[' yes = no ']'
May 25 09:26:33 sh-ln01 xcatpostinit1: + '[' 0 -eq 0 ']'
May 25 09:26:33 sh-ln01 xcatpostinit1: + logger -t xcat -p local4.info './syncfiles: Perform Syncing File action successfully'
May 25 09:26:33 sh-ln01 xcat: ./syncfiles: Perform Syncing File action successfully
```

`syncfiles` tries to connect to the deployed node using the hostname of the xCAT MN (`sh-hn01.SUNet`) instead of `root`.

Once deployment completes and the node reboots, running `updatenode sh-ln01 -F` works flawlessly, using the correct `root` user, and the files are actually synchronized.

Could you please advise, or suggest ways of tracking down the problem?

Thanks!

**Comment by kcgthb** [comment] 2018-05-25 22:15
Uh, so apparently that was an issue with the service node itself, because the `syncfiles` works great when the node is deployed form another SN, or from the MN. And redeploying that SN actually fixed the problem.

So I assume there were a leftovers from a previous xCAT version on that SN. Sorry for the noise, all is good now.

**Comment by kcgthb** [comment] 2018-07-27 18:35
I need to re-open this issue, as we're consistently seeing this problem happening again.

In our hierarchical setup, the initial `syncfiles` postscript execution fail during deployment (in the kickstart/anaconda environment) with the error reported above, that is, the username used for the SSH connection from the SN to the node being deployed is the hostname of the MN, instead of `root`.

Example log:

```
Jul 27 11:28:32 sh-dtn02.int xcat.mypostscript: postscript remoteshell return with 0
Jul 27 11:28:32 sh-dtn02.int xcat.mypostscript: Running postscript: syncfiles
Jul 27 18:28:32 sh-dtn02 xcat: Performing syncfiles postscript
Jul 27 18:28:32 sh-dtn02 xcat: ./syncfiles: the OS name = Linux
Jul 27 18:28:39 sh-dtn02 sshd[42360]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
Jul 27 18:28:39 sh-dtn02 sshd[42360]: Invalid user sh-hn01.SUNet from 10.10.0.3 port 54900
Jul 27 18:28:39 sh-dtn02 sshd[42360]: input_userauth_request: invalid user sh-hn01.SUNet [preauth]
Jul 27 18:28:39 sh-dtn02 sshd[42360]: Failed none for invalid user sh-hn01.SUNet from 10.10.0.3 port 54900 ssh2
Jul 27 18:28:39 sh-dtn02 sshd[42360]: Failed password for invalid user sh-hn01.SUNet from 10.10.0.3 port 54900 ssh2
Jul 27 18:28:39 sh-dtn02 sshd[42360]: Failed password for invalid user sh-hn01.SUNet from 10.10.0.3 port 54900 ssh2
Jul 27 18:28:39 sh-dtn02 sshd[42360]: Connection closed by 10.10.0.3 port 54900 [preauth]
Jul 27 18:28:39 sh-dtn02 sshd[42362]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
Jul 27 18:28:39 sh-dtn02 sshd[42362]: Invalid user sh-hn01.SUNet from 10.10.0.3 port 54902
Jul 27 18:28:39 sh-dtn02 sshd[42362]: input_userauth_request: invalid user sh-hn01.SUNet [preauth]
Jul 27 18:28:39 sh-dtn02 sshd[42362]: Failed none for invalid user sh-hn01.SUNet from 10.10.0.3 port 54902 ssh2
```
where:
* `sh-dtn02` is the node being deployed
* `sh-hn03` is the Service Node (SN) for `sh-dtn02`
* `sh-hn01.SUNet` is the FQDN of the Master Node

As a result, `syncfiles` fails to synchronize files and the whole deployment sequence is failing.

Any insight about why this happen would be much appreciated. Thanks!

**Comment by immarvin** [comment] 2018-07-30 09:11
hi @kcgthb , which xCAT release are you using  for the latest comment?

**Comment by cxhong** [comment] 2018-09-21 14:36
working on this issue.  I think syncfile is failed during the node deployment even for non-hierarchical cluster.   something relate to openssl.
```
++ /xcatpost/startsyncfiles.awk -v RCP=/usr/bin/rsync
69872 semi-random bytes loaded
depth=1 CN = xCAT CA
verify error:num=19:self signed certificate in certificate chain
DONE
+ print env: 1 172.21.253.31:3001
./syncfiles: line 55: print: command not found
+ returncode=127
````
updatenode worked file.

**Comment by cxhong** [comment] 2018-09-24 18:30
manually ran `/xcatpost/startsyncfiles.awk -v RCP=/usr/bin/rsync` on the compute node, it failed because it couldn't find syncfile 
```
<xcatresponse>
  <error>File:/var/xcat/syncfiles/install/custom/netboot/rh/compute.synclist does not exist.</error>
  <errorcode>1</errorcode>
  <xcatdsource>sn02</xcatdsource>
</xcatresponse>
````
right, there are no `/var/xcat/syncfiles` dir in the MN or SN, that is the default syncfile dir.   The osimage defined syncfile list at 
````
# lsdef -t osimage rhels7.5-alternate-ppc64le-netboot-compute -i synclists
Object name: rhels7.5-alternate-ppc64le-netboot-compute
    synclists=/install/custom/netboot/rh/compute.synclist
````
why add default syncfile dir in the front of synlists dir ?

**Comment by cxhong** [comment] 2018-09-24 20:51
ok, figured out above issue.

Before provision the compute node,  syncfile needs to be available on the service node, the command `updatenode compute_group_name -f` will push the the syncfile to the service node.  
@kcgthb , can u check if syncfile available on the service node?  the default location starts /var/xcat/syncfiles/..... ,   the location can be changed via site attribute `SNsyncfiledir`

**Comment by cxhong** [comment] 2018-09-25 13:42
@kcgthb , No, `rinstall` and `nodeset` didn't take care of this `for now`.  I think we should do that.  That's very easy  to forget.   I didn't run `updatenode compute -f` command while I was debugging this issue.  Took me days to figure out this :(

**Comment by kcgthb** [comment] 2018-09-25 15:31
Ah yes, in that case, that's an issue. I always assumes that this was the case.

**Comment by cxhong** [comment] 2018-10-01 18:02
right now, you have to run the `updatenode` command before provision the compute node.

Anyway,  you can try to modify the site table to change location of syncfile (It seems worked for me when I tested this issue).
```
chdef -t site SNsyncfiledir=
chdef -t site nodesyncfiledir=
````
assume MN and SN share / dir.

"SNsyncfiledir","/var/xcat/syncfiles",,
"nodesyncfiledir","/var/xcat/node/syncfiles",,

**Comment by kcgthb** [comment] 2018-10-01 18:15
Hi @cxhong 
Thanks for the suggestion. But would that work when sync'ing different files to different node groups? 

For instance if the same file with different contents is synchronized to separate node groups, like this:
```
/path/to/file_a -> (group_a)  /path/to/file
/path/to/file_b -> (group_b)  /path/to/file
```
how will that work? Won't the file be overwritten in `SNsyncfiledir`/`nodesynfiledir` and the wrong contents possibly copied to the destination nodes?

**Comment by kcgthb** [comment] 2018-10-01 18:35
All right, thanks for looking into it!

**Comment by cxhong** [comment] 2018-10-01 20:48
@kcgthb ,  sorry, my fault.  
nodesyncfiledir is only created on the compute node when syncfiles has `APPEND` and `MERGE`,  so don't need to change `nodesyncfiledir` attribute for site table. leave it as default or set to `"nodesyncfiledir","/var/xcat/node/syncfiles",,`
if change `SNsyncfiledir` to `/`,  the syncfiles has to be in the `/install or /tftpboot` dir,  because only those two dirs are shared between MN and SN.

maybe easier just ran `updatenode compute -f` before deploy the compute node..  I will look into if we can add that command to `nodeset`

**Comment by kcgthb** [comment] 2018-10-03 00:12
Ok, thanks for the suggestions.
So I've tried to run `updatenode cn -f` before `rinstall`, but I always have cases where the `syncfiles` postscript silently fails to properly synchronize files. And running `updatenode cn -F` invariably works each time.

Is there any way to diagnose the `syncfile` execution during deployment? Like logging what commands are executed on the MN, what synclist is used, what files are actually transferred, errors, etc... ?

**Comment by kcgthb** [comment] 2018-10-03 21:58
To try to move forward with this issue, I modified the `syncfile` postscript to force use `scp` instead of `rsync` (I hard-coded `RCP=/usr/bin/scp` in `/install/postcripts/syncfiles`).

I them tried to deploy `sh-dtn02`, whose SN is `sh-hn03`. The result is the following sync file generated on the SN:
```
# cat /tmp/scp_sh-dtn02
#!/bin/sh
/usr/bin/ssh  sh-hn01.SUNet@sh-dtn02 '/bin/mkdir -p /tmp/foo'
/usr/bin/scp -p -r /var/xcat/syncfiles/tmp/foo/bar sh-hn01.SUNet@sh-dtn02:/tmp/foo/bar
```
To recap:
* `sh-dtn02` is the node being deployed
* `sh-hn03` is the Service Node (SN) for `sh-dtn02`
* `sh-hn01.SUNet` is the FQDN of the Master Node

Obviously, `ssh sh-hn01.SUNet@sh-dtn02` can't work, because `sh-hn01.SUNet` is a **hostname** not a **username** (that should be `root`).

This problem is specific to `syncfile` being executed as a postscript and doesn't happen with `updatenode -F`

**Comment by kcgthb** [comment] 2018-10-03 22:29
Uh, I just remembered that this is #4455 over again, looks like the fixes there were focused on `xdsh` but didn't touch `RSYNC.pm` and `SSH.pm`. Maybe they should?

@robin2008 @jjohnson42 do you have any comment?

**Comment by kcgthb** [comment] 2018-10-03 22:53
I believe the root issue described in https://github.com/xcat2/xcat-core/issues/4425#issuecomment-350063752 is still a problem, and should really be fixed.

**Comment by kcgthb** [comment] 2018-10-04 19:16
Would the PR in #5680 work for you? 

It still doesn't solve the fundamental problem of the MN's hostname being passed as a username in some CN <-> SN <-> MN communications, but it at least prevents creating synclists that do `ssh <MN_hostname>@cn` and makes `syncfiles` work in those cases.

**Comment by robin2008** [comment] 2018-10-16 03:01
Merged, so close it.

**Closed by robin2008** 2018-10-16 03:01 UTC
Labels: component:file_sync, sprint1

**Comment by ChrisPJames** [comment] 2018-11-15 19:51
Not sure of this related but we have found an issue where syncfiles returns an exit code 1 when provisioning centos/redhat 6 hosts. centos/redhat7 hosts are absolutely fine. However, same symptoms as above whereby once the provision has finished provisioning you can run updatenode <node> -F and the files are copied across no problem. Again - just a problem with centos/redhat6 systems. I thought this might have something to do with SSL and certificates. Ideas welcome.

**Comment by robin2008** [comment] 2018-11-16 02:12
@ChrisPJames
Could you tell us more about your environment?  we want to recreate it on our test environment. 
- MN's OS and xCAT version
- Is it hierarchy?
- what's the `node definition`  (get rid of the sensitive info) `lsdef -t node <foo> --osimage`
- and what's the site definition (get rid of the sensitive info) `lsdef -t site -l`

And yes, postscript `syncfiles` is just a wrapper on CN. When executed, it will connect its xcatmaster (MN or SN) with SSL and trigger the real `syncfiles`.

**Comment by ChrisPJames** [comment] 2018-11-16 11:49
MN = centos7.4 with various updates but probably not the latest updates
xCAT version= We upgraded to 2.14.4 and started experiencing this particular issue. We have since downgraded using yum downgrade, back to 2.13.11 and still see the same issue so something hasnt been cleaned up correctly. Its currently on 2.13.11.
hierarchy = MN with a bunch of stateful CNs. no SNs

# lsdef -t node shark012 --osimage
Object name: shark012
    addkcmdline=rdblacklist=nouveau nouveau.modeset=0
    arch=x86_64
    cons=ipmi
    consoleenabled=1
    currchain=boot
    currstate=boot
    groups=og,v.og-compute
    mgt=ipmi
    netboot=pxe
    os=centos6.2
    postbootscripts=vessel/v.pgs-setupbashrc,vessel/v.installnvidia
    postscripts=vessel/delete_public_repos,remoteshell,hardeths,otherpkgs,syncfiles,
    power=ipmi
    profile=v.og-compute
    provmethod=centos6.2-x86_64-install-v.og-compute
    serialflow=hard
    serialport=1
    serialspeed=115200
    status=failed
    statustime=11-16-2018 11:29:17
    updatestatus=synced
    updatestatustime=11-16-2018 11:31:39
    profile=v.og-compute
    pkglist=/install/vessel/templates/v.og-compute.pkglist
    osname=Linux
    template=/install/vessel/templates/v.og-compute.tmpl
    osdistroname=centos6.2-x86_64
    otherpkglist=/install/vessel/templates/v.og-compute.otherpkgs.pkglist
    osvers=centos6.2
    objtype=osimage
    osarch=x86_64
    synclists=/install/vessel/templates/v.synclist
    provmethod=install
    imagetype=linux
    otherpkgdir=/install/vessel/otherpkgs/centos6.2/x86_64
    pkgdir=/install/global/os/centos6.2/x86_64,/install/global/osupdates/centos6.2/x86_64

# lsdef -t site -l
Object name: clustersite
    SNsyncfiledir=/var/xcat/syncfiles
    auditnosyslog=0
    auditskipcmds=ALL
    blademaxp=64
    cleanupxcatpost=no
    consoleondemand=no
    databaseloc=/var/lib
    db2installloc=/mntdb2
    dhcpinterfaces=em1,em2,em3
    dhcplease=43200
    dnshandler=ddns
    dnsinterfaces=em1,em2,em3
    enableASMI=no
    fsptimeout=0
    installdir=/install
    ipmimaxp=64
    ipmiretries=3
    ipmitimeout=2
    keyboard=uk
    language=en_US
    managedaddressmode=static
    maxssh=8
    nodesyncfiledir=/var/xcat/node/syncfiles
    powerinterval=0
    ppcmaxp=64
    ppcretry=3
    ppctimeout=0
    sharedtftp=1
    sitetype=prod
    sshbetweennodes=ALLGROUPS
    syspowerinterval=0
    tftpdir=/tftpboot
    timezone=Etc/UTC
    useNmapfromMN=no
    vsftp=n
    xcatconfdir=/etc/xcat
    xcatdebugmode=2
    xcatdport=3001
    xcatiport=3002
    xcatsslversion=TLSv1

We have a slightly non standard directory structure in order to cater for the various regions however we know it works and this is likely not the cause. I have done a tree listing of /install for reference. I have removed sensitive information:

# tree -L 2 install
install
├── admin -> vessel/admin
├── autoinst
│   ├── shark012
├── global
│   ├── os
│   ├── osupdates
│   └── postscripts
├── postscripts
│   ├── global -> /install/global/postscripts
│   ├── site -> /install/site/postscripts
│   ├── vessel -> /install/vessel/postscripts
├── prescripts
│   └── setupdhcp
├── site
│   └── postscripts
├── vessel
│   ├── admin
│   ├── ansible-vessel
│   ├── otherpkgs
│   ├── postscripts
│   ├── setup
│   ├── syncfiles
│   ├── sysclone
│   ├── templates
│   └── xcat

Although this host is provisioned with 6.2 we get the same symptoms with hosts on 6.9.

**Comment by ChrisPJames** [comment] 2018-11-16 11:52
This is what we see in the cluster log at the time of syncfiles:

Nov 16 11:25:44 shark012 xcat.mypostscript:  Running postscript: syncfiles
Nov 16 11:25:44 xcat xcat[19560]: DEBUG xcatd: connection from shark012
Nov 16 11:25:44 xcat xcat[19560]: DEBUG xcatd: open new process : xcatd SSL: syncfiles for shark012
Nov 16 11:25:44 xcat xcat[19560]: xCAT: Allowing syncfiles from shark012
Nov 16 11:25:44 xcat xcat[19562]: DEBUG xcatd: dispatch request 'syncfiles ' to plugin 'syncfiles'
Nov 16 11:25:44 xcat xcat[19562]: DEBUG xcatd: handle request 'syncfiles' by plugin 'syncfiles''s process_request
Nov 16 11:25:44 xcat xcat[19562]: DEBUG xcatd: dispatch request 'xdcp -F /install/vessel/templates/v.synclist' to plugin 'xdsh'
Nov 16 11:25:44 xcat xcat[19562]: DEBUG xcatd: handle request 'xdcp' by plugin 'xdsh''s preprocess_request
Nov 16 11:25:49 xcat xcat[19560]: DEBUG xcatd: close connection with shark012
..
..
<repeat a number of times then fail>
..
..
Nov 16 11:27:22 shark012 xcat.mypostscript:  postscript syncfiles return with 1

After provision:

# updatenode shark012 -F
File synchronization has completed for nodes.

**Comment by ChrisPJames** [comment] 2018-11-16 13:34
One last comment: I added syncfiles to the postbootscripts section and it completes without any problem:

Nov 16 13:18:34 shark012 xcat.mypostscript:  Running postbootscript: syncfiles
Nov 16 13:18:34 xcat xcat[26844]: DEBUG xcatd: connection from shark012
Nov 16 13:18:34 xcat xcat[26844]: DEBUG xcatd: open new process : xcatd SSL: syncfiles for shark012
Nov 16 13:18:34 xcat xcat[26844]: xCAT: Allowing syncfiles from shark012
Nov 16 13:18:34 xcat xcat[26845]: DEBUG xcatd: dispatch request 'syncfiles ' to plugin 'syncfiles'
Nov 16 13:18:34 xcat xcat[26845]: DEBUG xcatd: handle request 'syncfiles' by plugin 'syncfiles''s process_request
Nov 16 13:18:35 xcat xcat[26845]: DEBUG xcatd: dispatch request 'xdcp -F /install/vessel/templates/v.synclist' to plugin 'xdsh'
Nov 16 13:18:35 xcat xcat[26845]: DEBUG xcatd: handle request 'xdcp' by plugin 'xdsh''s preprocess_request
Nov 16 13:18:43 xcat xcat[26844]: DEBUG xcatd: close connection with shark012
Nov 16 13:18:43 shark012 xcat.mypostscript:  postbootscript syncfiles return with 0
