### ISSUE TITLE
［FVT］:rflash --check gives out different HPM firmwares for BIOS component

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1860] opened 2016-09-20 02:32 UTC
Test platform(including OS and Hardware): RHELS7.2 , CN:Garrision
Test xCAT version: Version 2.12.3 (git commit 2a6d456, built Wed Sep 7 06:16:01 EDT 2016)
How to reproduce: 
[root@fs1 ~]# rpm -qa |grep -i ipmitool
ipmitool-xcat-1.8.15-3.ppc64le
[root@fs1 ~]# rflash frame45cn02 /iso/8335GTB_820.1634.20160902a_update.hpm --check
HPM firmware version for BOOT component:  2.13 35000000
HPM firmware version for APP  component:  2.13 35000000
HPM firmware version for BIOS component:  1.0a 0000000E
frame45cn02: Node firmware version for BOOT component:   2.13 35000000
frame45cn02: Node firmware version for APP component:   2.13 35000000
frame45cn02: Node firmware version for BIOS component:   1.10 0000000E

**Comment by tingtli** [comment] 2016-09-21 09:07
[root@fs1 ~]# rflash frame45cn02,frame45cn06 /iso/8335GTB_820.1634.20160917a_update.hpm --check
HPM firmware version for BOOT component:  2.13 35000000
HPM firmware version for APP  component:  2.13 35000000
HPM firmware version for BIOS component:  1.0b 00000001
frame45cn06: Node firmware version for BOOT component:   2.13 35000000
frame45cn06: Node firmware version for APP component:   2.13 35000000
frame45cn06: Node firmware version for BIOS component:   1.11 00000001
frame45cn02: Node firmware version for BOOT component:   2.13 35000000
frame45cn02: Node firmware version for APP component:   2.13 35000000
frame45cn02: Node firmware version for BIOS component:   1.11 00000001

**Comment by whowutwut** [comment] 2016-09-21 10:33
@tingtli please get the 1.8.17 version from the shared gpfs directrory. Email Pat for the location. We need to test with that version for 2.12.3.   It's not clear to me what the issue is you are opening against.   What is the version suppose to be and what is it showing?

**Comment by whowutwut** [comment] 2016-09-21 10:34
Please assign rflash issues to @pdlun92

**Comment by chenglch** [comment] 2016-09-21 14:44
This issue is that the BIOS version from HPM file and BMC is different. `1.0b` vs`1.11` from tingting's comment.

I guess this is the hex format from hpm file and decimal format from the BMC.
As the BIOS version from the old BMC can not be detected, we do not pay much attention to this before.

From the code for HPM file
https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/xcat/plugins/ipmi.pm#L8069
and the code for the BMC
https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/xcat/plugins/ipmi.pm#L1876

Both `%02x` are used, not sure if we should use the upper case hex format for this version field.
But for the hex or dec issue , we should compare the result from `ipmitool hpm check` at first.

**Comment by chenglch** [comment] 2016-09-22 02:05
From my investigation, the output from both `ipmitool-xcat` and `ipmitool-1.8.17` is like this:

```
--------------------------------------------------------------------------
|ID  | Name        |                     Versions                        |
|    |             |     Active      |     Backup      |      File       |
--------------------------------------------------------------------------
|*^ 2|BIOS         |   1.11 00000001 | ---.-- -------- |   1.0b 00000001 |
|*  0|BOOT         |   2.13 35000000 | ---.-- -------- |   2.13 35000000 |
|*  1|APP          |   2.13 35000000 | ---.-- -------- |   2.13 35000000 |
--------------------------------------------------------------------------
```

I have no idea to fix this issue, if the lower case version like `1.0b` is reasonable, there may be issue on the BMC or firmware side to fill the BIOS version field.

**Comment by zet809** [comment] 2016-09-26 07:29
@pdlun92 Hi, Pat, do you think this defect can be fixed in this release? If not, we shall move it forward.

**Comment by pdlun92** [comment] 2016-09-26 18:45
@zet809 @tingtli I agree with @chenglch I think that this is issue on ipmitool, BMC, or firmware. We directly output hpm version as it is given back to us by `ipmitool hpm check` which is what I believe our code should do.

```[root@fs1 ~]# rflash -c frame45cn02 /iso/8335GTB_820.1634.20160917a_update.hpm
HPM firmware version for BOOT component:  2.13 35000000
HPM firmware version for APP  component:  2.13 35000000
HPM firmware version for BIOS component:  1.0b 00000001
frame45cn02: Node firmware version for BOOT component:   2.13 35000000
frame45cn02: Node firmware version for APP component:   2.13 35000000
frame45cn02: Node firmware version for BIOS component:   1.11 00000001
[root@fs1 ~]# ipmitool-xcat -H 50.45.2.1 -U ADMIN -P admin hpm check /iso/8335GTB_820.1634.20160917a_update.hpm

PICMG HPM.1 Upgrade Agent 1.0.9:

Validating firmware image integrity...OK
Performing preparation stage...OK

Comparing Target & Image File version
--------------------------------------------------------------------------
|ID  | Name        |                     Versions                        |
|    |             |     Active      |     Backup      |      File       |
--------------------------------------------------------------------------
|*^ 2|BIOS         |   1.11 00000001 | ---.-- -------- |   1.0b 00000001 |
|*  0|BOOT         |   2.13 35000000 | ---.-- -------- |   2.13 35000000 |
|*  1|APP          |   2.13 35000000 | ---.-- -------- |   2.13 35000000 |
--------------------------------------------------------------------------
(*) Component requires Payload Cold Reset
(^) Indicates component would be upgraded
``` The `HPM firmware version for BIOS component` output from `rflash -c` directly matches the `file` column and `BIOS` row output from `ipmitool hpm check` 

Going to close this issue as invalid

**Closed by pdlun92** 2016-09-26 18:45 UTC
Labels: component:hw_control, type:bug
