### ISSUE TITLE
Using the --template option to create a new osimage definition for netboot does not create a new rootimgdir

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1797] opened 2016-09-01 13:38 UTC
I tried the --template option to create a new osimage definition from a netboot (diskless) osimage, and the result does not create a new `rootimgdir` attribute.  It re-uses the image directory from the template.  

I think this is very dangerous for the new user to xCAT who is trying to duplicate diskless osimages and we should provide some protection.   If a osimgae is copied using this feature, running `genimage` will wipe out the template osimage. 

```
[root@fs1 ~]# mkdef -t osimage -o victor-beta-rhels7.3-netboot --template rhels7.3-beta-ppc64le-netboot-compute
1 object definitions have been created or modified.
```

The resulting osimage uses the `rootimgdir` from the template: 
```
[root@fs1 ~]# lsdef -t osimage -o victor-beta-rhels7.3-netboot -i rootimgdir
Object name: victor-beta-rhels7.3-netboot
    rootimgdir=/install/netboot/rhels7.3-beta/ppc64le/compute
```

Suggested solutions here: 
1) Use the name provided to create a new path for the `rootimgdir` 
2) Add a option to the mkdef command to allow the user to specify a "short name" that will be used.  If we have this option, then we block the mkdef command to not successfully complete if the template is a "netboot" osimage and the `--name` is not specified
3) Print a warning message to inform the user to create a new `rootimgdir` and chdef the osimage to use the new directory.

**Comment by daniceexi** [comment] 2016-09-01 14:40
@whowutwut 
It does have the issue as you mentioned. But the current implementation also has some goodness, 
1. From user, it's consistent for mkdef that mkdef won't do any specific operation. If we make mkdef handle the **rootimgdir** in a specific way, user might worry is there any other attributes have special handling?
2. For code, it's consistent that no special code logic for specific attribute.

**Comment by whowutwut** [comment] 2016-09-01 15:43
Sure, if we want to keep the code changes to a minimium, then maybe suggest a warning message if the template contains a `rootimgdir` attribute , such as: 
```
[root@fs1 ~]# mkdef -t osimage -o victor-beta-rhels7.3-netboot --template rhels7.3-beta-ppc64le-netboot-compute
WARNING: The rootimgdir attribute is copied from the template.   Change this value before running genimage to avoid overwriting the diskless image for 'rhels7.3-beta-ppc64le-netboot-compute' definition.
1 object definitions have been created or modified.

**Comment by immarvin** [comment] 2016-09-02 02:01
hi @whowutwut , the design of "mkdef --template" is creating object definitions based on xCAT shipped object definition templates or existing object definitions, it just manipulate the records in xCAT database, it's user's responsibility to specify the correct attributes and prepare the underlie entity of the object attributes. 

````
--template template-object-name

Name of the xCAT shipped object definition template or an existing object, from which the new object definition will be created. 

**The newly created object will inherit the attributes of the template definition unless the attribute is specified in the arguments of mkdef command.** 

If there are a template and an existing object with the same name template-object-name, the tempalte object takes precedence over the existing object. 

For the details of xCAT shipped object definition templates, refer to the manpage of --template option in lsdef(1).
````   

So the issue you described is the behaviour by design. The message you suggest have been mentioned in the manage. I think "def" commands should only manipulate the object definition things,   involving the manipulating of entity of the objects in "def" commands might make too much things coupled together

**Comment by whowutwut** [comment] 2016-09-02 11:59
Thanks for the explanation. I'm ok with it

**Comment by whowutwut** [comment] 2016-09-02 12:00
@immarvin do you think we should at least print a warning msg?

**Comment by immarvin** [comment] 2016-09-05 13:06
hi @whowutwut , I think we do not need to print a warning message on this. The man page is clear enough.

Think of a scenario that user create a diskless osimage definition with "mkdef xxx <attribute>=yyy ..." without "--template" option or "cat <osimage definition stanza file>|mkdef -z", the problem of the "rootimgdir"  of 2 osimages refer to the same directory might still exist. 

Another example, if there are 2 node definitions representing one physical machine, there might be problem if we reprovision or power off one of them by mistake.   
 
So my idea is that it is always dangerous if user is not quite clear about what he/she is doing, there are too many possibilities to reminder the usage errors of this kind.

**Comment by daniceexi** [comment] 2016-09-06 11:54
Even I also want to keep the code of *def to be simple and clear, but to make xCAT to be easier to use I'd like we can do something here.

**Comment by whowutwut** [comment] 2016-09-17 17:39
Another option is similar to nodecheck option for xcatprobe we could have osimagecheck which would be separate from the xcat main path code but check things like multiple diskless osimage definitions using the same rootimg dir...

**Comment by whowutwut** [comment] 2016-09-18 14:14
Perhaps @gurevichmark  can work on the probe command for that and that could be the solution here instead of changing any main xCAT code path

**Comment by gurevichmark** [comment] 2016-09-27 20:03
Fixed by adding new osimagecheck probe under PR #1874

**Comment by whowutwut** [comment] 2016-10-03 14:19
@gurevichmark  , I've tested this on the GA 2.12.3 build and I see that it flags the issue, but I'm not sure the message is easily understood.  Sorry for not looking more closely at the externals in the pull request 

```
[root@fs4 ~]# mkdef -t osimage -o mytest --template rhels7.3-snap4-ppc64le-netboot-compute
1 object definitions have been created or modified.
[root@fs4 ~]# lsdef -t osimage -o mytest -i rootimgdir
Object name: mytest
    rootimgdir=/install/netboot/rhels7.3-snap4/ppc64le/compute
[root@fs4 ~]# lsdef -t osimage -o rhels7.3-snap4-ppc64le-netboot-compute -i rootimgdir
Object name: rhels7.3-snap4-ppc64le-netboot-compute
    rootimgdir=/install/netboot/rhels7.3-snap4/ppc64le/compute
```

![image](https://cloud.githubusercontent.com/assets/10049070/19040319/916d4bca-8951-11e6-888e-70bb17dbba6d.png)

My suggestion here is: 
```
Duplicate 'rootimgdir' attribute is being used for the following osimages:               [WARN]
    rhels7.3-snap4-ppc64le-netboot-compute
    mytest
    <osimage3> 
    <osimage4>
```
or if we don't want to collect to a single list, 

```
Duplicate 'rootimgdir' being used by osimage 'mytest' and 'mytest2' (rootimgdir=/install/netboot/rhels7.3-snap4/ppc64le/compute)      [WARN]
```

thoughts?

**Comment by gurevichmark** [comment] 2016-10-04 19:49
How about something like:
```
Duplicate attribute value (rootimgdir=/install/netboot/rhels7.3-snap4/ppc64le/compute) being used by      [WARN]
   osimage definition 'mystest' and 'mytest2'
```

**Comment by whowutwut** [comment] 2016-10-06 01:00
Can you show what the output is if we have 4-6 osimages configured with the same rootimgdir?

**Comment by gurevichmark** [comment] 2016-10-13 14:40
Output improvements and checks for template value of `compute.tmpl` and `service.tmpl` added under PR #1962

**Closed** 2016-10-25 19:01 UTC
Labels: status:pending, test:testcase_added, test:testcase_requested
