### ISSUE TITLE
[Customer] bmcdiscover command cannot get the MTMS attributes for Habanero Server

### ISSUE THREAD

**Issue by fenghaizhu** [xcat2/xcat-core#559] opened 2015-12-28 08:32 UTC
**Environment:** 
RHEL7.2 (GA)
Habanero server

**Issue:** MTMS_based_discovery didn't work for Habanero .  
The MTMs/serials are not discovered as bellow.
```
[root@smn~]# bmcdiscover -s nmap --range 50.2.0.65-80 -u ADMIN -p admin  -z
node-32020041:
	objtype=node
	groups=all
	bmc=50.2.0.65
	cons=ipmi
	mgt=ipmi
	bmcusername=ADMIN
	bmcpassword=admin

node-32020042:
	objtype=node
	groups=all
	bmc=50.2.0.66
	cons=ipmi
	mgt=ipmi
	bmcusername=ADMIN
	bmcpassword=admin

node-32020044:
	objtype=node
	groups=all
	bmc=50.2.0.68
	cons=ipmi
	mgt=ipmi
	bmcusername=ADMIN
	bmcpassword=admin
```

**Comment by whowutwut** [comment] 2016-01-18 17:36
@xuweibj  Can you please add some response to this issue as to what cause the problem and how did we fix it? There is no information provided in the pull reqeust, the only way to know is to look at the code.

**Comment by daniceexi** [comment] 2016-01-19 08:56
@whowutwut I changed the subject to a reasonable text. And set the lable: ``status:pending`` since the code has been merged.

**Comment by whowutwut** [comment] 2016-01-19 13:10
Thanks @daniceexi ... What I was looking for was a solution to the Issue.  The customer opens an issue but we don't move the issue discussion through to completion.  In this case we just reference a pull request that claims to fix the issue.  In the pull request, we also do not have any text indicating what the fix was, that would have been OK also.   What is left is that the customer needs to go into the code and look at the code change to understand why this did not work in the first place.   

So I was looking for some simple response to explain the cause of the problem and the solution. Something like: 

*The problem is caused by Tyan OpenPower (Habanero) servers having the MTMS information in FRU2 and we are not checking that FRU.  Historically, SystemX and Tuletta Power machines have the MTMS is in FRU0, For OpenPower S822LC, it is in FRU3.  Will add a check in the code to look for MTMS information in FRU2 for Habanero*

**Comment by daniceexi** [comment] 2016-01-20 06:21
@whowutwut Thanks for the remind. Yes, the root cause was xCAT code could not find the MTMS for Habanero nodes from FRU0. The fix was to try to go through FRU0, 2, 3 until to find a MTMS information.

@zet809 and @xuweibj have discussed with the creator of this issue and confirmed that the fix could resolve customer's issue. They should paste the discussion as comments here.

**Closed** 2016-03-25 03:18 UTC
Labels: component:discovery, status:pending, type:bug

**Comment by fenghaizhu** [comment] 2016-03-25 03:25
I copied the updated file bmcdiscover.pm from xcat team and made a patch by ourselves to fix this issue. It has worked well.
