### ISSUE TITLE
[FVT] Ping failed after the CN is booted quickly, but works later.

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1309] opened 2016-06-15 02:46 UTC
Test ENV: X86, RH7.2 with latest daily build.

```
[root@c910f04x27v02 result]# rpm -qa | grep -i xCAT
grub2-xcat-2.02-0.16.el7.snap201506090204.noarch
perl-xCAT-2.12.1-snap201606140645.noarch
xCAT-server-2.12.1-snap201606140645.noarch
elilo-xcat-3.14-4.noarch
syslinux-xcat-3.86-2.noarch
conserver-xcat-8.1.16-10.x86_64
xCAT-genesis-base-x86_64-2.12-snap201605051534.noarch
xCAT-client-2.12.1-snap201606140645.noarch
xCAT-2.12.1-snap201606140646.x86_64
xCAT-buildkit-2.12.1-snap201606140646.noarch
ipmitool-xcat-1.8.15-1.x86_64
xCAT-genesis-scripts-x86_64-2.12.1-snap201606140646.noarch
xCAT-test-2.12.1-snap201606140646.noarch
[root@c910f04x27v02 result]# cat /etc/*release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.2 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.2"
Red Hat Enterprise Linux Server release 7.2 (Maipo)
Red Hat Enterprise Linux Server release 7.2 (Maipo)
```
Description:
After installing diskfull hierarchy on CN successfully quickly(less than one minute), "ping CN -c 3" failed.
But "xdsh c910f04x27v04 date/mount" works and the "ping CN -c 3" works later.

**Comment by daniceexi** [comment] 2016-06-16 00:50
@caomengmeng This might be timing issue. Or it might caused by the system is in heave load that ICMP is not stable than tcp ...
How do we check the CN deployment has been done before running the ``ping CN -c 3``?

**Comment by daniceexi** [comment] 2016-06-17 08:18
Discussed with @caomengmeng that this should be a timing issue. A potential fix might be adding a ``sleep 60`` before the ``ping CN -c 3`` so the new installed system have time to be ready.

We close this one first and if it would be recreated later, then change the test case.

**Closed by daniceexi** 2016-06-17 08:18 UTC
Labels: component:network
