### ISSUE TITLE
Request a unique group be setup during bmcdiscovery

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#1452] opened 2016-07-01 13:44 UTC
It would be useful to have the bmcdiscover definition to have a unique group name setup when created.
```
[root@c712ems4 ~]# lsdef node-8335-gtb-100463a
Object name: node-8335-gtb-100463a
    bmc=192.168.130.138
    cons=ipmi
    groups=all
    mgt=ipmi
    mtm=8335-GTB
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=100463A
    status=booting
    statustime=06-30-2016 21:21:53
```
I would think a group that groups by similar hardware type would allow us to easily see a list of just discovered BMCs, maybe groups=all,n8335

**Comment by daniceexi** [comment] 2016-07-04 02:09
we had made a feature to automatically determine the groups for a new added node. @zet809 could you give more information about this feature?

**Comment by zet809** [comment] 2016-07-04 03:14
@markprez Hi, Mark, what is the purpose of assign an unique group name?
We support a feature may help you:   
1. define a dynamic group like this:
    mkdef -t group -d -o n8335 -w mtm=~8335      # It means the nodes with mtm attribute match 8335 will be added into this group
2. then after using bmcdiscover to discover BMC node, using following command to check the nodes belong to the dynamic group
    nodels n8335
The issue is that, xcat only can return the group n8335 include a group of nodes, it can not return which group a node is belonged to.

One more idea may help you but need to be implemented:
    within bmcdiscover, add options like "[-r \"regular_expression\" -g <group_name>]" to let  bmcdiscover deal with the group attributes

**Comment by markprez** [comment] 2016-07-05 03:40
Hello,
  I like your suggestion, "mkdef -t group -d -o n8335 -w mtm=~8335". I'd 
prefer not to add options.

  The current documentation is handy for a small number of nodes, adding 
this suggestion would
be ideal. 

Thanks, Mark

**Comment by zet809** [comment] 2016-07-06 06:48
@markprez Hi, mark, if the suggestion works for you, will you pls close this defect?

**Comment by zet809** [comment] 2016-07-08 05:08
Close this defect since there is a solution can fulfill the request.

**Closed by zet809** 2016-07-08 05:08 UTC
Labels: component:discovery, type:feature

**Comment by whowutwut** [comment] 2016-07-08 19:28
Is this something that we should add to the documentation, if it's not already there?

**Comment by markprez** [comment] 2016-07-08 19:40
I would like to see some more suggestions like this for managing large 
numbers of nodes in the discovery doc.
The documentation now seems more for doing a couple nodes at a time.

In practice, we will predefine a large number of nodes and discover and 
power on discovered nodes. After the first group is discovered, nodes 
could be coming in asynchronously.
