### ISSUE TITLE
xcat 2.14 is unable to recognize centos versions

### ISSUE THREAD

**Issue by bebosudo** [xcat2/xcat-core#5287] opened 2018-06-11 16:22 UTC
Hi, I'm using xcat 2.14 installed on a Centos 7.5 and another xcat 2.10 on another centos 7.5, to install centos version 7.5 and 6.6.

Version 2.10 is able to correctly install centos 7.5, version 2.14 halts with a "Pane is dead".

After a couple of hours of debugging, I found out that the template assigned by 2.14 to centos distributions is the default `/opt/xcat/share/xcat/install/centos/compute.tmpl`, which targets a centos 5.
This happens both for centos 7.5 and 6.6 isos; it doesn't happen instead with xcat 2.10.

**Steps to reproduce**:
```
# wget -P /etc/yum.repos.d/ https://xcat.org/files/xcat/repos/yum/2.14/xcat-core/xcat-core.repo
# wget -P /etc/yum.repos.d/ https://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/x86_64/xcat-dep.repo
# yum install xCAT
# rpm -q xCAT
xCAT-2.14.1-snap201806010300.x86_64

# copycds -n centos75 /mnt/CentOS-7-x86_64-Everything-1804.iso

# lsdef -t osimage centos75-x86_64-install-compute
Object name: centos75-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osdistroname=centos75-x86_64
    osname=Linux
    osvers=centos75
    otherpkgdir=/install/post/otherpkgs/centos75/x86_64
    pkgdir=/install/centos75/x86_64
    pkglist=/opt/xcat/share/xcat/install/centos/compute.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/centos/compute.tmpl
```

The template `/opt/xcat/share/xcat/install/centos/compute.tmpl` contains attributes illegal in a Centos7 installation, such as `zerombr yes` instead of the new `zerombr` in centos7/rhel7, which causes an halt in the installation.
I didn't have time to test which version between 2.10 and 2.14 first presents such behavior.

**Comment by bebosudo** [comment] 2018-06-11 19:35
I've found that the problem happens when the name passed doesn't comply with the "standard" `distro<major>.<minor>`: in that case the templates are those of the main version.

Wouldn't it be better to route the installation files to the latest version, in this case Centos 7?
And would be great to have at least a warning message, something like "distro version not recognized, defaulting to base <distro> version".

**Comment by whowutwut** [comment] 2018-06-11 20:09
@bebosudo Yes, the issue is that if we cannot determine the correct OS, we default to an OLD version of the template file.  I think we should probably change this to default to the latest version of the template file, it seems like it would alleviate headaches like this. 

We have hit this  many times in the past...  for example
https://github.com/xcat2/xcat-core/issues/4819

Thank you for opening this issue as it seems like it is a real usability problem...  @zet809 It seems like for CentOS and RHEL , the `compute.tmpl` file does not work with the later versions of the OS, why not update compute.tmpl to match the latest.. or symlink it to match the latest version?

**Comment by cxhong** [comment] 2018-06-11 20:24
it cause by this https://github.com/xcat2/xcat-core/pull/4823

If -n xxxx doesn't include the ".",  it will not get to this block of code, and couldn't find correct tmpl file

````
my $dotpos = rindex($os, ".");
    my $osbase = substr($os, 0, $dotpos);
.........
# If the osimge name was specified with -n, the name might contain multiple "."
    # Chop them off one at a time until filename match is found
    else {
        while ($dotpos > 0) {

            if (-r "$searchpath/$profile.$osbase.$arch.$extension") {
                return "$searchpath/$profile.$osbase.$arch.$extension";
            }
            elsif (-r "$searchpath/$profile.$osbase.$extension") {
                return "$searchpath/$profile.$osbase.$extension";
            }
            # Chop off "." from the end and try again
            $dotpos = rindex($osbase, ".");
            $osbase = substr($osbase, 0, $dotpos);
        }
    }
````

**Comment by bebosudo** [comment] 2018-06-14 21:59
> I do not think -n centos75 is a valid value for a centos 7.5 iso, only the user who run copycds know it's cantos 7.5, the code and the admin with no knowledge on centos releases will take it as centos75

I agree, but in that case I think that at least a warning message, something like ` "distro version not recognized, defaulting to base version /opt/xcat/x/y/z"` could be displayed, so the future user can immediately realize something is wrong with its naming, without waiting for the installation to mysteriously crash.

Maybe the link to the newest distribution could be introduced in the next major release?

**Comment by whowutwut** [comment] 2018-06-18 19:37
@immarvin We can look back to see when `compute.tmpl` was created, the last time it was touched was 2013. ...  5 years ago.  Do we really think anyone is using this file?  but a safer alternative is to just remove `compute.tmpl` and let the error propagate itself up, then at least it would be flagged if we could not detect a template file.  

While `centos75` is not valid, we still don't restrict any one from using any name via `-n option`...  I had created a PR a long time ago https://github.com/xcat2/xcat-core/pull/3262 but it didn't pass running it through regression on all OS/arch so I didn't keep working on it...  If we wanted to support just RHEL changes, it would be a smaller scope and I think it can be contained.

**Comment by immarvin** [comment] 2018-06-21 05:39
hi @bebosudo , the fix has been merged in https://github.com/xcat2/xcat-core/pull/5300, please try it in the lates development build

**Comment by bebosudo** [comment] 2018-06-21 09:04
Hi, thanks for your work.
I just installed the latest devel build of xcat on a vm to test this, and it doesn't seem to improve the situation.

```
# copycds -n centos66 /mnt/CentOS-6.6-x86_64-bin-DVD{1,2}.iso 
Copying media to /install/centos66/x86_64
Media copy operation successful
Copying media to /install/centos66/x86_64
Media copy operation successful

# lsdef -t osimage
centos66-x86_64-install-compute  (osimage)
centos66-x86_64-netboot-compute  (osimage)
centos66-x86_64-statelite-compute  (osimage)

# lsdef -t osimage centos66-x86_64-install-compute
Object name: centos66-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osdistroname=centos66-x86_64
    osname=Linux
    osvers=centos66
    otherpkgdir=/install/post/otherpkgs/centos66/x86_64
    pkgdir=/install/centos66/x86_64
    pkglist=/opt/xcat/share/xcat/install/centos/compute.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/centos/compute.tmpl
```

The template associated `/opt/xcat/share/xcat/install/centos/compute.tmpl` is for centos 5, which breaks things at install time for both centos 6 and 7 images.
I expected at least a _warning_ message if the name cannot be interpreted correctly.

I've also tried: `# copycds -n centosasfasfsd66 /mnt/CentOS-6.6-x86_64-bin-DVD{1,2}.iso` and it parsed it as a "plain" centos, associating the centos5 template to it.

```
# lsdef --version
lsdef - Version 2.14.2 (git commit 2840e4d4029f1d529651edf3258c085bb027d402, built Wed Jun 20 06:15:46 EDT 2018)
```

Many thanks for your work!

**Comment by chuckbrazie** [comment] 2018-07-03 04:00
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
xcat 2.14 is unable to recognize centos versions (#5287)" sent on 7/3/18
2:29:49 AM.

This is the only notification you will receive while this person is away.

**Comment by bebosudo** [comment] 2018-07-03 22:08
@immarvin could you please explain me how #5300 should fix this? it doesn't seem to improve the original situation, as I showed in my previous comment https://github.com/xcat2/xcat-core/issues/5287#issuecomment-399030584

**Comment by chuckbrazie** [comment] 2018-07-04 04:00
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
xcat 2.14 is unable to recognize centos versions (#5287)" sent on 7/3/18
10:08:58 PM.

This is the only notification you will receive while this person is away.

**Comment by immarvin** [comment] 2018-07-04 08:05
hi @bebosudo , my test result:
```
[root@c910f03c05k21 xcat]# lsxcatd -v
Version 2.14.2 (git commit 1f2ba0d8918eaa45f21900cbe701cb0a740a4c82, built Tue Jul  3 06:15:41 EDT 2018)

[root@c910f03c05k21 xcat]# copycds -n centos66 /iso/iso/centos/6.6/CentOS-6.6-x86_64-bin-DVD1.iso
Copying media to /install/centos66/x86_64
Media copy operation successful

[root@c910f03c05k21 xcat]# lsdef -t osimage -o centos66-x86_64-install-compute
Object name: centos66-x86_64-install-compute
    imagetype=linux
    osarch=x86_64
    osdistroname=centos66-x86_64
    osname=Linux
    osvers=centos66
    otherpkgdir=/install/post/otherpkgs/centos66/x86_64
    pkgdir=/install/centos66/x86_64
    pkglist=/opt/xcat/share/xcat/install/centos/compute.centos6.pkglist
    profile=compute
    provmethod=install
    template=/opt/xcat/share/xcat/install/centos/compute.centos6.tmpl


```

**Comment by immarvin** [comment] 2018-07-04 08:06
the commit of the fix is 
```
commit c922ad2cf74626b4b30705f83f496282c0371f8a
Author: cxhong <abcdqiu@gmail.com>
Date:   Thu Jun 21 01:38:31 2018 -0400

    Find correct template and postinstall file to build osimage for copycds -n command (#5300)

    * Parse copycd -n options to get correct tmpl and postinstall file

    * Add support for Ubuntu
```

**Comment by chuckbrazie** [comment] 2018-07-04 10:00
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
xcat 2.14 is unable to recognize centos versions (#5287)" sent on 7/4/18
8:05:55 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment] 2018-07-04 10:00
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
xcat 2.14 is unable to recognize centos versions (#5287)" sent on 7/4/18
7:02:37 AM.

This is the only notification you will receive while this person is away.

**Comment by chuckbrazie** [comment] 2018-07-04 10:00
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
xcat 2.14 is unable to recognize centos versions (#5287)" sent on 7/4/18
8:06:26 AM.

This is the only notification you will receive while this person is away.

**Comment by zet809** [comment] 2018-07-11 02:57
hi, @bebosudo , do you have chance to verify the fix mentioned above, it is fixed from our point of view, so I will close it and you can reopen if doesn't work for you.  Thx!

**Closed by zet809** 2018-07-11 02:57 UTC
Labels: component:os_provision, sprint2, status:pending, type:bug, type:usability

**Comment by chuckbrazie** [comment] 2018-07-11 04:00
I am out of the office until 07/16/2018.

I am out of the office until  Monday July 16.


Note: This is an automated response to your message  "Re: [xcat2/xcat-core]
xcat 2.14 is unable to recognize centos versions (#5287)" sent on 7/11/18
2:57:08 AM.

This is the only notification you will receive while this person is away.

**Comment by bebosudo** [comment] 2018-07-17 15:44
I had no hardware available to test this before: I just tested as @immarvin did in https://github.com/xcat2/xcat-core/issues/5287#issuecomment-402398675 on xcat 2.14.3 and I can reproduce the correct behaviour, so I can consider this as fixed. Thanks for your time and all your work!
