### ISSUE TITLE
nodeset fails to set petitboot files on node range if one node errors.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#3838] opened 2017-09-02 12:47 UTC
There really should be a way to have this command set the nodes it can, and leave the ones that are miss configured out.

[root@c460mgt01 ~]# nodeset c460c[801-816] osimage=rh74_compute_sf
c460c813: Error: missing mac data for c460c813

The specific situation is we are bringing up a rack of nodes and one node is in a state where genesis is not working so the mac address is bad, but we want to set the rest of the nodes up anyway.

[root@c460mgt01 ~]# lsxcatd -v
Version 2.13.7 (git commit 9cb9a8d4d5ce4d81617e2e5a5c2d32c42b596c5b, built Fri Sep  1 06:15:38 EDT 2017)

```
[root@c460mgt01 ~]# for n in c460c{801..816}; do cat /tftpboot/petitboot/$n; done;^C
[root@c460mgt01 ~]# nodeset c460c[801-816] boot
c460c801: boot
c460c802: boot
c460c803: boot
c460c804: boot
c460c805: boot
c460c806: boot
c460c807: boot
c460c808: boot
c460c809: boot
c460c810: boot
c460c811: boot
c460c812: boot
c460c813: boot
c460c814: boot
c460c815: boot
c460c816: boot
[root@c460mgt01 ~]# for n in c460c{801..816}; do cat /tftpboot/petitboot/$n; done;
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
```

all nodes in boot state:
```
[root@c460mgt01 ~]# nodeset c460c[801-816] osimage=rh74_compute_sf
c460c813: Error: missing mac data for c460c813

```

no nodes got their osimage set...
[root@c460mgt01 ~]# for n in c460c{801..816}; do cat /tftpboot/petitboot/$n; done;
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
#boot
```

Setting the nodes one at a time works though.
```
[root@c460mgt01 ~]# for n in c460c{801..816}; do nodeset $n osimage=rh74_compute_sf; done;
c460c801: install rhels7.4-ppc64le-compute
c460c802: install rhels7.4-ppc64le-compute
c460c803: install rhels7.4-ppc64le-compute
c460c804: install rhels7.4-ppc64le-compute
c460c805: install rhels7.4-ppc64le-compute
c460c806: install rhels7.4-ppc64le-compute
c460c807: install rhels7.4-ppc64le-compute
c460c808: install rhels7.4-ppc64le-compute
c460c809: install rhels7.4-ppc64le-compute
c460c810: install rhels7.4-ppc64le-compute
c460c811: install rhels7.4-ppc64le-compute
c460c812: install rhels7.4-ppc64le-compute
c460c813: Error: missing mac data for c460c813
c460c814: install rhels7.4-ppc64le-compute
c460c815: install rhels7.4-ppc64le-compute
c460c816: install rhels7.4-ppc64le-compute

```
[root@c460mgt01 ~]# for n in c460c{801..816}; do cat /tftpboot/petitboot/$n; done;
#install rhels7.4-ppc64le-compute                                                 
default xCAT                                                                      
label xCAT                                                                        
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz 
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c801 BOOTIF=70:e2:84:14:28:38  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c802 BOOTIF=70:e2:84:14:28:95  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c803 BOOTIF=70:e2:84:14:29:4f  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c804 BOOTIF=70:e2:84:14:29:49  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c805 BOOTIF=70:e2:84:14:29:13  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c806 BOOTIF=70:e2:84:14:2a:4b  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT                                                                                             
label xCAT                                                                                               
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz                        
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img                     
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c807 BOOTIF=70:e2:84:14:29:91  ip=dhcp "            
#install rhels7.4-ppc64le-compute                                                                        
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c808 BOOTIF=70:e2:84:14:2a:3c  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c809 BOOTIF=70:e2:84:14:29:43  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c810 BOOTIF=70:e2:84:14:28:d7  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c811 BOOTIF=70:e2:84:14:29:2b  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c812 BOOTIF=70:e2:84:14:28:dd  ip=dhcp "
#boot
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c814 BOOTIF=70:e2:84:14:2a:45  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c815 BOOTIF=70:e2:84:14:2a:3f  ip=dhcp "
#install rhels7.4-ppc64le-compute
default xCAT
label xCAT
        kernel http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/vmlinuz
        initrd http://10.1.0.101:80/tftpboot/xcat/osimage/rh74_compute_sf/initrd.img
        append "quiet inst.repo=http://10.1.0.101:80/install/RHEL-ALT-7.4-20170808.0-Server-ppc64le/ppc64le inst.ks=http://10.1.0.101:80/install/autoinst/c460c816 BOOTIF=70:e2:84:14:28:56  ip=dhcp "
[root@c460mgt01 ~]#
```

**Comment by immarvin** [comment] 2017-09-04 02:20
hi @robin2008 , would you please take a look at this  ? 

thanks

**Comment by robin2008** [comment] 2017-09-04 04:52
In nodeset relate plugins, like petitboot/xnba/grub2,  it will call `setdestiny` with the noderange first and then after it succeed, plugins will generate the boot configuration file for the node range.

In current implementation, if any error when `setdestiny`, the full process will be stopped. So no boot configuration file will be modified.

The current design is not good as most of us want the below behavior:
**when doing operation on a node range,  if one of the node has error, other nodes could still be executed.**

A simple method is just let the process continue for the noderange which contains the error nodes, but it may cause duplicate error messages for the same failed nodes.

So we need enhance current design of nodeset, for such kinds of multiple steps operation, better to check the failure nodes after each steps. And only pass the succeed nodes to next steps.

**Comment by robin2008** [comment] 2017-09-04 08:55
@ralphbellofatto 

xCAT has a technical discussion about this issue and solution today, and it seems A bit complexity and big risk to fix for such needs. Because now the nodeset related plugins are not handling well on such error nodes and also the called sub-plugins did not handle it well too and return the failure nodes back to caller.

As the sub-plugins are shared for many feature, the fix has big impact we cannot fix and finish full test on 2.13.7. And not only nodeset has such issue, many other xCAT CLI may hit the same issue, we may need a consistent behavior.

Here is a short term workaround for nodeset, we plan to add key parameter prechecking at the beginning, for example, MAC. So we can get rid of the failure nodes before we start the nodeset, and you pass a noderange with one node w/o MAC, nodeset can continue the tasks for other nodes, but only the node w/o MAC fails.

Let me know if you want the workaround fix or just waiting the long term solution.

**Comment by ralphbellofatto** [comment] 2017-09-05 12:27
what is the time frame for a long term fix,  will a fix for this be available BEFORE we start trying to deploy 100's of nodes here at the end of this month or 1000's of nodes at the labs at the end of next month?

This is where this behavior will really be a problem.  I discovered it because I did a node set on an entire range and then got confused when some of the nodes did not react like it actually had worked and some did.

**Comment by robin2008** [comment] 2017-09-06 09:41
It is hardly to say as we did not try a full regression on all CLIs which support node range. We will enhance our test case first to find the current situation.

But we will target to fix it for nodeset first in this month.

**Comment by robin2008** [comment] 2017-09-29 10:27
The petitboot and rhel is fixed in #4037

**Comment by ralphbellofatto** [comment] 2017-09-29 12:43
what version or development update will this be picked up in?

**Comment by robin2008** [comment] 2017-09-30 10:42
@ralphbellofatto 
Because the code change set is large,  and most of the us in vacation in the next week, there might not be enough time to finish the review and merge. 

If you want a early try, you could backup and replace with below files on your xCAT environment for both MN and SNs
`/opt/xcat/lib/perl/xCAT_plugin/destiny.pm`  <-- https://raw.githubusercontent.com/robin2008/xcat-core/petitboot-error-handle-4-noderange/xCAT-server/lib/xcat/plugins/destiny.pm
`/opt/xcat/lib/perl/xCAT_plugin/petitboot.pm` <-- https://raw.githubusercontent.com/robin2008/xcat-core/petitboot-error-handle-4-noderange/xCAT-server/lib/xcat/plugins/petitboot.pm
`/opt/xcat/lib/perl/xCAT_plugin/anaconda.pm` <-- https://raw.githubusercontent.com/robin2008/xcat-core/petitboot-error-handle-4-noderange/xCAT-server/lib/xcat/plugins/anaconda.pm
`/opt/xcat/lib/perl/xCAT/MsgUtils.pm` <-- https://raw.githubusercontent.com/robin2008/xcat-core/petitboot-error-handle-4-noderange/perl-xCAT/xCAT/MsgUtils.pm

And then restart `xcatd` to make the patch working.

**Closed** 2017-10-17 06:34 UTC
Labels: component:os_provision, priority:high, sprint2, test:testcase_requested
