### ISSUE TITLE
[FVT]Install xCAT failed with go-xcat tools when no input, x input, xcat version input

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1931] opened 2016-09-30 06:28 UTC
Test ENV: sles11, sles12.1 on ppc64le, x86
Description:
When run "./go-xcat --yes install", "./go-xcat -x 2.11 -y install", "./go-xcat --xcat-version=devel -y install", failed to install xCAT sccuessfully. 
Details are below:
As the test environment is not existed, and it is easy to read the autotest result, so just paste them directly below:
no input:
```
RUN:xdsh c910f04x12v04 "cd /; ./go-xcat --yes install"

[xdsh c910f04x12v04 "cd /; ./go-xcat --yes install"] Running Time:2 sec
RETURN rc = 1
OUTPUT:
c910f04x12v04: Operating system:   linux
c910f04x12v04: Architecture:       x86_64
c910f04x12v04: Linux Distribution: sles
c910f04x12v04: Version:            11.4
c910f04x12v04: 
c910f04x12v04: Reading repositories ...... done
c910f04x12v04: Loading repository data...
c910f04x12v04: Reading installed packages...
c910f04x12v04: 'xnba-undi' is already installed.
c910f04x12v04: No update candidate for 'xnba-undi-1.0.3-131028.noarch'. The highest available version is already installed.
c910f04x12v04: Resolving package dependencies...
c910f04x12v04: 
c910f04x12v04: The following NEW packages are going to be installed:
c910f04x12v04:   conserver-xcat elilo-xcat grub2-xcat ipmitool-xcat perl-xCAT syslinux-xcat xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-probe xCAT-server yaboot-xcat 
c910f04x12v04: 
c910f04x12v04: The following packages are not supported by their vendor:
c910f04x12v04:   conserver-xcat elilo-xcat grub2-xcat ipmitool-xcat perl-xCAT syslinux-xcat xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-probe xCAT-server yaboot-xcat 
c910f04x12v04: 
c910f04x12v04: 16 new packages to install.
c910f04x12v04: Overall download size: 77.6 MiB. After the operation, additional 257.0 MiB will be used.
c910f04x12v04: Continue? [y/n/? shows all options] (y): y
c910f04x12v04: Retrieving package xCAT-buildkit-4:2.12.2-snap201608180643.noarch (1/16), 68.0 KiB (303.0 KiB unpacked)
c910f04x12v04: Retrieving: xCAT-buildkit-2.12.2-snap201608180643.noarch.rpm [done]
c910f04x12v04: Retrieving package xCAT-probe-4:2.12.2-snap201608180643.noarch (2/16), 58.0 KiB (269.0 KiB unpacked)
c910f04x12v04: Retrieving: xCAT-probe-2.12.2-snap201608180643.noarch.rpm [done]
c910f04x12v04: Retrieving package conserver-xcat-8.1.16-10.x86_64 (3/16), 237.0 KiB (550.0 KiB unpacked)
c910f04x12v04: Retrieving: conserver-xcat-8.1.16-10.x86_64.rpm [done]
c910f04x12v04: Retrieving package elilo-xcat-3.14-4.noarch (4/16), 76.0 KiB (238.0 KiB unpacked)
c910f04x12v04: Retrieving: elilo-xcat-3.14-4.noarch.rpm [done]
c910f04x12v04: Retrieving package grub2-xcat-2.02-0.16.el7.snap201506090204.noarch (5/16), 1.9 MiB (7.4 MiB unpacked)
c910f04x12v04: Retrieving: grub2-xcat-2.02-0.16.el7.snap201506090204.noarch.rpm [done]
c910f04x12v04: 
c910f04x12v04: Warning: Digest verification failed for file 'grub2-xcat-2.02-0.16.el7.snap201506090204.noarch.rpm'
c910f04x12v04: [/var/cache/zypp/packages/xcat-dep/grub2-xcat-2.02-0.16.el7.snap201506090204.noarch.rpm]
c910f04x12v04: 
c910f04x12v04:   expected e49266f413b5be6e9850472a1c6d32ccb81c625e
c910f04x12v04:   but got  cd8c7040260da803148e31d17a3898d3fe8f2d1f
c910f04x12v04: 
c910f04x12v04: Accepting packages with wrong checksums can lead to a corrupted system and in extreme cases even to a system compromise.
c910f04x12v04: 
c910f04x12v04: However if you made certain that the file with checksum 'cd8c..' is secure, correct
c910f04x12v04: and should be used within this operation, enter the first 4 characters of the checksum
c910f04x12v04: to unblock using this file on your own risk. Empty input will discard the file.
c910f04x12v04: 
c910f04x12v04: Unblock or discard? [cd8c/? shows all options] (discard): discard
c910f04x12v04: Abort, retry, ignore? [a/r/i] (a): a
c910f04x12v04: Failed to provide Package grub2-xcat-2.02-0.16.el7.snap201506090204. Do you want to retry retrieval?
c910f04x12v04: 
c910f04x12v04: [xcat-dep|http://xcat.org/files/xcat/repos/yum/xcat-dep/sles11/x86_64] Can't provide file './grub2-xcat-2.02-0.16.el7.snap201506090204.noarch.rpm' from repository 'xcat-dep'
c910f04x12v04: History:
c910f04x12v04:  - grub2-xcat-2.02-0.16.el7.snap201506090204.noarch.rpm has wrong checksum
c910f04x12v04: Problem occured during or after installation or removal of packages:
c910f04x12v04: Installation aborted by user
c910f04x12v04: 
c910f04x12v04: Please see the above error message for a hint.
c910f04x12v04: 
c910f04x12v04: 
c910f04x12v04: Boo-boo
c910f04x12v04: =======
c910f04x12v04: 
c910f04x12v04: Something went wrong. :(
c910f04x12v04: 
c910f04x12v04: Please check log file `/tmp/go-xcat.log' for more details.
CHECK:rc == 0	[Failed]
```

with X input:
```
RUN:xdsh c910f04x12v04 "cd /; ./go-xcat -x 2.11 -y install"

[xdsh c910f04x12v04 "cd /; ./go-xcat -x 2.11 -y install"] Running Time:3 sec
RETURN rc = 1
OUTPUT:
c910f04x12v04: Operating system:   linux
c910f04x12v04: Architecture:       x86_64
c910f04x12v04: Linux Distribution: sles
c910f04x12v04: Version:            11.4
c910f04x12v04: 
c910f04x12v04: Reading repositories ...... done
c910f04x12v04: Loading repository data...
c910f04x12v04: Reading installed packages...
c910f04x12v04: 'xnba-undi' is already installed.
c910f04x12v04: No update candidate for 'xnba-undi-1.0.3-131028.noarch'. The highest available version is already installed.
c910f04x12v04: Resolving package dependencies...
c910f04x12v04: 
c910f04x12v04: The following NEW packages are going to be installed:
c910f04x12v04:   conserver-xcat elilo-xcat grub2-xcat ipmitool-xcat perl-xCAT syslinux-xcat xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-server yaboot-xcat 
c910f04x12v04: 
c910f04x12v04: The following packages are not supported by their vendor:
c910f04x12v04:   conserver-xcat elilo-xcat grub2-xcat ipmitool-xcat perl-xCAT syslinux-xcat xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-server yaboot-xcat 
c910f04x12v04: 15 new packages to install.
c910f04x12v04: Overall download size: 77.4 MiB. After the operation, additional 255.8 MiB will be used.
c910f04x12v04: Continue? [y/n/? shows all options] (y): y
c910f04x12v04: Retrieving package xCAT-buildkit-4:2.11.1-snap201604140932.noarch (1/15), 68.0 KiB (300.0 KiB unpacked)
c910f04x12v04: Retrieving: xCAT-buildkit-2.11.1-snap201604140932.noarch.rpm [done]
c910f04x12v04: Retrieving package perl-xCAT-4:2.11.1-snap201604140932.noarch (2/15), 605.0 KiB (3.6 MiB unpacked)
c910f04x12v04: Retrieving: perl-xCAT-2.11.1-snap201604140932.noarch.rpm [done]
c910f04x12v04: Retrieving package xCAT-client-4:2.11.1-snap201604140932.noarch (3/15), 489.0 KiB (2.8 MiB unpacked)
c910f04x12v04: Retrieving: xCAT-client-2.11.1-snap201604140932.noarch.rpm [.done]
c910f04x12v04: Retrieving package grub2-xcat-2.02-0.16.el7.snap201506090204.noarch (4/15), 1.9 MiB (7.4 MiB unpacked)
c910f04x12v04: Retrieving: grub2-xcat-2.02-0.16.el7.snap201506090204.noarch.rpm [done]
c910f04x12v04: Retrieving package syslinux-xcat-3.86-2.noarch (5/15), 499.0 KiB (919.0 KiB unpacked)
c910f04x12v04: Retrieving: syslinux-xcat-3.86-2.noarch.rpm [done]
c910f04x12v04: 
c910f04x12v04: Warning: Digest verification failed for file 'syslinux-xcat-3.86-2.noarch.rpm'
c910f04x12v04: [/var/cache/zypp/packages/xcat-dep/syslinux-xcat-3.86-2.noarch.rpm]
c910f04x12v04: 
c910f04x12v04:   expected 621c01a297efebe4e23a2892cd6c6f3125b39f41
c910f04x12v04:   but got  d12f26f37bab37162885d0848f17aef4ec4f6e32
c910f04x12v04: 
c910f04x12v04: Accepting packages with wrong checksums can lead to a corrupted system and in extreme cases even to a system compromise.
c910f04x12v04: However if you made certain that the file with checksum 'd12f..' is secure, correct
c910f04x12v04: and should be used within this operation, enter the first 4 characters of the checksum
c910f04x12v04: to unblock using this file on your own risk. Empty input will discard the file.
c910f04x12v04: 
c910f04x12v04: Unblock or discard? [d12f/? shows all options] (discard): discard
c910f04x12v04: Abort, retry, ignore? [a/r/i] (a): a
c910f04x12v04: Failed to provide Package syslinux-xcat-3.86-2. Do you want to retry retrieval?
c910f04x12v04: 
c910f04x12v04: [xcat-dep|http://xcat.org/files/xcat/repos/yum/xcat-dep/sles11/x86_64] Can't provide file './syslinux-xcat-3.86-2.noarch.rpm' from repository 'xcat-dep'
c910f04x12v04: History:
c910f04x12v04:  - syslinux-xcat-3.86-2.noarch.rpm has wrong checksum
c910f04x12v04: Problem occured during or after installation or removal of packages:
c910f04x12v04: Installation aborted by user
c910f04x12v04: 
c910f04x12v04: Please see the above error message for a hint.
c910f04x12v04: 
c910f04x12v04: 
c910f04x12v04: Boo-boo
c910f04x12v04: =======
c910f04x12v04: 
c910f04x12v04: Something went wrong. :(
c910f04x12v04: 
c910f04x12v04: Please check log file `/tmp/go-xcat.log' for more details.
CHECK:rc == 0	[Failed]
```
with xcat version input
```
RUN:xdsh c910f04x12v04 "cd /; ./go-xcat --xcat-version=devel -y install"

[xdsh c910f04x12v04 "cd /; ./go-xcat --xcat-version=devel -y install"] Running Time:6 sec
RETURN rc = 1
OUTPUT:
c910f04x12v04: Operating system:   linux
c910f04x12v04: Architecture:       x86_64
c910f04x12v04: Linux Distribution: sles
c910f04x12v04: Version:            11.4
c910f04x12v04: 
c910f04x12v04: Reading repositories ...... done
c910f04x12v04: Loading repository data...
c910f04x12v04: Reading installed packages...
c910f04x12v04: 'xnba-undi' is already installed.
c910f04x12v04: No update candidate for 'xnba-undi-1.0.3-131028.noarch'. The highest available version is already installed.
c910f04x12v04: Resolving package dependencies...
c910f04x12v04: 
c910f04x12v04: The following NEW packages are going to be installed:
c910f04x12v04:   conserver-xcat elilo-xcat grub2-xcat ipmitool-xcat perl-xCAT syslinux-xcat xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-probe xCAT-server yaboot-xcat 
c910f04x12v04: 
c910f04x12v04: The following packages are not supported by their vendor:
c910f04x12v04:   conserver-xcat elilo-xcat grub2-xcat ipmitool-xcat perl-xCAT syslinux-xcat xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64 xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-probe xCAT-server yaboot-xcat 
c910f04x12v04: 16 new packages to install.
c910f04x12v04: Overall download size: 77.6 MiB. After the operation, additional 257.2 MiB will be used.
c910f04x12v04: Continue? [y/n/? shows all options] (y): y
c910f04x12v04: Retrieving package xCAT-probe-4:2.12.3-snap201609290616.noarch (1/16), 68.0 KiB (321.0 KiB unpacked)
c910f04x12v04: Retrieving: xCAT-probe-2.12.3-snap201609290616.noarch.rpm [done]
c910f04x12v04: Retrieving package xCAT-buildkit-4:2.12.3-snap201609290616.noarch (2/16), 68.0 KiB (303.0 KiB unpacked)
c910f04x12v04: Retrieving: xCAT-buildkit-2.12.3-snap201609290616.noarch.rpm [done]
c910f04x12v04: Retrieving package syslinux-xcat-3.86-2.noarch (3/16), 499.0 KiB (919.0 KiB unpacked)
c910f04x12v04: Retrieving: syslinux-xcat-3.86-2.noarch.rpm [done]
c910f04x12v04: Retrieving package xCAT-genesis-base-ppc64-1:2.12-snap201607221057.noarch (4/16), 41.2 MiB (160.1 MiB unpacked)
c910f04x12v04: Retrieving: xCAT-genesis-base-ppc64-2.12-snap201607221057.noarch.rpm [...done (11.6 MiB/s)]
c910f04x12v04: 
c910f04x12v04: Warning: Digest verification failed for file 'xCAT-genesis-base-ppc64-2.12-snap201607221057.noarch.rpm'
c910f04x12v04: [/var/cache/zypp/packages/xcat-dep/xCAT-genesis-base-ppc64-2.12-snap201607221057.noarch.rpm]
c910f04x12v04: 
c910f04x12v04:   expected e11be3cdbd71346b745a8b4b4aa697d477f8636e
c910f04x12v04:   but got  e695ad8c3a8d1ee42ccd790c1dd62fd79a01bf1a
c910f04x12v04: 
c910f04x12v04: Accepting packages with wrong checksums can lead to a corrupted system and in extreme cases even to a system compromise.
c910f04x12v04: However if you made certain that the file with checksum 'e695..' is secure, correct
c910f04x12v04: and should be used within this operation, enter the first 4 characters of the checksum
c910f04x12v04: to unblock using this file on your own risk. Empty input will discard the file.
c910f04x12v04: 
c910f04x12v04: Unblock or discard? [e695/? shows all options] (discard): discard
c910f04x12v04: Abort, retry, ignore? [a/r/i] (a): a
c910f04x12v04: Failed to provide Package xCAT-genesis-base-ppc64-1:2.12-snap201607221057. Do you want to retry retrieval?
c910f04x12v04: 
c910f04x12v04: [xcat-dep|http://xcat.org/files/xcat/repos/yum/xcat-dep/sles11/x86_64] Can't provide file './xCAT-genesis-base-ppc64-2.12-snap201607221057.noarch.rpm' from repository 'xcat-dep'
c910f04x12v04: History:
c910f04x12v04:  - xCAT-genesis-base-ppc64-2.12-snap201607221057.noarch.rpm has wrong checksum
c910f04x12v04: Problem occured during or after installation or removal of packages:
c910f04x12v04: Installation aborted by user
c910f04x12v04: 
c910f04x12v04: Please see the above error message for a hint.
c910f04x12v04: 
c910f04x12v04: 
c910f04x12v04: Boo-boo
c910f04x12v04: =======
c910f04x12v04: 
c910f04x12v04: Something went wrong. :(
c910f04x12v04: 
c910f04x12v04: Please check log file `/tmp/go-xcat.log' for more details.
CHECK:rc == 0	[Failed]
```

**Comment by neo954** [comment] 2016-09-30 07:26
The same problem was found days ago. This is not a `go-xcat` problem but a network environment problem. See the email discussing below.

    ---- 8< ----

A really seriously problem was found today. And I spent a couple of hours to dig into it. Below is what I found.

The original problem is quite simple. Please see the detailed output below. It is just a simple zypper problem. I highlight the important error message in blue.

    # zypper install xcat# zypper install xcat
    Loading repository data...
    Reading installed packages...
    Resolving package dependencies...

    The following 56 NEW packages are going to be installed:
      conserver-xcat gcc gcc48 gettext-tools glibc-devel gnutls grub2-xcat ipmitool-xcat libatomic1
      libgomp1 libitm1 libvirt-client libyajl2 linux-glibc-devel nmap perl-Crypt-CBC perl-Crypt-Rijndael
      perl-Crypt-SSLeay perl-DBD-SQLite perl-Encode-Locale perl-File-Listing perl-HTML-Form
      perl-HTML-Parser perl-HTML-Tagset perl-HTTP-Async perl-HTTP-Cookies perl-HTTP-Daemon perl-HTTP-Date
      perl-HTTP-Message perl-HTTP-Negotiate perl-IO-HTML perl-JSON perl-libwww-perl perl-LWP-MediaTypes
      perl-LWP-Protocol-https perl-Net-HTTP perl-Net-HTTPS-NB perl-Net-Telnet perl-SOAP-Lite perl-Sys-Virt
      perl-Test-Manifest perl-TimeDate perl-WWW-RobotRules perl-xCAT rpm-build systemd-rpm-macros tftp
      xCAT xCAT-buildkit xCAT-client xCAT-genesis-base-ppc64 xCAT-genesis-base-x86_64
      xCAT-genesis-scripts-ppc64 xCAT-genesis-scripts-x86_64 xCAT-probe xCAT-server

    The following 2 recommended packages were automatically selected:
      perl-LWP-Protocol-https perl-TimeDate

    56 new packages to install.
    Overall download size: 75.2 MiB. Already cached: 23.1 MiB  After the operation, additional 347.4 MiB
    will be used.
    Continue? [y/n/? shows all options] (y): y
    In cache linux-glibc-devel-3.12-3.98.noarch.rpm                  (1/56), 909.2 KiB (  3.7 MiB unpacked)
    In cache perl-Encode-Locale-1.03-7.19.noarch.rpm                 (2/56),  18.1 KiB ( 18.2 KiB unpacked)
    In cache perl-HTML-Tagset-3.20-71.19.noarch.rpm                  (3/56),  14.7 KiB ( 19.3 KiB unpacked)
    In cache perl-HTTP-Date-6.02-7.19.noarch.rpm                     (4/56),  12.6 KiB ( 19.7 KiB unpacked)
    In cache perl-IO-HTML-1.00-3.19.noarch.rpm                       (5/56),  22.7 KiB ( 42.6 KiB unpacked)
    In cache perl-JSON-2.90-2.15.noarch.rpm                          (6/56),  95.6 KiB (269.2 KiB unpacked)
    In cache perl-LWP-MediaTypes-6.02-7.19.noarch.rpm                (7/56),  23.6 KiB ( 61.4 KiB unpacked)
    In cache perl-Net-HTTP-6.06-3.19.noarch.rpm                      (8/56),  27.1 KiB ( 50.9 KiB unpacked)
    In cache perl-Net-Telnet-3.04-3.19.noarch.rpm                    (9/56),  59.2 KiB (179.8 KiB unpacked)
    In cache perl-Test-Manifest-1.23-18.20.noarch.rpm               (10/56),  10.1 KiB ( 11.6 KiB unpacked)
    In cache perl-TimeDate-1.20-24.19.noarch.rpm                    (11/56),  45.0 KiB ( 96.7 KiB unpacked)
    In cache perl-WWW-RobotRules-6.02-7.17.noarch.rpm               (12/56),  17.1 KiB ( 26.1 KiB unpacked)
    In cache systemd-rpm-macros-2-7.161.noarch.rpm                  (13/56),   4.8 KiB (  4.4 KiB unpacked)
    In cache gnutls-3.2.15-1.8.ppc64le.rpm                          (14/56), 525.1 KiB (  3.0 MiB unpacked)
    In cache libatomic1-4.8.3+r212056-6.3.ppc64le.rpm               (15/56),  21.4 KiB ( 33.9 KiB unpacked)
    In cache libgomp1-4.8.3+r212056-6.3.ppc64le.rpm                 (16/56),  37.3 KiB ( 78.2 KiB unpacked)
    In cache libitm1-4.8.3+r212056-6.3.ppc64le.rpm                  (17/56),  41.1 KiB (158.3 KiB unpacked)
    In cache libyajl2-2.0.1-15.77.ppc64le.rpm                       (18/56),  22.7 KiB ( 49.8 KiB unpacked)
    In cache nmap-6.46-1.72.ppc64le.rpm                             (19/56),   3.6 MiB ( 16.6 MiB unpacked)
    In cache perl-DBD-SQLite-1.40-3.175.ppc64le.rpm                 (20/56), 436.4 KiB (  1.2 MiB unpacked)
    In cache tftp-5.2-8.84.ppc64le.rpm                              (21/56),  43.7 KiB ( 95.0 KiB unpacked)
    In cache glibc-devel-2.19-17.72.ppc64le.rpm                     (22/56), 696.6 KiB (  4.9 MiB unpacked)
    In cache perl-HTML-Parser-3.71-1.178.ppc64le.rpm                (23/56), 106.8 KiB (231.8 KiB unpacked)
    In cache perl-File-Listing-6.04-7.15.noarch.rpm                 (24/56),  13.1 KiB ( 16.8 KiB unpacked)
    In cache perl-HTTP-Message-6.06-3.14.noarch.rpm                 (25/56),  77.8 KiB (158.2 KiB unpacked)
    In cache perl-Crypt-Rijndael-1.11-3.144.ppc64le.rpm             (26/56),  25.8 KiB ( 47.6 KiB unpacked)
    In cache gettext-tools-0.19.2-1.103.ppc64le.rpm                 (27/56),   1.8 MiB (  8.1 MiB unpacked)
    In cache libvirt-client-1.2.5-13.3.ppc64le.rpm                  (28/56),   5.1 MiB ( 24.9 MiB unpacked)
    In cache gcc48-4.8.3+r212056-6.3.ppc64le.rpm                    (29/56),   6.8 MiB ( 24.7 MiB unpacked)
    In cache perl-HTTP-Negotiate-6.01-7.11.noarch.rpm               (30/56),  16.9 KiB ( 28.6 KiB unpacked)
    In cache perl-HTTP-Daemon-6.01-7.11.noarch.rpm                  (31/56),  19.1 KiB ( 39.2 KiB unpacked)
    In cache perl-HTTP-Cookies-6.01-7.11.noarch.rpm                 (32/56),  25.1 KiB ( 46.1 KiB unpacked)
    In cache perl-Sys-Virt-1.2.5-1.10.ppc64le.rpm                   (33/56), 213.8 KiB (810.9 KiB unpacked)
    In cache gcc-4.8-6.189.ppc64le.rpm                                (34/56),   5.4 KiB (    0 B unpacked)
    In cache perl-libwww-perl-6.05-3.11.noarch.rpm                  (35/56), 191.7 KiB (432.5 KiB unpacked)
    In cache rpm-build-4.11.2-5.92.ppc64le.rpm                      (36/56),  32.7 KiB ( 28.0 KiB unpacked)
    In cache perl-LWP-Protocol-https-6.04-5.4.noarch.rpm            (37/56),  10.2 KiB (  7.9 KiB unpacked)
    In cache perl-Crypt-SSLeay-0.64-3.57.ppc64le.rpm                (38/56), 127.0 KiB (361.3 KiB unpacked)
    In cache xCAT-probe-2.12.2-snap201608180643.noarch.rpm          (39/56),  57.4 KiB (268.7 KiB unpacked)
    In cache xCAT-buildkit-2.12.2-snap201608180643.noarch.rpm       (40/56),  67.2 KiB (302.6 KiB unpacked)
    In cache grub2-xcat-2.02-0.16.el7.snap201506090204.noarch.rpm   (41/56),   1.9 MiB (  7.4 MiB unpacked)
    Retrieving package perl-Crypt-CBC-2.33-3.7.noarch               (42/56),  28.8 KiB ( 58.8 KiB unpacked)
    Retrieving: perl-Crypt-CBC-2.33-3.7.noarch.rpm ..................................................[done]
    Digest verification failed for perl-Crypt-CBC-2.33-3.7.noarch.rpm. Expected b8e79c62d43ebdf4aa8f13b55fb88a192ac53db7, found 4cb1db150544851ca43252c19d5bdcd8ff75e489. Continue? [yes/no] (no): no
    Failed to provide Package perl-Crypt-CBC-2.33-3.7. Do you want to retry retrieval?

    [xcat-dep|http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/ppc64le] Can't provide file './perl-Crypt-CBC-2.33-3.7.noarch.rpm' from repository 'xcat-dep'
    History:
     - perl-Crypt-CBC-2.33-3.7.noarch.rpm has wrong checksum

    Abort, retry, ignore? [a/r/i] (a):
    Problem occured during or after installation or removal of packages:
    Installation aborted by user

    Please see the above error message for a hint.

Blow are some extra verifications I did in the c910 environment. I highlight all the difference in blue. It seems it is a network problem. This kind of weird things only happened in the c910 environment. I cannot recreate it with the machine in the server room of Beijing lab. And I cannot recreate it on my laptop machine as well.

To make things clear, the problem is not `go-xcat` related. And it is not SLES related. And it is not architecture related. I can recreate the same things on RHEL machines in c910.

The best guess I have is, there is a transparent cache server somewhere between the c910 network and `xcat.org`.

Anyone has any idea about this issue? Any comment is welcome.

    # wget http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/ppc64le/perl-Crypt-CBC-2.33-3.7.noarch.rp# wget http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/ppc64le/perl-Crypt-CBC-2.33-3.7.noarch.rpm -O perl-Crypt-CBC-2.33-3.7.noarch.rpm.v1
    --2016-09-29 09:32:20--  http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/ppc64le/perl-Crypt-CBC-2.33-3.7.noarch.rpm
    Resolving xcat.org (xcat.org)... 166.70.135.166
    Connecting to xcat.org (xcat.org)|166.70.135.166|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 29521 (29K) [application/x-redhat-package-manager]
    Saving to: ‘perl-Crypt-CBC-2.33-3.7.noarch.rpm.v1’

    100%[=============================================================>] 29,521      --.-K/s   in 0.003s

    2016-09-29 09:32:20 (8.54 MB/s) - ‘perl-Crypt-CBC-2.33-3.7.noarch.rpm.v1’ saved [29521/29521]

    # wget http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/ppc64le/perl-Crypt-CBC-2.33-3.7.noarch.rp# wget http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/ppc64le/perl-Crypt-CBC-2.33-3.7.noarch.rpm?blah -O perl-Crypt-CBC-2.33-3.7.noarch.rpm.v2
    --2016-09-29 09:32:35--  http://xcat.org/files/xcat/repos/yum/xcat-dep/sles12/ppc64le/perl-Crypt-CBC-2.33-3.7.noarch.rpm?blah
    Resolving xcat.org (xcat.org)... 166.70.135.166
    Connecting to xcat.org (xcat.org)|166.70.135.166|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 29521 (29K) [application/x-redhat-package-manager]
    Saving to: ‘perl-Crypt-CBC-2.33-3.7.noarch.rpm.v2’

    100%[=============================================================>] 29,521      --.-K/s   in 0.06s

    2016-09-29 09:32:36 (514 KB/s) - ‘perl-Crypt-CBC-2.33-3.7.noarch.rpm.v2’ saved [29521/29521]

    # diff -u perl-Crypt-CBC-2.33-3.7.noarch.rpm.v1 perl-Crypt-CBC-2.33-3.7.noarch.rpm.v2
    Binary files perl-Crypt-CBC-2.33-3.7.noarch.rpm.v1 and perl-Crypt-CBC-2.33-3.7.noarch.rpm.v2 differ
    # echo $?
    2
    # openssl sha1 perl-Crypt-CBC-2.33-3.7.noarch.rpm.v1 perl-Crypt-CBC-2.33-3.7.noarch.rpm.v2
    SHA1(perl-Crypt-CBC-2.33-3.7.noarch.rpm.v1)= 4cb1db150544851ca43252c19d5bdcd8ff75e489
    SHA1(perl-Crypt-CBC-2.33-3.7.noarch.rpm.v2)= b8e79c62d43ebdf4aa8f13b55fb88a192ac53db7
    # rpm -qpi perl-Crypt-CBC-2.33-3.7.noarch.rpm.v1
    Name        : perl-Crypt-CBC
    Version     : 2.33
    Release     : 3.7
    Architecture: noarch
    Install Date: (not installed)
    Group       : Development/Libraries/Perl
    Size        : 60169
    License     : GPL-1.0+ or Artistic-1.0
    Signature   : DSA/SHA1, Mon 15 Aug 2016 05:01:11 PM EDT, Key ID 60a3e9acc6565bc9
    Source RPM  : perl-Crypt-CBC-2.33-3.7.src.rpm
    Build Date  : Thu 23 Oct 2014 06:56:38 AM EDT
    Build Host  : slescn3.ppd.pok.ibm.com
    Relocations : (not relocatable)
    URL         : http://search.cpan.org/dist/Crypt-CBC/
    Summary     : Encrypt Data with Cipher Block Chaining Mode
    Description :
    This module is a Perl-only implementation of the cryptographic cipher block
    chaining mode (CBC). In combination with a block cipher such as DES or
    IDEA, you can encrypt and decrypt messages of arbitrarily long length. The
    encrypted messages are compatible with the encryption format used by the
    *OpenSSL* package.

    To use this module, you will first create a Crypt::CBC cipher object with
    new(). At the time of cipher creation, you specify an encryption key to use
    and, optionally, a block encryption algorithm. You will then call the
    start() method to initialize the encryption or decryption process, crypt()
    to encrypt or decrypt one or more blocks of data, and lastly finish(), to
    pad and encrypt the final block. For your convenience, you can call the
    encrypt() and decrypt() methods to operate on a whole data value at once.
    Distribution: (none)
    # rpm -qpi perl-Crypt-CBC-2.33-3.7.noarch.rpm.v2
    Name        : perl-Crypt-CBC
    Version     : 2.33
    Release     : 3.7
    Architecture: noarch
    Install Date: (not installed)
    Group       : Development/Libraries/Perl
    Size        : 60169
    License     : GPL-1.0+ or Artistic-1.0
    Signature   : DSA/SHA1, Tue 27 Sep 2016 05:27:36 PM EDT, Key ID 60a3e9acc6565bc9
    Source RPM  : perl-Crypt-CBC-2.33-3.7.src.rpm
    Build Date  : Thu 23 Oct 2014 06:56:38 AM EDT
    Build Host  : slescn3.ppd.pok.ibm.com
    Relocations : (not relocatable)
    URL         : http://search.cpan.org/dist/Crypt-CBC/
    Summary     : Encrypt Data with Cipher Block Chaining Mode
    Description :
    This module is a Perl-only implementation of the cryptographic cipher block
    chaining mode (CBC). In combination with a block cipher such as DES or
    IDEA, you can encrypt and decrypt messages of arbitrarily long length. The
    encrypted messages are compatible with the encryption format used by the
    *OpenSSL* package.

    To use this module, you will first create a Crypt::CBC cipher object with
    new(). At the time of cipher creation, you specify an encryption key to use
    and, optionally, a block encryption algorithm. You will then call the
    start() method to initialize the encryption or decryption process, crypt()
    to encrypt or decrypt one or more blocks of data, and lastly finish(), to
    pad and encrypt the final block. For your convenience, you can call the
    encrypt() and decrypt() methods to operate on a whole data value at once.
    Distribution: (none)

**Comment by neo954** [comment] 2016-09-30 07:28
This is not a `go-xcat` bug. Since even without `go-cat`, you will meet the same problem.

**Comment by whowutwut** [comment] 2016-10-06 00:44
I think this is caused by pointing the nameserver to the c910loginx03 node.  Something is funny with that one.  Please verify this when you are back

**Comment by zet809** [comment] 2016-10-13 08:54
Since this defect is rejected, I will close it.

**Closed by zet809** 2016-10-13 08:54 UTC
Labels: component:test, status:rejected, type:bug
