### ISSUE TITLE
bmcsetup failed to set  static bmc ip.

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1405] opened 2016-06-27 09:38 UTC
My env: 
My node define is ; 
```
[root@c712ems4 tools]# lsdef c712f7n04-pvt
Object name: c712f7n04-pvt
    arch=ppc64le
    bmc=10.128.130.34
    chain=runcmd=bmcsetup
    cons=ipmi
    currchain=runcmd=bmcsetup
    currstate=runcmd=bmcsetup
    groups=all,f7,compute
    initrd=xcat/genesis.fs.ppc64.gz
    installnic=mac
    ip=192.168.130.34
    kcmdline=quiet xcatd=192.168.130.1:3001 destiny=runcmd=bmcsetup
    kernel=xcat/genesis.kernel.ppc64
    mac=70:e2:84:14:0a:5f
    mgt=ipmi
    netboot=petitboot
    nicips.ib0=172.17.0.34
    nicips.ib1=172.17.1.34
    nicips.enP5p7s0f1=9.114.75.34
    nicnetworks.ib0=c712ib0
    nicnetworks.ib1=c712ib1
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
    os=rhels7.2
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles,confignics -s,confignics --ibaports=2,setroute
    primarynic=mac
    profile=compute
    provmethod=rh72openpower4diskless1625
    routenames=v2094gw9
    switch=c712f11u30vc
    switchport=0/0/3
```
```
[root@c712ems4 tools]# lsdef node-8335-gtb-100463a
Object name: node-8335-gtb-100463a
    bmc=192.168.130.215
    cons=ipmi
    groups=all
    hwtype=bmc
    mgt=ipmi
    mtm=8335-GTB
    nodetype=mp
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=100463A
    status=booting
    statustime=06-27-2016 05:13:29
```

then I rpower  node-8335-gtb-100463a reset
```
....
[   26.258635] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   26.328328]  sda: sda1 sda2 sda3 sda4 < sda5 >
[   26.328989] sd 0:0:0:0: [sda] Attached SCSI removable disk
[   26.338675] tg3 0005:07:00.1 enP5p7s0f1: renamed from eth1
 Petitboot (dev.20160606)                     8335-GTB         100463A
 ──────────────────────────────────────────────────────────────────────────────
  [Disk: sda2 / bb12fd7a-7a15-4164-982d-a5582e584fba]
    Red Hat Enterprise Linux Server (0-rescue-0629eef8cc984b069cb5322c443c8216)
    Red Hat Enterprise Linux Server (3.10.0-327.10.1.el7.openpower3.ppc64le) 7.
  [Network: enP5p7s0f0 / 70:e2:84:14:0a:5f]
    xCAT

  System information
  System configuration
  Language
  Rescan devices
  Retrieve config from URL
 *Exit to shell
─────────────────────────────────────────────────────────────────────────────
 Enter=accept, e=edit, n=new, x=exit, l=language, h=help
The system is going down NOW!t
Sent SIGTERM to all processes
Sent SIGKILL to all processes
[34526384271,3] OPAL: Trying a CPU re-init with flags: 0x1
[34605500385,3] OPAL: Trying a CPU re-init with flags: 0x1
 -> smp_release_cpus()
spinning_secondaries = 119
 <- smp_release_cpus()
 <- setup_system()
[    1.106690] OFfb vga: enable CONFIG_FB_LITTLE_ENDIAN to support this framebuffer
starting version 222
Done
ERROR: BOOTIF missing, can't detect boot nic
ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
Generating private key...Done
Setting IP via DHCP...
Acquiring network addresses..

Acquired IPv4 address on enP5p7s0f0: 192.168.130.34/24
ppc64
Retrying in 41 seconds
Retrying in 16 seconds

rm: cannot remove '/tmp/ipmicfg.xml': No such file or directory
/usr/bin/bmcsetup: line 45:  1816 Terminated              allowcred.awk
Auto detecting LAN channel...Detected LAN channel 1
Setting LAN IP Address to 10.128.130.34
Setting LAN Subnet Mask to 255.255.255.0
Setting LAN Default Gateway IP to 10.128.130.1
Set up following user table:
ID  Name             Callin  Link Auth  IPMI Msg   Channel Priv Limit
1                    false   false      true       ADMINISTRATOR
2   ADMIN            false   false      true       ADMINISTRATOR
Enabling Channel 1: OK
Enabling ARP responses: OK
Enabling IPMI v 1.5 MD5 LAN access:OK
Enabling IPMI v 2.0 LAN access: OK
Enabling SOL for channel 1:OK
Enabling SOL for ADMIN:OK
Error: No response to keepalive - Terminating session
Error: No response de-activating SOL payload
Acquiring startup lock...done
Console not ready, retrying in 11 seconds (Ctrl-e,c,o to skip delay)
Acquiring startup lock...done
Info: SOL payload already de-activated
[SOL Session operational.  Use ~? for help]
[291382007310,3] BT: seq 0x9b netfn 0x06 cmd 0x42: Retry sending message
[292410878959,3] BT: seq 0x9b netfn 0x06 cmd 0x42: Timeout sending message
[293439700221,3] BT: seq 0x9c netfn 0x06 cmd 0x42: Retry sending message
[294468765457,3] BT: seq 0x9c netfn 0x06 cmd 0x42: Retry sending message
[295497417215,3] BT: seq 0x9c netfn 0x06 cmd 0x42: Timeout sending message
[296526456091,3] BT: seq 0x9d netfn 0x06 cmd 0x42: Retry sending message
[297555060249,3] BT: seq 0x9d netfn 0x06 cmd 0x42: Retry sending message
```

after enter the genesis : 
```
[xCAT Genesis running on c712f7n04-pvt /]# ipmitool lan print 1
Get Device ID command failed: 0xc3 Timeout
^C
SIGN INT: Close Interface Linux OpenIPMI Interface
[xCAT Genesis running on c712f7n04-pvt /]# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enP5p7s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 70:e2:84:14:0a:5f brd ff:ff:ff:ff:ff:ff
    inet 192.168.130.34/24 scope global enP5p7s0f0
       valid_lft forever preferred_lft forever
    inet6 fe80::72e2:84ff:fe14:a5f/64 scope link
       valid_lft forever preferred_lft forever
3: enP5p7s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 70:e2:84:14:0a:60 brd ff:ff:ff:ff:ff:ff
    inet6 fd55:faaf:e1ab:365:72e2:84ff:fe14:a60/64 scope global mngtmpaddr dynamic
       valid_lft 2591878sec preferred_lft 604678sec
    inet6 fe80::72e2:84ff:fe14:a60/64 scope link
       valid_lft forever preferred_lft forever
[xCAT Genesis running on c712f7n04-pvt /]# ls
bin  debian  dev  etc  init  lib  lib64  proc  root  run  sbin  screenlog.0  sys  sysroot  tmp  usr  var


[root@c712ems4 tools]# ping 10.128.130.34
PING 10.128.130.34 (10.128.130.34) 56(84) bytes of data.
^C
--- 10.128.130.34 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

[root@c712ems4 tools]# ping 192.168.130.215
PING 192.168.130.215 (192.168.130.215) 56(84) bytes of data.
64 bytes from 192.168.130.215: icmp_seq=1 ttl=64 time=0.296 ms
^C
--- 192.168.130.215 ping statistics ---
```

**Comment by whowutwut** [comment] 2016-06-30 02:07
@wwzhubj Is there any VLAN tagging being used in your environment?

**Comment by wwzhubj** [comment] 2016-06-30 03:25
no, there is no VLAN tagging being used.

**Comment by whowutwut** [comment] 2016-07-01 13:42
@wwzhubj  I think @markprez restored this node in the test environment so cannot go in to investigate more.  If you can reproduce this issue, please re-open this issue.  If the BMC is still pinging the old IP address, please try to `ssh sysadmin@<bmcIP>` then issue command `ipmitool -H 127.0.0.1 lan print 1` to see what IP address is configured from the BMC point of view. 

We want to also be running a version of 2.12.1 with Pull request #1366 (not merged yet at this time of this note)  to make sure we are doing the right calls.  It looks like the version you are running with does a `mc reset cold` and after that in-band ipmitool does not work from the genesis kernel.

**Closed by whowutwut** 2016-07-01 13:42 UTC
Labels: component:hw_control, priority:high, status:cannot_recreate, type:bug, xCAT 2.12.1 Sprint 2
