### ISSUE TITLE
[FVT]:syncfile failed on hierarchy ramdisk statelite

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1265] opened 2016-06-06 09:12 UTC
xCAT 2.12.1 on rhels7.2
[root@c910f02c01p13 installation]# lsxcatd -v
Version 2.12.1 (git commit fbd9abfdf212c1381b166fb3e402eb982c09c0d3, built Sun Jun  5 06:45:48 EDT 2016)

```
[root@c910f02c01p13 installation]# lsdef -l c910f02c02p27
Object name: c910f02c02p27
    arch=ppc64
    cons=hmc
    currchain=boot
    currstate=statelite rhels7.2-ppc64-compute
    groups=all
    hcp=c910hmc01
    hidden=0
    hwtype=lpar
    id=27
    initrd=xcat/osimage/rhels7.2-ppc64-statelite-compute/initrd-stateless.gz
    kcmdline=imgurl=http://c910f02c01p07:80//install/netboot/rhels7.2/ppc64/compute/rootimg-statelite.gz STATEMNT=c910f02c01p07:/nodedata XCAT=10.2.1.7:3001 NODE=c910f02c02p27 BOOTIF=da:08:4b:9b:a6:03  MNTOPTS=
    kernel=xcat/osimage/rhels7.2-ppc64-statelite-compute/kernel
    mac=da:08:4b:9b:a6:03
    mgt=hmc
    monserver=c910f02c01p07
    netboot=grub2
    nfsserver=c910f02c01p07
    nicaliases.eth5=aliases2-1|aliases2-2
    nicaliases.eth4=aliases1-1|aliases1-2
    nichostnamesuffixes.eth5=-eth5-1|-eth5-2
    nichostnamesuffixes.eth4=-eth4-1|-eth4-2
    nicips.eth4=100.1.0.100
    nicips.eth5=13.1.0.100|14.1.0.100
    nicnetworks.eth4=100_1_0_0-255_255_0_0
    nicnetworks.eth5=13_1_0_0-255_255_0_0|14_1_0_0-255_255_0_0
    nictypes.eth4=Ethernet
    nictypes.eth5=Ethernet
    nodetype=ppc
    os=rhels7.2
    parent=c910f02fsp02
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    pprofile=c910f02c02p27
    profile=compute
    provmethod=rhels7.2-ppc64-statelite-compute
    servicenode=c910f02c01p07
    status=booted
    statustime=06-06-2016 04:46:09
    tftpserver=c910f02c01p07
    updatestatus=synced
    updatestatustime=06-05-2016 13:34:11
    xcatmaster=c910f02c01p07
[root@c910f02c01p13 installation]# lsdef -t osimage -o rhels7.2-ppc64-statelite-compute
Object name: rhels7.2-ppc64-statelite-compute
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64.exlist
    imagetype=linux
    osarch=ppc64
    osname=Linux
    osvers=rhels7.2
    otherpkgdir=/install/post/otherpkgs/rhels7.2/ppc64
    permission=755
    pkgdir=/install/rhels7.2/ppc64
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64.postinstall
    profile=compute
    provmethod=statelite
    rootfstype=ramdisk
    rootimgdir=/install/netboot/rhels7.2/ppc64/compute
    synclists=/install/custom/netboot/rh/compute.synclist
[root@c910f02c01p13 installation]# cat /etc/resolv.conf
; generated by /usr/sbin/dhclient-script
search pok.stglabs.ibm.com.
nameserver 10.2.1.13
[root@c910f02c01p13 installation]#
```

On compute node, check resolv.conf file
```
[root@c910f02c02p27 ~]# cat /etc/resolv.conf
search pok.stglabs.ibm.com. pok.stglabs.ibm.com
nameserver 10.2.1.13
```

**Comment by daniceexi** [comment] 2016-06-29 08:48
The root cause for this issue was the rsync has problem to rename the statellite file when its option is ``tmpfs``.

the target /etc/resolv.conf was bind mounted from tmpfs
~~~~
cp -r -a /sysroot/.default/etc/resolv.conf /sysroot/.statelite/tmpfs/etc/resolv.conf
mount --bind /sysroot/.statelite/tmpfs/etc/resolv.conf /sysroot/etc/resolv.conf
~~~~

The error of ``rsync`` command
~~~~
renaming .resolv.conf.ubf8dW to resolv.conf
rsync: rename "/etc/.resolv.conf.ubf8dW" -> "resolv.conf": Device or resource busy (16)
~~~~

**Comment by daniceexi** [comment] 2016-06-29 08:50
The workaround is to use ``--inplace`` option for ``rsync`` so that rsync won't rename the /etc/resolv.conf but write it inplace.

~~~~
xdcp c910f02c08p10 --nodestatus -F /install/custom/netboot/rh/compute.synclist  -o "--inplace"
~~~~

**Comment by daniceexi** [comment] 2016-06-29 09:00
Since xCAT has decided to obsolete **statelite** netbooting method gradually, we won't fix this issue but mark it as an known issue.

**Closed** 2016-07-06 03:09 UTC
Labels: component:os_provision, status:won't fix
